[Extension] Add Info Icon on Export Design Modal
meshery/meshery pull request #10008
Opened 2024-01-18 06:09 UTC by AjaxAueleke

**Notes for Reviewers**

This PR adds an info icon on export design modal.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-01-18 06:17 UTC, AjaxAueleke commented
@iArchitSharma

2024-01-18 06:48 UTC, iArchitSharma commented
Can you please add screenshot??

2024-01-18 07:02 UTC, Yashsharma1911 commented on ui/components/ExportModal.js
> +          title={renderTooltipContent()}
Can you use this function which already has a predefined regex to identify a link 

https://github.com/layer5labs/meshery-extensions/blob/64d2f06b58d7f4795501f57e54e03cef6770149d/meshmap/src/sections/MesheryDesignerComponent/PatternServiceFormWrapper/RJSFCustomComponents/utils.js#L56

2024-01-18 07:02 UTC, Yashsharma1911 commented on ui/components/ExportModal.js
> +    color: theme.palette.secondary.link2,
Nice work by adding theme color

2024-01-18 20:33 UTC, Yashsharma1911 commented on ui/components/ExportModal.js
> +          title={renderTooltipContent()}
I missed, you raised this PR in Meshery :) however we do have same function in Meshery too I guess you updated that right?

2024-01-20 07:53 UTC, AjaxAueleke commented
@Yashsharma1911 please review

2024-01-20 17:59 UTC, Yashsharma1911 requested changes

2024-01-20 17:59 UTC, Yashsharma1911 commented on ui/components/ExportModal.js
> +      'Learn more',
@AjaxAueleke thankyou however we discuss to have support of passing link something like this 
```suggestion
      'MeshMap Designer offers multiple export options, allowing you to choose the format that suits your needs. [Learn More](https://docs.layer5.io/meshmap/designer/export-designs/)'
```

Can you make sure we are passing link in this way

2024-01-22 08:35 UTC, leecalcote commented on ui/components/ExportModal.js
> +import InfoOutlinedIcon from '@material-ui/icons/InfoOutlined';
@nebula-aac, docile you link to this icon in Sistent, so that @AjaxAueleke might use from the central library?

2024-01-22 08:37 UTC, leecalcote commented
I accepted @Yashsharma1911’s suggested change.

2024-01-23 02:25 UTC, leecalcote commented on ui/components/ExportModal.js
> +      'MeshMap Designer offers multiple export options, allowing you to choose the format that suits your needs. [Learn More](https://docs.layer5.io/meshmap/designer/export-designs/)'
Lovely.

2024-01-23 02:25 UTC, leecalcote commented on ui/components/ExportModal.js
> +          backgroundColor="#3C494F"
theme reference for color...?

2024-01-23 14:38 UTC, AjaxAueleke commented on ui/components/ExportModal.js
> +          backgroundColor="#3C494F"
fixed

2024-01-23 22:53 UTC, leecalcote commented on ui/components/MesheryMeshInterface/PatternService/helper.js
Ok, sounds great.

2024-01-23 22:53 UTC, leecalcote approved these changes
Appears to be ready...

2024-01-31 20:32 UTC, leecalcote commented
@Yashsharma1911 is this one good to go?

2024-02-03 21:10 UTC, Yashsharma1911 approved these changes
LGTM

2024-02-03 21:11 UTC, merged

2024-02-03 21:12 UTC, Yashsharma1911 commented
Ohh this was your first PR in Meshery, nice 👏