Feature/add selectors documentation
meshery/meshery pull request #10035
Opened 2024-01-20 16:48 UTC by RipulHandoo

**Notes for Reviewers**

This PR fixes #10034 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-01-20 16:55 UTC, l5io commented
🚀 Preview for commit aac8a7bcd19677d0bbd9545071c66a765de53005 at: https://65abfaea70a827bb2b649e98--meshery-docs-preview.netlify.app

2024-01-20 17:44 UTC, leecalcote requested changes

2024-01-21 12:37 UTC, saurabh100ni commented
Hi @RipulHandoo  ,
Thanks for your PR! I encourage you to share this in the Website Meeting tomorrow at 6:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

2024-01-21 19:19 UTC, leecalcote commented on docs/pages/concepts/logical/relationships.md
> +## Selectors in Meshery
```suggestion
## Selectors in Relationships
```

2024-01-21 19:50 UTC, leecalcote commented on docs/pages/concepts/logical/relationships.md
> +Selectors in Meshery are a powerful tool for defining relationships between different components within the service mesh environment. They are organized as an array, providing a flexible and reusable
```suggestion
Selectors in Meshery are a powerful tool for defining relationships between different components. Selectors are organized in an array, providing a flexible way to specify match conditions and  corresponding actions. Multiple sets of selectors may be defined in order to precisely match and not match specific components and their attributes. ```

2024-01-21 19:52 UTC, leecalcote commented on docs/pages/concepts/logical/relationships.md
> +### Hierarchical Relationships
```suggestion
## Types of Relationships

### Hierarchical Relationships
```

2024-01-21 19:54 UTC, leecalcote commented on docs/pages/concepts/logical/relationships.md
> +When defining relationships that involve a large number of combinations between from and to, selectors provide a mechanism to organize and manage these relationships hierarchically. This prevents the
```suggestion
When defining relationships that involve a large number of combinations between `from` and `to`, selectors provide a mechanism to organize and manage these relationships hierarchically. This prevents the need for crafting complex deny attributes and facilitates easier maintenance.
```

@MUzairS15, please expand upon this phrasing: "....manage these relationships hierarchically." Is this accurate? "Hierarchically" isn't the word that best describes how selectors and sets of selectors augment their evaluation. Please update.

2024-01-21 19:56 UTC, leecalcote commented
@MUzairS15 please write a section on the evaluation engine and its behaviors in terms of munging of relationships, their selectors, their selector sets, and their scopes. Include how scopes can be controlled on a per evaluation basis (specific policies evaluated vs all policies).

2024-01-22 11:08 UTC, l5io commented
🚀 Preview for commit fc8fe23abdc093acc944506e1703984edcf463ce at: https://65ae4c8231747e206e3596be--meshery-docs-preview.netlify.app

2024-01-25 04:41 UTC, l5io commented
🚀 Preview for commit a697df3cf9116cbcb2deaca94111855e25bbeff2 at: https://65b1e63f2cfb502087031550--meshery-docs-preview.netlify.app

2024-01-25 05:10 UTC, leecalcote commented
@RipulHandoo will you put together a master design that has all relationships in it?

2024-01-25 06:22 UTC, RipulHandoo commented
> @RipulHandoo will you put together a master design that has all relationships in it?

Yes @leecalcote, I will.

2024-01-26 07:50 UTC, RipulHandoo commented on docs/pages/concepts/logical/relationships.md
> +3. **ConfigMap - Deployment**
Done. ✅

2024-01-26 07:52 UTC, RipulHandoo commented on docs/pages/concepts/logical/relationships.md
> +These pairs establish hierarchical inventory relationships, and the policy and visual paradigm remain consistent across different components. To avoid ambiguity when defining relationships, selectors
It was misplaced. It is supposed to be after the `Example` section. Corrected. ✅

2024-01-26 07:55 UTC, RipulHandoo commented
Would it be acceptable to describe the relationships in 2-3 lines, along with providing the link to the relationship from the master repo?

2024-01-26 07:56 UTC, l5io commented
🚀 Preview for commit e453799bec4b605cbb362ed27592b53b43dd0693 at: https://65b36596d92c7894a2dc2888--meshery-docs-preview.netlify.app

2024-01-26 18:18 UTC, leecalcote commented
Today is the delivery date for this doc, @MUzairS15

2024-01-26 19:31 UTC, l5io commented
🚀 Preview for commit f890b2ca577cd01572130c18c6ea8dfc7ccd8270 at: https://65b4086261304e0eb572f3ab--meshery-docs-preview.netlify.app

2024-01-26 19:35 UTC, MUzairS15 approved these changes

2024-01-26 19:35 UTC, merged