Update Integration pages layout
meshery/meshery pull request #10181
Opened 2024-02-02 15:21 UTC by iArchitSharma

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-02-02 15:24 UTC, l5io commented
🚀 Preview for commit 732e18eb556120a5b2cccb2484bf414d60fea6ad at: https://65bd0927df4b2f009f651073--meshery-docs-preview.netlify.app

2024-02-02 22:31 UTC, leecalcote requested changes

2024-02-02 22:31 UTC, leecalcote commented on docs/_layouts/integration.html
> +<p>To get started with {{ page.title }}, follow these simple steps: <a href="/installation">See Installation Guide</a></p>
Call me when you're next at keyboard, @iArchitSharma. You need a different format; different set of data here.

2024-02-02 22:44 UTC, leecalcote commented on docs/_layouts/integration.html
> +<p>To get started with {{ page.title }}, follow these simple steps: <a href="/installation">See Installation Guide</a></p>
@vishalvivekm @ritiksaxena124 we're not trying to have two sites with the same set of page information.

2024-02-05 09:56 UTC, vishalvivekm commented
@iArchitSharma 
Let's discuss this on website call at 6:30 PM IST / 7 AM Central time Today. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

2024-02-05 12:27 UTC, leecalcote commented on docs/_layouts/integration.html
> +<p>To get started with {{ page.title }}, follow these simple steps: <a href="/installation">See Installation Guide</a></p>
@iArchitSharma where are you at on this?

2024-02-09 14:56 UTC, leecalcote commented on docs/_layouts/integration.html
> +<p>To get started with {{ page.title }}, follow these simple steps: <a href="/installation">See Installation Guide</a></p>
Anywhere?

2024-07-11 21:49 UTC, closed without merging