Resolving Failed Go Unit Tests:
meshery/meshery pull request #10267
Opened 2024-02-10 21:15 UTC by yash37158

**Notes for Reviewers**
In this pull request, I have addressed failing unit tests by updating outdated golden files and rewriting certain test files to ensure compatibility with the latest codebase. After implementing these changes, all unit tests now pass successfully, demonstrating improved code integrity and reliability. This effort aligns with our commitment to maintaining a robust testing environment.  Please review the modifications made to ensure that the tests accurately reflect the expected behavior of the system. Your insights and suggestions are welcomed and appreciated to further enhance the quality and reliability of our codebase.

<img width="700" alt="Screenshot 2024-02-11 at 2 42 57 AM" src="https://github.com/meshery/meshery/assets/68152307/1aefb290-8c7b-42f8-b127-3c2c0f2967f9">

This PR fixes #9825[ failing unit tests in meshery ]

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-02-10 21:18 UTC, l5io commented
🚀 Preview for commit ec3d90caf20688701533e2ac5087aef5b75fcf1f at: https://65c7e7f4722bc9a5ac6e63d5--meshery-docs-preview.netlify.app

2024-02-12 06:40 UTC, theBeginner86 requested changes
Thanks for this. Such cleanup is much appreciated and needed.

2024-02-12 06:40 UTC, theBeginner86 commented on mesheryctl/internal/cli/root/app/app_test.go
> +			log.Println(err, "Logging error")
Can we please remove these debug logs?

2024-02-12 06:40 UTC, theBeginner86 commented on mesheryctl/internal/cli/root/perf/testdata/apply/1001.golden
Are these golden file not being used? If not, then please consider deleting the file instead of just deleting the contents.

2024-02-12 06:40 UTC, theBeginner86 commented on docs/pages/reference/mesheryctl/test.md
Have you added a new `test` command? 
Please consider deleting this.

2024-02-12 13:18 UTC, yash37158 commented on mesheryctl/internal/cli/root/app/app_test.go
> +			log.Println(err, "Logging error")
Yeah sure, I think I just missed that

2024-02-12 13:19 UTC, l5io commented
🚀 Preview for commit 4a9e25aea503295632b9d3d33cc87cda94543c1b at: https://65ca1aac92c2f4e923806eb4--meshery-docs-preview.netlify.app

2024-02-12 13:27 UTC, yash37158 commented on docs/pages/reference/mesheryctl/test.md
Yeah sure

2024-02-13 14:39 UTC, saurabh100ni commented
Hi @yash37158 
Thanks for your PR! I encourage you to share this in the Meshery Development Meeting tomorrow at 8:30 PM IST. Share your screen, and walk us through it. It's cool to take and share feedback. Check the [Doc](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit) here to include this PR.

You're welcome at the meeting

Check to [community calendar](https://layer5.io/community/calendar) for more details of meetings at Layers.

2024-02-14 05:42 UTC, leecalcote commented
@Althaf66 will you give this a review?

2024-02-15 23:05 UTC, leecalcote commented
Are the lint check failures expected?

2024-02-16 13:54 UTC, yash37158 commented
Yes @leecalcote, It is expected to fail. Will pass after this PR is merged.

2024-03-01 18:38 UTC, yash37158 commented
Do I have any update on this PR @theBeginner86?

2024-03-13 14:24 UTC, closed without merging