Rtk migration designs
meshery/meshery pull request #10334
Opened 2024-02-16 23:05 UTC by cesartheroman

**Notes for Reviewers**

This PR fixes #10046

This is a draft PR so that I can get feedback to see if I'm approaching the migration of the following the right way:

- publish design 
  - api/pattern/catalog/publish [POST] -> https://docs.meshery.io/reference/rest-apis#api-pattern-catalog-publish 
- Unpublish design 
  - api/pattern/catalog/unpublish [DELETE] -> https://docs.meshery.io/reference/rest-apis#api-pattern-catalog-unpublish

I left the previous `dataFetch()` implementations commented just in case, but also added comments in the `design.js` file to see if I'm missing information. 

Please let me know!

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2024-02-21 21:51 UTC, cesartheroman commented
@sudhanshutech look good?

2024-02-22 11:31 UTC, sudhanshutech commented on ui/components/MesheryPatterns.js
> +        //Previous implementation
you can remove this

2024-02-22 11:32 UTC, sudhanshutech commented on ui/components/MesheryPatterns.js
> +    //Previous implementation:
remove

2024-02-22 11:35 UTC, sudhanshutech commented
looks good, are you also migrating other area to rtk here in designs @cesartheroman ?

2024-02-29 11:44 UTC, sudhanshutech requested changes

2024-02-29 11:44 UTC, sudhanshutech commented on ui/rtk-query/design.js
> +      addPatterns: builder.mutation({
publishPattern is more appropriate naming convention

2024-02-29 11:44 UTC, sudhanshutech commented on ui/rtk-query/design.js
> +      removePatterns: builder.mutation({
same unpublishPattern here

2024-03-11 16:34 UTC, closed without merging