fix: test for model commands
meshery/meshery pull request #10345
Opened 2024-02-18 18:31 UTC by RipulHandoo

**Notes for Reviewers**

This PR fixes #
1. Improves UX for models command.
2. Adds tests for models command.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-02-18 18:47 UTC, RipulHandoo commented
**_All tests for the models command are passing without any issues._**
![image](https://github.com/meshery/meshery/assets/107461226/a4092f06-3687-4b70-b2cc-ee1fb0e5784a)

2024-02-21 17:08 UTC, leecalcote requested changes
@RipulHandoo @MUzairS15 as a discussion point in this week's CI meeting, will you please confirm the library/framework and approach being used for unit testing? @alphaX86, will you attend and participate? A minimum of once-a-month attendance to a Meshery meeting is requested of each maintainer.

2024-02-24 05:39 UTC, RipulHandoo commented on mesheryctl/internal/cli/root/system/component_test.go
> +)
Yes, We can use Testify in here. Instead of `utils.Equal` we will use `assert.Equal`.  I'll update the pr soon.

2024-03-16 09:02 UTC, MUzairS15 requested changes

2024-03-16 09:02 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/system/model_test.go
>  			utils.Equals(t, expectedResponse, actualResponse)
This can be removed I believe.

2024-04-06 09:17 UTC, MUzairS15 commented
conflicts.

2024-05-11 08:35 UTC, closed without merging