[Add]: Relationship between StorageClass and other k8s components
meshery/meshery pull request #10357
Opened 2024-02-20 20:08 UTC by pandeyshubham03

**Notes for Reviewers**

This PR fixes #

1. Adds Relationship between StorageClass and other k8s components.

Working proof of this PR:
https://github.com/meshery/meshery/assets/128715606/c284c457-acc6-4434-9c89-1e5156fb5192

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-02-21 00:28 UTC, leecalcote commented
@pandeyshubham03 would you like to offer review here?

2024-02-21 12:45 UTC, pandeyshubham03 commented
I currently have the read-only access to the [spreadsheet](https://docs.google.com/spreadsheets/d/1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw/edit#gid=1646054916). Kindly allow me to edit it in order to make necessary changes.

2024-02-21 18:27 UTC, RipulHandoo commented
**_Note:_** [Spreadsheet ](https://docs.google.com/spreadsheets/d/1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw/edit#gid=1646054916)updated.  ✅

2024-02-24 01:08 UTC, leecalcote requested changes

2024-02-24 01:08 UTC, leecalcote commented on server/meshmodel/kubernetes/relationships/hierarchical_inventory.json
> +              "description": "A StorageClass in Kubernetes defines the type and properties of storage that can be dynamically provisioned for persistent volumes."
Please add a description of how one component modifies or is modified by the other.

2024-02-24 17:56 UTC, MUzairS15 commented on server/meshmodel/kubernetes/relationships/hierarchical_inventory.json
> +              "description": "A StorageClass in Kubernetes defines the type and properties of storage that can be dynamically provisioned for persistent volumes and its name is mentioned in a Persist
```suggestion
              "description": "StorageClass is used in conjunction with PVC that allow Pods to dynamically request a new storage."
```

2024-02-24 17:57 UTC, MUzairS15 approved these changes

2024-02-24 17:58 UTC, merged