add: Relationship for IngressClass and other k8s resources
meshery/meshery pull request #10355
Opened 2024-02-20 15:37 UTC by RipulHandoo

**Notes for Reviewers**

This PR fixes #
1. Adds relationship for Ingress Class and other k8s resources.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-02-20 15:38 UTC, RipulHandoo commented
_**Note:**_ [Spreadsheet ](https://docs.google.com/spreadsheets/d/1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw/edit#gid=1646054916)updated. ✅

2024-02-21 05:31 UTC, pandeyshubham03 commented
Looks good to me!

2024-02-21 18:59 UTC, leecalcote commented
> Looks good to me!

Thanks for this, @pandeyshubham03 👍

2024-02-24 01:09 UTC, leecalcote requested changes

2024-02-24 01:09 UTC, leecalcote commented on server/meshmodel/kubernetes/relationships/hierarchical_inventory.json
> +              "description": "IngressClass establishes an inventory relationship with Ingress. IngressClass is a resource to provide default class for Ingress. When a IngressClass is dropped on Ingre
Please don't use "dropped". Such phrasing is only applicable to a visual designer interface.

2024-02-24 16:52 UTC, MUzairS15 commented on server/meshmodel/kubernetes/relationships/hierarchical_inventory.json
> +              "description": "Ingress is a collection of rules that allow inbound connections to reach the services. When a IngressClass is dragged over Ingress specification of Ingress will be updat
```suggestion
              "description": "Ingress is a collection of rules that allow inbound connections to reach the services. IngressClass configures the class of Ingress resource which is then used by the Ingress Controller."
```

2024-02-24 16:52 UTC, MUzairS15 commented on server/meshmodel/kubernetes/relationships/hierarchical_inventory.json
> +              "description": "IngressClass establishes an inventory relationship with Ingress. IngressClass is a resource to provide default class for Ingress. When a IngressClass is dragged on Ingre
```suggestion
              "description": "IngressClass is a resource to specify class for Ingress to be used by the IngressController."
```

2024-02-24 16:52 UTC, merged