[Add]: Relationship between PriorityClass and other k8s components
meshery/meshery pull request #10376
Opened 2024-02-22 06:56 UTC by pandeyshubham03

**Notes for Reviewers**

This PR fixes #
1. Adds relationship between PriorityClass and other k8s components.

https://github.com/meshery/meshery/assets/128715606/84ae25eb-b32b-4b7c-9cdc-d1afe3a29639

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-02-24 01:17 UTC, leecalcote commented on server/meshmodel/kubernetes/relationships/hierarchical_inventory.json
> +              "description": "PriorityClass in Kubernetes defines scheduling priority for Pods."
Please describe the relationship in addition to the component.

2024-02-24 16:36 UTC, RipulHandoo commented
@pandeyshubham03 PriorityClass can indeed have relationships with various Kubernetes components, including Deployments, Pod Template and others.

2024-02-26 13:22 UTC, pandeyshubham03 commented
I have added the description for the relationships added @leecalcote and I have also added all the components that could have a relationships with PriorityClass @RipulHandoo.

2024-02-26 20:44 UTC, leecalcote requested changes

2024-02-26 20:44 UTC, leecalcote commented on server/meshmodel/kubernetes/relationships/hierarchical_inventory.json
> +              "description": "PriorityClass in Kubernetes assigns importance levels to Pods, influencing scheduling decisions. The name of the PriorityClass is referenced by other k8s components"
Let's not abbreviate "Kubernetes" or if we do, make sure that we abide by their branding request that "K8s" be capitalized. Having said that, let's not abbreviate Kubernetes. The PriorityClass name is referenced by other components... for what purpose?

2024-02-26 20:44 UTC, leecalcote commented on server/meshmodel/kubernetes/relationships/hierarchical_inventory.json
> +              "description": "PodTemplate specifies the name of priorityClass, guiding Kubernetes controller to assign priority to Pods created from it, influencing scheduling behavior accordingly."
"Kubernetes controller" - make this plural.

"created from it" - "it" who?

2024-02-26 20:44 UTC, leecalcote commented on server/meshmodel/kubernetes/relationships/hierarchical_inventory.json
> +              "description": "StatefulSets manage stateful applications. PriorityClass can be applied to StatefulSets' Pods to prioritize them during scheduling."
"them" - to what component are you referring?

2024-02-26 20:44 UTC, leecalcote commented on server/meshmodel/kubernetes/relationships/hierarchical_inventory.json
> +              "description": "DaemonSets ensure all nodes run a copy of a Pod. PriorityClass assigns importance, impacting scheduling decisions for DaemonSet-managed Pods."
"impacting" - in what way?

2024-02-26 20:44 UTC, leecalcote commented on server/meshmodel/kubernetes/relationships/hierarchical_inventory.json
> +              "description": "PriorityClass in Kubernetes influences Job scheduling, ensuring high-priority Jobs execute first, critical for resource allocation and workload management."
Rephrase - ", critical for resource allocation and workload management."

2024-02-26 20:44 UTC, leecalcote commented on server/meshmodel/kubernetes/relationships/hierarchical_inventory.json
> +              "description": "CronJobs can use PriorityClass to prioritize scheduled job execution, ensuring critical tasks are handled with precedence in Kubernetes."
CronJobs can or do use?

"handled with precedence in Kubernetes." or "ensuring CronJobs are scheduled for execution in accordance with the precedence specified in the associated PriorityClass."?

2024-02-27 22:12 UTC, leecalcote commented on server/meshmodel/kubernetes/relationships/hierarchical_inventory.json
> +              "description": "CronJobs can use PriorityClass to prioritize the scheduled job execution, ensuring CronJobs are scheduled for execution in accordance with the precedence specified in th
Nice!

2024-02-27 22:12 UTC, leecalcote approved these changes

2024-02-27 22:12 UTC, merged