Updated the GKE version and syntax yaml files
meshery/meshery pull request #10412
Opened 2024-02-26 13:47 UTC by anirudh-hegde

**Notes for Reviewers**

This PR fixes syntax of YAML files and updates GKE version

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-02-26 21:13 UTC, leecalcote requested changes

2024-02-26 21:13 UTC, leecalcote commented on .goreleaser.yml
@anirudh-hegde thanks. If there's no meaningful change other than whitespace, let's forego inclusion of this file / these changes in the PR.

2024-02-26 21:13 UTC, leecalcote commented on mesheryctl/pkg/utils/fixtures/TestConfig.yaml
>      version: v0.5.10
@asubedy, if we don't use a specific version number for each test of the stable release of an adapter, will this make sense in the [Compatibility Matrix](https://docs.meshery.io/installation/compatibility-matrix)? I suspect not.

2024-02-26 21:13 UTC, leecalcote commented on mesheryctl/pkg/utils/fixtures/platform/original/TestChangeEndpointConfig.yaml
>      version: v0.5.10
perhaps, we're in need of identifying the last stable release's version number. In the case of meshery-istio, that currently would be v0.7.0.

2024-02-27 01:46 UTC, anirudh-hegde commented on .goreleaser.yml
On VSCode, accidentaly I pressed Ctrl+Alt+L to this file

2024-02-29 09:11 UTC, leecalcote commented
Reviewing again. No changes since last feedback offered.

2024-02-29 10:52 UTC, anirudh-hegde commented
GKE versions : 1.29.1-gke.1575000
If required please refer: https://cloud.google.com/kubernetes-engine/docs/release-notes

2024-03-08 21:40 UTC, leecalcote commented on mesheryctl/pkg/utils/fixtures/TestConfig.yaml
>      version: v0.5.10
@asubedy?

2024-03-25 22:14 UTC, leecalcote commented on .goreleaser.yml
@anirudh-hegde, are you still working on fixing this?

2024-03-26 13:36 UTC, leecalcote commented
PR abandoned.

2024-03-26 13:36 UTC, closed without merging