Migrate stepper component apis to rtk
meshery/meshery pull request #10453
Opened 2024-02-29 08:58 UTC by sudhanshutech

**Notes for Reviewers**

This PR fixes #

- [x] register a connection
- [x] verify connection
- [x] initialize connections
- [x] credentials

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-02-29 09:10 UTC, leecalcote commented on ui/components/connections/meshSync/Stepper/StepperContent.js
> +            connectToConnection();
What does "ConnectToConnection" mean? Could this name be more descriptive, and less redundant?

2024-03-01 10:03 UTC, aabidsofi19 requested changes

2024-03-01 10:03 UTC, aabidsofi19 commented on ui/components/connections/meshSync/Stepper/StepperContent.js
> +    connectionRegister({
@sudhanshutech  please use async/await syntax

2024-03-01 10:03 UTC, aabidsofi19 commented on ui/components/connections/meshSync/Stepper/StepperContent.js
> +    connectionRegister({
same here use async.await

2024-04-22 03:45 UTC, closed without merging