feat: command to view relationship by model
meshery/meshery pull request #10479
Opened 2024-03-02 12:29 UTC by RipulHandoo

**Notes for Reviewers**

This PR fixes #

1. Sub-Command `[view]` for relationship.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-03-02 13:07 UTC, MUzairS15 commented
Nice 👌🏻

2024-03-03 13:50 UTC, alphaX86 commented
This PR can be linked to this issue #9844

2024-03-03 13:52 UTC, alphaX86 reviewed
@MUzairS15 are we planning this command to be within `system` command itself. Or as a separate one?

2024-03-08 21:36 UTC, leecalcote commented on mesheryctl/internal/cli/root/system/relationship.go
> +// Copyright 2023 Layer5, Inc.
```suggestion
// Copyright Meshery Authors
```

2024-03-16 09:25 UTC, MUzairS15 requested changes

2024-03-16 09:25 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/system/relationship.go
> +			return fmt.Errorf("model name isn't specified\n\n%v", errMsg)
Meshkit error

2024-03-16 09:25 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/system/relationship.go
> +		if outFormatFlag == "yaml" {
What if the user provides "yml"?

2024-03-16 09:25 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/system/relationship.go
> +		if outFormatFlag == "yaml" {
The default format is yaml/yml, correct?

2024-03-16 09:25 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/system/relationship.go
> +// To view list of components
Update the docs and usages.

2024-03-28 19:58 UTC, leecalcote commented
@RipulHandoo when will this be finished?

2024-03-29 12:59 UTC, closed without merging

2024-03-29 13:04 UTC, leecalcote commented
Why is this being closed?