Add meshery-nighthawk helm chart
meshery/meshery pull request #10581
Opened 2024-03-17 18:43 UTC by lekaf974

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-03-17 18:55 UTC, lekaf974 commented
Hello, my first contribution waiting for any feedback

2024-03-18 20:05 UTC, leecalcote commented
Thank you, @lekaf974 👍

2024-03-19 02:32 UTC, gyohuangxin requested changes
@lekaf974 Great! Thank you for contributing on this, I left some comments.

2024-03-19 02:32 UTC, gyohuangxin commented on install/kubernetes/helm/meshery/charts/meshery-nighthawk/Chart.yaml
> +description: Meshery Adapter for App Mesh chart.
Please also update the description for meshery-nighthawk.

2024-03-19 02:32 UTC, gyohuangxin commented on install/kubernetes/helm/meshery/charts/meshery-nighthawk/Chart.yaml
> +icon: https://meshery.io/images/logos/meshery-logo.png
We have the meshery-nighthawk icon: https://github.com/meshery/meshery-nighthawk/blob/master/assets/img/icon/nighthawk-logo.png, can we use that? // @leecalcote

2024-03-19 02:32 UTC, gyohuangxin commented on install/kubernetes/helm/meshery/charts/meshery-nighthawk/Chart.yaml
> +  - https://github.com/layer5io/meshery-nighthawk
```suggestion
  - https://github.com/meshery/meshery-nighthawk
```

2024-03-19 02:32 UTC, gyohuangxin commented on install/kubernetes/helm/meshery/charts/meshery-nighthawk/Chart.yaml
> +appVersion: stable-latest
```suggestion
appVersion: edge-latest
```
We only have the edge-latest version of meshery-nighthawk image currently: https://hub.docker.com/layers/meshery/meshery-nighthawk/edge-latest/images/sha256-4efc9a803b2c31b0395596af6bc4b1289da067fc058684cbf49799eb56e74901?context=explore

2024-03-19 02:32 UTC, gyohuangxin commented on install/kubernetes/helm/meshery/charts/meshery-nighthawk/values.yaml
> +  repository: layer5/meshery-nighthawk:stable-latest
```suggestion
  repository: meshery/meshery-nighthawk:edge-latest
```

2024-03-19 02:32 UTC, gyohuangxin commented on install/kubernetes/helm/meshery/charts/meshery-nighthawk/README.md
> +Meshery Adapter for App Mesh chart.
Ditto

2024-03-19 02:32 UTC, gyohuangxin commented on install/kubernetes/helm/meshery/charts/meshery-nighthawk/README.md
> +![Version: 0.5.0](https://img.shields.io/badge/Version-0.5.0-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![App
The "Version" and "AppVersion" should also be updated.

2024-03-19 02:32 UTC, gyohuangxin commented on install/mesheryapp.dockerapp/docker-compose.yml
> +    image: layer5/meshery-nighthawk:stable-latest
```suggestion
    image: meshery/meshery-nighthawk:edge-latest
```

2024-03-20 01:56 UTC, lekaf974 commented
@gyohuangxin thx for feedback, will do the changes based on comments soon

2024-03-20 03:06 UTC, gyohuangxin commented on install/kubernetes/helm/meshery/Chart.yaml
>    - name: meshery-perf
Do we need to delete the meshery-perf component? @leecalcote

2024-03-20 03:06 UTC, gyohuangxin commented on install/kubernetes/helm/meshery/values.yaml
>    fullnameOverride: meshery-perf
Ditto.

2024-03-23 21:19 UTC, leecalcote commented
@lekaf974 thanks for digging in here.

Are you all done incorporating feedback and ready for another review?

2024-03-24 00:05 UTC, lekaf974 commented
> @lekaf974 thanks for digging in here.
> 
> Are you all done incorporating feedback and ready for another review?

Yes all have been updated and ready for new feedback

2024-03-25 11:47 UTC, gyohuangxin approved these changes

2024-03-26 13:37 UTC, leecalcote commented
> > @lekaf974 thanks for digging in here.
> > Are you all done incorporating feedback and ready for another review?
> 
> @leecalcote Yes all have been updated and ready for new review

👨‍🎤 👍

2024-03-26 13:37 UTC, merged