I have made changes to the scrollbar css and now it is not overflowin…
meshery/meshery pull request #10639
Opened 2024-03-29 10:09 UTC by kunal-511

I have made changes to the scrollbar css and now it is not overflowing the parent container
I have made changes to the MesheryTreeView.js file.
**Notes for Reviewers**
This is my first PR in meshry 

This PR fixes #10434 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-03-29 20:53 UTC, Yashsharma1911 requested changes
Thankyou for raising the PR @kunal-511 but issue was not to remove scroll bar instead shifting it to right most side of that box.

2024-03-30 04:40 UTC, kunal-511 commented
@Yashsharma1911 I have moved the scroll bar

2024-03-30 13:51 UTC, sudhanshutech commented
@kunal-511 any screenshot or recording?

2024-03-31 11:06 UTC, kunal-511 commented
<img width="960" alt="Screenshot 2024-03-31 1632389" src="https://github.com/meshery/meshery/assets/118254863/5e6daff0-07cf-4d97-b190-15afc6b685fd">
<img width="960" alt="Screenshot 2024-03-31 163136" src="https://github.com/meshery/meshery/assets/118254863/93e53bed-52a2-4557-90d4-d59feeb4ceb8">

2024-03-31 11:08 UTC, kunal-511 commented
@sudhanshutech Above are the screenshots for the fix made
screenshot1- is the error
screenshot2- is after the fix

2024-04-03 12:19 UTC, vishalvivekm commented
@kunal-511 Let's discuss this in Meshery dev call today. I'm adding this as an agenda item to the meeting[ minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#).

2024-04-03 12:34 UTC, kunal-511 commented
> @kunal-511 Let's discuss this in Meshery dev call today. I'm adding this as an agenda item to the meeting[ minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#).

ok I will be there in the meeting

2024-04-03 20:03 UTC, MUzairS15 commented
@sudhanshutech @Yashsharma1911

2024-04-04 00:04 UTC, Yashsharma1911 reviewed
Thankyou for this @kunal-511 this is small item but should be covered, can you make sure that the way this line connect on right side it also does on left? make sure it does not affect the other UI 

![Screenshot 2024-04-04 at 5 40 27 AM](https://github.com/meshery/meshery/assets/71271069/da09de93-026f-4da7-83ba-1dd438561616)

2024-04-04 04:13 UTC, kunal-511 commented
> Thankyou for this @kunal-511 this is small item but should be covered, can you make sure that the way this line connect on right side it also does on left? make sure it does affect the other UI
> 
> ![Screenshot 2024-04-04 at 5 40 27 AM](https://private-user-images.githubusercontent.com/71271069/319395390-da09de93-026f-4da7-83ba-1dd438561616.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDM4NTksIm5iZiI6MTcxMjIwMzU1OSwicGF0aCI6Ii83MTI3MTA2OS8zMTkzOTUzOTAtZGEwOWRlOTMtMDI2Zi00ZGE3LTgzYmEtMWRkNDM4NTYxNjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA0MDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYjg4NzAzOTc3NWQ5ZThlOTkzYWY1OWU4ZjU3MGMxMjk5YWQ3OWYxMDQxODNkNTFkYzVkNmFkYzIyYTJjODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TZXFNyWUZvR6fhM0mIshqOJCQAzYu_Tf42AU_V6fYDE)

In the original UI, there is a gap from both sides so I have to make that gap or join it from left side as in right side?

2024-04-13 00:08 UTC, leecalcote commented
@kunal-511, please know that @Yashsharma1911 is out for exams for a few days, but will be back early next week.

2024-06-07 03:02 UTC, closed without merging