feat: environment command
meshery/meshery pull request #10663
Opened 2024-04-02 06:09 UTC by RipulHandoo

**Notes for Reviewers**

This PR fixes #10583 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-04-03 13:07 UTC, leecalcote commented
merge conflicts...

2024-04-06 09:17 UTC, MUzairS15 requested changes
@RipulHandoo Go through previous PR reviews, this PR also suffers from the same issues. Logs, error, returning err vs logging

2024-04-08 19:12 UTC, RipulHandoo commented
> @RipulHandoo Go through previous PR reviews, this PR also suffers from the same issues. Logs, error, returning err vs logging

Done. Reviews answered.

2024-04-11 04:55 UTC, leecalcote commented
@RipulHandoo merge conflicts...

2024-04-11 16:32 UTC, RipulHandoo commented
> @RipulHandoo merge conflicts...

Resolved.

2024-04-23 09:06 UTC, MUzairS15 submitted a review, later dismissed
Please fix formatting (run gofmt)

2024-04-23 09:06 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/environments/delete.go
> +var DeleteEnvironmentCmd = &cobra.Command{
```suggestion
var deleteEnvironmentCmd = &cobra.Command{
```

2024-04-23 09:06 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/environments/create.go
> +var CreateEnvironmentCmd = &cobra.Command{
```suggestion
var createEnvironmentCmd = &cobra.Command{
```

2024-04-23 09:06 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/environments/environment.go
> +	availableSubcommands = []*cobra.Command{listEnvironmentCmd, CreateEnvironmentCmd, DeleteEnvironmentCmd}
```suggestion
	availableSubcommands = []*cobra.Command{listEnvironmentCmd, createEnvironmentCmd, deleteEnvironmentCmd}
```

2024-04-23 09:06 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/environments/environment.go
> +	CreateEnvironmentCmd.Flags().StringVarP(&orgID, "orgId", "o", "", "Organization ID")
```suggestion
	createEnvironmentCmd.Flags().StringVarP(&orgID, "orgId", "o", "", "Organization ID")
```

2024-04-23 09:06 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/environments/environment.go
> +	CreateEnvironmentCmd.Flags().StringVarP(&name, "name", "n", "", "Name of the environment")
```suggestion
	createEnvironmentCmd.Flags().StringVarP(&name, "name", "n", "", "Name of the environment")
```

2024-04-23 09:06 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/environments/environment.go
> +	CreateEnvironmentCmd.Flags().StringVarP(&description, "description", "d", "", "Description of the environment")
```suggestion
	createEnvironmentCmd.Flags().StringVarP(&description, "description", "d", "", "Description of the environment")
```

2024-04-23 09:06 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/environments/view.go
> +				return errors.Wrap(err, "failed to format output in YAML")
Please update to meshkit error.

2024-04-23 09:06 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/environments/view.go
> +					return errors.Wrap(err, "failed to save output as YAML file")
same

2024-04-23 09:06 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/environments/view.go
> +		if outFormatFlag == "yaml" {
yaml | yml?

2024-04-23 09:06 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/environments/view.go
> +			return errors.New("output-format choice invalid, use [json|yaml]")
same

2024-04-24 17:48 UTC, RipulHandoo commented on mesheryctl/internal/cli/root/environments/view.go
> +			return errors.New("output-format choice invalid, use [json|yaml]")
Done with requested changes.

2024-04-25 17:46 UTC, MUzairS15 approved these changes

2024-04-25 17:48 UTC, merged