Fix redirection link of docs and use sistent schemas
meshery/meshery pull request #10672
Opened 2024-04-03 13:13 UTC by sudhanshutech

**Notes for Reviewers**

This PR fixes #
1. The link on tooltip for docs was not clickable and one place the link was also not correct which is fixed here: https://github.com/layer5io/sistent/pull/561
2. While i was here i used the available scehmas from sistent for import designs and filters and publish designs and filters

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-04-03 15:35 UTC, betelgeuse-code requested changes

2024-04-03 15:35 UTC, betelgeuse-code commented on ui/components/Filters.js
> +      uiSchema={publishCatalogItemUiSchema}
thankyou for this, do make sure you remove the API code for fetching schema, also make sure that this schema goes through the function that publishFormSchema.rjsfSchema goes, we don't get meshmodels already in schema we update them in UI

2024-04-03 15:35 UTC, betelgeuse-code commented on ui/components/Filters.js
> +      uiSchema={publishCatalogItemUiSchema}
For technology field

2024-04-03 15:35 UTC, betelgeuse-code commented on ui/components/MesheryPatterns.js
> +        uiSchema={publishCatalogItemUiSchema}
Same here

2024-04-04 16:58 UTC, sudhanshutech commented
Thanks @betelgeuse-code for the feedback, i will do so

2024-04-10 08:31 UTC, sudhanshutech commented
@Yashsharma1911 i have updated, you can test this now

2024-04-16 16:46 UTC, leecalcote commented on ui/package.json
> +        "@layer5/sistent": "^0.14.21",
Bump this to 0.14.23?

2024-04-17 14:09 UTC, sudhanshutech commented
@Yashsharma1911 looks good?

2024-05-14 15:27 UTC, leecalcote commented
merge conflicts... 

Gents, where do we stand on this PR? Still WIP or have we tossed in the towel?

2024-05-16 05:03 UTC, 11happy commented
@leecalcote I have taken reference from @sudhanshutech PRs as told by him & have also included further work in my PR #10720

2024-05-16 15:32 UTC, leecalcote commented
@11happy ok. Based on your description, I assume this PR is no longer being advanced.

2024-05-16 15:32 UTC, closed without merging