Fix behavior to display helper function
meshery/meshery pull request #10685
Opened 2024-04-08 03:29 UTC by lekaf974

**Notes for Reviewers**

This PR fixes #10350 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.
 

```bash
[matthieu@ikki mesheryctl]$ ./mesheryctl exp model
View list of models and detailed information of a specific model

Usage:
  mesheryctl exp model [flags]
  mesheryctl exp model [command]

Examples:

// To view list of components
mesheryctl exp model list

// To view a specific model
mesheryctl exp model view [model-name]
	

Available Commands:
  list        list registered models
  search      search models
  view        view model

Flags:
  -h, --help   help for model

Global Flags:
      --config string   path to config file (default "/home/matthieu/.meshery/config.yaml")
  -v, --verbose         verbose output

Use "mesheryctl exp model [command] --help" for more information about a command.
View list of models and detailed information of a specific model

Usage:
  mesheryctl exp model [flags]
  mesheryctl exp model [command]

Examples:

// To view list of components
mesheryctl exp model list

// To view a specific model
mesheryctl exp model view [model-name]
	

Available Commands:
  list        list registered models
  search      search models
  view        view model

Flags:
  -h, --help   help for model

Global Flags:
      --config string   path to config file (default "/home/matthieu/.meshery/config.yaml")
  -v, --verbose         verbose output

Use "mesheryctl exp model [command] --help" for more information about a command.
```

@leecalcote this is the new behavior.

2024-04-09 16:11 UTC, vishalvivekm commented
Thank you @lekaf974 
Let's discuss this on Meshery Dev call, add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit) , if you would, please.

2024-04-09 19:29 UTC, RipulHandoo reviewed
Could you please clarify why we're logging the command usage twice in the PR description?

2024-04-09 19:33 UTC, RipulHandoo requested changes

2024-04-09 19:33 UTC, RipulHandoo commented on mesheryctl/internal/cli/root/system/model.go
> +		if len(args) == 0 {
Could you move the logic to the Args section for clarity?

2024-04-11 02:12 UTC, lekaf974 commented
@RipulHandoo by moving the logic in Args section the helper respponse is displayed following by the error message, is this the expected behavior ? 

new output
```bash
View list of models and detailed information of a specific model

Usage:
  mesheryctl exp model [flags]
  mesheryctl exp model [command]

Examples:

// To view list of components
mesheryctl exp model list

// To view a specific model
mesheryctl exp model view [model-name]
        

Available Commands:
  list        list registered models
  search      search models
  view        view model

Flags:
  -h, --help   help for model

Global Flags:
      --config string   path to config file (default "/home/matthieu/.meshery/config.yaml")
  -v, --verbose         verbose output

Use "mesheryctl exp model [command] --help" for more information about a command.
Error: Meshery server is not reachable: dial tcp [::1]:9081: connect: connection refused

```

changes
![image](https://github.com/meshery/meshery/assets/6630779/3ac2cae5-a60d-4d01-8199-2ba6af3e2ab5)

2024-04-12 03:40 UTC, RipulHandoo commented
> @RipulHandoo by moving the logic in Args section the helper respponse is displayed following by the same error message of the opened issue, is this the expected behavior ?
> 
> new output
> 
> ```shell
> View list of models and detailed information of a specific model
> 
> Usage:
>   mesheryctl exp model [flags]
>   mesheryctl exp model [command]
> 
> Examples:
> 
> // To view list of components
> mesheryctl exp model list
> 
> // To view a specific model
> mesheryctl exp model view [model-name]
>         
> 
> Available Commands:
>   list        list registered models
>   search      search models
>   view        view model
> 
> Flags:
>   -h, --help   help for model
> 
> Global Flags:
>       --config string   path to config file (default "/home/matthieu/.meshery/config.yaml")
>   -v, --verbose         verbose output
> 
> Use "mesheryctl exp model [command] --help" for more information about a command.
> Error: Meshery server is not reachable: dial tcp [::1]:9081: connect: connection refused
> ```

Nice.

2024-04-13 05:25 UTC, RipulHandoo commented on mesheryctl/internal/cli/root/system/model.go
>  			return cmd.Help()
```suggestion
	
```

2024-04-13 05:25 UTC, RipulHandoo commented on mesheryctl/internal/cli/root/system/model.go
>  		if len(args) == 0 {
```suggestion
```

2024-04-13 05:27 UTC, RipulHandoo requested changes

2024-04-13 05:27 UTC, RipulHandoo commented on mesheryctl/internal/cli/root/system/model.go
> +			return cmd.Help()
@lekaf974 Ensure error handling consistency: Consider returning errors for failed cmd.Help() calls and provide descriptive messages for better debugging.

2024-04-14 12:22 UTC, alphaX86 requested changes

2024-04-14 12:22 UTC, alphaX86 commented on mesheryctl/internal/cli/root/system/model.go
> +			return cmd.Help()
```suggestion
			return cmd.Help()
```
You can return an error message as @RipulHandoo said. Eg: `This command takes at least one arg.` and then you could use `cmd.Help()` to display the help message

2024-04-15 18:54 UTC, lekaf974 commented
@RipulHandoo @alphaX86 ready for review

2024-04-15 19:14 UTC, RipulHandoo requested changes

2024-04-15 19:14 UTC, RipulHandoo commented on mesheryctl/internal/cli/root/system/model.go
> +			return errors.New("please provide a subcommand")
Define an ErrInvalidArgs() (generic function).

2024-04-15 21:56 UTC, l5io commented
🚀 Preview for commit 7ea325a3bc02578eee5e6edd5591265ed52f4d0b at: https://661da26a32900c42e161d248--meshery-docs-preview.netlify.app

2024-04-16 05:24 UTC, RipulHandoo requested changes

2024-04-16 05:24 UTC, RipulHandoo commented on mesheryctl/internal/cli/root/system/model.go
> +				return nil
```suggestion
				return err
```

2024-04-16 05:24 UTC, RipulHandoo approved these changes

2024-04-20 22:50 UTC, lekaf974 commented
@alphaX86 approve is still required

2024-04-21 00:08 UTC, leecalcote approved these changes
Looking good.

2024-04-21 00:09 UTC, merged