make tables accessible in mobile view.
meshery/meshery pull request #10731
Opened 2024-04-14 19:53 UTC by Aseem22

**Notes for Reviewers**

This PR fixes #10704

This PR make tables used at various pages of references scrollable.

changes made at:
https://docs.meshery.io/reference/rest-apis
https://docs.meshery.io/reference/error-codes
https://docs.meshery.io/reference/mesheryctl

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-04-14 19:55 UTC, l5io commented
🚀 Preview for commit 70e0b704f7c63932ccd5ae2e3e0fa972f526804a at: https://661c34b000cb3bb092a135bc--meshery-docs-preview.netlify.app

2024-04-16 16:25 UTC, Yashsharma1911 commented
Thankyou for this @Aseem22 checks are failing, also video format if not supported

2024-04-16 16:47 UTC, leecalcote requested changes

2024-04-16 16:47 UTC, leecalcote commented on docs/pages/reference/error-codes.md
> +{% for files in site.data.errorref %}
@Aseem22 please revert this change in indentation.

2024-04-16 18:12 UTC, vishalvivekm commented
@Aseem22 Let's discuss this in Meshery dev call today. Add this as an agenda item to the meeting[ minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#), if you would :)

2024-04-17 12:20 UTC, Aseem22 commented
> @Aseem22 Let's discuss this in Meshery dev call today. Add this as an agenda item to the meeting[ minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#), if you would :)

Thanks @vishalvivekm. This issue has been discussed this monday on website meeting. I recieved some feedback which I am working on currently.

2024-05-13 06:23 UTC, vishalvivekm commented
> > @Aseem22 Let's discuss this in Meshery dev call today. Add this as an agenda item to the meeting[ minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#), if you would :)
> 
> Thanks @vishalvivekm. This issue has been discussed this monday on website meeting. I recieved some feedback which I am working on currently.

@Aseem22 
Do you have any updates on the issue ?
let's discuss this on today's website meeting at 5:30 PM IST. I am adding this as an [agenda item](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk). Please Join [https://meet.layer5.io/websites](https://www.google.com/url?q=http://meet.layer5.io/websites&sa=D&source=calendar&usd=2&usg=AOvVaw1CNpNwmYd_rTFcQa_7fBB5) if you are available during the meet.

2024-06-28 21:47 UTC, leecalcote commented
PR abandoned.

2024-06-28 21:47 UTC, closed without merging