Add custom dropdown
meshery/meshery pull request #10795
Opened 2024-04-26 01:17 UTC by 11happy

**Notes for Reviewers**

This PR fixes #9227, Currenlt I have added a custom drop down please see the attached image,

![Screenshot from 2024-04-26 06-38-36](https://github.com/meshery/meshery/assets/76656712/77394e33-5da4-4a7e-8de3-e0aa584d8563)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-04-26 01:21 UTC, l5io commented
🚀 Preview for commit 74f9778fbcacfcb0d2dd2aec7cf0c4be9b00806f at: https://662b014acd3a97456dc8caf3--meshery-docs-preview.netlify.app

2024-04-27 14:47 UTC, betelgeuse-code commented on docs/_sass/navbar.scss
> +    width: 83px;
We should use `rem`

2024-04-28 08:11 UTC, iArchitSharma requested changes
There are couple of problem

1. why is text color and arrow color different?
2. why are you displaying bullets?
3. test font should be same as rest of the header

2024-04-28 14:31 UTC, vishalvivekm commented
@11happy 
Adding the item to agenda for website call on Monday: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

2024-05-04 03:46 UTC, l5io commented
🚀 Preview for commit 6834f2a8033cc90b6ea5cc896cebf4d17a35bb15 at: https://6635af6c240d769649e97c76--meshery-docs-preview.netlify.app

2024-05-04 11:09 UTC, 11happy commented
As soon as my academic commitments ease up by 8-9 may, I'll promptly update the PR. Thank you for being patient with this PR.

2024-05-09 14:49 UTC, 11happy commented
I have addressed all the above suggestions.

2024-05-09 14:51 UTC, l5io commented
🚀 Preview for commit b4a9935b29ea9ddee0dd53d9027e66783ae7d419 at: https://663ce2c9db4c2d00ac8d10fa--meshery-docs-preview.netlify.app

2024-05-13 06:21 UTC, vishalvivekm commented
Hey @11happy , let's discuss this on today's website meeting today at 7 AM CT. I am adding this as an [agenda item](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk). Please Join [https://meet.layer5.io/websites](https://www.google.com/url?q=http://meet.layer5.io/websites&sa=D&source=calendar&usd=2&usg=AOvVaw1CNpNwmYd_rTFcQa_7fBB5) if you are available during the meet.

2024-05-18 14:41 UTC, vishalvivekm commented
> Hey @11happy , let's discuss this on today's website meeting today at 7 AM CT. I am adding this as an [agenda item](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk). Please Join [https://meet.layer5.io/websites](https://www.google.com/url?q=http://meet.layer5.io/websites&sa=D&source=calendar&usd=2&usg=AOvVaw1CNpNwmYd_rTFcQa_7fBB5) if you are available during the meet.

Will you join next websites call on Monday to discuss this item @11happy ?

2024-05-18 15:10 UTC, 11happy commented
Yes I will be able to join this monday, I am sorry for not being able to attend last week due to my health issues.

2024-05-20 13:24 UTC, 11happy commented
If its okay can we discuss this on dev meet wednesday as today time didn't allow :(

2024-05-21 19:40 UTC, iArchitSharma commented
@11happy please remove the border color
![image](https://github.com/meshery/meshery/assets/74408634/e6ff9036-fe1a-4268-9bb5-fd312a245a86)

2024-07-12 16:14 UTC, closed without merging