[relationships] add edge mount  relationship between Hashicorp vault and k8's secrets
meshery/meshery pull request #10819
Opened 2024-04-30 09:43 UTC by deepak4566

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-05-01 23:04 UTC, leecalcote commented
🥇

2024-05-07 08:40 UTC, RipulHandoo requested changes

2024-05-07 08:40 UTC, RipulHandoo commented on server/meshmodel/k8svault-controller/relationships/edge_relationship.json
> +                [
```suggestion
                ["name"],
                ["namespace"]
```

2024-05-07 08:40 UTC, RipulHandoo commented on server/meshmodel/k8svault-controller/relationships/edge_relationship.json
> +                  "spec.secret.name",
This is not going to work. 
Update the path to `["settings" ,"spec", "secret", "name"]`.

2024-05-07 08:40 UTC, RipulHandoo commented on server/meshmodel/k8svault-controller/relationships/edge_relationship.json
> +                  "spec.secret.namespace"
Same.

2024-05-07 08:40 UTC, RipulHandoo commented on server/meshmodel/k8svault-controller/relationships/edge_relationship.json
> +              "mutatedRef": [
This field is for the Inventory relationship.

2024-05-07 08:40 UTC, RipulHandoo commented on server/meshmodel/k8svault-controller/relationships/edge_relationship.json
> +    "description": ""
Please add description.

2024-05-07 08:40 UTC, RipulHandoo commented on server/meshmodel/k8svault-controller/relationships/edge_relationship.json
> +    "version": "0.1.2",
Will this relationship work for `version: "0.1.2"`, but not for `version: "1.1.155"` ?

2024-05-07 08:40 UTC, RipulHandoo commented on server/meshmodel/k8svault-controller/relationships/edge_relationship.json
> +    "version": "0.1.2",
If it works for both use `version: "*"`.

2024-05-07 08:40 UTC, RipulHandoo commented on server/meshmodel/k8svault-controller/relationships/edge_relationship.json
> +   "subType": "Mount",
Could you please ensure that you are specifying the relationship for subType -> Mount? Currently, I don't see any components being mounted.

2024-05-07 08:40 UTC, RipulHandoo commented on server/meshmodel/k8svault-controller/relationships/edge_relationship.json
> +             "patch": {
These fields won't work for `Mount` relationship.

2024-05-07 08:40 UTC, RipulHandoo commented on server/meshmodel/k8svault-controller/relationships/edge_relationship.json
> +{
Please rename the file. It should be `edge_<relationship_subType>.json`

2024-05-07 08:41 UTC, RipulHandoo commented
@deepak4566, could you please provide a working proof of this PR? A screen recording would be preferred.

2024-05-07 09:11 UTC, RipulHandoo commented
If you're considering setting up a Mount relationship, I found this resource helpful: https://www.hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar.
 It offers guidance on injecting Vault secrets into Kubernetes pods via a sidecar. Just a heads-up, this is just one reference among many available. Feel free to explore other documentation and resources as well.

2024-05-14 15:21 UTC, leecalcote requested changes
Is this supposed to have a third component implicated? Which of the three components is to sit atop the edge?

Will you contrast this against the existing PVC mount relationship?

A description of the relationship is still missing.

2024-05-14 15:22 UTC, leecalcote commented
Have you tested this relationship? Does it mutate the implicated components as expected? Are you able to deploy Vault and bind the Secret successfully with this relationship? 

@deepak4566, please demo this at tomorrow's Meshery Dev meeting. Add the agenda, if you would.

2024-05-15 11:39 UTC, deepak4566 commented
> Have you tested this relationship? Does it mutate the implicated components as expected? Are you able to deploy Vault and bind the Secret successfully with this relationship?
> 
> @deepak4566, please demo this at tomorrow's Meshery Dev meeting. Add the agenda, if you would.

i think at present this relationship doesnt work , before this relationship between secrets i think there is need of some other relationships like mount service account jwt token to vault and role , and many more .

2024-07-06 01:11 UTC, closed without merging