org & workspace
meshery/meshery pull request #10812
Opened 2024-04-29 15:43 UTC by captain-Akshay

**Notes for Reviewers**

This PR fixes #
[Screencast from 2024-04-29 18-47-19.webm](https://github.com/meshery/meshery/assets/59491379/e1f2863b-785c-4769-a477-1c7432b69c13)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-04-30 01:09 UTC, dragon-slayer875 requested changes
Please check these out.

2024-05-01 23:04 UTC, leecalcote commented
merge conflicts...

2024-05-05 20:50 UTC, leecalcote commented
@captain-Akshay merge conflicts...

2024-05-06 08:16 UTC, ShivamCoder23 requested changes

2024-05-06 08:16 UTC, ShivamCoder23 commented on ui/assets/icons/WorkspaceOutlinedIcon.js
> +function WorkspaceOutlinedIcon({ width = '24px', height = '24px', fill = '#F6F8F8' }) {
put theme in sistent

2024-05-06 19:24 UTC, leecalcote commented
@captain-Akshay merge conflicts...

2024-05-07 11:22 UTC, closed without merging