[useDesignLifecycle.js] fixed a bug where an error used to come when renaming/saving/updating design
meshery/meshery pull request #10857
Opened 2024-05-03 03:08 UTC by Aryakoste

**Notes for Reviewers**

This PR fixes https://github.com/meshery/meshery/issues/10738

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [*] Yes, I signed my commits.

2024-05-03 07:28 UTC, codeKraken19 commented
Looks good , Thankyou @Aryakoste

2024-05-06 08:13 UTC, ShivamCoder23 requested changes

2024-05-06 08:13 UTC, ShivamCoder23 commented on ui/components/configuratorComponents/MeshModel/hooks/useDesignLifecycle.js
> +    const designYamlBytes = new TextEncoder().encode(designYaml);
do we need this @Yashsharma1911

2024-06-15 23:41 UTC, shubham251972 requested changes
@Aryakoste thanks for creating this PR, are you still working on this, please fix the merge conflict and let's ensure we merge this PR

2024-06-16 06:03 UTC, Aryakoste commented
The function getUnit8ArrayForDesign has been added by someone which does the same as what i have done. Convert it into Unit8 Byte array which solves the issue. So which changes i should merge. @Yashsharma1911 @shubham251972

2025-04-23 08:21 UTC, amitamrutiya commented
This issue is already fixed. Thank you @Aryakoste .

2025-04-23 08:21 UTC, closed without merging