Workspace and org
meshery/meshery pull request #10884
Opened 2024-05-07 11:22 UTC by captain-Akshay

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-05-07 19:48 UTC, leecalcote approved these changes
This is working well in my tests.

It would be ideal to see a screenshot of the empty state (of an expired session or missing org id).

2024-05-07 19:55 UTC, leecalcote commented
@captain-Akshay Here is my experience while using the Local Provider:

<img width="1405" alt="Screenshot 2024-05-07 at 2 53 41 PM" src="https://github.com/meshery/meshery/assets/7570704/8c4ed188-1037-4c3f-b6fa-d4ee18e5140e">

2024-05-07 20:20 UTC, captain-Akshay commented
Duplication is an issue I will try to fix it

2024-05-07 20:34 UTC, betelgeuse-code commented
> Duplication is an issue I will try to fix it

This duplication happens because of bad logic in the server itself, whenever Meshery boots it registers a new org, @captain-Akshay this is server specific issue not on UI

2024-05-07 20:42 UTC, betelgeuse-code approved these changes
LGTM

2024-05-07 20:42 UTC, betelgeuse-code commented on ui/components/SpacesSwitcher/SpaceSwitcher.js
> +  },
We are avoiding to use makeStyles @captain-Akshay

2024-05-07 21:32 UTC, leecalcote commented
> > Duplication is an issue I will try to fix it
> 
> This duplication happens because of bad logic in the server itself, whenever Meshery boots it registers a new org, @captain-Akshay this is server specific issue not on UI

Where has the issue been filed to fix the poor Server behavior? Merging this PR only exacerbates exposure of this poor behavior.

2024-05-08 03:38 UTC, leecalcote requested changes
Must use styled components.

This is something that @captain-Akshay already knows (or at least has already been informed of multiple times).

2024-05-08 12:33 UTC, leecalcote commented
> Must use styled components.
> 
> This is something that @captain-Akshay already knows (or at least has already been informed of multiple times).

@captain-Akshay please fix today.

2024-05-08 12:33 UTC, leecalcote commented
> > Duplication is an issue I will try to fix it
> 
> This duplication happens because of bad logic in the server itself, whenever Meshery boots it registers a new org, @captain-Akshay this is server specific issue not on UI

Open a new issue, please.

2024-05-08 12:51 UTC, Yashsharma1911 commented
> > > Duplication is an issue I will try to fix it
> > 
> > 
> > This duplication happens because of bad logic in the server itself, whenever Meshery boots it registers a new org, @captain-Akshay this is server specific issue not on UI
> 
> Open a new issue, please.

Issue is alreay being opened here - https://github.com/meshery/meshery/issues/10594

2024-05-08 17:31 UTC, Yashsharma1911 commented
> > > > Duplication is an issue I will try to fix it
> > > 
> > > 
> > > This duplication happens because of bad logic in the server itself, whenever Meshery boots it registers a new org, @captain-Akshay this is server specific issue not on UI
> > 
> > 
> > Open a new issue, please.
> 
> Issue is alreay being opened here - #10594, I will raise a fix today

I raised a fix Here - https://github.com/meshery/meshery/pull/10899/files

2024-05-10 23:17 UTC, leecalcote commented
Is there an open PR in Meshery Extensions?

2024-05-10 23:17 UTC, leecalcote approved these changes

2024-05-13 22:31 UTC, leecalcote commented
@captain-Akshay what Meshery Docs did you update based on this change?

2024-05-13 22:31 UTC, leecalcote requested changes
Build warning:

```
./components/Header.js
457:21  Warning: Missing "key" prop for element in iterator 
```

2024-05-14 15:33 UTC, merged