Err comp config pairs code
meshery/meshery pull request #10895
Opened 2024-05-08 07:12 UTC by Jougan-0

**Notes for Reviewers**

This PR fixes #10762 

Update documentation and error codes in Go by including missing long descriptions, probable causes, and suggested remedy.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-05-08 07:15 UTC, l5io commented
🚀 Preview for commit 04e8b86728a79aa6bdf4066afc0e02dcaef1da9e at: https://663b26842cc488d107b159c0--meshery-docs-preview.netlify.app

2024-05-14 15:14 UTC, leecalcote requested changes

2024-05-14 15:14 UTC, leecalcote commented on docs/_data/errorref/meshery-server_errors_export.json
> +        "probable_cause": "Missing or invalid user token, invalid Kubernetes handler or serviceActionProvider error.",
Refactor to make this user-facing. To a user, what is a Kubernetes handler or serviceActionProvider? 

Users know about Meshery Connections and can be offered a link to troubleshooting or understanding connections and Meshery's interactions with Kubernetes (in Meshery Docs), but they will not understand references to function names or golang routines.

2024-05-14 16:32 UTC, l5io commented
🚀 Preview for commit 06c4a8c0e87309c2da28576b27526d78cd6a320e at: https://664391e13eb358009ebe2e20--meshery-docs-preview.netlify.app

2024-05-14 16:36 UTC, Jougan-0 commented
should MeshMap Screenshot Service / MeshMapScreenshot (pull_request_target) 
this fail?

2024-05-22 17:40 UTC, l5io commented
🚀 Preview for commit b9a0b2971861b4653b4a9b07ba2333c0f7934867 at: https://664e2de3ab580a0417858800--meshery-docs-preview.netlify.app

2024-05-22 17:40 UTC, MUzairS15 requested changes

2024-05-22 17:40 UTC, MUzairS15 commented on server/handlers/error.go
> +	return errors.New(ErrCompConfigPairsCode, errors.Alert, []string{"Unable to Create Component Configuration.", err.Error()}, []string{("An error occurred while trying to create Component Configuratio
Add name of the component for which it failed, (its kind and name).
> "Missing or invalid user token, or an issue with Meshery's interactions with Kubernetes." 
only single cause?
1. No registered model/comp  found inside registry
2. failed validation

Will you verify what error you get if we try to deploy a CR inside a cluster which doesn't have a CRD deployed.

What error you get from meshery vs when you do same from kubectl

2024-07-01 21:57 UTC, leecalcote approved these changes

2024-07-10 12:19 UTC, Jougan-0 commented
Closing this as @singh1203 is working on similar issue and is updating the error.

2024-07-10 12:19 UTC, closed without merging