[Docs]Added Kubernetes Deployments using Meshery Playground tutorial
meshery/meshery pull request #10987
Opened 2024-05-17 08:03 UTC by deepak4566

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-05-17 08:06 UTC, l5io commented
🚀 Preview for commit 0780609b844596d3a5b77beb45bfcc3d5b4099f6 at: https://66470fe15b0c7988ef32658b--meshery-docs-preview.netlify.app

2024-05-17 08:59 UTC, l5io commented
🚀 Preview for commit 3094c300194ba67d32d6e9757e89b1dd7493a9ec at: https://66471c6084ebc7921fd9f325--meshery-docs-preview.netlify.app

2024-05-17 14:51 UTC, l5io commented
🚀 Preview for commit cf7e65ab23a64bb6582a70ae350a3d36d2b562b1 at: https://66476ed91ee1d0e034011400--meshery-docs-preview.netlify.app

2024-05-27 15:50 UTC, l5io commented
🚀 Preview for commit daf92bfbcbe4ce40bb8a10ad504517c773f97472 at: https://6654ab95b7b01c3d8d1331f4--meshery-docs-preview.netlify.app

2024-07-12 13:07 UTC, dusdjhyeon requested changes

2024-07-12 13:07 UTC, dusdjhyeon commented on docs/pages/guides/tutorials/Kubernetes-deployments.md
> +   7. In the Spec section , U  will have an option to define **replicas**, fill that with ur desired number of replicas and  for this tutorial we can use three replicas as the base minimum .
IMO, since this is docs for users, it seems more appropriate to use `you` wherever you use `u` or `U`.

2024-07-12 13:07 UTC, dusdjhyeon commented on docs/pages/guides/tutorials/Kubernetes-deployments.md
> +   18. after this u can see a golden layer is present behind deployment .
Why do you go from 19 to 18 again?

2024-07-12 13:07 UTC, dusdjhyeon commented on docs/pages/guides/tutorials/Kubernetes-deployments.md
> +   19. After this whole process , click on validate button to have an validation of errors before deployment.
You're back to number 19.

2026-04-14 10:34 UTC, matrixkavi commented
Closing this PR as the author seems to have abandoned the effort

2026-04-14 10:34 UTC, closed without merging