[Cert-manager]: Sync upstream master and add cert-manager relationships
meshery/meshery pull request #10986
Opened 2024-05-17 07:24 UTC by innocentrda

**Notes for Reviewers**

This PR fixes #

![Screenshot from 2024-05-16 13-38-36](https://github.com/meshery/meshery/assets/82156933/0462c4cd-6b77-4277-adc1-cb63db9eed11)

In cert-manager, a secret may contain certificate data, and the Issuer resource references the secret resource by name to access the certificates. In other words, the Issuer is  is patched with the configuration of the Secret. This is Hierarchical-Inventory relationship similar to Secret-Pod relationship. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-05-17 13:44 UTC, deepak4566 requested changes
A proof of working relationship as video or screenshot would be benificial

2024-05-22 22:45 UTC, leecalcote commented on server/meshmodel/cert-manager/relationships/hierarchical_inventory.json
> +      "version": "1.14"
@innocentrda yes/no?

2024-05-22 22:45 UTC, leecalcote commented on server/meshmodel/cert-manager/relationships/hierarchical_inventory.json
> +      "version": "1.14"
Please add this as a Relationship authoring best practice.

2024-05-23 11:34 UTC, innocentrda commented on server/meshmodel/cert-manager/relationships/hierarchical_inventory.json
> +      "version": "1.14"
Yes it's done

2024-07-10 17:45 UTC, leecalcote approved these changes

2024-07-10 17:45 UTC, merged