Warning mesheryctl start
meshery/meshery pull request #10997
Opened 2024-05-19 00:10 UTC by Jougan-0

**Notes for Reviewers**

This PR fixes #

- [ ] Add warn command and if docker use give an error command
- [ ] docs update for --port-forward command add a note that it is intended to work with docker only
- [ ] Note addition to kubernetes getting started page
- [ ] Note addition to Guides file

@leecalcote Might need to re-position this( placement of include) in dashboard.go couldn't figure out where to keep it . Currently under Example I am unable to understand where to place them so that it can be detected other than example and long description. The placement in docs gives error.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-05-19 00:26 UTC, l5io commented
🚀 Preview for commit fcfa157da3567c2a7289272b914caf1546f184cb at: https://6649471156a6513f8608f6d0--meshery-docs-preview.netlify.app

2024-05-19 00:31 UTC, Jougan-0 commented
For mesheryctl docs update to be shown do we need to pass something else I wonder?

2024-05-19 00:48 UTC, Jougan-0 commented
https://github.com/meshery/meshery/actions/runs/9143648489/job/25140595734?pr=10997#step:7:317

this error because the old pr of json returning panic for error
https://github.com/meshery/meshkit/pull/496

needs to merge .

2024-05-22 17:53 UTC, MUzairS15 requested changes

2024-05-22 17:53 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/system/dashboard.go
> +			log.Warn("The current flag is intended for use exclusively when Meshery is deployed on a Kubernetes platform.")
Only if `port-forward` flag is used, issue this warning.

2024-05-22 22:41 UTC, leecalcote commented
merge conflict.

2024-05-23 13:38 UTC, l5io commented
🚀 Preview for commit fde18f22be524efb239001b4437b7a5f6cc5d3d2 at: https://664f46b64da29f0099664e48--meshery-docs-preview.netlify.app

2024-05-23 14:08 UTC, l5io commented
🚀 Preview for commit 364998e55875a7a648905f45a098f9f896b9ef85 at: https://664f4dd7a662f50b3fd9e8da--meshery-docs-preview.netlify.app

2024-05-25 14:41 UTC, leecalcote commented
merge conflict

2024-05-25 14:50 UTC, l5io commented
🚀 Preview for commit ca91df044c73f76577d36bfca58a5df2a302c4df at: https://6651fa8839c2b05cd4abbcd6--meshery-docs-preview.netlify.app

2024-05-25 14:57 UTC, l5io commented
🚀 Preview for commit 04c91d22eeabd7e0b17568c5dc08fef14064fce5 at: https://6651fc2739c2b05e9eabbede--meshery-docs-preview.netlify.app

2024-06-27 13:02 UTC, leecalcote commented on docs/_includes/mesheryctl/system-dashboard.md
> +Note: The `--port-forward` flag is intended for use exclusively when Meshery is deployed on a "Kubernetes" platform.
```suggestion
Note: The `--port-forward` flag is intended for use exclusively when Meshery is deployed in a Kubernetes cluster (`platform: kubernetes`).
```

2024-06-27 13:05 UTC, leecalcote approved these changes

2024-06-27 13:07 UTC, l5io commented
🚀 Preview for commit 703d19984d46a0ec5cf12456da9786bc9705e393 at: https://667d63f6caa5b7d91ff0dcb1--meshery-docs-preview.netlify.app

2024-07-01 21:53 UTC, leecalcote approved these changes

2024-07-01 21:53 UTC, merged