added responsiveness to "remote provider" page
meshery/meshery pull request #11096
Opened 2024-06-02 18:33 UTC by hargunkaur286

**Notes for Reviewers**

This PR fixes #10743 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-06-03 00:46 UTC, leecalcote commented
@nebula-aac here's one...

2024-06-12 13:41 UTC, vishalvivekm commented
Thank you @hargunkaur286 
Let's discuss this in Meshery Dev meeting starting in 20 minutes.
Meeting minutes: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#
Meeting link: https://meet.layer5.io/meshery

2024-06-13 01:03 UTC, shubham251972 requested changes

2024-06-13 01:03 UTC, shubham251972 commented on ui/components/UserPreferences/index.js
> +    backgroundColor: theme.palette.type === 'dark' ? '#3D4F57' : '#C9DBE3',
@hargunkaur286 thankyour for working on it, please use theme colors

2024-06-29 06:39 UTC, sudhanshutech requested changes

2024-06-29 06:39 UTC, sudhanshutech commented on ui/components/UserPreferences/index.js
> +    backgroundColor: theme.palette.type === 'dark' ? '#3D4F57' : '#C9DBE3',
why adding these colors? Use themeing instead.

2024-07-07 19:39 UTC, closed without merging