fix when mouse leaves the avatar or menu area the menu should be closed
meshery/meshery pull request #11115
Opened 2024-06-05 07:32 UTC by EleisonC

**Notes for Reviewers**

This PR fixes #11015

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-06-05 07:39 UTC, EleisonC commented
@Jougan-0 @leecalcote

2024-06-05 13:20 UTC, aabidsofi19 requested changes

2024-06-05 14:29 UTC, EleisonC commented on ui/components/User.js
> +  useEffect(() => {
Hey, @aabidsofi19 could you point me to the library or popper event that I would use to achieve this without timeouts?

2024-06-11 23:43 UTC, leecalcote commented on ui/components/User.js
> +  useEffect(() => {
Checking back in...

2024-06-12 13:27 UTC, EleisonC commented on ui/components/User.js
> +  useEffect(() => {
Hey @leecalcote I was able to solve it with out the timeout am just dealing with the merge conflicts from signing off

2024-06-12 13:28 UTC, l5io commented
🚀 Preview for commit 02e3419ef683e0339f3dad01d423f43006542127 at: https://6669a265c556462db01a1dce--meshery-docs-preview.netlify.app

2024-06-12 13:31 UTC, leecalcote requested changes
Over 2,000 file changes included here. This PR should contain only changes pertinent to the issue it’s fixing. Commits from other people for other issues should not be included.

2024-06-12 14:00 UTC, l5io commented
🚀 Preview for commit 692fe233156f3c0f4e2554ced5320fb519214092 at: https://6669a9e8fd5589343c24dda4--meshery-docs-preview.netlify.app

2024-06-12 14:01 UTC, closed without merging