[Docs] Add Tutorial :Deploying PHP Guestbook application(Stateless) with Redis
meshery/meshery pull request #11198
Opened 2024-06-17 11:06 UTC by deepak4566

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-06-17 11:09 UTC, l5io commented
🚀 Preview for commit e1dbf01074d45e3dc1f59c3d818c1e8a9df82957 at: https://66701969e6b7b137f80cd592--meshery-docs-preview.netlify.app

2024-06-17 12:56 UTC, deepak4566 commented
@vishalvivekm //

2024-06-17 14:11 UTC, l5io commented
🚀 Preview for commit 0c866da9f589605c661a8ddfd824c159761fa1fb at: https://6670440aee256521b4ba5503--meshery-docs-preview.netlify.app

2024-07-12 13:17 UTC, dusdjhyeon requested changes

2024-07-12 13:17 UTC, dusdjhyeon commented on docs/pages/guides/tutorials/Deploying-Guestbook-Application-With-Redis.md
> +- shery Playground_. If you don't have an account, sign up at [Meshery Playground](https://meshery.layer5.io/).
Don't line break.

2024-07-12 13:17 UTC, dusdjhyeon commented on docs/pages/guides/tutorials/Deploying-Guestbook-Application-With-Redis.md
> +- Basic understanding of containerization , Kubernetes concepts and basic knowledge of reddis .
reddis -> redis

2024-07-12 13:17 UTC, dusdjhyeon commented on docs/pages/guides/tutorials/Deploying-Guestbook-Application-With-Redis.md
> +- Basic understanding of containerization , Kubernetes concepts and basic knowledge of reddis .
Delete the space before the comma(,) and the space before the period(.).

2024-07-12 13:17 UTC, dusdjhyeon commented on docs/pages/guides/tutorials/Deploying-Guestbook-Application-With-Redis.md
> +#### Step6 - Vizualizing  the Cassandra StatefulSet
Vizualizing -> Visualizing

2024-07-12 13:17 UTC, dusdjhyeon commented on docs/pages/guides/tutorials/Deploying-Guestbook-Application-With-Redis.md
> +#### Step6 - Vizualizing  the Cassandra StatefulSet
Also, is the docs about Cassandra correct?

2024-11-09 02:15 UTC, closed without merging