[mesheryctl] consistent mesheryctl pattern list
meshery/meshery pull request #11264
Opened 2024-06-28 03:38 UTC by dusdjhyeon

**Notes for Reviewers**

This PR fixes #11248 
Now, pattern list is consistent with pattern model
![image](https://github.com/meshery/meshery/assets/73868703/23bc6174-0fb7-41f1-848a-53ddddef642c)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-06-28 03:41 UTC, l5io commented
🚀 Preview for commit d5056cd61f6343537423daff3b5bd3e015e02b0f at: https://667e30d60c97fbc08d6ea3e8--meshery-docs-preview.netlify.app

2024-06-28 03:59 UTC, l5io commented
🚀 Preview for commit fe63af47349948fc8d92cd3ddf1415275e73469a at: https://667e351de6cd03be44647e59--meshery-docs-preview.netlify.app

2024-06-28 04:07 UTC, l5io commented
🚀 Preview for commit c96eaf5d65f4be4e4275aba8e8b789bc537cf9e9 at: https://667e36d2343796c6fb03d79d--meshery-docs-preview.netlify.app

2024-06-28 04:09 UTC, dusdjhyeon commented
Because I added a call to the HandlePagination function, the loop stops when there is an event(such as keyboard input), which causes the existing pattern's [list_test ](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/pattern/list_test.go)to fail. 
@Jougan-0 Can you give me some feedback on this?

2024-06-28 08:32 UTC, Jougan-0 commented
> Because I added a call to the HandlePagination function, the loop stops when there is an event(such as keyboard input), which causes the existing pattern's [list_test ](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/pattern/list_test.go)to fail. @Jougan-0 Can you give me some feedback on this?

Try using pagination rather than calling normal route use ```--page``` flag and in query.
Though these tests are not appropriate but this should fix the issue.
Tests are written badly that just queries the route and command and matches the output.

2024-06-28 23:23 UTC, l5io commented
🚀 Preview for commit c14d259d67a69cb04f02024fe00f18ec6ab1cb8a at: https://667f45d0ca7a2bb8189621c0--meshery-docs-preview.netlify.app

2024-06-30 06:08 UTC, Jougan-0 commented
@dusdjhyeon Unit and Integrations test failing.

2024-06-30 06:51 UTC, dusdjhyeon commented
> @dusdjhyeon Unit and Integrations test failing.


![image](https://github.com/meshery/meshery/assets/73868703/3d6ef007-c50b-4456-ac12-37cbb3a15007)

Since we no longer want the bottom to represent TOTAL(even with the --page flag), I deleted that part of the list golden file in test data as shown above.
But, the golden testdata is used in many places, so it looks like an error occurred. 
I can put the TOTAL back in, and set the expected error in list_test to true.
If you don't think that's appropriate, I don't know how to resolve it,,

2024-06-30 22:24 UTC, Jougan-0 commented on docs/pages/reference/mesheryctl/mesheryctl-pattern-list.md
> +View list of models with specified page number (25 models per page)
This is auto-generated when you run `make docs` inside `mesheryctl`.

2024-07-01 00:43 UTC, l5io commented
🚀 Preview for commit af386e56c384f03c968334af033fccfb17ed2488 at: https://6681fb84cd6edb71bd2866dc--meshery-docs-preview.netlify.app

2024-07-01 06:19 UTC, singh1203 requested changes

2024-07-01 06:19 UTC, singh1203 commented on docs/pages/reference/mesheryctl/mesheryctl-pattern-list.md
> +      --config string   path to config file (default "/home/dusdjhyeon/.meshery/config.yaml")
it is correct to point config file path `/home/dusdjhyeon/.meshery/config.yaml` instead of `/home/user/.meshery/config.yaml` like something.

2024-07-01 13:19 UTC, Jougan-0 commented on docs/pages/reference/mesheryctl/mesheryctl-pattern-list.md
> +  -h, --help       help for list
@dusdjhyeon this auto-generated I don't think we need to pass this in a PR.
Here it is done with this [GH action](https://github.com/meshery/meshery/actions/runs/9744810579).

2024-07-01 14:04 UTC, l5io commented
🚀 Preview for commit 1d7bdf2cbe4a64ebec19b74469ffbb2204858450 at: https://6682b75bf3a7c708014c56e6--meshery-docs-preview.netlify.app

2024-07-02 18:41 UTC, Deepak0320Singhal commented
@dusdjhyeon Let's discuss this in Meshery Dev meeting on Wednesday. Adding this as an agenda item....
Meeting minutes: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#
Meeting link: https://meet.layer5.io/meshery

2024-07-10 17:02 UTC, leecalcote commented
Merge conflict. @dusdjhyeon, I believe this is ready to merge once the conflict is addressed.

2024-07-10 17:03 UTC, leecalcote approved these changes

2024-07-10 17:04 UTC, leecalcote approved these changes
Merge conflict resolved.

2024-07-10 17:04 UTC, merged

2024-07-10 17:05 UTC, Jougan-0 commented
> A final review, @Jougan-0, would be good.

Was GTG forgot to approve.