[Feat] `mesherywtl model export` command
meshery/meshery pull request #11338
Opened 2024-07-07 18:13 UTC by humblenginr

**Notes for Reviewers**

This PR adds support for `mesheryctl model export <model-name>` command. It includes three flags: `output-type`, `include-components` and `include-relationships` as of now

This makes use of the meshkit https://github.com/meshery/meshkit/pull/530 pr. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-07-08 10:34 UTC, MUzairS15 reviewed
Having an additional flag for specifying output location is good to have.

2024-07-08 17:55 UTC, MUzairS15 requested changes

2024-07-08 17:55 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/model/model.go
> +		utils.Log.Error(fmt.Errorf("Could not write model file: %s", err))
Same here and at few other places.

2024-07-08 17:55 UTC, MUzairS15 commented on mesheryctl/internal/cli/root/model/model.go
> +		utils.Log.Error(fmt.Errorf("Could not reach meshery server: %s", err))
This will panic, as it isn't meshkit compatible error.

2024-07-09 11:59 UTC, humblenginr commented
This has to be merged and released - https://github.com/meshery/meshkit/pull/534/

2024-07-09 12:01 UTC, humblenginr commented
Note: New meshkit release needs to be done and updated here.

2024-07-09 12:01 UTC, humblenginr commented
This PR needs to be merged after the meshkit PR in order for the mesheryctl build to succeed.

2024-07-09 17:40 UTC, aabidsofi19 approved these changes
Looks good :rocket:

2024-07-09 17:41 UTC, merged

2024-07-10 03:48 UTC, PalashChitnavis commented
hey @humblenginr , you removed a closing bracket in go.mod file at line 336, by mistake i guess 🫠