docs: fixed link not working in contributing-ui-notification-center.md
meshery/meshery pull request #11353
Opened 2024-07-09 18:54 UTC by ashish0kumar

**Notes for Reviewers**

This PR fixes #11349

Link navigating to Meshery UI docs not working in Contributing to Meshery UI - Notification Center page
fixed this by simply adding the desired link: (https://docs.meshery.io/project/contributing/contributing-ui) in docs/pages/project/contributing/contributing-ui-notification-center.md

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2024-07-09 18:58 UTC, l5io commented
🚀 Preview for commit e1daec83281068ccf30b8c6b3c4d0cef170067ce at: https://668d881efdccceccb06c2863--meshery-docs-preview.netlify.app

2024-07-10 05:26 UTC, vishalvivekm commented
@ashish0kumar 
Let's discuss this in Meshery Dev meeting starting 7:30 PM IST Today. Add this as an agenda item to the meeting minutes, if you would :)
Meeting minutes: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#
Meeting link: https://meet.layer5.io/meshery

2024-07-10 16:39 UTC, leecalcote requested changes

2024-07-10 16:39 UTC, leecalcote commented on docs/pages/project/contributing/contributing-ui-notification-center.md
> +  <ol><li><a href="https://docs.meshery.io/project/contributing/contributing-ui">Contributing to Meshery UI</a></li></ol>
Thanks!

Will you use `{{site.baseurl}}` instead of `https://docs.meshery.io`?

2024-07-10 18:55 UTC, l5io commented
🚀 Preview for commit dd03c1290ddf35358574142d040c0c48a2c5614b at: https://668ed907f53fa73d6d327086--meshery-docs-preview.netlify.app

2024-07-11 10:47 UTC, l5io commented
🚀 Preview for commit 0a381d5aade59c383373a1fc5568cde114d38de1 at: https://668fb81bb79f1f20ba6a56bb--meshery-docs-preview.netlify.app

2024-07-21 10:00 UTC, closed without merging

2024-07-21 14:06 UTC, leecalcote commented
@ashish0kumar will you be fixing this issue or have you abandoned the effort entirely?

@Muhammed-Moinuddink, please fix this issue.