Update contributing-model-relationships.md
meshery/meshery pull request #11377
Opened 2024-07-11 17:13 UTC by humblenginr

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-07-11 17:16 UTC, l5io commented
🚀 Preview for commit 5ebf37e29cc3d6884f3f21150dffcef1264b84fe at: https://6690136ce471f914b33fb6c4--meshery-docs-preview.netlify.app

2024-07-11 21:22 UTC, leecalcote commented on docs/pages/project/contributing/contributing-model-relationships.md
> +{% include alert.html title="Caution While Defining Relationships" type="warning" content="Relationships are not imported directly and they have to be packaged inside a model. Use caution when defini
```suggestion
{% include alert.html title="Gratuitous Scoping of Relationships" type="warning" content="Relationships are not imported directly and they have to be packaged inside a model. Use caution when defining relationships that span models." %}
```

2024-07-11 21:23 UTC, leecalcote requested changes

2024-07-11 21:23 UTC, leecalcote commented on docs/pages/project/contributing/contributing-model-relationships.md
> +{% include alert.html title="Caution While Defining Relationships" type="warning" content="Relationships are not imported directly and they have to be packaged inside a model. Use caution when defini
"Relationships are not imported directly and they have to be packaged inside a model." There is some relevance of this information to the warning, but it's not clear what that is given this phrasing and lack of explanation. Please revisit.

2024-07-11 21:23 UTC, leecalcote commented on docs/pages/project/contributing/contributing-model-relationships.md
> +{% include alert.html title="Caution While Defining Relationships" type="warning" content="Relationships are not imported directly and they have to be packaged inside a model. Use caution when defini
"Use caution when defining relationships that span models." Great. Why? Where's the explanation here?

2024-07-16 05:29 UTC, Ashparshp commented
@humblenginr Could we discuss this issue during the Meshery dev meeting call? Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

2024-07-19 12:15 UTC, leecalcote commented
@humblenginr, thoughts on the feedback offered? Please accept or reject each point of feedback.

2024-07-19 12:40 UTC, l5io commented
🚀 Preview for commit ba04c00016e015912a2d84ff137ceba064db3a10 at: https://669a5eabb2a59436b89e90e3--meshery-docs-preview.netlify.app

2024-07-19 20:53 UTC, leecalcote commented on docs/pages/project/contributing/contributing-model-relationships.md
> +{% include alert.html title="Caution While Defining Relationships" type="warning" content="Relationships are not imported directly and they have to be packaged inside a model. Use caution when defini
This feedback has not been addressed.

2024-07-19 20:53 UTC, leecalcote requested changes
The current warning is insufficiently introduced to the reader, leaving them no better off in terms of the objective of this warning.

2024-07-20 02:31 UTC, humblenginr commented
Updated the warning

2024-07-20 02:33 UTC, l5io commented
🚀 Preview for commit 0ad4eccf04f82d17e85055bf635604af7a3e4488 at: https://669b21d028818da1854f9ebe--meshery-docs-preview.netlify.app

2024-11-09 02:15 UTC, closed without merging