[Meshery-UI] Add Support For Exporting Models as OCI Images
meshery/meshery pull request #11408
Opened 2024-07-16 23:56 UTC by humblenginr

**Notes for Reviewers**

This PR fixes #11352 
  

https://github.com/user-attachments/assets/db8e048f-0991-45af-9d3e-56c83a8cbf34

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-07-17 09:51 UTC, Jougan-0 approved these changes

2024-07-17 09:51 UTC, Jougan-0 commented
Any update on import button. Are you working on it?

2024-07-17 13:25 UTC, leecalcote requested changes

2024-07-17 13:25 UTC, leecalcote commented on ui/components/MeshModelRegistry/MeshModelDetails.js
> +              startIcon={<DownloadIcon />}
Icon should be white (should support user-selected color theme).

@captain-Akshay can you assist here?

2024-07-17 13:39 UTC, leecalcote commented on server/handlers/component_handler.go
> +		h.log.Error(ErrGetMeshModels(err)) //TODO: Add appropriate meshkit error
@humblenginr a pattern of short cutting is developing.

2024-07-17 13:40 UTC, leecalcote commented on server/handlers/component_handler.go
> +		h.log.Error(ErrGetMeshModels(err)) //TODO: Add appropriate meshkit error
This makes for much back and forth on reviews. Dot your i's and cross your t's, please.

2024-07-17 13:42 UTC, leecalcote commented on server/handlers/component_handler.go
> +	err = oci.SaveOCIArtifact(img, tarfileName, model.Name)
Is archive compression happening here? If not, where is the `.gz` bit happening?

2024-07-17 13:53 UTC, leecalcote commented on server/handlers/component_handler.go
> +	err = oci.SaveOCIArtifact(img, tarfileName, model.Name)
Ideally, we're being consistent with behavior used while exporting Designs (same function, same options). Using MeshKit to achieve this? https://github.com/meshery/meshkit/blob/fd9565f3bbbfb6731c25726714029913f82b3743/models/oci/utils.go#L27

2024-07-18 12:00 UTC, leecalcote commented
Stopping by to review again. No new commits to review.

2024-07-19 12:14 UTC, leecalcote commented
Stopping by to review again. No new commits to review.

2024-08-04 22:43 UTC, Jougan-0 commented
@humblenginr Update??? Could you please address the comments or shall we close and move forward in another PR.

2024-08-06 23:33 UTC, leecalcote commented
No updates here. PR abandoned?

2024-08-08 21:36 UTC, humblenginr commented
closing this in favour of https://github.com/meshery/meshery/pull/11354

2024-08-08 21:36 UTC, closed without merging