Migrate designs to rtk
meshery/meshery pull request #11413
Opened 2024-07-17 13:44 UTC by sudhanshutech

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-07-17 14:11 UTC, sudhanshutech commented
@dottharun it will be nice if checkout this branch and test , thanks.

2024-07-18 07:40 UTC, Aut0R3V commented on ui/components/MesheryPatterns.js
> +  return (
I think the provided inputs solve the problem to some extent

2024-07-20 14:28 UTC, sudhanshutech commented
The left task of schema to use sistent schema can be done in iterative pr because that will not include rtk migration just use schema and fix around that.

2024-07-22 09:26 UTC, dottharun requested changes

2024-07-22 11:45 UTC, sudhanshutech commented on ui/components/MesheryPatterns.js
> +const MesheryPatternsProvider = (props) => {
fixed

2024-07-22 11:45 UTC, sudhanshutech commented on ui/components/MesheryPatterns.js
> +        // fetchPatternsCaller()();
fixed

2024-07-22 11:53 UTC, sudhanshutech commented
All feedbacks incorporated @dottharun , thanks

2024-07-22 11:54 UTC, sudhanshutech commented on ui/components/MesheryPatterns.js
> +  // if (loading) {
fixed

2024-07-23 03:22 UTC, merged