pattern import log statement improved/signoff
meshery/meshery pull request #11438
Opened 2024-07-21 10:59 UTC by rahulrana701

**Notes for Reviewers**

This PR fixes #11422

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2024-07-23 22:05 UTC, vishalvivekm commented
Thank you @rahulrana701 
Let's discuss this on the Meshery dev meeting. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

2024-07-24 14:10 UTC, Jougan-0 commented on mesheryctl/internal/cli/root/pattern/import.go
> +		utils.Log.Debug("Successfully fetched the pattern from the remote host")
Remove the word Successfully

2024-07-26 22:28 UTC, leecalcote requested changes
@rahulrana701, you left a "successfully" behind. :/

Also:

1. Please use the word "design" instead of pattern.
2. Include the name of the design or the filename of the design in the response to the user.

2024-07-27 04:06 UTC, rahulrana701 commented
@leecalcote sure

2024-07-27 20:04 UTC, leecalcote approved these changes
Excellent!

2024-07-27 20:04 UTC, merged