Add troubleshooting guide callout to operator page
meshery/meshery pull request #11456
Opened 2024-07-24 12:59 UTC by Shubhf

**Notes for Reviewers**

This PR fixes #11430

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.
 

**Operator Documentation**:
Added a callout to the troubleshooting guide in the Meshery Operator architecture documentation.
**Meshsync Documentation**:
Added a callout to the troubleshooting guide in the Meshsync architecture documentation.

**The PR fixes #11430**

2024-07-24 13:04 UTC, l5io commented
🚀 Preview for commit e973602f923fa8bcfd43cac3fdb0dd945d602249 at: https://66a0fb9220914622354b6dee--meshery-docs-preview.netlify.app

2024-07-24 13:08 UTC, vishalvivekm commented
@Shubhf 
Let's discuss this on the Meshery dev meeting starting 7:30 PM IST today. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

2024-07-24 19:10 UTC, l5io commented
🚀 Preview for commit dd9cad242a84e7270c3d5bf7aed6b00d06e0aab8 at: https://66a1518227d684263362f7cc--meshery-docs-preview.netlify.app

2024-07-24 19:35 UTC, Shubhf commented
As I am a newcomer , whatever I could do.I have tried to integrate as per
your guidance Pls suggest any necessary changes. And I am very well open to
all the suggestions and guidance
Thanking You
Shubh

On Thu, Jul 25, 2024 at 12:40 AM l5io ***@***.***> wrote:

> 🚀 Preview for commit dd9cad2
> <https://github.com/meshery/meshery/commit/dd9cad242a84e7270c3d5bf7aed6b00d06e0aab8>
> at: https://66a1518227d684263362f7cc--meshery-docs-preview.netlify.app
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/meshery/meshery/pull/11456#issuecomment-2248724071>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5WMIMUCVGFFSWWLX75ZJCLZN733PAVCNFSM6AAAAABLMOCRZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENBYG4ZDIMBXGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-24 20:56 UTC, l5io commented
🚀 Preview for commit 6c96a017cb09730713e1185214a51e1106afcf52 at: https://66a16a706c7a623b1bee3357--meshery-docs-preview.netlify.app

2024-07-24 20:57 UTC, Shubhf commented
@leecalcote I think changes are incorporated Pls check it out in both operator and meshsync
<img width="847" alt="Screenshot 2024-07-25 at 2 25 49 AM" src="https://github.com/user-attachments/assets/cbd31a18-54d8-4739-9646-c5c7fa567100">
Pls check it out

2024-07-25 06:24 UTC, Shubhf commented
I think it's perfect!

On Thu, Jul 25, 2024 at 2:15 AM Lee Calcote ***@***.***>
wrote:

> As I am a newcomer , whatever I could do.I have tried to integrate as per
> your guidance Pls suggest any necessary changes. And I am very well open to
> all the suggestions and guidance Thanking You Shubh
> … <#m_8733046871019690605_>
> On Thu, Jul 25, 2024 at 12:40 AM l5io *@*.*> wrote: 🚀 Preview for commit
> dd9cad2
> <https://github.com/meshery/meshery/commit/dd9cad242a84e7270c3d5bf7aed6b00d06e0aab8>
> <dd9cad2
> <https://github.com/meshery/meshery/commit/dd9cad242a84e7270c3d5bf7aed6b00d06e0aab8>>
> at: https://66a1518227d684263362f7cc--meshery-docs-preview.netlify.app
> <https://66a1518227d684263362f7cc--meshery-docs-preview.netlify.app> —
> Reply to this email directly, view it on GitHub <#11456 (comment)
> <https://github.com/meshery/meshery/pull/11456#issuecomment-2248724071>>,
> or unsubscribe
> https://github.com/notifications/unsubscribe-auth/A5WMIMUCVGFFSWWLX75ZJCLZN733PAVCNFSM6AAAAABLMOCRZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENBYG4ZDIMBXGE
> <https://github.com/notifications/unsubscribe-auth/A5WMIMUCVGFFSWWLX75ZJCLZN733PAVCNFSM6AAAAABLMOCRZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENBYG4ZDIMBXGE>
> . You are receiving this because you were mentioned.Message ID: @.*>
>
> Great. I offered feedback, which is ready for incorporation.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/meshery/meshery/pull/11456#issuecomment-2248868313>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5WMIMV4R4LAWSJ73NIVICDZOAHAFAVCNFSM6AAAAABLMOCRZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENBYHA3DQMZRGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-25 06:31 UTC, l5io commented
🚀 Preview for commit 7531ada2acd13943bca77a773015fe582228511a at: https://66a1f12d7f5682bc6961b617--meshery-docs-preview.netlify.app

2024-07-26 07:59 UTC, l5io commented
🚀 Preview for commit 9f93d4b8888c11b11fbfe343f603ad1b7b4a4ac1 at: https://66a357441c1731558318f92b--meshery-docs-preview.netlify.app

2024-07-26 13:43 UTC, leecalcote requested changes
Add title and type.

2024-07-31 03:52 UTC, Ashparshp commented
@Shubhf, let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

2025-02-11 16:40 UTC, sudhanshutech commented
@Shubhf checking in one last time otherwise we will closing this pr and reassign it.

2025-06-28 16:34 UTC, zihanKuang commented
Hi @Shubhf! Since our related issue has been closed, I'll close this PR as well. Thanks!

2025-06-28 16:34 UTC, closed without merging