feat: move utils and invokegeneration to meshkit
meshery/meshery pull request #11454
Opened 2024-07-24 07:31 UTC by dusdjhyeon

**Notes for Reviewers**

This PR fixes #
Issue: https://github.com/meshery/meshkit/issues/541
Related PR: https://github.com/meshery/meshkit/pull/543

- now you can see like this (with small amounts of test data )
![스크린샷 2024-07-24 162508](https://github.com/user-attachments/assets/06c02a58-6299-49a7-9fa8-e8d7979c9553)
- I tested by replacing it with a temporary branch(my repo), so meshkit needs to be merged first for things to work. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-07-24 20:46 UTC, leecalcote requested changes

2024-07-24 20:46 UTC, leecalcote commented on mesheryctl/internal/cli/root/registry/generate.go
> +	"log"
@dusdjhyeon please use MeshKit's logger.

2024-07-29 09:41 UTC, Jougan-0 commented on mesheryctl/internal/cli/root/registry/generate.go
> +		logrus.SetOutput(multiWriter)
Why logrus?

2024-08-02 18:38 UTC, leecalcote commented
@humblenginr please review / be aware.

@dusdjhyeon, please see to the merge conflicts.

2024-09-18 11:59 UTC, closed without merging