[Docs] Adding generic legends
meshery/meshery pull request #11508
Opened 2024-07-31 13:25 UTC by SAHU-01

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-07-31 13:28 UTC, l5io commented
🚀 Preview for commit 50e015b23ecdc45b68bd112fdaa4c9ca40a99123 at: https://66aa3bcd1207153a5aec4820--meshery-docs-preview.netlify.app

2024-07-31 13:29 UTC, SAHU-01 commented
The description and common use-cases related to each shape are yet to added in docs, it is currently present [here](https://docs.google.com/spreadsheets/d/14dXTKTqn_PB9E87xhanaIUIudiBpka54eqluxLxD028/edit?usp=sharing) and needs confirmation.

2024-07-31 20:30 UTC, leecalcote reviewed
Thanks!

The "SqlJob", "User" - are these shapes that Meshery has?

The "Textbox" icon is presented differently, if my memory serves.

It'd be great to get all icons uniformly presented of the same color.

2024-07-31 20:55 UTC, leecalcote reviewed
@vishalvivekm, I wonder if we wouldn't be better suited to use a datafile here. Thoughts?

See also: https://docs.google.com/spreadsheets/d/1nUgr0b7Ju8FxeWBLAgBO_OiYkaQkPWRh0gOX5M0cByc/edit

2024-08-02 04:44 UTC, SAHU-01 commented
> Thanks!
> 
> The "SqlJob", "User" - are these shapes that Meshery has?
> 
> The "Textbox" icon is presented differently, if my memory serves.
> 
> It'd be great to get all icons uniformly presented of the same color.

Yes, I found them here so I added these in the shapes listed on meshmap they are absent though:
- https://github.com/meshery/meshery/blob/master/server/meshmodel/meshery-shapes/0.7.2/v1.0.0/components/SqlJob.json
- https://github.com/meshery/meshery/blob/master/server/meshmodel/meshery-shapes/0.7.2/v1.0.0/components/User.json

Yes you are right the textbox and section look same just the fill color is different for both : I'll check the json again and fix this
<img width="75" alt="image" src="https://github.com/user-attachments/assets/a8a602bc-bb89-42fe-9989-382b3fbf88ae">

currently for the newly added icons the color is based on what the json returns, for the previous ones I'll modify them to match the current color scheme

2024-08-02 13:38 UTC, l5io commented
🚀 Preview for commit 6babbffece8f9c4c53e6c11dde634d042e04b121 at: https://66ace11d64f3fc5698377620--meshery-docs-preview.netlify.app

2024-08-02 15:08 UTC, vishalvivekm commented
the data file (csv)  is now accessible throughout the site in the variable `site.data.shapes`

2024-08-02 18:25 UTC, leecalcote commented
@vishalvivekm, I retract my suggestion that we'll need to have an ongoing refresh of this datafile. This isn't necessary. The spreadsheet can go away (soon) and the datafile take its place.

2024-08-03 05:36 UTC, vishalvivekm commented
> @vishalvivekm, I retract my suggestion that we'll need to have an ongoing refresh of this datafile. This isn't necessary. The spreadsheet can go away (soon) and the datafile take its place.

Roger

2024-08-05 10:53 UTC, SAHU-01 commented
A couple of things we might want look into @vishalvivekm and @leecalcote 

1. For TextBox I found Namespace in figma would this be an ideal shape?
<img width="145" alt="image" src="https://github.com/user-attachments/assets/1407cb7f-4eab-47e3-b2ca-73d0776967c2">

2. Or for textbox sticking to 

<img width="312" alt="image" src="https://github.com/user-attachments/assets/83e68e39-40e5-4224-a409-b2ae58dbd1aa">

as represented in Meshmap design section is good?
3. For SQLJob I'm not sure what description would fit and where it is used.
4. The rectangle, section and TextBox in Meshmap design section all three have same shape but in figma we've got a separate rectangle and square for generic legends which shape do you suggest should be used?
<img width="745" alt="image" src="https://github.com/user-attachments/assets/3c94bd70-47c4-430c-a8b1-b6997308b69a">
5. Is it necessary to create another datafile ? [Here](https://github.com/meshery/meshery/tree/master/server/meshmodel/meshery-shapes/0.7.2/v1.0.0/components) there is an empty key for description and complete svg, can we not add it here?

2024-08-05 19:36 UTC, leecalcote commented on docs/_data/shapes.csv
> +Shape,Description,Common usecase,Depend on,Note,SVG
@vishalvivekm, @SAHU-1 in order to maintain this data file long-term, I propose converting to YAML.

2024-08-05 19:38 UTC, leecalcote requested changes

2024-08-05 19:38 UTC, leecalcote commented on docs/_data/shapes.csv
> +SqlJob,,,,,"<svg viewBox=""0 0 40 40"" fill=""none"" xmlns=""http://www.w3.org/2000/svg"">
Comment out this shape given that it isn't included in releases yet, @sahu-01.

// @aabidsofi19

2024-08-05 19:38 UTC, leecalcote commented on docs/_data/shapes.csv
> +User,"This node represents an individual user, often depicted with an icon or simple human silhouette.","- Representing end-users or user roles in system diagrams
Comment out this shape given that it isn't included in releases yet, @sahu-01.

// @aabidsofi19

2024-08-06 05:51 UTC, l5io commented
🚀 Preview for commit f6841e2e50de591485ef3cfa5a15b293da0761c2 at: https://66b1b9def46ccd8531aeb2be--meshery-docs-preview.netlify.app

2024-08-06 05:51 UTC, SAHU-01 commented
@leecalcote this is what it looks like now:
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/8f2d78ea-635a-4892-a85c-d5cc88558850">

I added the YAML file and mapped data from here in a tabular structure, things I'm unable to debug currently:

1. The common usecases and depends on though present in YAML return a null when I try to map them in the table
2. Despite commenting SQLJob and User in YAML it still shows up
3. The polygon and Octagon SVG shapes need to be fixed height sizes are too big.

2024-08-06 06:17 UTC, l5io commented
🚀 Preview for commit 4a8b7455e91577be4f77cad7cbee9e8b241641ac at: https://66b1bfed871fef8b5049ec63--meshery-docs-preview.netlify.app

2024-08-07 00:25 UTC, leecalcote commented
@Ashparshp, help, if you can.

@vishalvivekm you might have input to offer.

2024-08-07 05:42 UTC, Ashparshp commented
@SAHU-01 let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

2024-08-07 11:51 UTC, vishalvivekm commented
Thank you @SAHU-01 
We also would want to make the table responsive in mobile-view.
make it scrollable in smaller screen-width ?
Here's an example table: https://docs.meshery.io/concepts/architecture#meshery-connections-and-their-actions

Also, instead of having SVGs in the data file, I wonder if we could have a assets/shapes/<all the svgs here> and in the data file just the path to svgs.

2024-08-07 13:05 UTC, Ashparshp commented
@SAHU-01 LMK if you need any help.

2024-08-07 13:26 UTC, SAHU-01 commented
Thanks @Ashparshp , I believe I can sort the image size issue if we remove those svgs and just add the SVG path info in datafiles!

2024-08-10 01:21 UTC, Muhammed-Moinuddin commented
![Screenshot from 2024-08-10 06-17-21](https://github.com/user-attachments/assets/f04247fc-0a77-4c81-9159-19aa483e64b5)
We should use space like we are doing with other names.
Can we display them in alphabetical order? [Shapes from A - Z]

2024-08-13 13:43 UTC, vishalvivekm commented
Thank you @SAHU-01 for putting all the efforts.
Will you please push your latest changes ?

2024-08-13 13:45 UTC, vishalvivekm requested changes

2024-08-13 13:45 UTC, vishalvivekm commented on docs/pages/extensions/meshmap/Node_ Volume.svg
let's have url-friendly names for svg files i.e `node_volume.svg` :heavy_check_mark:  `node_ volume.svg` :x: 
@SAHU-01

2024-08-13 13:45 UTC, vishalvivekm commented on docs/pages/extensions/meshmap/Polygon 6.svg
same here too, let's not have whitespaces in the file names @SAHU-01

2024-08-13 13:49 UTC, SAHU-01 commented on docs/pages/extensions/meshmap/Node_ Volume.svg
Heya, I did not add these I'll make sure to remove these files.

2024-08-13 13:50 UTC, SAHU-01 commented on docs/pages/extensions/meshmap/Polygon 6.svg
Same goes for this one, I'll remove this as well.

2024-08-13 13:50 UTC, l5io commented
🚀 Preview for commit ce1e6c75a9409f0abf59eab07fff790e5dae762b at: https://66bb64896652183f73b2eed1--meshery-docs-preview.netlify.app

2024-08-13 13:56 UTC, vishalvivekm commented on docs/pages/extensions/meshmap/component-shape-guide.md
> +</style> -->
should we get rid of the commented out styles @SAHU-01 ?

2024-08-13 13:58 UTC, vishalvivekm commented on docs/pages/extensions/meshmap/component-shape-guide.md
> +</style> -->
```suggestion
```

2024-08-13 13:59 UTC, vishalvivekm commented on docs/pages/extensions/meshmap/component-shape-guide.md
> +</style> -->
@SAHU-01 ^^

2024-08-13 14:12 UTC, SAHU-01 commented on docs/pages/extensions/meshmap/component-shape-guide.md
> +</style> -->
I'll remove the commented portion

2024-08-13 14:17 UTC, l5io commented
🚀 Preview for commit 91e2e6c38a8e420633bf0011f706a3d7d530c9c2 at: https://66bb6ac7ab60233d14659a3d--meshery-docs-preview.netlify.app

2024-08-13 15:55 UTC, vishalvivekm approved these changes
Thank you @SAHU-01 
I'll follow up with a PR.

2024-08-13 15:55 UTC, merged