[Docs] Guide for practicing schema driven development for Meshery Server.
meshery/meshery pull request #11539
Opened 2024-08-02 13:46 UTC by MUzairS15

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-08-02 13:49 UTC, l5io commented
🚀 Preview for commit f5c24c9342ba0eae58f77e82a138851a1a5ab6a5 at: https://66ace3e06e8dc35a49410a1e--meshery-docs-preview.netlify.app

2024-08-05 19:27 UTC, leecalcote commented on docs/pages/project/contributing/meshery-server.md
> +1. `oapi-codegen`: https://github.com/oapi-codegen/oapi-codegen?tab=readme-ov-file#install
@MUzairS15 describe each of these tools.

2024-08-05 19:28 UTC, leecalcote commented on docs/pages/project/contributing/meshery-server.md
> +1. `oapi-codegen`: https://github.com/oapi-codegen/oapi-codegen?tab=readme-ov-file#install
@MUzairS15 combine the "Install Required Tools" with the "Prerequisites" section below. This should be a step within that section.

2024-08-05 19:31 UTC, leecalcote requested changes

2024-08-05 19:31 UTC, leecalcote commented on docs/pages/project/contributing/meshery-server.md
> +2. Resolving References in JSON Schemas:
This step is out of place; not well-described. There's no lead-in or explanation.

2024-08-05 19:31 UTC, leecalcote commented on docs/pages/project/contributing/meshery-server.md
> +```bash
Step 3?

2024-08-05 19:35 UTC, l5io commented
🚀 Preview for commit 8289d18d8c313cada92e69b99f8649fe7c797b2d at: https://66b1295e957417041a71eedd--meshery-docs-preview.netlify.app

2024-09-15 03:58 UTC, leecalcote commented
Willfix

2024-10-31 02:28 UTC, closed without merging