refactor: Add proper event description for design handler
meshery/meshery pull request #11548
Opened 2024-08-04 15:04 UTC by singh1203

**Notes for Reviewers**
Enhance event short description and long description in the design handler.

This PR fixes #11547

Screenshot:
![Screenshot from 2024-08-04 18-57-14](https://github.com/user-attachments/assets/dbe00f93-e912-418d-9ecb-a1bb8358c338)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-08-06 23:52 UTC, leecalcote requested changes

2024-08-06 23:52 UTC, leecalcote commented on server/handlers/design_engine_handler.go
> +		return nil, ErrInvalidKubeHandler(fmt.Errorf("Kubernetes cluster for \"%s\", is unavailable.", pattern.Name), userID)
Don't use "for".

Don't include ",".

2024-08-07 05:42 UTC, Ashparshp commented
@singh1203 let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

2024-08-15 01:30 UTC, leecalcote approved these changes

2024-08-15 01:30 UTC, merged