Enable Table Scroll
meshery/meshery pull request #11569
Opened 2024-08-06 18:21 UTC by vaishnaviadhau

**Notes for Reviewers**

This PR fixes #11552 

https://github.com/user-attachments/assets/66809e45-0d91-4336-a381-b26a80381d40

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-08-06 18:24 UTC, l5io commented
🚀 Preview for commit 21e6d7a9f035bb57324af8851fd032b5a9d5578b at: https://66b26a58c900463e6eb60c5a--meshery-docs-preview.netlify.app

2024-08-06 20:29 UTC, l5io commented
🚀 Preview for commit b66bfa3daec3404f4f767898057c622229919921 at: https://66b287a741b363622eb62e57--meshery-docs-preview.netlify.app

2024-08-06 20:37 UTC, vaishnaviadhau commented
@yash37158, I have signed my commit.

2024-08-06 23:47 UTC, leecalcote requested changes
Thanks! This amount of inline styling is overkill and redundant. Please refactor.

2024-08-07 05:43 UTC, Ashparshp commented
@vaishnaviadhau let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

2024-08-07 06:11 UTC, vaishnaviadhau commented
> Thanks! This amount of inline styling is overkill and redundant. Please refactor.

@leecalcote I'll work on it

2024-08-07 06:11 UTC, vaishnaviadhau commented
> @vaishnaviadhau let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

@Ashparshp Okay

2024-08-07 13:32 UTC, l5io commented
🚀 Preview for commit 6469397fe4465549c4c5456b662016e5e5486b20 at: https://66b37747b2f269007d787dcd--meshery-docs-preview.netlify.app

2024-08-12 10:38 UTC, sudhanshutech commented
@vaishnaviadhau this the good item to discuss in website meeting today please add as agenda item for today: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit and please jump to share your progress here at 5:30pm IST.

2024-08-21 13:41 UTC, Ashparshp commented
@vaishnaviadhau, any updates?

2024-08-26 18:58 UTC, sudhanshutech requested changes

2024-08-26 19:11 UTC, vaishnaviadhau commented on docs/pages/project/security-vulnerabilities.md
> +<style>
@sudhanshutech okay I'll make the required changes

2024-08-26 21:24 UTC, l5io commented
🚀 Preview for commit dc0e48d3388b7ce34a6f50b3960b93325b8acee1 at: https://66ccf264d759532162a36a61--meshery-docs-preview.netlify.app

2024-10-03 04:00 UTC, sudhanshutech approved these changes

2024-10-03 04:04 UTC, merged