[UI]: RTK Migration for User Preference
meshery/meshery pull request #11568
Opened 2024-08-06 15:24 UTC by senthil-athiban

**Notes for Reviewers**

This PR fixes #9985

- [x] **GET**: Migrate user pref to RTK
- [x] **POST**: Add RTK query for `api/user/pref` 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-08-07 05:43 UTC, Ashparshp commented
@senthil-athiban let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

2024-08-07 14:25 UTC, sudhanshutech requested changes

2024-08-07 14:25 UTC, sudhanshutech commented on ui/rtk-query/user.js
> +        body: queryArg,
@senthil-athiban for clarity and consistency pass the body based on the querArg
```suggestion
        body: queryArg.body,
```
and pass the payload with respect to body. See other places

2024-08-10 16:50 UTC, leecalcote commented
Ready for another round of review.

2024-08-21 10:30 UTC, sudhanshutech approved these changes

2024-08-21 10:31 UTC, merged