[CI] Update go-testing-ci.yml to latest actions.
meshery/meshery pull request #11592
Opened 2024-08-09 11:00 UTC by singh1203

**Notes for Reviewers**

This PR fixes #11591 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-08-09 11:01 UTC, singh1203 commented
// @Jougan-0

2024-08-09 13:40 UTC, leecalcote requested changes

2024-08-09 13:40 UTC, leecalcote commented on .github/workflows/go-testing-ci.yml
> +      - name: Install Docker Compose
https://github.com/meshery/meshery/issues/11591#issuecomment-2277970531

2024-08-10 16:03 UTC, leecalcote requested changes

2024-08-10 16:03 UTC, leecalcote commented on .github/workflows/go-testing-ci.yml
> +          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
Remove uname.

2024-08-10 16:07 UTC, leecalcote approved these changes

2024-08-10 16:07 UTC, merged