[UI]: RTK Migration for Extension Page
meshery/meshery pull request #11628
Opened 2024-08-13 07:17 UTC by senthil-athiban

**Notes for Reviewers**

This PR fixes #

Migration of dataFetch to RTK query for the following api's:

**Extensions:** 
- [x] GET: `api/user/prefs`
- [x] POST: `api/user/prefs`  

## Screen Recorder

https://github.com/user-attachments/assets/11c3f948-2a30-46a6-9343-146ee78a5aa2

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-08-14 03:36 UTC, Ashparshp commented
@senthil-athiban let's discuss this PR during the Meshery dev meeting call, if you would. Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?usp=drivesdk).

2024-08-21 10:40 UTC, sudhanshutech requested changes

2024-08-21 10:40 UTC, sudhanshutech commented on ui/rtk-query/user.js
> +  useUpdateUserPrefMutation,
use the existing query and remove this

2024-08-21 11:16 UTC, sudhanshutech approved these changes

2024-08-21 11:24 UTC, merged