version-selector
meshery/meshery pull request #11898
Opened 2024-09-03 12:24 UTC by vaishnaviadhau

**Notes for Reviewers**

This PR fixes #11554

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-09-03 12:34 UTC, l5io commented
🚀 Preview for commit 152b1919ad257b53fe736e6db3b49ef33a36bd89 at: https://66d70207a7edd4218570d9ff--meshery-docs-preview.netlify.app

2024-09-03 14:27 UTC, l5io commented
🚀 Preview for commit c9a0eaee01ddd4e1dac5a12df0c5df67cb50ba5f at: https://66d71c70064dad4dc0d7382c--meshery-docs-preview.netlify.app

2024-09-03 14:27 UTC, l5io commented
🚀 Preview for commit c9a0eaee01ddd4e1dac5a12df0c5df67cb50ba5f at: https://66d71c78d6f7df4f843d8bff--meshery-docs-preview.netlify.app

2024-09-11 10:37 UTC, Ashparshp commented
Thank you @vaishnaviadhau,
Noticed an issue: selecting `v6` shows `latest`, and clicking `latest `again still stays on `v6`. Works fine with other versions. Otherwise, looks good to me.

Could you please fix this?

[Meshery Documentation _ Meshery.webm](https://github.com/user-attachments/assets/97f38e31-9b87-41a5-a174-a2fbe27f9f29)

2024-09-11 11:11 UTC, vaishnaviadhau commented
@Ashparshp : the changes  are visible when I run the site locally, but they aren’t showing up in the preview section after I raised the PR. Could you check if something is affecting this on the PR side?

2024-09-18 03:20 UTC, sudhanshutech requested changes
I am not seeing and changes in behaviour with the current scenario and the changes from this pr. When i am trying to click 0.6 it selects the latest because 0.6 is the latest.
Either case should be that latest and 0.6 should consolidated at one.

2024-09-18 03:20 UTC, sudhanshutech commented on docs/_includes/header.html
> +         <script>
what this script for?

2024-11-17 17:49 UTC, closed without merging