Remove duplicate error code table of meshery-server in Error Code Ref…
meshery/meshery pull request #11951
Opened 2024-09-10 13:08 UTC by 102vansh

**Title:**
[UI] [Bug] Remove duplicate error code table of meshery-server in Error Code Reference #11942

**Description:**
This PR addresses the issue #11942 where the error code table for `meshery-server` was duplicated in the Error Code Reference page. The duplicate table has been removed, and the page now correctly displays a single table for `meshery-server` error codes.

**Notes for Reviewers:**
Please review the changes to ensure that the duplicate error code table has been removed and that the remaining content is accurate and correctly displayed.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-09-10 13:38 UTC, l5io commented
🚀 Preview for commit 95345efd4e0c84c4af1cb458015ee44e9a36f2a1 at: https://66e04b9eb04f413599ed743e--meshery-docs-preview.netlify.app

2024-09-10 15:51 UTC, leecalcote requested changes

2024-09-10 15:51 UTC, leecalcote commented on docs/pages/reference/error-codes.md
> +{% include alert.html type="info" title="Error codes format" content="Error codes are a hyphenated collection of details:
Please revert this change.

2024-09-10 15:51 UTC, leecalcote commented on docs/pages/reference/error-codes.md
> +Meshery and its components use a common framework (defined within MeshKit) to generate and document an event with a unique error code identifier as the combination of `[component type]-[component nam
Please revert this change.

2024-09-10 22:45 UTC, leecalcote requested changes
Thanks for refactoring, @102vansh 👏 

It looks like we might be missing an opening or a closing `if` / `endif` - https://github.com/meshery/meshery/actions/runs/10799459830/job/29955241832?pr=11951#step:4:354. Will you double-check?

2024-09-11 06:49 UTC, Ashparshp commented
Thank you @102vansh
Let's discuss this PR on Meshery development call today. Adding it as an agenda item to the meeting minutes.

Timing: 9:00 AM CT
Meeting minutes: [Google Docs](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit)
Meeting link: [meet.layer5.io/meshery](https://meet.layer5.io/meshery)

2024-10-03 03:46 UTC, sudhanshutech commented
@102vansh build is failing. Have you fix the endif syntax which is coming in build error and also mentioned by @leecalcote

2024-12-03 06:59 UTC, closed without merging