[UI]:Workspace Page MUI migration from v4 to Sistent components
meshery/meshery pull request #11974
Opened 2024-09-11 13:14 UTC by SAHU-01

**Notes for Reviewers**

This PR fixes part of  #11493 , based on [this](https://docs.google.com/spreadsheets/d/1RlUcr-iLtCFCsV1VZvWD0jBijPJAx-Rk-1GLLsL9sSI/edit?usp=sharing) sheet , the workspace page and its related components have been migrated to use sistent components and necessary mui v5 changes have been applied to these pages.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-09-11 13:23 UTC, SAHU-01 commented
> > @sudhanshutech the `SearchBar` used in the `index.js` file [_import SearchBar from '../../../utils/custom-search'_] is not the sistent `SearchBar` , would you recommend using the sistent `SearchBar` here, if yes, I'll implement it.
> 
> where this search bar from utils being used? Because we already use searc bar from sistent.

Here the utils SearchBar is being used:
<img width="1262" alt="image" src="https://github.com/user-attachments/assets/0fff7930-bb2e-489d-868b-a938f1587fca">

2024-09-11 13:26 UTC, SAHU-01 commented
> use it from sistent directly . Search bar is already in sistent . See other places for example , it might have missed .

Got it, yes I noticed other places using the sistent, so I was wondering why we had this utils one here, either ways, I'll implement the sistent one here.

2024-09-12 16:55 UTC, Ajay-singh1 requested changes
We need to import the components from @material/mui/core not from @material-ui/core.

2024-09-12 21:41 UTC, leecalcote commented
> We need to import the components from @mui/material/core not from @material-ui/core.

Thanks for helping out here, @Ajay-singh1 👍

2024-09-16 13:06 UTC, sudhanshutech commented
@SAHU-01 any caveats here? or everything is fine?

2024-09-16 13:51 UTC, SAHU-01 commented
@sudhanshutech I've tested all the features for workspace and there isn't any sort of glitch or potential issues I think this code would cause, I'll probably add a demo video of how this works locally testing all features.

2024-09-17 15:32 UTC, sudhanshutech requested changes

2024-09-17 15:32 UTC, sudhanshutech commented on ui/components/Lifecycle/Workspaces/index.js
> +  backgroundColor: theme.palette.mode === 'dark' ? '#464646' : '#FFFFFF',
we should use sistent tokens instead hard code hex colors

2024-10-11 14:44 UTC, aabidsofi19 approved these changes

2024-10-19 11:52 UTC, sudhanshutech approved these changes

2024-10-30 12:53 UTC, merged