[Docs] Create Newcomer's Meeting Attendance Folder for Week of 09/09/2024
meshery/meshery pull request #12037
Opened 2024-09-14 20:25 UTC by 102vansh

Description:
This pull request addresses issue #11929 by creating a new folder for the Newcomer's Meeting attendance records for the week of September 9, 2024.
Changes made:

Created a new folder under the appropriate directory structure for storing meeting attendance records.
Added a README.md file in the new folder explaining its purpose and how to use it.
Ensured the folder naming convention follows the established pattern (e.g., "2024-09-09_newcomers_meeting").

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-09-14 20:28 UTC, l5io commented
🚀 Preview for commit 317e0c39689f81249e455bb5a99791862fe590b6 at: https://66e5f1d7490049ba5f38a2ca--meshery-docs-preview.netlify.app

2024-09-15 16:02 UTC, leecalcote requested changes

2024-09-15 16:02 UTC, leecalcote commented on eval "$(ssh-agent -s)"
Please remove.

2024-09-15 16:02 UTC, leecalcote commented on eval "$(ssh-agent -s)".pub
Please remove.

2024-09-15 17:19 UTC, l5io commented
🚀 Preview for commit 8f5eeda67b0b107a927878f31abf7ba75baa3991 at: https://66e71705d16ab521818f48b5--meshery-docs-preview.netlify.app

2024-09-15 17:23 UTC, l5io commented
🚀 Preview for commit 582e3bfc7bac1983533ef486ef5fd212e530d581 at: https://66e718100165a8223e9fb572--meshery-docs-preview.netlify.app

2024-09-16 06:33 UTC, l5io commented
🚀 Preview for commit c7a47d073f86c1c11ab1d1b8e961c9cfe2718e3d at: https://66e7d107985c3fcb887247c4--meshery-docs-preview.netlify.app

2024-09-16 17:48 UTC, l5io commented
🚀 Preview for commit 7bb0b23a9e55842f3a3142a5744a66d6fe3f005d at: https://66e86f50d2400324fdfe1d1b--meshery-docs-preview.netlify.app

2024-09-16 19:36 UTC, l5io commented
🚀 Preview for commit f6667c96f5d5a896aeb3656810aa30692367a426 at: https://66e8889ba9149800cd6491e4--meshery-docs-preview.netlify.app

2024-09-17 04:41 UTC, leecalcote approved these changes

2024-09-17 04:42 UTC, merged

2024-09-17 04:42 UTC, leecalcote commented
@102vansh thanks. You might be in a position to review some upcoming PRs for the other open issues on this topic.

We actually need a few more issues opened using the same format found in https://github.com/meshery/meshery/issues/11929 for upcoming weeks. // @hargunkaur286