[UX] Improve error handling for Meshery-Server-1085 on send design failure
meshery/meshery pull request #12278
Opened 2024-10-05 09:44 UTC by shinigami-777

**Notes for Reviewers**

This PR fixes #12233 

- Add clearer causes and remediation for Error Meshery-Server-1085.
- Handle 413 (Payload Too Large), 401 (Unauthorized), and 400 (Bad Request) status codes with specific error messages.
- Include remote provider name in error logs for better clarity and context.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-10-08 20:41 UTC, leecalcote commented
Thanks for contributing, @shinigami-777!

2024-10-09 12:50 UTC, vishalvivekm commented
@shinigami-777 
Thank you for your contributions! Let's discuss this during the Meshery Development call today at 9:00 AM CT. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

2024-10-11 08:11 UTC, alphaX86 reviewed
Thanks a lot for your PR @shinigami-777 

Has this been tested in local? Just want to confirm before proceeding

2024-10-11 10:56 UTC, shinigami-777 commented
@alphaX86 Yes it was tested.

2024-10-11 11:22 UTC, alphaX86 commented
> @alphaX86 Yes it was tested.

Okay...

2024-10-11 17:02 UTC, alphaX86 requested changes

2024-10-11 17:02 UTC, alphaX86 commented on server/models/remote_provider.go
> +			err = ErrPost(fmt.Errorf("failed to send design %s to remote provider %s. Check if the design is valid or undo recent changes.", pattern.Name, l.ProviderName), "", resp.StatusCode)
This seems fine to me.

2024-10-13 05:30 UTC, alphaX86 approved these changes
LGTM. Approved from my side

2024-10-14 04:16 UTC, lekaf974 approved these changes

2024-10-14 07:20 UTC, Jougan-0 commented on server/models/remote_provider.go
> +			return bdr, err
I think if we are logging it here we don't need to return back the error.

2024-10-14 07:20 UTC, Jougan-0 commented on server/models/remote_provider.go
> +			return bdr, err
Same here.

2024-10-14 07:20 UTC, Jougan-0 commented on server/models/remote_provider.go
> +			return bdr, err
Same here.

2024-10-14 07:20 UTC, Jougan-0 commented on server/models/remote_provider.go
> +			return bdr, err
Same here.

2024-10-15 04:58 UTC, shinigami-777 commented on server/models/remote_provider.go
> +			return bdr, err
I have removed the error logs for this.

2024-10-17 04:35 UTC, alphaX86 approved these changes

2024-10-17 11:56 UTC, lekaf974 approved these changes
LGTM

2024-10-25 15:57 UTC, alphaX86 commented
Thanks @shinigami-777 for the PR. Apologies for late delay though in response

2024-10-25 15:57 UTC, merged