[Docs] Added new CLI Plugins page under Extensibility
meshery/meshery pull request #12366
Opened 2024-10-13 18:12 UTC by Tharanishwaran

**Notes for Reviewers**

This PR fixes ##12181

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-10-13 18:16 UTC, l5io commented
🚀 Preview for commit 26dcbe7a3ecdc95665538cd5eb192b70d331fb53 at: https://670c0e492ae625c1335c8357--meshery-docs-preview.netlify.app

2024-10-14 02:00 UTC, l5io commented
🚀 Preview for commit f2250bb4ae041d1b13514fa570bf0aa7c3c1ff47 at: https://670c7b09c1ee79260aa3cc90--meshery-docs-preview.netlify.app

2024-10-16 12:17 UTC, Tharanishwaran commented
> @Tharanishwaran Thank you for your contributions! Let's discuss this during the Meshery Development call today at 9:00 AM CT | 7:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

Thank you @vishalvivekm

2024-10-17 18:22 UTC, l5io commented
🚀 Preview for commit 11e44e082a3729f0b444b6d61b686143d5f1ec6a at: https://671155bbcfdb129b13749c8d--meshery-docs-preview.netlify.app

2024-10-28 02:09 UTC, leecalcote requested changes
Thanks! 

In addition to this central page, can we get each extension listed on it's own page?

2024-10-28 02:28 UTC, Tharanishwaran commented
> Thanks!
> 
> In addition to this central page, can we get each extension listed on it's own page?

Thanks @leecalcote! I'll split this into individual pages for each plugin while keeping this as the overview.

2024-10-28 02:49 UTC, leecalcote commented
Good, although, this overview needs reformatted, condensed and much of its info moved into individual pages. We don't need the Design Spec or the Design Overview sections here either. Be sure that you're reviewing what the LLM that you're using is spitting out and make it work for the docs. 

See the other collections' index pages in which they loop over a subset of collections and dynamically offer links to "X" number of items in the (extensions) collection.

2024-11-13 13:46 UTC, l5io commented
🚀 Preview for commit c2f2ecdb58bb95fb7594dcffcae0f7db7ebbc6d8 at: https://6734ad6a2650620d05c2a90f--meshery-docs-preview.netlify.app

2024-11-27 06:21 UTC, Tharanishwaran commented
@leecalcote  Yes, I am incorporating the feedback and will update the changes soon.

2024-12-03 06:41 UTC, l5io commented
🚀 Preview for commit 71ca6424c35cb67ba11c3e99d56e0e24b7eb778f at: https://674ea7e5a2cbffe4ae5e59ef--meshery-docs-preview.netlify.app

2024-12-03 06:46 UTC, l5io commented
🚀 Preview for commit 45816199464b5e2b34f31f052370196312cc3e0a at: https://674ea912b63332e6a8843fcf--meshery-docs-preview.netlify.app

2025-01-25 06:33 UTC, closed without merging