[UI] Migrate DatabaseSummary component to Sistient and MUI v5. Fixes #12421
meshery/meshery pull request #12430
Opened 2024-10-18 05:20 UTC by Vaibhav701161

***Notes for Reviewers***

This PR migrates the **DatabaseSummary.js** component to use Sistent and MUI v5.

**Changes:**
- Updated MUI v4 components to MUI v5 with Sistent equivalents (Button, Typography, useTheme).
- Wrapped the component with **UsesSistent** for consistent theming.
- No logic changes; functionality remains intact.

- [x] Yes, I signed my commits.

2024-10-25 15:08 UTC, Vaibhav701161 commented
@SAHU-01 please review this pr

2024-10-28 02:00 UTC, leecalcote commented
Thanks, @Vaibhav701161.

@sudhanshutech are we still doing this?

```
Wrapped the component with UsesSistent for consistent theming.
```

2024-11-03 13:45 UTC, leecalcote commented
@sudhanshutech are we still doing this?

> Wrapped the component with UsesSistent for consistent theming.

2024-11-21 22:26 UTC, leecalcote commented
> @sudhanshutech are we still doing this?
> 
> > Wrapped the component with UsesSistent for consistent theming.

@sudhanshutech, asking again: are we still doing this?

2024-11-23 14:18 UTC, sudhanshutech requested changes

2024-11-23 14:18 UTC, sudhanshutech commented on ui/components/DatabaseSummary.js
> -      <div className={StyleClass.toolWrapper} style={customInlineStyle}>
its good that you have removed the class uses but have you ensure that are converted to style components and there styles are not lost?

2024-11-23 14:23 UTC, sudhanshutech commented
> > @sudhanshutech are we still doing this?
> > > Wrapped the component with UsesSistent for consistent theming.
> 
> @sudhanshutech, asking again: are we still doing this?

yes until the all pages are completed and then we will remove from everywhere and use it in single place that is app.js.

2024-11-29 04:56 UTC, sudhanshutech commented
@Vaibhav701161 checking in again...

2024-12-03 19:09 UTC, closed without merging