[ UI ] - Popup component MUI version updated.
meshery/meshery pull request #12457
Opened 2024-10-22 19:04 UTC by Pratik-050

**Notes for Reviewers**

This PR fixes #12423

Migrated the Popup.js function to MUI V5 using supported sistent components.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2024-10-22 19:52 UTC, Pratik-050 commented
Hello @SAHU-01 @yash37158 @sudhanshutech I've made the PR as assigned to me have a look at this. Thanks!

2024-10-23 11:32 UTC, vishalvivekm commented
@Pratik-050 
Thank you for your contributions! Let's discuss this during the Meshery Development call today at 9:00 AM CT | 7:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

2024-10-23 12:43 UTC, SAHU-01 commented
This looks good to me @Pratik-050, have you run this locally to test with other components, to ensure it's not breaking the existing functionality/style? 
Once, you add the necessary sistent token changes we should be good to merge.

2024-10-23 13:51 UTC, Pratik-050 commented
Hello @SAHU-01 everything is working fine, I'm just unable to find the correct background token from sistent. 
Once that is fixed then we are good to go. Can you help me finding that?

2024-10-24 19:13 UTC, Pratik-050 commented
Hello @SAHU-01 I've made some some changes please have a look. @leecalcote @yash37158 @sudhanshutech does the new colors good to go?

2024-10-31 20:46 UTC, leecalcote commented
Is there a pop-up component in Sistent?

2024-10-31 20:47 UTC, leecalcote approved these changes

2024-11-01 14:46 UTC, Pratik-050 commented
> Is there a pop-up component in Sistent?

No sir I don't think there's a dedicated component for popup in the sistent library.

2024-11-29 04:48 UTC, sudhanshutech requested changes

2024-11-29 04:48 UTC, sudhanshutech commented on ui/components/Popup.js
> +import { useTheme } from '@material-ui/core';
this can also be used from sistent

2024-11-29 04:49 UTC, sudhanshutech commented
LGTM otherwise

2024-11-29 04:52 UTC, sudhanshutech commented
LGTM otherwise

2024-11-29 04:54 UTC, sudhanshutech approved these changes
// @SAHU-01 fyi

2024-11-29 04:54 UTC, merged