feat: add ability to display custom information on integration pages
meshery/meshery pull request #12539
Opened 2024-11-01 06:12 UTC by Touriist

**Notes for Reviewers**

- This PR fixes #12534 

- For ui changes: Please add a screenshot showcasing the UI before/after changes. 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-11-01 06:16 UTC, l5io commented
🚀 Preview for commit af53559cab861ea2647732c790944542181f79c6 at: https://6724720d5aedebce260f0230--meshery-docs-preview.netlify.app

2024-11-01 07:04 UTC, l5io commented
🚀 Preview for commit 775837494bf10737d8ec75e692a6f739ce9ced65 at: https://67247d70e02b81d9b9d8f15d--meshery-docs-preview.netlify.app

2024-11-01 07:16 UTC, l5io commented
🚀 Preview for commit 34255bfeb1306e4816efee0a60f18cdfd2a7aa50 at: https://67248023045e1ededa193086--meshery-docs-preview.netlify.app

2024-11-01 08:26 UTC, Alero-Awani commented on docs/pages/project/contributing/contributing-docs.md
> +[modelscustominfo](https://github.com/meshery/meshery/tree/master/docs/_modelscustominfo) collection holds custom markdown files. Follow these steps:
should this be `https://github.com/meshery/meshery/tree/master/docs/_models` instead

2024-11-01 11:51 UTC, l5io commented
🚀 Preview for commit 09fa33392abbc3de2539d07c6954189cec9d44a9 at: https://6724c08c88973430f3c048f0--meshery-docs-preview.netlify.app

2024-11-03 13:36 UTC, leecalcote requested changes

2024-11-03 13:36 UTC, leecalcote commented on docs/_modelscustominfo/aws-ec2.md
This is invalid and needs changed.

2024-11-03 15:42 UTC, vishalvivekm commented
@Touriist Let's discuss this on websites call on Monday at 6:30 PM IST (7:00 AM CT). Add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk), if you would :)

2024-11-03 15:42 UTC, vishalvivekm commented on docs/_modelscustominfo/aws-ec2.md
@Alero-Awani ^^

2024-11-04 16:18 UTC, merged