UI: [component/MesheryResultDialog] convert from mui4 to mui5 with sistent component use
meshery/meshery pull request #12640
Opened 2024-11-13 10:45 UTC by Karan-Palan

### Description
This PR migrates the `MesheryResultDialog` component from Material-UI v4 to Material-UI v5 and integrates Sistient components for consistent theming and styling. This Pull Request addresses the issue #12217 .

### Changes Made:
1. Migration to Material-UI v5

2. Integration with Sistient

### **Screenshots/Terminal Output:**
I have built and tested my changes locally.

2024-11-13 11:01 UTC, vishalvivekm commented
@Karan-Palan 
Let's discuss this during the Meshery Development call today at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

2024-11-20 13:52 UTC, SAHU-01 commented
@Karan-Palan could you test this locally, wherever this component is used could you check and confirm that the functionality and styling isn't hampered?

2024-11-21 21:47 UTC, leecalcote commented
Thank you, @SAHU-01. 👍 @nebula-aac, I wonder if any issues jump out to you in here.

2024-11-23 14:14 UTC, sudhanshutech requested changes

2024-11-23 14:14 UTC, sudhanshutech commented on ui/components/MesheryResultDialog.js
> +import { NoSsr, Grid, Table, TableRow, TableCell, TableBody, Typography } from '@mui/material';
use from sistent not mui

2024-11-29 04:55 UTC, sudhanshutech commented
@Karan-Palan any update?

2025-01-19 07:15 UTC, closed without merging