Updated the ui/pages/performance to Sistent and MUI v5
meshery/meshery pull request #12679
Opened 2024-11-18 03:25 UTC by Ajay-singh1

**Notes for Reviewers**

I have updated the performance page to Sistent and MUI v5 based on the sheet provided in 

![Screenshot from 2024-11-18 08-36-30](https://github.com/user-attachments/assets/b2c7e912-d979-4b30-a8bd-75a7f68c3e24)
![Screenshot from 2024-11-18 08-36-54](https://github.com/user-attachments/assets/130bb8a5-4ee1-4059-91a7-1d9af3a4aa04)
![Screenshot from 2024-11-18 08-37-59](https://github.com/user-attachments/assets/52f1ad02-4276-40c3-a18f-861a5e14fc6a)

- This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-11-18 04:27 UTC, Ajay-singh1 commented
@aabidsofi19 Can you kindly review this PR?

2024-11-20 10:33 UTC, vishalvivekm commented
@Ajay-singh1 
Let's discuss this during the Meshery Development call today at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

2024-11-23 14:12 UTC, sudhanshutech requested changes

2024-11-23 14:12 UTC, sudhanshutech commented on ui/pages/performance/results.js
> +import { Paper, SistentThemeProvider } from '@layer5/sistent';
not required to use Sistentthemeprovider. There is already a wrapper use that : usesSisistent

2024-11-23 14:12 UTC, sudhanshutech commented on ui/pages/performance/results.js
> +import { Paper, SistentThemeProvider } from '@layer5/sistent';
and why we directly updating pages, are the parent component updated to sistent that is here MesheryResults? That should done first.

2024-11-26 18:23 UTC, leecalcote commented
@Ajay-singh1 is this still a draft or is it ready for review?

2024-11-27 02:11 UTC, Ajay-singh1 commented
@leecalcote It is still in draft!

2024-12-08 03:19 UTC, closed without merging