[UI]: Update the Outdated Button Component to Sistent Component
meshery/meshery pull request #12673
Opened 2024-11-16 13:37 UTC by Ajay-singh1

**Notes for Reviewers**

- This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-11-20 10:33 UTC, vishalvivekm commented
@Ajay-singh1 
Let's discuss this during the Meshery Development call today at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

2024-11-23 14:15 UTC, sudhanshutech requested changes

2024-11-23 14:15 UTC, sudhanshutech commented on ui/components/General/ErrorBoundary.js
> +      <SistentThemeProvider>
use the wrapper usesSistent not this because its use with wrapper already

2024-11-24 11:34 UTC, Ajay-singh1 commented
@sudhanshutech  This PR is ready to be merged now.

2024-11-26 18:24 UTC, leecalcote commented
@sudhanshutech we're ready for final review here.

2024-12-08 03:19 UTC, closed without merging