[UI] User preferences page MUI v5 migration
meshery/meshery pull request #12699
Opened 2024-11-20 07:17 UTC by SAHU-01

**Notes for Reviewers**

- This PR successfully migrates user preferences page to MUIv5 compatible code.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-11-20 07:19 UTC, SAHU-01 commented
@sudhanshutech based on [this](https://layer5io.slack.com/archives/C023QGMSH8D/p1731936190789379) slack message I left formControl as it is without changing.
`import {FormLabel} from '@material-ui/core';`

2024-11-20 08:50 UTC, Ajay-singh1 commented
`<a href="https://mui.com/material-ui/api/form-label">FormLabel API in Material UI</a>`.

2024-11-20 09:13 UTC, Ajay-singh1 commented
`import {FormLabel} from '@mui/material/FormLabel` update the import statement :).

2024-11-20 15:55 UTC, sudhanshutech commented on ui/components/UserPreferences/style.js
> +  border: '1.5px solid #969696',
here too?

2024-11-20 15:55 UTC, sudhanshutech commented on ui/components/UserPreferences/style.js
> +    fill: theme.palette.charcoal || '#333', // Fallback color
here too?

2024-11-20 15:58 UTC, sudhanshutech requested changes

2024-11-20 15:58 UTC, sudhanshutech commented on ui/components/UserPreferences/index.js
> +export const StyledTabs = styled(Tabs)(({ theme }) => ({
are these tabs can't be styled directly to sistent instead custom styling here?

2024-11-21 21:30 UTC, hamza-mohd commented on ui/components/UserPreferences/style.js
> +  backgroundColor: theme.palette.primary.main,
🤔

2024-11-29 18:08 UTC, leecalcote commented
@shanu your review here is encouraged.

2025-01-13 19:38 UTC, sudhanshutech commented
https://github.com/meshery/meshery/pull/13230 fixed here

2025-01-13 19:38 UTC, closed without merging