Update version of go
meshery/meshery pull request #12837
Opened 2024-12-05 06:25 UTC by eyeaadil

**Notes for Reviewers**

- This PR fixes #12892
- Description:Update the version of Go lang as some of the dependencies not supported in earlier version.
- 
**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-12-05 12:54 UTC, leecalcote requested changes
Thanks. It’s going to take a lot more work than this to complete this issue. 

Among many other items that need attended to, you need to build the project and ensure go.sum is included. Again, this is one of a number of other tasks to perform.  If those are unfamiliar or you can’t figure it out, please remove
your assignment from this particular issue.

2024-12-06 12:50 UTC, hamza-mohd commented on docs/.ruby-version
Remove

2024-12-06 12:51 UTC, hamza-mohd requested changes

2024-12-06 12:51 UTC, hamza-mohd commented on docs/Gemfile.lock
Inappropriate. Remove.

2024-12-06 12:51 UTC, hamza-mohd commented on docs/_catalog/deployment/29b94780-865c-460b-b852-cc5c31730561.md
Inappropriate for the respective issue.

2024-12-06 15:48 UTC, eyeaadil commented on docs/_catalog/deployment/29b94780-865c-460b-b852-cc5c31730561.md
By mistake, I ended up combining the resolution of another issue in this PR.

2024-12-13 18:55 UTC, jamieplu requested changes
The feedback offered by other maintainers remains outstanding.

2025-01-24 06:43 UTC, closed without merging