Fix #11942
meshery/meshery pull request #12851
Opened 2024-12-06 09:19 UTC by eyeaadil

**Notes for Reviewers**

- This PR fixes #11942

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.
-Description:-resolve redundancy in error page.

2024-12-09 20:44 UTC, leecalcote requested changes
Please don't delete this file.

2024-12-10 15:54 UTC, eyeaadil commented
> Please don't delete this file.

that file is redundant file or copy of this file  docs/_data/errorref/meshery-server_errors_export.json.
remove file and this file are same.

2024-12-10 19:28 UTC, eyeaadil commented
> Please don't delete this file.

that deleted file create this issue , the redundancy in docs page.

2024-12-11 06:45 UTC, vishalvivekm commented
@eyeaadil 
Let's discuss this during the Meshery Development call today at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1#) || [meeting link](https://meet.layer5.io/meshery).

2024-12-20 05:06 UTC, eyeaadil commented
@vishalvivekm ,can you please review this PR,In last  Meshery Development call i was not present because i was travelling that day.

2025-02-09 11:34 UTC, closed without merging