Remove the word "successfully"
meshery/meshery pull request #12932
Opened 2024-12-20 21:00 UTC by weilirs

Signed-off-by: weilirs <weilirs@umich.edu>

**Notes for Reviewers**
In the last week's development call, Lee told me to remove the word "successfully" from Meshery events, error code messages, and notifications sent to the user.
- This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-12-22 13:11 UTC, alphaX86 requested changes

2024-12-22 13:11 UTC, alphaX86 commented on mesheryctl/internal/cli/root/design/error.go
> +	return errors.New(ErrInvalidDesignFileCode, errors.Fatal, []string{err.Error()}, []string{"Design appears invalid. Could not parse"}, []string{"Design file provided is not valid"}, []string{"Please
```suggestion
	return errors.New(ErrInvalidDesignFileCode, errors.Fatal, []string{err.Error()}, []string{"Design appears invalid. Could not parse provided design"}, []string{"Design file provided is not valid"}, []string{"Please check that your design file is a valid yaml file"})
```

2024-12-22 13:11 UTC, alphaX86 commented on mesheryctl/pkg/utils/auth.go
> +		fmt.Fprint(rw, "logged in, you can close this window now")
```suggestion
		fmt.Fprint(rw, "you have logged in, you can close this window now")
```

2024-12-25 12:56 UTC, vishalvivekm commented
@weilirs 
Thank you for your contributions! Let's discuss this today, during Meshery Development call at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1&tab=t.0#) || [meeting link.](https://meet.layer5.io/meshery)

2024-12-25 16:34 UTC, weilirs commented
> @weilirs Thank you for your contributions! Let's discuss this today, during Meshery Development call at 9:00 AM CT | 8:30 PM IST. Adding it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1&tab=t.0#) || [meeting link.](https://meet.layer5.io/meshery)

sorry I can't make it today

2024-12-27 03:08 UTC, alphaX86 submitted a review, later dismissed
Approved on my side. @weilirs pls fix merge conflicts.

@lekaf974 could you review this once?

2024-12-27 14:45 UTC, weilirs commented
> Approved on my side. @weilirs pls fix merge conflicts.
> 
> @lekaf974 could you review this once?

I fixed the merge conflict, I don't know why it dismissed your review...

2024-12-27 16:27 UTC, alphaX86 approved these changes

2024-12-27 16:28 UTC, alphaX86 commented
> > Approved on my side. @weilirs pls fix merge conflicts.
> > 
> > @lekaf974 could you review this once?
> 
> I fixed the merge conflict, I don't know why it dismissed your review...

Not a problem @weilirs :) no worries

2024-12-27 20:17 UTC, leecalcote approved these changes
Awesome. Thank you, @weilirs and @alphaX86. 👏

2024-12-27 20:18 UTC, merged