Update server and mesheryctl Go version to 1.23
meshery/meshery pull request #12941
Opened 2024-12-21 08:33 UTC by devhindo

updating meshery/meshery server & meshery/meshery ctl

fixes: meshery/meshery#12829

2024-12-27 20:16 UTC, leecalcote commented
@weilirs you're eyes on this would be great.

2024-12-27 20:37 UTC, weilirs commented
> @weilirs you're eyes on this would be great.

I'll review it and talk about my reviewing process to make sure everything is correct.

2024-12-30 18:48 UTC, weilirs requested changes
And I think the `GOVERSION` in the file "Makefile.core.mk" needs to be updated to 1.23.

Others look good to me.
I ran `go mod tidy`, `go mod verify` and `go list -m all` they all went well.
And I did `make server` it works as well.

2024-12-30 18:48 UTC, weilirs commented on .github/workflows/go-testing-ci.yml
I think line 24 should be updated to 1.23 as well

2025-01-02 17:15 UTC, leecalcote commented
@devhindo still needed?

2025-01-02 17:32 UTC, closed without merging