Dashboard migration
meshery/meshery pull request #13005
Opened 2024-12-25 14:28 UTC by SAHU-01

**Notes for Reviewers**

- This PR migrates all Dashboard page components to MUI v5

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-12-26 17:54 UTC, miacycle commented
Eslint check... 👁️

2024-12-28 15:34 UTC, Ajay-singh1 requested changes
Grid is a deprecated component , I think.

2024-12-30 20:10 UTC, sudhanshutech approved these changes
revert package lock changes and fix eslint otherwsie looks good

2024-12-31 19:12 UTC, sudhanshutech requested changes

2024-12-31 19:12 UTC, sudhanshutech commented on ui/components/DashboardComponent/overview.js
> +// import React from 'react';
remove it if not needed

2025-01-05 14:13 UTC, sudhanshutech commented
merge conflict

2025-01-07 16:35 UTC, sudhanshutech requested changes

2025-01-07 16:35 UTC, sudhanshutech commented on ui/components/DashboardComponent/charts/DashboardMeshModelGraph.js
> +                    color={theme.palette.secondary.iconMain}
```suggestion
                    color={theme.palette.icon.default}
```

this is a sistent token.

2025-01-07 16:35 UTC, sudhanshutech commented on ui/components/DashboardComponent/charts/DashboardMeshModelGraph.js
> +                    color={theme.palette.secondary.iconMain}
```suggestion
                    color={theme.palette.icon.default}
```

2025-01-07 16:35 UTC, sudhanshutech commented on ui/components/DashboardComponent/charts/MesheryConfigurationCharts.js
> +                    color={theme.palette.secondary.iconMain}
```suggestion
                    color={theme.palette.icon.default}
```

2025-01-13 08:21 UTC, sudhanshutech commented
https://github.com/meshery/meshery/pull/13221

2025-01-13 08:21 UTC, closed without merging