fix: generate command error handling
meshery/meshery pull request #13002
Opened 2024-12-25 11:50 UTC by capricorn-32

**Notes for Reviewers**

- This PR fixes #
Fixed error handling in generate command `mesheryctl registry generate`

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-12-25 15:44 UTC, devhindo requested changes

2024-12-25 15:44 UTC, devhindo commented on mesheryctl/internal/cli/root/registry/generate.go
so it would be more efficient to do something like this to just show the docs of the command suppossing that these docs contains every needed information about each of the parameters instead of explicitly fmt.Errorfing them
```Go
    if len(args) == 0 {
        return cmd.Help()
    }
```

2024-12-25 15:45 UTC, devhindo commented
also can you please link the issue in the pr? to be `This PR fixes #13001`

2024-12-26 10:11 UTC, capricorn-32 commented
fixes #13001

2024-12-27 20:16 UTC, leecalcote commented
@souvikinator, you're eyes here would be great.

2024-12-28 13:03 UTC, souvikinator requested changes

2024-12-28 13:03 UTC, souvikinator commented on mesheryctl/internal/cli/root/registry/generate.go
> +		if csvDirectory != "" && (spreadsheeetID != "" || pathToRegistrantConnDefinition != "") {
only following two checks should be kept since the rest are handled by Cobra directives.

2024-12-28 13:03 UTC, souvikinator commented on mesheryctl/internal/cli/root/registry/generate.go
>  	RunE: func(cmd *cobra.Command, args []string) error {
Why are we adding these checks in `RunE` instead of `PreRunE`?

2024-12-28 13:11 UTC, souvikinator requested changes

2024-12-28 13:11 UTC, souvikinator commented on mesheryctl/internal/cli/root/registry/generate.go
> +		if csvDirectory != "" && (spreadsheeetID != "" || pathToRegistrantConnDefinition != "") {
can define cobra directive for csv directory condition check in the `inti()` function like so:
```go
    generateCmd.MarkFlagsMutuallyExclusive("directory", "spreadsheet-id")
    generateCmd.MarkFlagsMutuallyExclusive("directory", "registrant-def")
```

2024-12-28 14:44 UTC, lekaf974 requested changes

2024-12-28 14:44 UTC, lekaf974 commented on mesheryctl/internal/cli/root/registry/generate.go
> +			return fmt.Errorf("both 'spreadsheet-id' and 'spreadsheet-cred' must be provided together")
For this and all following errors, it should return a MeshkitError instead

2024-12-28 14:49 UTC, capricorn-32 commented
@souvikinator @lekaf974 thanks for the review, I know this is wrong approach for checking flag. In previous meeting I was told to use cobra validation instead. I'm working on it.

2024-12-28 17:10 UTC, lekaf974 commented
> @souvikinator @lekaf974 thanks for the review, I know this is wrong approach for checking flag. In previous meeting I was told to use cobra validation instead. I'm working on it.

Good, you can take example on other commands

2024-12-28 18:45 UTC, capricorn-32 commented
@souvikinator @lekaf974 thats it from my side can you review it again, thanks

2024-12-30 15:13 UTC, lekaf974 commented on mesheryctl/internal/cli/root/registry/generate.go
> +				return fmt.Errorf("Csv directory is invalid.")
Should use a Meshkit Error example line 83

2024-12-30 15:13 UTC, lekaf974 commented on mesheryctl/internal/cli/root/registry/generate.go
>  				return fmt.Errorf("error reading the directory: %v", err)
Should use Meshkit Error

2024-12-30 15:14 UTC, lekaf974 commented on mesheryctl/internal/cli/root/registry/generate.go
>  				return fmt.Errorf("both ModelCSV and ComponentCSV files must be present in the directory")
Should use Meshkit Error

2024-12-30 15:14 UTC, lekaf974 commented on mesheryctl/internal/cli/root/registry/generate.go
> +				return fmt.Errorf("spreadsheet cred is invalid.")
Should use Meshkit Error

2024-12-30 15:18 UTC, capricorn-32 commented
@lekaf974 Okay I'll check meshkit, and add the corresponding error messages.
thanks for review

2025-01-01 11:16 UTC, vishalvivekm commented
@capricorn-32 
Thank you for your contributions! Let's discuss this today, during Meshery Development call at 9:00 AM CT | 8:30 PM IST. Add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit?pli=1&tab=t.0#) || [meeting link.](https://meet.layer5.io/meshery), if you would, please.

2025-01-14 02:41 UTC, leecalcote commented
@lekaf974, could I ask that you take over this PR? @capricorn-32 has abandoned his effort here.

2025-01-15 00:13 UTC, closed without merging

2025-01-15 00:14 UTC, lekaf974 commented
Closing PR