fix(docs): Add hyperlinks to command headings for direct navigation w…
meshery/meshery pull request #13044
Opened 2024-12-29 10:54 UTC by makifyegin

…/signoff

**Notes for Reviewers**

- This PR fixes # [Docs] Improve meshseryctl docs UI #13008

- Updated headings to include hyperlinks that allow users to navigate directly to the relevant section of the page.
- Example: Clicking on a heading like "mesheryctl perf" now takes the user directly to the corresponding section.
- Improves user experience by reducing the need for manual scrolling.

![image](https://github.com/user-attachments/assets/201d6775-31cb-4493-9614-81d48aa09225)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-12-29 10:58 UTC, l5io commented
🚀 Preview for commit 1d65ff5b4c69340b791b3e39f4aee51ef1106292 at: https://67712b42eee13cbde91788ff--meshery-docs-preview.netlify.app

2024-12-29 11:22 UTC, devhindo requested changes
make sure that every command is set to the right table. some commands are not correct like `mesheryctl registry` is set to `components` table. check the rest as well.

2024-12-29 13:01 UTC, l5io commented
🚀 Preview for commit 688fc71b951730f96f8be6f14f986345d256bd14 at: https://6771482897d6eae2a8fb0b6d--meshery-docs-preview.netlify.app

2024-12-29 13:09 UTC, devhindo approved these changes
LGTM

2024-12-29 13:10 UTC, devhindo commented
good so far! also make sure to link the related issue by editing the pr description to be `fixes: #13008` (the issue number after the # sign)

2024-12-29 13:11 UTC, devhindo commented
@leecalcote ready to merge!

2024-12-30 22:20 UTC, Yashsharma1911 approved these changes
LGTM

2024-12-30 22:21 UTC, Yashsharma1911 commented
By the way why the colors are in red no our traditional green? I mean Kepple Green as other links?

2024-12-30 22:22 UTC, Yashsharma1911 commented
Ohh never mind I see we are using it in multiple places already for CLI

2024-12-30 22:24 UTC, merged

2024-12-30 22:52 UTC, makifyegin commented
If it's a code looks like a red if it's a something it's green I think...

2024-12-31 00:00 UTC, leecalcote commented
Yes, this coloring is not ideal.

2024-12-31 00:34 UTC, makifyegin commented
I can create an issue to address this, including changing all instances of red to green (or another specified color) and work on it. I also have a concern regarding hyperlinks—currently, titles appear under the navbar. I’ve checked before the PR, and all hyperlink titles seem to follow the same behavior. I wanted to highlight this in case we decide to modify it.