[Docs] Resolves the missing bullet points (Issue #12903)
meshery/meshery pull request #13064
Opened 2024-12-31 00:06 UTC by FilledEther20

**Notes for Reviewers**

- This PR fixes #12903 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

**Before**
![image](https://github.com/user-attachments/assets/05dae50b-3f91-4979-a13b-df252cfdda5b)

**After**
![image](https://github.com/user-attachments/assets/cbf88cc9-b1f6-49af-a83d-9d91c54e87e0)

2024-12-31 00:10 UTC, l5io commented
🚀 Preview for commit 0f1cf3f1cd9991b90d2974200fd1d26ba85a2b9f at: https://67733644e1dbb342f1c32a7e--meshery-docs-preview.netlify.app

2025-01-01 20:49 UTC, leecalcote requested changes

2025-01-01 20:49 UTC, leecalcote commented on docs/_releases/v0.6.0-rc.5t.md
> +- [UI] : Display filename after upload. @SAEb-ai (#5501)
@FilledEther20, thank you.

The whitespace between the square bracket and the colon is improper. Will you identify and use another way to solve this issue, excluding insertion of this whitespace?

e.g. use of a `\`
```
[UI\]: some text here
```

2025-01-02 18:23 UTC, l5io commented
🚀 Preview for commit d1bce45479a4eac2e3051e12b475176ea17504ee at: https://6776d96fe1dbb383b4c32b60--meshery-docs-preview.netlify.app

2025-01-21 17:25 UTC, sangramrath commented
@FilledEther20 and @leecalcote checked a few of the release pages and looks good. Merging this for now.

2025-01-21 17:25 UTC, merged