[UI] Grafana components migration
meshery/meshery pull request #13077
Opened 2024-12-31 18:19 UTC by SAHU-01

**Notes for Reviewers**

- This PR migrates all the grafana components to MUI v5 styling and uses sistent components and tokens

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-12-31 19:47 UTC, leecalcote commented on ui/components/telemetry/grafana/GrafanaCustomCharts.js
> +const DateRangePickerContainer = styled('div')({
`({ theme })` not needed here, right?

2025-01-01 06:23 UTC, Ajay-singh1 requested changes
Minor changes needed.

2025-01-01 06:23 UTC, Ajay-singh1 commented on ui/components/telemetry/grafana/GrafanaConfigComponent.js
> +import { NoSsr } from '@material-ui/core';
```suggestion
import { NoSsr } from '@mui/core/NoSsr';
```
Update import

2025-01-01 06:23 UTC, Ajay-singh1 commented on ui/components/telemetry/grafana/GrafanaCustomChart.js
> +import { NoSsr } from '@material-ui/core';
```suggestion
import { NoSsr } from '@mui/core/NoSsr';
```
Here too

2025-01-01 06:23 UTC, Ajay-singh1 commented on ui/components/telemetry/grafana/GrafanaCustomGaugeChart.js
>  import { NoSsr } from '@material-ui/core';
```suggestion
import { NoSsr } from '@mui/core/NoSsr';
```

2025-01-01 06:23 UTC, Ajay-singh1 commented on ui/components/telemetry/grafana/GrafanaDateRangePicker.js
> +import { NoSsr } from '@material-ui/core';
```suggestion
import { NoSsr } from '@mui/core/NoSsr';
```

2025-01-01 06:23 UTC, Ajay-singh1 commented on ui/components/telemetry/grafana/GrafanaDisplaySelection.js
> +import { NoSsr } from '@material-ui/core';
```suggestion
import { NoSsr } from '@mui/core';
```

2025-01-01 06:23 UTC, Ajay-singh1 commented on ui/components/telemetry/grafana/GrafanaSelectionComponent.js
> +import { NoSsr } from '@material-ui/core';
```suggestion
import { NoSsr } from '@mui/core';
```

2025-01-05 14:11 UTC, sudhanshutech requested changes
@SAHU-01 have you able to test that everything looks good?

2025-01-05 14:13 UTC, sudhanshutech requested changes

2025-01-05 14:13 UTC, sudhanshutech commented on ui/components/telemetry/grafana/GrafanaCustomChart.js
> +  color: '#D32F2F',
if this a error then use sistent error token

2025-01-07 16:28 UTC, sudhanshutech commented on ui/components/telemetry/grafana/GrafanaDateRangePicker.js
> +  color: 'white',
```suggestion
  color: theme.palette.text.constant?.white
```

2025-01-07 16:29 UTC, sudhanshutech commented on ui/components/telemetry/grafana/GrafanaDateRangePicker.js
> +  borderTop: `1px solid ${theme.palette.divider}`,
how this theme is working if using sistent because this particular color is in meshery. Use sistent border color
```suggestion
  borderTop: `1px solid ${theme.palette.border.<>}`,
```

2025-01-07 16:31 UTC, sudhanshutech commented on ui/components/telemetry/grafana/GrafanaSelectionComponent.js
> +  grafanaBoards: state.grafanaBoards,
why this change?

2025-01-12 13:12 UTC, sudhanshutech commented on ui/components/telemetry/grafana/GrafanaSelectionComponent.js
> +  grafanaBoards: state.grafanaBoards,
@SAHU-01 ?

2025-01-16 15:15 UTC, closed without merging