Enhancement: Added tooltips for navigation menu items while in minimised state
meshery/meshery pull request #1425
Opened 2020-08-18 14:38 UTC by kalradev

**Description**

This PR fixes #1413

**Notes for Reviewers**
disableFocusListener, disableHoverListener, disableTouchListener
I added these three props, so that the tooltip won't show when the drawer is not in a collapsed state.
I didn't add tooltip for the expand and shrink icon, because I think the symbol in itself is enough.

Here is a screenshot for your reference
![Screenshot from 2020-08-18 19-42-24](https://user-images.githubusercontent.com/32228313/90525070-756d7480-e18c-11ea-9646-b775cecb6196.png)

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2020-08-18 20:51 UTC, leecalcote commented
Cool! Thanks for this, @kalradev

2020-08-18 23:44 UTC, dhruv0000 commented
Great work @kalradev . Looks good to me.

2020-08-19 03:02 UTC, Nikhil-Ladha approved these changes
Nice work @kalradev 🎉👍🏼

2020-08-19 13:46 UTC, dhruv0000 approved these changes

2020-08-19 18:03 UTC, kushthedude requested changes
Hey @kalradev Great work here! 
Just a small change, please remove the following props as `!isDrawerCollapsed = False` when the following code is used, and according to ToolTip API, these props are defaulted to false.
Hence this code is not required

2020-08-19 18:03 UTC, kushthedude commented on ui/components/Navigator.js
> +            disableTouchListener={!drawerCollapsed}
```suggestion

```

2020-08-19 18:03 UTC, kushthedude commented on ui/components/Navigator.js
> +                            disableTouchListener={!isDrawerCollapsed}
```suggestion
```

2020-08-19 18:03 UTC, kushthedude commented on ui/components/Navigator.js
> +                    disableTouchListener={!isDrawerCollapsed}
```suggestion
```

2020-08-19 18:13 UTC, kalradev commented
Hey @kushthedude,

I added the props not for when the drawer will be in a collapsed state but for when it is not.

Drawer is not in a collapsed state
Then the condition !drawercollapsed will return true and it will basically disable the tooltip. The reason for adding this is if the tooltip is not disabled and a user hover over the icon the tooltip will be displayed and the user will see two same text. I didn't like that if it has to be like that I can do the change.

2020-08-19 18:20 UTC, kushthedude approved these changes

2020-08-19 18:22 UTC, kushthedude commented
> Drawer is not in a collapsed state
> Then the condition !drawercollapsed will return true and it will basically disable the tooltip. The reason for adding this is if the tooltip is not disabled and a user hover over the icon the tooltip will be displayed and the user will see two same text. I didn't like that if it has to be like that I can do the change.

Got it, Great work 🚀 !

2020-08-19 18:22 UTC, merged