Udoka vrede branch
meshery/meshery pull request #1516
Opened 2020-09-02 09:28 UTC by UdokaVrede

**Description**

This PR fixes #1512 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2020-09-02 11:37 UTC, leecalcote commented
@UdokaVrede remember to use a PR title that is descriptive of the contents of the PR.

2020-09-02 11:43 UTC, subhamkrai commented on mesheryctl/internal/cli/root/version.go
>  		build := mctlCfg.GetVersion().GetBuild()
with the current changes we will get `build declared but not usedcompiler
`

2020-09-02 11:44 UTC, subhamkrai commented on mesheryctl/internal/cli/root/version.go
>  		commitsha := mctlCfg.GetVersion().GetCommitSHA()
same

2020-09-03 13:56 UTC, PluckyPrecious commented
> @UdokaVrede remember to use a PR title that is descriptive of the contents of the PR.

Hi @UdokaVrede as Lee rightly pointed out, what do you think about using this `Add letter v to client version` as the PR title? 😃

2020-09-03 22:08 UTC, leecalcote commented
> > @UdokaVrede remember to use a PR title that is descriptive of the contents of the PR.
> 
> Hi @UdokaVrede as Lee rightly pointed out, what do you think about using this `Add letter v to client version` as the PR title? 😃

Nice suggested title. I've updated the PR title to reflect.

2020-09-04 16:19 UTC, anirudhjain75 requested changes
The Error you are currently facing states tha you have build and commitsha variables but you have not used them. Go is a strict languages in terms of code syntax. You get errors if import a package and not use it or even if you leave any variables unused. Using Go linter along with your IDE would be preferred and root out common lint issues. I use Goland and it points out every lint issue there is and also helps me fix them.

2020-09-04 16:19 UTC, anirudhjain75 commented on mesheryctl/internal/cli/root/version.go
> +		logrus.Infof("Client Version: %v \t  GitSHA: %v", version.GetBuild(), version.GetCommitSHA())
Hey @UdokaVrede , You can simply use build and commitsha instead of using version.GetBuild() or version.GetCommitSha().

2020-09-04 16:22 UTC, anirudhjain75 commented
I'd recommend running the steps to figure out the issue before trying to fix them. Partly my fault for creating issue without testing it out. That would've saved your time. Hope you also learned from this experience. 😅

2020-09-04 16:24 UTC, anirudhjain75 commented
Someone must've patched it and got it merged

2020-09-04 16:24 UTC, closed without merging

2020-09-05 10:50 UTC, UdokaVrede commented
@anirudhjain75 @leecalcote I've been unavailable on here for awhile, I could not effect the necessary changes. Nice its been fixed