added missing windows installation steps
meshery/meshery pull request #1587
Opened 2020-09-15 21:24 UTC by abiodunolunu

This Fixes #1585

2020-09-15 23:58 UTC, akashgp09 reviewed
LGTM 👍

2020-09-16 08:25 UTC, KarenEfereyan approved these changes
Great.

2020-09-16 13:20 UTC, chandrashritii requested changes

2020-09-16 13:20 UTC, chandrashritii commented on docs/pages/installation/windows.md
> +
The prerequisites need to be mentioned. Docker is one of them. As far as I'm aware, one also needs a Linux VM, to easily work with Docker on Windows.

2020-09-17 01:55 UTC, vijcheru requested changes
You also need a Kubernetes config file. This file is in the default setting C:\Users\username\\.kube directory and is called config.
Also, as mentioned by @chandrashritii , you will need Docker and docker should be set to use Linux containers. If you are trying to run this on your own desktop without any outside resources, you can install Docker Desktop. You will also need a Linux VM as mentioned by @chandrashritii . If you are running the Windows Professional Edition, your machine can be set up to enable Hyper-V using Turning Windows Features on and Off. I think installing Docker Desktop will give the choice of using Hyper-V.

Everything else looks good.

2020-09-17 10:42 UTC, chandrashritii commented
@vijcheru You're right. One update here, with the recent WSL2 announcement by Microsoft, you do not need to enable HyperV, nor do you need the Windows professional edition to enable WSL2 and consecutively integrate and run Docker Desktop. Both, Docker Desktop and WSL2 can be run on Windows 10 Home edition (version>1903) and Windows Professional editions now. For any lower Windows versions, one option is to resort to using the deprecated version of Docker, the Docker toolbox. The documentation should be updated accordingly.

@leecalcote I have a template written up for this. Perhaps this PR can be merged and I will open a different one to include the prerequisites and update the Windows documentation.

2020-09-17 21:20 UTC, leecalcote commented
@chandrashritii sounds great.

@abiodunolunu thank you for your contribution here. 👍

2020-09-17 21:20 UTC, leecalcote approved these changes

2020-09-17 21:20 UTC, merged