added release notes v0.4.3
meshery/meshery pull request #1600
Opened 2020-09-22 14:12 UTC by anshdhinhgra47

Signed-off-by: Ansh Dhingra  anshdhingra47@gmail.com

This PR fixes ##1598

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2020-09-22 16:18 UTC, kushthedude requested changes

2020-09-22 16:18 UTC, kushthedude commented on docs/pages/project/releases.md
> +Released on 22 August
Can you please add year also?

2020-09-22 16:18 UTC, kushthedude commented on docs/pages/project/releases.md
>  Released on 8 August
Please add year here too

2020-09-22 16:27 UTC, anshdhinhgra47 commented
Should I then create a new PR afterwards ?

2020-09-22 16:32 UTC, kushthedude commented
> Should I then create a new PR afterwards ?

The following change can be accommodated in the same PR, having more micro-PRs can lead to a bad git commit history.

2020-09-22 16:33 UTC, anshdhinhgra47 commented
Oh okay

2020-09-22 16:34 UTC, anshdhinhgra47 commented
I'll just add

2020-09-22 16:34 UTC, kushthedude commented
Thank you !

2020-09-22 16:39 UTC, anshdhinhgra47 commented
Added year to the dates. Please review

2020-09-22 16:48 UTC, kushthedude commented on docs/pages/project/releases.md
> +- Featured
```suggestion
- Features
```

2020-09-22 16:49 UTC, kushthedude commented on docs/pages/project/releases.md
> +- Other fixes
```suggestion
- Bug fixes
```

2020-09-22 17:19 UTC, kushthedude approved these changes
Thank you @anshdhinhgra47, great work here!

2020-09-22 17:19 UTC, merged

2020-09-23 06:13 UTC, KarenEfereyan commented
@anshdhinhgra47 well done

2020-09-23 06:36 UTC, anshdhinhgra47 commented
Thank you so much 😊