update readme. maesh to traefik mesh
meshery/meshery pull request #1663
Opened 2020-10-08 09:52 UTC by dannylwe

Signed-off-by: Daniel Lwetabe <acehanks@gmail.com>

**Description**
Update readme documentation.
Change Mesh to Traefik Mesh

This PR fixes #1662

**Notes for Reviewers**
Ready for merge

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2020-10-08 15:46 UTC, bartkalanski submitted a review, later dismissed
Good job!

2020-10-08 16:57 UTC, leecalcote approved these changes
Thank you, @dannylwe 👍

2020-10-08 16:58 UTC, leecalcote requested changes
@dannylwe will you make a copy of the icon and place in this repo under this folder? https://github.com/layer5io/meshery/tree/master/docs/assets/img/readme

Cross-linked resources go missing and we end up with broken images.

2020-10-09 10:41 UTC, PluckyPrecious approved these changes
LGTM 👍🏽

2020-10-09 12:45 UTC, bartkalanski requested changes
Now you added the icon to the repo, would you mind using that as ```src``` for the image ? You'll have to change one line of code, and once that's done, you'll be good to go!

2020-10-09 21:36 UTC, leecalcote approved these changes

2020-10-09 21:36 UTC, leecalcote commented on README.md
> +            <img src='https://raw.githubusercontent.com/layer5io/meshery/master/docs/assets/img/service-meshes/traefik.svg' alt='Traefik Service Mesh' align="middle" hspace="5px" vspace="5px" height=
A repo-local reference. Good deal.

2020-10-09 21:36 UTC, merged