Updating Istio Documentation,
meshery/meshery pull request #1683
Opened 2020-10-15 18:14 UTC by Maxgit3

## Istio Documentation Update 1.7.3

**Description**
changed documentation to fit the new version of Istio.

This PR fixes  #1676 

**Notes for Reviewers**
would you like me to look through the Istio documentation to see if anything should be added?

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x ] Yes, I signed my commits.

2020-10-15 18:40 UTC, Maxgit3 commented
fixed the sign off issue.  how do you rerun checks?

2020-10-15 18:54 UTC, kishore007k commented
> fixed the sign off issue. how do you rerun checks?
Do the following while you are in your branch `Maxgit3:istio-1.7.3-doc-update`
- `git add .`
-  `git commit --amend --signoff`
-  `git push --force-with-lease origin "Your branch name"`

2020-10-16 03:27 UTC, Maxgit3 commented
the sign off is expecting unknown for name.  not sure why that is.

2020-10-16 03:57 UTC, kishore007k commented
> the sign off is expecting unknown for name.  not sure why that is.

Could you reach me on slack?

2020-10-16 05:36 UTC, chandrashritii requested changes
Except for the version in the page layout details, the placeholders (for example, {{page.name}}) don't need to be changed.

2020-10-16 05:36 UTC, chandrashritii commented on docs/_adapters/istio/istio.md
> +The Meshery Adapter for Istio can install **v1.7.3** of the Istio service mesh. The SMI adapter for Istio can also be installed using Meshery.
```suggestion
The {{page.name}} can install **{{page.version}}** of the {{page.title}} service mesh. The SMI adapter for Istio can also be installed using Meshery.
```

2020-10-16 15:24 UTC, Maxgit3 commented
> > the sign off is expecting unknown for name.  not sure why that is.
> 
> Could you reach me on slack?

@kishore007k sorry for the late reply.  yes I can check slack.  what name should I look for?

2020-10-16 15:25 UTC, kishore007k commented
> > > the sign off is expecting unknown for name.  not sure why that is.
> > 
> > Could you reach me on slack?
> 
> @kishore007k sorry for the late reply.  yes I can check slack.  what name should I look for?

its kishore

2020-10-16 20:32 UTC, leecalcote approved these changes

2020-10-16 20:33 UTC, merged

2020-10-16 22:51 UTC, leecalcote commented
Pretty 😎, @Maxgit3