translate es project, installation/index.md page
meshery/meshery pull request #1711
Opened 2020-10-20 22:52 UTC by alonsolopezr

Signed-off-by: Alonso López Romo <alonsolopez@uthermosillo.edu.mx>

**Description**

This PR fixes #

**Notes for Reviewers**
@jesuslerma Tag for review... gracias por el apoyo

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2020-10-20 22:58 UTC, jesuslerma requested changes
Hello @alonsolopezr I just added some changes on spelling and also there is a missing part that requires to be translated: Installing with Bash :)

2020-10-20 22:58 UTC, jesuslerma commented on docs/pages/es/project/installation/index.md
> +Los Userios pueden controlar la imagen de contenedor específico y etiqueta(versión) de Meshery que quieran ejecutar mediante la edición de su archivo local `~/.meshery/meshery.yaml` (un archivo de do
Los usuarios*

2020-10-20 22:58 UTC, jesuslerma commented on docs/pages/es/project/installation/index.md
> +Cuando Meshery esta levantado y corriendo, las instrucciones para acceder Meshery serán impresas en la pantalla y su navegador web por default deberá ser dirigido a la pantalla de ingreso de Meshery.
está levantado y corriendo.

2020-10-20 22:58 UTC, jesuslerma commented on docs/pages/es/project/installation/index.md
> +**Installing with Bash**
Instalación con Bash

2020-10-20 22:58 UTC, jesuslerma commented on docs/pages/es/project/installation/index.md
> +Install `mesheryctl` and run Meshery on Mac or Linux with this script:
Instala `mesheryctl` y ejecuta Meshery en Mac o Linux con este script:

2020-10-20 23:44 UTC, closed without merging

2020-10-21 04:07 UTC, leecalcote commented
It's good to see this, @alonsolopezr. 👍