[Docs] Section update
meshery/meshery pull request #1726
Opened 2020-10-22 16:14 UTC by chandrashritii

**Description**

- Rearranged the overview page
- Added pages to the Project section

Signed-off-by: Shriti <shritichan@gmail.com>

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2020-10-22 16:26 UTC, leecalcote commented
Back to the drawing board for the administrative-tools.png image.

2020-10-22 16:29 UTC, leecalcote requested changes

2020-10-22 16:29 UTC, leecalcote commented on docs/assets/css/main.css
> +.img-thumbnail {
The book cover image is skewed.
<img width="258" alt="Screen Shot 2020-10-22 at 11 23 23 AM" src="https://user-images.githubusercontent.com/7570704/96901609-18768f00-1459-11eb-8bff-69b08bbf6490.png">

2020-10-22 16:29 UTC, leecalcote commented on docs/pages/project/resources.md
> +
Add something like "Have you given a presentation? Add yours here!" with link to submit docs issue. Be inspired from here - https://linkerd.io/community/

2020-10-22 16:29 UTC, leecalcote commented on docs/assets/css/main.css
> +    border: 1px solid #ddd;
Remove border or if you'd like to make these buttons, reuse the existing button style (or set a new one) on the site.

2020-10-22 16:29 UTC, leecalcote commented on docs/pages/project/FAQ.md
> +on the <a hre="http://slack.layer5.io/">Layer5 Slack</a>. </div>
keep these on the same line (avoid line break)

2020-10-22 16:42 UTC, chandrashritii commented
> 
> 
> Back to the drawing board for the administrative-tools.png image.

I've used a generic icon here. Is there any other image we can use for _service mesh landscape tools_?

2020-10-22 17:45 UTC, leecalcote commented
> > Back to the drawing board for the administrative-tools.png image.
> 
> @leecalcote I've used a generic icon here. Is there any other image we can use for _service mesh landscape tools_?



> > Back to the drawing board for the administrative-tools.png image.
> 
> @leecalcote I've used a generic icon here. Is there any other image we can use for _service mesh landscape tools_?

Yes, but icon is out of place with the theme that we have. You might leverage the gear icon from here - 
https://drive.google.com/drive/u/0/folders/1-JzsjwJwCT2yiSRzW0n9qkQq4jDjlq_a

2020-10-27 01:55 UTC, leecalcote approved these changes
Two issues filed to follow up this PR.

2020-10-27 01:55 UTC, leecalcote commented on docs/pages/project/resources.md
> +
Created https://github.com/layer5io/meshery/issues/1762 to track this request.

2020-10-27 01:55 UTC, leecalcote commented on docs/assets/css/main.css
> +.img-thumbnail {
Created https://github.com/layer5io/meshery/issues/1763 to track this required change.

2020-10-27 01:55 UTC, merged