Ccoss2020 fixes1803
meshery/meshery pull request #1804
Opened 2020-10-31 04:31 UTC by Drake8710

Signed-off-by: Vladimir GS <vladimir.garcia@ibm.com>

**Description**

This PR fixes #1803 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2020-10-31 04:32 UTC, Drake8710 commented
Hey @jesuslerma 
Please review this. Thanks

2020-11-02 22:44 UTC, leecalcote requested changes

2020-11-02 22:44 UTC, leecalcote commented on docs/pages/es/architecture.md
> +#### La arquitectura de Meshery puede ser vista desde dos perspectivas:
Thank you for this, @Drake8710. 

Let's avoid constraining the architectural perspective of Meshery to only two perspectives, understanding that there are a number of diagrams that we will publish over time.

2020-11-02 22:44 UTC, leecalcote commented on docs/pages/es/architecture.md
> +
Will you incorporate this new [Languages section](https://meshery.layer5.io/docs/architecture#languages), too?

2020-11-02 22:44 UTC, leecalcote commented on docs/pages/es/architecture.md
> +
Will you incorporate the [Deployments section](https://meshery.layer5.io/docs/architecture#deployments), too? 

Meshery se implementa como un conjunto de contenedores. Los contenedores de Meshery se pueden implementar en Docker o Kubernetes.

2020-11-12 02:32 UTC, leecalcote approved these changes

2020-11-12 02:32 UTC, merged

2020-11-12 02:32 UTC, leecalcote commented
Thank you, @Drake8710 👍