[Docs] update installation guides
meshery/meshery pull request #1950
Opened 2020-11-18 14:15 UTC by chandrashritii

**Description**

- add mesheryctl as a prerequisite
- add platform icons
- fix broken links
- styling changes

This PR fixes #1918 

Signed-off-by: Shriti <shritichan@gmail.com>

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2020-11-19 04:34 UTC, leecalcote commented on docs/pages/installation/aks.md
> +- Install [mesheryctl]({{ site.baseurl }}/guides/mesheryctl)
@chandrashritii will you move this to a common include file?

2020-11-20 14:03 UTC, leecalcote requested changes
@kushthedude how does the rest look?

2020-11-20 14:22 UTC, kushthedude commented on docs/pages/installation/eks.md
> +## Quick Start with Amazon Elastic Kubernetes Service (EKS) <img src="/docs/assets/img/platforms/eks.png" width="35" height="35" />
This section needs to be removed and replace with coming soon, @leecalcote

2020-11-30 18:22 UTC, leecalcote submitted a review, later dismissed

2020-12-02 03:11 UTC, leecalcote requested changes
@chandrashritii please address conflicts.

2020-12-06 06:52 UTC, leecalcote reviewed
Closing this PR the same updates were included across multiple PRs.

2020-12-06 06:52 UTC, closed without merging