Remove default location from usage test and let cobra handle that
meshery/meshery pull request #2032
Opened 2020-12-03 07:48 UTC by anirudhjain75

**Description**

This PR fixes #1994 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [.] Yes, I signed my commits.

2020-12-03 11:05 UTC, kushthedude requested changes
Please run gofmt

2020-12-08 14:46 UTC, anirudhjain75 commented
@kushthedude @leecalcote Sorry for keeping this stale. gofmt'ed the file and pushed. Do review and merge :)

2020-12-08 16:10 UTC, kushthedude approved these changes
Lgtm!

2020-12-12 00:23 UTC, leecalcote approved these changes

2020-12-12 00:23 UTC, merged