mesheryctl: Added current-context for system channel command
meshery/meshery pull request #2209
Opened 2021-01-05 18:52 UTC by SudhanAruna

Signed-off-by: Arunagirinadan Sudharshan <sudhan.aruna.97@gmail.com>

**Description**
Added current-context support for system channel command

This PR fixes #2164 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-01-05 20:07 UTC, leecalcote commented
...and here it is!

2021-01-05 20:08 UTC, leecalcote commented on mesheryctl/internal/cli/root/system/channel.go
> +			log.Println("Subscribe dchannel:", currentChannel)
```suggestion
			log.Println("Channel subscription:", currentChannel)
```

2021-01-05 20:09 UTC, leecalcote commented on mesheryctl/pkg/utils/helpers.go
> +	Channel:  "",
```suggestion
	Channel:  "stable",
```

`stable` will be the default channel.

2021-01-05 20:11 UTC, leecalcote commented
@anirudhjain75 for some reason, I can't add you as a reviewer...

2021-01-05 20:14 UTC, anirudhjain75 commented
I think it's better to have enum instead of string field for channel. It might be less error prone

2021-01-05 20:15 UTC, anirudhjain75 commented
Sorry but I'll be able to review this tomorrow . 12hrs from how. Great work though :)

2021-01-06 03:31 UTC, leecalcote commented on mesheryctl/internal/cli/root/system/channel.go
> +				log.Fatal("Please subscribe to either the 'stable' or 'edge' release channel.")
```suggestion
				log.Fatal("No release channel subscription found. Please subscribe to either the 'stable' or 'edge' release channel.")
```

2021-01-06 03:34 UTC, leecalcote commented
Scenario: 
- User has config.yaml with current-context defined, but no `channel` attribute.
- User executes `meshery system channel --set stable` and receives this output:

```
 ./mesheryctl system channel --set stable
unable to switch channel with stable
Error subscribing to release channel:unable to set channel
```

The `channel` attribute should be created if one is not found.

2021-01-06 03:36 UTC, leecalcote requested changes
@SudhanAruna thanks for this PR. Please have a look and fix this lint issue, if you would - https://github.com/layer5io/meshery/pull/2209/checks?check_run_id=1654184977#step:3:65

2021-01-06 03:37 UTC, SudhanAruna commented
> @SudhanAruna thanks for this PR. Please have a look and fix this lint issue, if you would - https://github.com/layer5io/meshery/pull/2209/checks?check_run_id=1654184977#step:3:65

Sorry for that, I'll amend it and push it now.

2021-01-06 03:54 UTC, SudhanAruna commented
> Scenario:
> 
> * User has config.yaml with current-context defined, but no `channel` attribute.
> * User executes `meshery system channel --set stable` and receives this output:
> 
> ```
>  ./mesheryctl system channel --set stable
> unable to switch channel with stable
> Error subscribing to release channel:unable to set channel
> ```
> 
> The `channel` attribute should be created if one is not found.

@leecalcote  Working on this. It is raised because when a context is deleted, the meshery.yaml file has last updated channel. When we try to set the same channel again above error is raised.

2021-01-06 09:36 UTC, anirudhjain75 commented
Hi @SudhanAruna , There is a issue for modulating the docker compose file. I'll be delivering it today. The best thing here is that once that is created, the work here would become easier.

2021-01-06 11:17 UTC, SudhanAruna commented
> Hi @SudhanAruna , There is a issue for modulating the docker compose file. I'll be delivering it today. The best thing here is that once that is created, the work here would become easier.
> 
> #2207

@anirudhjain75 Okay

2021-01-09 05:40 UTC, leecalcote approved these changes
Thank you, @SudhanAruna

2021-01-09 05:40 UTC, merged