Add frontend ui codecov
meshery/meshery pull request #2254
Opened 2021-01-15 19:16 UTC by shubhank-saxena

**Description**

This PR fixes #2251 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-01-15 20:04 UTC, leecalcote commented
@shubhank-saxena will you send a request for the app to be installed?

2021-01-15 20:10 UTC, leecalcote commented
Ok, the CodeCov app is now installed at the `layer5io` org level. 👍

2021-01-15 20:11 UTC, leecalcote approved these changes

2021-01-15 20:11 UTC, leecalcote commented on .codecov.yml
> +        target: 40%
We will be no where near these targets.

2021-01-15 20:12 UTC, leecalcote commented
@ramrodo, I assume [this failed check](https://github.com/layer5io/meshery/pull/2254/checks?check_run_id=1710696918) isn't due to this PR.

2021-01-15 22:09 UTC, leecalcote commented
There wasn’t a very specific or actionable error description in the failed check, so I’m re-running the CI job in case it was a glitch

2021-01-16 00:32 UTC, ramrodo commented
@leecalcote @shubhank-saxena the error on CI is:

```
/home/runner/work/_temp/e796806c-0606-4729-a8bd-3a1cf0397754.sh: line 4: codecov: command not found
```

That is because we're trying to run **codecov** but it doesn't find the package in _node_modules_. So, as @Aisuko mentioned in [this comment](https://github.com/layer5io/meshery/issues/2251#issuecomment-760887131), we can add the Github Action for **codecov** and let it to execute the report.

I recommend removing that two **codecov** command and implement the GitHub Action in a later PR.

2021-01-16 00:34 UTC, ramrodo requested changes

2021-01-16 00:34 UTC, ramrodo commented on .github/workflows/ci.yml
> +        codecov
Remove this line and implement the **codecov** command with a GitHub Action in other PR.

```suggestion
        
```

2021-01-16 00:34 UTC, ramrodo commented on .github/workflows/ci.yml
> +        codecov
Remove this line and implement the **codecov** command with a GitHub Action in other PR.

```suggestion
        
```

2021-01-16 06:02 UTC, shubhank-saxena commented
> @leecalcote @shubhank-saxena the error on CI is:
> 
> ```
> /home/runner/work/_temp/e796806c-0606-4729-a8bd-3a1cf0397754.sh: line 4: codecov: command not found
> ```
> 
> That is because we're trying to run **codecov** but it doesn't find the package in _node_modules_. So, as @Aisuko mentioned in [this comment](https://github.com/layer5io/meshery/issues/2251#issuecomment-760887131), we can add the Github Action for **codecov** and let it to execute the report.
> 
> I recommend removing that two **codecov** command and implement the GitHub Action in a later PR.

@ramrodo the comment highlighted there is not actually a github action but github app. Also, if we even have another action for it, we still need to generate the coverage.xml report of every test.
Here is an example which shows how codecov is integrated with github actions (A different way) - https://github.com/codecov/codecov-action

2021-01-16 06:11 UTC, Aisuko commented
Thanks, @shubhank-saxena  I have one repo can as an example, please kindly check the PR https://github.com/Aisuko/meshinfra/pull/25#issuecomment-759967937, and I saw `coverage1.xml` configuration can be optional. So, we should discuss this more and clearly how we can do this before we merge this one.

2021-01-16 06:23 UTC, shubhank-saxena commented
> Thanks, @shubhank-saxena I have one repo can as an example, please kindly check the PR [Aisuko/meshinfra#25 (comment)](https://github.com/Aisuko/meshinfra/pull/25#issuecomment-759967937), and I saw `coverage1.xml` configuration can be optional. So, we should discuss this more and clearly how we can do this before we merge this one.

Ohh I see. Thank you for the link!

2021-01-16 06:28 UTC, shubhank-saxena commented
> > @leecalcote @shubhank-saxena the error on CI is:
> > ```
> > /home/runner/work/_temp/e796806c-0606-4729-a8bd-3a1cf0397754.sh: line 4: codecov: command not found
> > ```
> > 
> > 
> > That is because we're trying to run **codecov** but it doesn't find the package in _node_modules_. So, as @Aisuko mentioned in [this comment](https://github.com/layer5io/meshery/issues/2251#issuecomment-760887131), we can add the Github Action for **codecov** and let it to execute the report.
> > I recommend removing that two **codecov** command and implement the GitHub Action in a later PR.
> 
> @ramrodo the comment highlighted there is not actually a github action but github app. Also, if we even have another action for it, we still need to generate the coverage.xml report of every test.
> Here is an example which shows how codecov is integrated with github actions (A different way) - https://github.com/codecov/codecov-action

This is redundant

2021-01-16 06:35 UTC, leecalcote commented
Gents, it'd be good to get the approach designed and documented in here - https://docs.google.com/document/d/11nAxYtz2SUusCYZ0JeNRrOLIxkgmmbUVWz63MBZV2oE/edit#

2021-01-16 06:56 UTC, ramrodo approved these changes

2021-01-16 08:06 UTC, ramrodo commented
> > @leecalcote @shubhank-saxena the error on CI is:
> > ```
> > /home/runner/work/_temp/e796806c-0606-4729-a8bd-3a1cf0397754.sh: line 4: codecov: command not found
> > ```
> > 
> > 
> > That is because we're trying to run **codecov** but it doesn't find the package in _node_modules_. So, as @Aisuko mentioned in [this comment](https://github.com/layer5io/meshery/issues/2251#issuecomment-760887131), we can add the Github Action for **codecov** and let it to execute the report.
> > I recommend removing that two **codecov** command and implement the GitHub Action in a later PR.
> 
> @ramrodo the comment highlighted there is not actually a github action but github app. Also, if we even have another action for it, we still need to generate the coverage.xml report of every test.
> Here is an example which shows how codecov is integrated with github actions (A different way) - https://github.com/codecov/codecov-action

@shubhank-saxena sounds good, Could you add that Github Action? Then we need to add the `CODECOV_TOKEN` to our Github Secrets (I already linked the Github App to the meshery project). @leecalcote I'll send you a slack message to add this Github Secret.

2021-01-17 04:29 UTC, leecalcote commented
Org-wide `codecov_token` has been added.

2021-01-18 06:55 UTC, closed without merging