Make use of Podman-compose
meshery/meshery pull request #2257
Opened 2021-01-17 09:16 UTC by jaybatra26

Since Docker-compose is going to be decommissioned.
This PR replaces docker-compose with podman-compose.

Fixes: #2158
Signed-off-by: Jay Batra <jaybatra73@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-01-18 02:00 UTC, leecalcote commented
@ishankhare07, would you like to review this PR?

2021-01-18 02:06 UTC, leecalcote requested changes
@jaybatra26, `docker-compose` will still be a supported platform for Meshery (the default platform). `podman-compose` will be an additionally supported platform. You'll want to add support for `podman-compose` to most of the `mesheryctl system` commands (start, stop, restart, update, logs, channel...) 

See the `platform` attribute in `~/.meshery/config.yaml` as the key to use when adding "podman" as an option. `system context` is a new comment, not yet released into a stable Meshery release. `system context` creates and controls `config.yaml` and currently only supports "docker" as a value. It needs to support "podman" and "kubernetes" as values, too.

2021-01-18 02:06 UTC, leecalcote commented
Thank you for taking this on, @jaybatra26 👍

2021-01-18 07:30 UTC, jaybatra26 commented
@leecalcote  It's my pleasure. :)

2021-01-18 10:54 UTC, jaybatra26 commented
Hi @leecalcote Do I have to make changes in a this file most likely. https://github.com/layer5io/meshery/blob/master/mesheryctl/pkg/utils/helpers.go#L208

2021-01-18 11:17 UTC, tripathyprateek commented
Yes we need to try and test how podman-compose behaves with Meshery. I guess it will be a good enough issue to tackle for some time. And we need to keep support for Docker as default platform. Also there seems some more development around Podman to support Docker-compose with Podman 3.0 [here](https://www.redhat.com/sysadmin/podman-docker-compose)

2021-01-18 13:59 UTC, anirudhjain75 commented
Hi @jaybatra26 , Do look into the golint error caused in the CI

2021-01-18 15:50 UTC, jaybatra26 commented
Thanks @tripathyprateek  and @anirudhjain75 sure.

2021-01-19 13:29 UTC, anirudhjain75 reviewed
The changes look fine to be. ignoring the docker as default for now. @leecalcote might be able to shed some light

2021-01-19 13:29 UTC, anirudhjain75 commented on mesheryctl/internal/cli/root/system/start.go
> +	if ctxPlatform == "docker" || ctxPlatform == "" {
We might not want to default to docker. @leecalcote shed some light if possible. I dont think we should do anything or maybe give an error if platform is not set.

2021-01-19 13:29 UTC, anirudhjain75 commented on mesheryctl/internal/cli/root/system/start.go
> +	ctxPlatform := mctlCfg.GetContextContent().Platform
These is an addon that can be done here. from #2256 I am planning to add a context flag. Taking that into consideration for which context to focus on would be great. Another issue could be created for this.

2021-01-22 02:40 UTC, leecalcote commented
> Yes we need to try and test how podman-compose behaves with Meshery. I guess it will be a good enough issue to tackle for some time. And we need to keep support for Docker as default platform. Also there seems some more development around Podman to support Docker-compose with Podman 3.0 [here](https://www.redhat.com/sysadmin/podman-docker-compose)

@tripathyprateek I would love to see results from your compatibility tests here. 👍

2021-02-07 18:55 UTC, leecalcote commented
@tripathyprateek have you been successful in running Meshery on Podman? Any luck progressing on the mesheryctl command here? 

Assuming we're in about the same spot, I'll suggest that we push this feature to post v0.5.0. What do you think?

2021-02-08 11:26 UTC, tripathyprateek commented
> @tripathyprateek have you been successful in running Meshery on Podman? Any luck progressing on the mesheryctl command here?
> 
> Assuming we're in about the same spot, I'll suggest that we push this feature to post v0.5.0. What do you think?

@leecalcote I have been trying to run Meshery on Podman. However I am  running into a lot of errors with Podman and Buildah which I am trying to figure out. I would suggest we can wait to add support for Podman for a little while as Podman is not fully working on some platforms (Ubuntu 20.10 and earlier) I guess.

2021-04-14 21:44 UTC, closed without merging