Kumarabd/feature/helm
meshery/meshery pull request #2866
Opened 2021-05-07 10:10 UTC by kumarabd

**Description**

- This PR fixes #2837 
- The ports are remapped to listen to `9081`

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-05-07 16:33 UTC, Anita-ihuman commented
> @Anita-ihuman fyi. Please note this with respect to your last update to the port number for the localhost endpoint after installing Meshery with helm.

I don't understand, Please can you explain further?

2021-05-07 23:41 UTC, leecalcote commented on ui/components/MesheryPerformance/index.js
> + 'nighthawk',
```suggestion
  'nighthawk',

```

2021-05-07 23:41 UTC, leecalcote commented on ui/components/MesheryPerformance/index.js
> + 'nighthawk',
```suggestion
  'nighthawk',

```

2021-05-07 23:43 UTC, leecalcote requested changes
@kumarabd - 

```
go: github.com/layer5io/nighthawk-go@v0.1.6: parsing /Users/abishekk/Documents/layer5/getnighthawk/go.mod: open /Users/abishekk/Documents/layer5/getnighthawk/go.mod: no such file or directory
```

2021-05-07 23:48 UTC, leecalcote commented on Dockerfile
> +RUN curl -Lo nighthawk_service-ubuntu-amd64-v1.0.1.tar.gz https://github.com/layer5io/getnighthawk/releases/download/v1.0.1/nighthawk_service-ubuntu-amd64-v1.0.1.tar.gz \
Don't hardcode the release.

2021-05-10 07:10 UTC, kumarabd commented
> > @Anita-ihuman fyi. Please note this with respect to your last update to the port number for the localhost endpoint after installing Meshery with helm.
> 
> I don't understand, Please can you explain further?

It means meshery will be accessible from `localhost:9081` instead of `localhost:8080`

2021-05-10 08:17 UTC, Anita-ihuman commented
Alright then, will make the change.

2021-05-11 08:40 UTC, kumarabd commented
@ramrodo @Aisuko Any idea why the releaser chart is failing?

2021-05-11 12:58 UTC, Aisuko commented
> @ramrodo @Aisuko Any idea why the releaser chart is failing?

I'm working on this, please kindly manually push the latest chart to the meshery.io

2021-05-11 17:12 UTC, kumarabd commented
@Aisuko Will you be able to link the issue that you are working on in here?

2021-05-12 01:30 UTC, Aisuko commented
issue https://github.com/layer5io/meshery/pull/2700

2021-05-12 21:16 UTC, closed without merging