Added Confirmation when Channel is Set
meshery/meshery pull request #3008
Opened 2021-05-23 14:27 UTC by DARK-art108

**Description**

It is an initial Draft PR for review and fixes.

This PR fixes #2952 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-05-23 17:03 UTC, navendu-pottekkat requested changes
@DARK-art108 Please check out the suggestion and check it out locally.

2021-05-23 17:03 UTC, navendu-pottekkat commented on mesheryctl/internal/cli/root/system/channel.go
> +		log.Info("Channel Set to %s", channelNameSeperated)
```suggestion
		log.Infof("Channel set to %s-%s", channelNameSeperated[0], channelNameSeperated[1])
```

2021-05-24 01:46 UTC, leecalcote commented
@DARK-art108 is this still a draft PR or is it ready for review?

2021-05-24 01:50 UTC, DARK-art108 commented
@leecalcote This is a draft PR, I have opened it to get review.

2021-05-24 01:58 UTC, leecalcote commented
@DARK-art108, ok, in that case, you'll want to remove the draft state by clicking "Ready for Review". A draft state PR means that you're working on it and are not ready for people to look at it. When you've marked it Ready for Review (or just submitted it without draft flagged), then maintainers will take a look.

2021-05-24 02:14 UTC, navendu-pottekkat commented
@DARK-art108 @leecalcote I have left a review above, please check it out

2021-05-24 21:47 UTC, leecalcote approved these changes
Thank you, @DARK-art108 and @navendu-pottekkat 👍

2021-05-24 21:47 UTC, merged