recommiting mesheryctl system missing pages
meshery/meshery pull request #3142
Opened 2021-06-05 08:37 UTC by Anita-ihuman

Signed-off-by: Anita-ihuman <charlesanita403@gmail.com>

**Description**
Created subcommands for mesheryctl system logs, restart and reset.

This PR, 
- fixes #2937 
- fixes #2935 
- fixes #2943 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-06-06 10:21 UTC, alphaX86 reviewed
![image](https://user-images.githubusercontent.com/59508546/120920939-ef042e00-c6de-11eb-8bcf-7fb7cae56a54.png)
 We can either add one standard flag --help or remove this part

![image](https://user-images.githubusercontent.com/59508546/120920964-093e0c00-c6df-11eb-92ac-0c21747cccfb.png)

Plus, the logs page can be linked

2021-06-06 10:24 UTC, alphaX86 reviewed
![image](https://user-images.githubusercontent.com/59508546/120921032-6a65df80-c6df-11eb-924c-74864ae422be.png)

Repetition found! 😶

2021-06-06 10:24 UTC, alphaX86 commented on docs/pages/reference/mesheryctl/subcommands/mesheryctl-sys-logs.md
> +<br/>
```suggestion

```
Either removed or `--help` can be added

2021-06-06 10:27 UTC, alphaX86 commented
Hmm, one sec... I'll check if I can push those changes

2021-06-06 11:16 UTC, Anita-ihuman commented
Alright then

2021-06-07 05:17 UTC, alphaX86 commented
@Anita-ihuman seems I can't co-author commits as it's limited to maintainers only..... Hmm, in that case I need to say few things IG

1. Some YAML files are duplicated, so you need to delete these files! 
     - `./_data/mesheryctlcommands/lifecycle/subcommands/log.yaml`
     - `./_data/mesheryctlcommands/lifecycle/subcommands/restart.yaml`
     
2. Change the rowspan to 18 at the mesheryctl-reference.md

2021-06-07 05:18 UTC, alphaX86 requested changes
Along with those 2 changes, do this also

2021-06-07 05:18 UTC, alphaX86 commented on docs/pages/reference/mesheryctl-commands.md
> +  {% endfor %}
```suggestion
  {% for subcommand_hash in site.data.mesheryctlcommands.lifecycle.system.logs.command %}{% assign subcommand = subcommand_hash[1] %}
    <tr>
      <td><a href="{{ site.baseurl }}/reference/mesheryctl/system/logs">{{ subcommand.name }}</a></td>
      <td></td>
      <td>{{ subcommand.description }}</td>
    </tr>
    {% for flag_hash in site.data.mesheryctlcommands.lifecycle.system.logs.flag %}{% assign flag = flag_hash[1] %}
      <tr>
        <td>{{ flag.flag }}</td>
        <td>{{ flag.description }}</td>
      </tr>
    {% endfor %}
  {% endfor %}
```

2021-06-07 05:19 UTC, alphaX86 commented
Then we're good to go

2021-06-08 11:43 UTC, leecalcote commented
Merge conflict - https://github.com/layer5io/meshery/pull/3142/conflicts

2021-06-09 04:39 UTC, leecalcote approved these changes
Thank you, MeshMate @Anita-ihuman 💪

2021-06-09 04:39 UTC, merged

2021-06-09 05:52 UTC, Anita-ihuman commented
Thank you everyone, for the tips, learnt a lot.

2021-06-09 18:35 UTC, ramrodo commented
@leecalcote Sorry if I am insistent. This PR should not be merged until we fix those failing Netlify tests. I know that you or anyone else don't want to be a blocker for those contributors that help a lot but, if we don't solve these bad practices it will be harder to be accepted as a good project for the CNCF or other Foundation. We need to have best practices to have a project reliable.

One thing that we can do in the meantime is to **not allow** maintainers to merge PRs if the tests fail. We can configure that in _"Settings / Branches / Branch protection rules / master / **Include administrators**"._

If there is a PR where the tests are falining please ping me, I'll reply ASAP. I think there is no a huge problem to wait some hours or even a couple of days to fix the tests first.