update perf docs
meshery/meshery pull request #3218
Opened 2021-06-16 20:41 UTC by NagaHarshita

Signed-off-by: NagaHarshita <harshitamarupaka@gmail.com>

**Description**

This PR fixes #3214.
The output of the help command is taken as a reference to update the docs. Please suggest changes if any.

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-06-17 11:00 UTC, leecalcote requested changes
Thank you, @NagaHarshita. Good work. 😄 

After giving some thought as to how we describe the `--token` flag, do mind changing all references to use the phrase "access token", instead of "auth config"?

2021-06-20 11:09 UTC, piyushsingariya commented on docs/_data/mesheryctlcommands/performance/view/flag/output-format.yaml
> +description: (optional) format to display in json
We support both YAM/JSON, few things need to be updated in cobra documentation for `perf` commands.

2021-06-20 11:13 UTC, piyushsingariya requested changes
@NagaHarshita The flags are under `apply` subcommand under `perf`. plus `perf list` is also not added.

2021-06-22 03:45 UTC, leecalcote commented
Good progress, @NagaHarshita 👍  Perhaps, we should breakdown this work into multiple PRs to make it a more digestible set of changes?

2021-06-22 03:47 UTC, leecalcote commented on docs/_data/mesheryctlcommands/performance/view/flag/output-format.yaml
> +description: (optional) format to display in json
@piyushsingariya are you tracking an issue to update the help text for this command?

2021-06-22 03:52 UTC, leecalcote commented
> @NagaHarshita The flags are under `apply` subcommand under `perf`. plus `perf list` is also not added.

Good catch @piyushsingariya. @NagaHarshita, do you feel that you can address these subcommands in this PR or is opening up a new PR to tie off the rest of the subcommands easier? If the latter, please open up an issue to track the need for `apply` and `list`

2021-06-22 06:19 UTC, NagaHarshita commented
> Good catch @piyushsingariya. @NagaHarshita, do you feel that you can address these subcommands in this PR or is opening up a new PR to tie off the rest of the subcommands easier? If the latter, please open up an issue to track the need for `apply` and `list`
I will try to complete the mentioned changes in this pr.

2021-06-24 05:55 UTC, leecalcote approved these changes
Looking good, @NagaHarshita. 😀

@piyushsingariya, what do you think?

2021-06-24 05:59 UTC, piyushsingariya requested changes
@NagaHarshita Can you replace all the profile-id under `perf apply` with profile-name. With some recent changes we have shifted the `perf apply` command to work with names instead of ids.
Keep in mind `list` and `view` work same as before.

2021-06-24 21:56 UTC, merged