[mesheryctl]Adding dashboard command to mesheryctl system
meshery/meshery pull request #3375
Opened 2021-07-02 16:54 UTC by DantrazTrev

Signed-off-by: Ayush PS <ayushpratap16@gmail.com>

**Description**

This PR aims to fix #3035 

Tasks
- [x] Base command to display the endpoint in the terminal 
- [x] Base command to open the endpoint in the browser
- [ ] Testing connection to UI
- [ ] For Kubernetes if not accessible initial kube proxy tunnel

**Notes for Reviewers**

**Not Ready for review yet**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-07-07 08:45 UTC, piyushsingariya commented
@DantrazTrev This issue got to be platform-dependent. We need to implement a Kube proxy tunnel in case of Kubernetes as a platform.

2021-07-07 08:49 UTC, DantrazTrev commented
@piyushsingariya I'm waiting to hear something about the bug related to UI endpoints in kubernetes env https://layer5io.slack.com/archives/C019426UBNY/p1625136547045900?thread_ts=1625136547.045900&cid=C019426UBNY

But yeah I would try to implement that meanwhile

2021-07-09 07:14 UTC, DantrazTrev commented
> @DantrazTrev This issue got to be platform-dependent. We need to implement a Kube proxy tunnel in case of Kubernetes as a platform.

Hei @piyushsingariya can you help me with the kube-proxy part , I'm not sure what's the exact command to use ?

2021-07-13 20:37 UTC, leecalcote commented
@DantrazTrev, I get excited each time I look at the subject line of this PR. Don't tease me like this. 😉 

In all seriousness, it would be great to have this command. I believe that implementation here will need to use or enhance MeshKit's capabilities. // @Aisuko

2021-07-13 21:05 UTC, DantrazTrev commented
Hei @leecalcote I believe there is just one major step left which is setting up a kube proxy tunnel for k8s when needed.  However this part is the one where I've been facing a few issues since simple kube proxy tunnels don't really work and also the endpoint for k8s is often incorrect so the tunneling would happen either way . 

I'll try my best to solve it although some dependent issues might need to be figured out first.

2021-07-14 02:47 UTC, Aisuko commented
Thanks for ping me, sir @leecalcote . If I understand right by the context, we want to achieve the feature is localhost open an proxy the dashboard. I believe that similar with the `osm dashboard`  command.
https://github.com/openservicemesh/osm/blob/7ef0c4723cc52a17feb8b8b744960a497e067d59/cmd/cli/dashboard.go#L65

2021-07-21 02:56 UTC, leecalcote commented
Right. Or another example is `linkerd dashboard`

2021-07-23 01:57 UTC, Aisuko commented on mesheryctl/internal/cli/root/system/dashboard.go
> +	mctlCfg, err := config.GetMesheryCtl(viper.GetViper())
We provide the reformat tools under the project, https://github.com/meshery/meshery/blob/1ff876f10e0a9a0387bb84f96ca0a2edb1add6cd/Makefile#L90-L92 , please kindly check how to use this tool under localhost.

2021-07-23 01:58 UTC, Aisuko requested changes
Please reformat the code style, and the tool below will help you.

2021-07-23 02:00 UTC, Aisuko commented on mesheryctl/internal/cli/root/system/dashboard.go
> +	mctlCfg, err := config.GetMesheryCtl(viper.GetViper())
If this does not work for you, please modify the environment `GO111MODULE` and `GOPROXY`

2021-07-29 21:49 UTC, leecalcote commented
Thanks for this review, @Aisuko. What do you think, @DantrazTrev?

2021-07-30 22:48 UTC, leecalcote commented
@Aisuko, perhaps, you'd like to carry this forward?

2021-07-31 02:45 UTC, Aisuko commented
@leecalcote No problem sir, I will do. Mid month I will move the home between two cities. I would schedule this after that.

2021-07-31 05:29 UTC, navendu-pottekkat commented
Thank you @Aisuko This needs some thought put into it to make sure that we get the correct endpoint. We would have to work to enhance the function in MeshKit.

2021-08-06 17:21 UTC, navendu-pottekkat commented
@Aisuko @leecalcote I'm closing this PR as this would be reworked.

2021-08-06 17:21 UTC, closed without merging

2021-08-13 00:59 UTC, Aisuko commented
@navendu-pottekkat No problem.