Feature/ayush khandelwal 007/metrics overhaul
meshery/meshery pull request #3380
Opened 2021-07-03 12:58 UTC by Ayush-Khandelwal-007

**Description**

This PR is related to the issue in the extension, that is the sparkling graphs for metrics in visualise drawer
https://github.com/layer5labs/meshery-extensions/issues/29

**Notes for Reviewers**
Changes are not complete yet designs are yet to be made and implemented but the basic skeleton is changed.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2021-07-08 00:12 UTC, dhruv0000 requested changes

2021-07-08 00:12 UTC, dhruv0000 commented on ui/components/GrafanaCustomChart.js
> +    background:'#f3efff',
![image](https://user-images.githubusercontent.com/44001539/124842737-e89ef580-dfad-11eb-94d6-67d624173c35.png)

Are we sure, we want to go with purple?

Light green/blue might be bettor option considering the Brand Guide.

I tried out few colors that might be better aligned with the style.
(#eaf8f5)
![image](https://user-images.githubusercontent.com/44001539/124843007-98746300-dfae-11eb-9788-54dd8a941104.png)

or (#eaf6fc)
![image](https://user-images.githubusercontent.com/44001539/124843157-ee490b00-dfae-11eb-9368-9d1463b286a2.png)

What do you think, @Ayush-Khandelwal-007 ?

2021-07-08 00:45 UTC, leecalcote commented
Pretty please with sugar on top, will you try selections from the Meshery color scheme to see if one of the these colors works? 

https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=65%3A6

<img width="1384" alt="Screen Shot 2021-07-07 at 7 44 03 PM" src="https://user-images.githubusercontent.com/7570704/124845210-d6946700-df5b-11eb-84ca-d8dc0da8e7c7.png">

2021-07-09 13:47 UTC, Ayush-Khandelwal-007 commented
I have made few changes. Ill just rebase my branch and look if everything is fine and push by tonight. @leecalcote 👀 there is something that you might like to see here(something that you were waiting for).

2021-07-09 14:01 UTC, Ayush-Khandelwal-007 commented
@dhruv0000 What if we let the cards be white itself and give bg colour to the accordion itself? 👀

2021-07-09 15:22 UTC, l5io commented
🚀 Preview for commit 59b2e37f4a5484b7ec9ee400c7c6038356a1add3 at: https://60e86983ad421f2df6cb1408--meshery-docs-preview.netlify.app

2021-07-09 16:03 UTC, Ayush-Khandelwal-007 commented
https://user-images.githubusercontent.com/59086855/125106299-1e062900-e0fd-11eb-8a18-43624a500a6b.mov

@leecalcote Is this something you were waiting for?

2021-07-09 16:12 UTC, closed without merging

2021-07-09 16:17 UTC, leecalcote commented
Very nice! Yes, you've nailed it in this screen recording. Those tickers are exactly it.