actions
meshery/meshery pull request #3464
Opened 2021-07-12 06:35 UTC by Chadha93

Signed-off-by: Chadha93 <gauravchadha1676@gmail.com>

**Description**
Adds actions and deploy/apply for application through dedicated applications endpoints

This PR fixes #3447 

**Notes for Reviewers**
![image](https://user-images.githubusercontent.com/65453826/125241719-6d20a980-e309-11eb-9000-8b33b69f3726.png)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-07-12 06:37 UTC, Chadha93 commented
// @leecalcote  @navendu-pottekkat 👀

2021-07-12 07:02 UTC, sudo-NithishKarthik requested changes
@Chadha93 , can you handle the errors as well 😄 ?

2021-07-12 07:02 UTC, sudo-NithishKarthik commented on ui/components/MesheryApplications.js
> +  const handleDeploy = (application_file) => {
add `updateProgress({ showProgress: true })` inside this function so that user can get the feedback that his action has been registered.

2021-07-12 07:02 UTC, sudo-NithishKarthik commented on ui/components/MesheryApplications.js
> +        console.error(e)
Show the error notification on failure of request.

2021-07-12 07:14 UTC, Chadha93 commented
@sudo-NithishKarthik  sure, this would be helpful in view of user perspective too

2021-07-13 06:53 UTC, Chadha93 commented
@navendu-pottekkat @sudo-NithishKarthik This PR is now ready, with required changes ( deploy + error handler + auto close modal on delete )

2021-07-13 07:04 UTC, sudo-NithishKarthik commented on ui/components/MesheryApplications.js
> +        handleError(ACTION_TYPES.FETCH_APPLICATIONS)
it should be `ACTION_TYPES.DELETE_APPLICATIONS`

2021-07-13 07:04 UTC, sudo-NithishKarthik commented on ui/components/MesheryApplications.js
> +        handleError(ACTION_TYPES.FETCH_APPLICATIONS)
`ACTION_TYPES.UPDATE_APPLICATIONS`

2021-07-13 07:05 UTC, sudo-NithishKarthik commented on ui/components/MesheryApplications.js
> +        handleError(ACTION_TYPES.FETCH_APPLICATIONS)
`ACTION_TYPES.UPLOAD_APPLICATIONS`

2021-07-13 07:06 UTC, sudo-NithishKarthik requested changes
Other than these changes that i've mentioned, it looks good to me 🎉  😄

2021-07-13 07:07 UTC, Chadha93 commented
> Other than these changes that i've mentioned, it looks good to me 🎉 😄

oops my auto-detect code did these correcting it asap

2021-07-13 07:07 UTC, sudo-NithishKarthik commented
> > Other than these changes that i've mentioned, it looks good to me 🎉 😄
> 
> oops my auto-detect code did these correcting it asap

Oh 😂 , ok ✌🏽

2021-07-13 07:10 UTC, Chadha93 commented
> > > Other than these changes that i've mentioned, it looks good to me 🎉 😄
> > 
> > 
> > oops my auto-detect code did these correcting it asap
> 
> Oh 😂 , ok ✌🏽

done 😂

2021-07-13 19:29 UTC, leecalcote approved these changes
Good work, @Chadha93, @sudo-NithishKarthik 😄

2021-07-13 19:29 UTC, merged