Upgraded the meshkit error for kubernetes.go
meshery/meshery pull request #3506
Opened 2021-07-14 17:27 UTC by sayantan1413

Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>

**Description**

Upgraded the meshkit error in the `helpers` directory

- kubernetes.go

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-07-14 19:54 UTC, dhruv0000 requested changes

2021-07-14 19:54 UTC, dhruv0000 commented on helpers/kubernetes.go
> +			return nil, ErrNewDynamicClientGenerator(err)
Why `ErrNewDynamicClientGenerator` here?

2021-07-14 19:54 UTC, dhruv0000 commented on helpers/error.go
> +	return errors.New(ErrAddAndValidateExtraHeaderCode, errors.Alert, []string{}, []string{err.Error()}, []string{}, []string{})
Same here. No short description?

2021-07-14 19:54 UTC, dhruv0000 commented on helpers/error.go
> +	return errors.New(ErrGeneratingLoadTestCode, errors.Alert, []string{}, []string{err.Error()}, []string{}, []string{})
No short description?

2021-07-14 19:54 UTC, dhruv0000 commented on helpers/error.go
> +	ErrStartingNighthawkServer = errors.New(ErrStartingNighthawkServerCode, errors.Alert, []string{"unable to start nighthawk server"}, []string{}, []string{}, []string{})
Make the First letter of the First word capital for consistency.

2021-07-14 19:54 UTC, dhruv0000 commented on helpers/kubernetes.go
> +	return client, ErrNewDynamicClientGenerator(err)
Dont pass Error on when err is `nil`.

2021-07-14 19:54 UTC, dhruv0000 commented on helpers/kubernetes.go
> +			return nil, ErrNewDynamicClientGenerator(err)
And here?

2021-07-14 19:54 UTC, dhruv0000 commented on helpers/kubernetes.go
> +			return nil, ErrInvalidK8SConfig(err)
Create a `ErrInClusterConfig` error instead using the same for external and internal config.

2021-07-14 19:54 UTC, dhruv0000 commented on helpers/kubernetes.go
> +		return nil, ErrCreateClient(err, "set")
Different errors for creating `clientConfig` and `clientset`

2021-07-14 19:57 UTC, dhruv0000 commented on helpers/load_test_interface.go
> +			return ErrStartingNighthawkServer
Pass in the error too.

2021-07-14 21:03 UTC, dhruv0000 approved these changes

2021-07-15 11:38 UTC, dhruv0000 commented
@sayantan1413 Still WIP?

2021-07-15 12:02 UTC, sayantan1413 commented
No @dhruv0000 I think I have completed it but is there any other requirements?

2021-07-15 12:07 UTC, dhruv0000 commented
Nope. Lets open the PR.

2021-07-15 12:17 UTC, kumarabd approved these changes

2021-07-15 12:17 UTC, merged