Updated bitcask smiresultss persister
meshery/meshery pull request #3509
Opened 2021-07-14 19:11 UTC by Shreyas220

**Description**
Updated bitcask smiresultss persister

This PR fixes #3469

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-07-14 19:33 UTC, sayantan1413 commented
Hey @Shreyas220 I think in `models` you do not have to log the error just return the error so the  logger is not requires I guess. And I think this will solve your problem.

2021-07-15 11:09 UTC, Shreyas220 commented
@kumarabd

2021-07-15 11:31 UTC, dhruv0000 requested changes
This was fast @Shreyas220 :zap: . Few changes you might want to consider.

2021-07-15 11:31 UTC, dhruv0000 commented on models/error.go
> +func ErrFailToConnecToDB() error {
You can use `ErrDBConnection` instead. They are the same error.

2021-07-15 11:31 UTC, dhruv0000 commented on models/bitcask_smiresults_persister.go
> +	s.log.Debug("received page: ", page, " page size: ", pageSize, "total:", total)
`BitCaskSmiResultsPersister` doesn't have a Logger, this might not work. You can leave `debug` statements as it is for now, let them use `logurus`.

2021-07-15 11:31 UTC, dhruv0000 commented on models/bitcask_smiresults_persister.go
> +		return nil, ErrFailToConnecToDB()
You can use `ErrDBConnection` here.

2021-07-15 11:31 UTC, dhruv0000 commented on models/bitcask_smiresults_persister.go
> +	log      logger.Handler
Lets not add specific logger for `Persister`.

2021-07-15 11:46 UTC, Shreyas220 commented
@dhruv0000 have a look

2021-07-15 12:21 UTC, kumarabd approved these changes

2021-07-15 12:21 UTC, merged