Add Docs regarding writing Unit and Integration Testing
meshery/meshery pull request #3557
Opened 2021-07-18 19:18 UTC by ishitakeshawani

Signed-off-by: ishitakeshawani <keshwaniishita054@gmail.com>

**Description**

This PR fixes #3553

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-07-18 19:20 UTC, l5io commented
🚀 Preview for commit 6061eb988a74adf6f65073ceb8a30687f0cd09ae at: https://60f47eeeb66d4bea4903c7fb--meshery-docs-preview.netlify.app

2021-07-19 01:43 UTC, alphaX86 submitted a review, later dismissed
Reviewed the page and output. LGTM on my side 🎉

2021-07-19 06:02 UTC, piyushsingariya requested changes

2021-07-19 06:25 UTC, ishitakeshawani commented on docs/pages/project/contributing/contributing-cli.md
> +4. **Fixtures** are the mock responses of an API call.
Done

2021-07-19 06:26 UTC, l5io commented
🚀 Preview for commit 64285682faf5e52b6dd3985826146e3eeb49d743 at: https://60f51b0d72767e8eb0034b1b--meshery-docs-preview.netlify.app

2021-07-19 10:12 UTC, adithyaakrishna approved these changes
LGTM 🎉 
Checked the Preview as well as links on the Docs 💯

2021-07-19 10:12 UTC, merged