Added SSE client for CLI to wait for operation to end
meshery/meshery pull request #3689
Opened 2021-07-30 06:18 UTC by dhruv0000

**Description**

This adds a SSE client for CLI which it can use to wait for the operation to be over or end in case of timeout (5 mins). 
Need to use `watch` flag for it to work.

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-07-30 06:21 UTC, leecalcote commented
Task linked: [CU-4hbp5y Event client Handler](https://app.clickup.com/t/4hbp5y)

2021-07-30 19:47 UTC, DelusionalOptimist commented
```
[  7:45PM ]  [ azureuser@test-vm:~/dev/meshery/mesheryctl(master-dhr✗) ]
 $ ./mesheryctl mesh validate --spec smi --adapter meshery-osm:10009 -t ~/Downloads/auth.json --watch
A new release of mesheryctl is available: Not Set → v0.5.41
https://github.com/layer5io/meshery/releases/tag/v0.5.41
Check https://docs.meshery.io/guides/upgrade#upgrading-meshery-cli for instructions on how to update mesheryctl

Starting service mesh validation...
{}
Verifying Operation
⣾ Validation started
⣽ Validation started
⣻ Validation started
⢿ Validation started
 Event :map[operation_id:ecbfac49-6c5a-4e8d-b7ac-f82573eab346 summary:SMI Conformance test completed successfully]

Validation complete
[  7:45PM ]  [ azureuser@test-vm:~/dev/meshery/mesheryctl(master-dhr✗) ]
 $
```
@dhruv0000 Apparently this still doesn't wait for the SMI conformance operation to complete : /

2021-08-02 08:12 UTC, dhruv0000 commented
> SMI Conformance test completed successfully

@DelusionalOptimist I am a bit confused. Isnt `Event :map[operation_id:ecbfac49-6c5a-4e8d-b7ac-f82573eab346 summary:SMI Conformance test completed successfully]
`  the event we are looking for, and it looks like it ended after it saw the event.

Am I missing something?

2021-08-02 19:32 UTC, DelusionalOptimist requested changes

2021-08-02 19:32 UTC, DelusionalOptimist commented on mesheryctl/internal/cli/root/mesh/validate.go
> +		s.Start()
```suggestion
```

2021-08-02 19:32 UTC, DelusionalOptimist commented on mesheryctl/internal/cli/root/mesh/validate.go
> +		s.Stop()
```suggestion

```

2021-08-02 19:38 UTC, DelusionalOptimist approved these changes
LGTM & CITY

2021-08-04 12:50 UTC, DelusionalOptimist approved these changes
LGTM

2021-08-04 12:50 UTC, merged