Fix broken links in Docs #3764
meshery/meshery pull request #3818
Opened 2021-08-08 01:56 UTC by sgibson19

**Description**

This PR fixes #3764 

**Notes for Reviewers**
* Please let know if there are any issues

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-08-08 01:59 UTC, l5io commented
🚀 Preview for commit d94c2c0d83dc308fdf63fb2e655962b4926e6cb6 at: https://610f3a5314cf62c020b6b2cc--meshery-docs-preview.netlify.app

2021-08-08 02:10 UTC, l5io commented
🚀 Preview for commit 59c03800c3274aa39dddc7817cb412355536e5b3 at: https://610f3d07fd210ea8f164e110--meshery-docs-preview.netlify.app

2021-08-09 18:12 UTC, leecalcote commented on docs/pages/functionality/patterns.md
> +- [`mesheryctl pattern`](https://docs.meshery.io/reference/mesheryctl/pattern)
```suggestion
- [`mesheryctl pattern`]({{ site.baseurl }}/reference/mesheryctl/pattern)
```

2021-08-09 21:55 UTC, l5io commented
🚀 Preview for commit 3894d2441d7002157785f7dcfb05534c36b6d38b at: https://6111a4397ea0e945d937b2d0--meshery-docs-preview.netlify.app

2021-08-09 23:06 UTC, l5io commented
🚀 Preview for commit f946e1edf0919bee832e58d1edbf558c69eafa83 at: https://6111b4d3de851d548e9b2a59--meshery-docs-preview.netlify.app

2021-08-09 23:11 UTC, leecalcote requested changes

2021-08-09 23:11 UTC, leecalcote commented on docs/pages/functionality/patterns.md
> +- [`mesheryctl pattern`](https://docs.meshery.io/reference/mesheryctl/pattern)
Let's be sure to use the Jekyll / liquid tag in order to avoid hardcoding the site's URL.

2021-08-09 23:11 UTC, leecalcote commented
Good work so far, @sgibson19

2021-08-09 23:53 UTC, l5io commented
🚀 Preview for commit 281f1395af9d670c1bf2c8447320c2f0d31faca2 at: https://6111bfe4148ef56e09419396--meshery-docs-preview.netlify.app

2021-08-09 23:57 UTC, l5io commented
🚀 Preview for commit 024ce4352288388c41fb0fc8006bbb87a62db8f4 at: https://6111c0da21764b69ea4fc9f2--meshery-docs-preview.netlify.app

2021-08-10 01:29 UTC, leecalcote approved these changes
Looks real good 👍

2021-08-10 01:34 UTC, alphaX86 approved these changes
LGTM 🎉 great work @sgibson19 👍

2021-08-10 17:04 UTC, adithyaakrishna approved these changes
LGTM 🎉 
Nice Work 🎈

2021-08-10 17:05 UTC, merged