added new FAQ
meshery/meshery pull request #3837
Opened 2021-08-10 08:55 UTC by The-Loony-Coder

Signed-off-by: Mritunjay <msengar121@gmail.com>

**Description**

This PR updates#3511

**Notes for Reviewers**
Have a look at the links that i've provided,should I include them or not, or should I change them.
I followed the FAQ pattern from [adapters](https://docs.meshery.io/concepts/architecture/adapters) page(faq are at the bottom).

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-08-10 08:58 UTC, l5io commented
🚀 Preview for commit 9460101fd6ff8d85482f61548e70f75c3b18a137 at: https://61123f8aedccb7ea10db5f22--meshery-docs-preview.netlify.app

2021-08-10 09:14 UTC, warunicorn19 commented
I think we should add some sort of bullets or numbers to differentiate between questions and answers, right now it all
 looks really similar.

2021-08-10 09:28 UTC, The-Loony-Coder commented
Are there any specific guidelines or design patterns that the documentation is following or should we decide our own.
Should we go with bullets,square bullets or numbers,or should I write "question"  in front of question.
Or we should just number them.

2021-08-10 09:38 UTC, warunicorn19 commented
There arent actually, lets hold off till @adithyaakrishna or @leecalcote review this.

2021-08-10 17:08 UTC, adithyaakrishna commented
@Anita-ihuman Could you please check the new FAQs which @The-Loony-Coder has added and suggest any changes if necessary :)

2021-08-10 18:42 UTC, Anita-ihuman commented
@The-Loony-Coder great job providing the answers for these questions.
I learnt a lot from them.

Concerning the pattern,
https://layer5.io/company/faq This is what most of our FAQ’s look like.
If you would like to pick inspiration from this.
Other than that, you did a fantastic job

2021-08-11 02:50 UTC, leecalcote requested changes

2021-08-11 02:50 UTC, leecalcote commented on docs/pages/project/FAQ.md
> +####  What does meshery do?
Always capitalize Meshery.

2021-08-11 02:50 UTC, leecalcote commented on docs/pages/project/FAQ.md
> +A Command Line Interface to manage Meshery.
command line interface can be lowercased.

2021-08-11 02:50 UTC, leecalcote commented on docs/pages/project/FAQ.md
> +#### How to run Meshery?
Improper grammar. Please rephrase.

2021-08-11 02:50 UTC, leecalcote commented on docs/pages/project/FAQ.md
> +<div class="center" style="color:gray;position:relative;top:-10px;font-size:1.25em;">Don't find an answer to your question here? Ask in the <a href="https://layer5io.slack.com/archives/C01AFD2D547">#
Missing the `f` in `href`

2021-08-11 02:50 UTC, leecalcote commented on docs/pages/project/FAQ.md
> +  Yes, both of them do run Meshery on your local machine. `make run local` builds Meshery from source and runs it on your local OS, while `mesheryctl system start` runs Meshery as a set of containers
...as a set of containers in Docker or in Kubernetes...

2021-08-11 02:51 UTC, leecalcote commented
Regarding formatting, yes, please leave the italics for answers and the labels "Question:" and "Answer:" as denotations.

2021-08-12 07:35 UTC, The-Loony-Coder commented
> Regarding formatting, yes, please leave the italics for answers and the labels "Question:" and "Answer:" as denotations.

should I also change the formatting [here](https://docs.meshery.io/concepts/architecture/adapters) "FAQ of adapters page". also.

2021-08-17 15:03 UTC, l5io commented
🚀 Preview for commit 2476b1bf873ccc289207223c9cc1af5fe60aeb77 at: https://611bcf86c8b22c3e60b25a7d--meshery-docs-preview.netlify.app

2021-08-17 15:07 UTC, l5io commented
🚀 Preview for commit 0aad2f906fa3a2343dd954ce39c1e9d6c01179bd at: https://611bd0a00955e93ee9f2ac83--meshery-docs-preview.netlify.app

2021-08-17 17:37 UTC, l5io commented
🚀 Preview for commit 4e7646dae5008e8cb69b2684adb9268f3b276f97 at: https://611bf3cf9fa1e315478c06b3--meshery-docs-preview.netlify.app

2021-08-17 17:44 UTC, l5io commented
🚀 Preview for commit 8cca93b54fe5944aa303caaefa58db183d9fcacc at: https://611bf54265309c00a3bf9769--meshery-docs-preview.netlify.app

2021-08-18 05:35 UTC, l5io commented
🚀 Preview for commit 5e50975965bbde47fbeb53d38316270ab25c32fd at: https://611c9bed1577d5a201799b0c--meshery-docs-preview.netlify.app

2021-08-18 05:53 UTC, l5io commented
🚀 Preview for commit 2abebef851594bce04198c90d755f6578f5c5d61 at: https://611ca0261936509c6a864503--meshery-docs-preview.netlify.app

2021-08-27 10:50 UTC, merged