Added the unit test for mesheryctl system restart command
meshery/meshery pull request #3858
Opened 2021-08-12 09:17 UTC by Shreyas220

Signed-off-by: Shreyas220 <shreyas.ny@gmail.com>

**Description**
Added the unit test for mesheryctl system restart command

This PR fixes #3407

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-08-12 09:28 UTC, sayantan1413 requested changes
Hey @Shreyas220 I think we can add the test for the docker platform as well

2021-08-12 12:40 UTC, leecalcote commented
Unit tests!! Yes, please. 🙂

2021-08-12 17:02 UTC, Shreyas220 commented
@piyushsingariya little help needed

2021-08-12 17:12 UTC, piyushsingariya requested changes

2021-08-12 17:12 UTC, piyushsingariya commented on mesheryctl/internal/cli/root/system/fixtures/.meshery/meshery.yaml
> +services:
This file isn't necessary. or is it?

2021-08-12 17:12 UTC, piyushsingariya commented on mesheryctl/internal/cli/root/system/system_test.go
> +		},
These should be shifted to appropriate places, like after the `system start` test for both docker and k8s.

2021-08-12 17:12 UTC, piyushsingariya commented on mesheryctl/pkg/utils/TestConfig.yaml
> +  name: Default
reset this file, this file is being used by so many things I can't even count.

2021-08-12 17:53 UTC, Shreyas220 commented on mesheryctl/internal/cli/root/system/system_test.go
> +			Args:            []string{"restart kubernetes"},
oh sorry, i was trying to add it in Action

2021-08-13 05:27 UTC, piyushsingariya requested changes
it's ready to merge after these changes

2021-08-13 05:27 UTC, piyushsingariya commented on mesheryctl/internal/cli/root/system/system_test.go
> +			Action:          "restart docker",
```suggestion
			Action:          "restart",
```

2021-08-13 05:27 UTC, piyushsingariya commented on mesheryctl/internal/cli/root/system/system_test.go
> +			Action:          "restart kubernetes",
```suggestion
			Action:          "restart",
```

2021-08-13 10:01 UTC, piyushsingariya approved these changes

2021-08-13 10:01 UTC, merged