Move the Performance tab in settings page to user preferences page
meshery/meshery pull request #3903
Opened 2021-08-16 14:14 UTC by yagarwal1307

Signed-Off-by: Yash Agarwal <yagarwal1307@gmail.com>

This PR fixes #3891

2021-08-16 14:41 UTC, sudo-NithishKarthik requested changes
@yagarwal1307 , a small change, can you revert the changes you made in `MesherySettings.js` file and just comment out the code that display's the Performance Tab ?

2021-08-16 14:43 UTC, yagarwal1307 commented
@sudo-NithishKarthik cool I will do that!

2021-08-16 15:56 UTC, sudo-NithishKarthik commented on ui/components/MesherySettings.js
> +            {/* <Tooltip title="Choose Performance Test Defaults" placement="top">
Also, add a comment here that says why you have commented this , that is, _functionality of this tab will take on a different shape, until that, keeping it commented_

2021-08-17 08:12 UTC, sudo-NithishKarthik approved these changes
LGTM
Thank you for your contributions @yagarwal1307 🎉

2021-08-17 08:12 UTC, merged

2021-08-19 00:32 UTC, leecalcote commented
We have a bug introduced here. The Remote Provider tab should only be shown when the user is connected to a Remote Provider.

This screenshot is of a user using the Local Provider (None). They should not see the Remote Provider tab.
<img width="1550" alt="Screen Shot 2021-08-18 at 7 30 22 PM" src="https://user-images.githubusercontent.com/7570704/129989268-e3caa15f-5c59-451c-a419-ae4d9e0b3c8d.png">