Docs - Static and Dynamic Boards concept
meshery/meshery pull request #3950
Opened 2021-08-21 15:03 UTC by suhaniii

Signed-off-by: Suhani Agarwal <suhani2612@gmail.com>

**Description**

This PR fixes #3933 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-08-21 15:05 UTC, l5io commented
🚀 Preview for commit 80090d758addb044005e9526698e02f724b3cf15 at: https://61211629f96e11277ea89416--meshery-docs-preview.netlify.app

2021-08-21 15:54 UTC, warunicorn19 commented on docs/pages/guides/meshery-metrics.md
> +Static Borads capture the Service Mesh Performance. Certain protos are defined and tracked as a part of performace tests. Static Boards Queries prometheus SDK directly.
```suggestion
Static Boards capture the Service Mesh Performance. Certain protos are defined and tracked as a part of performance tests. Static Boards Queries Prometheus SDK directly.
```
consider using this instead

2021-08-21 15:54 UTC, warunicorn19 commented on docs/pages/guides/meshery-metrics.md
> +Dynamic Boards can be generated from prometheus or grafana. These borads are defined by user. Grafana SDK is used for these boards.
```suggestion
Dynamic Boards can be generated from Prometheus or Grafana. These boards are defined by the user. Grafana SDK is used for these boards.
```
consider using this instead.

2021-08-21 17:05 UTC, sayantan1413 requested changes

2021-08-21 17:05 UTC, sayantan1413 commented on docs/pages/guides/meshery-metrics.md
> +User needs to set the prometheus URL and API key to create and query boards.
```suggestion
User needs to set the Prometheus URL and API key to create and query boards.
```

2021-08-21 17:08 UTC, sayantan1413 commented
<img width="742" alt="Screenshot 2021-08-21 at 10 37 39 PM" src="https://user-images.githubusercontent.com/64970095/130329634-8ba955d5-4422-40f2-9b81-8b9d6cfb91e1.png">
<img width="768" alt="Screenshot 2021-08-21 at 10 37 29 P@suhaniii rc="https://user-images.githubusercontent.com/64970095/130329636-1f198033-94ce-4961-b6d0-1eb21c8793e0.png">
@suhaniii the images look a bit odd here.

2021-08-21 20:51 UTC, suhaniii commented
> <img alt="Screenshot 2021-08-21 at 10 37 39 PM" width="742" src="https://user-images.githubusercontent.com/64970095/130329634-8ba955d5-4422-40f2-9b81-8b9d6cfb91e1.png">
> 
> <img alt="Screenshot 2021-08-21 at 10 37 29 PM" width="768" src="https://user-images.githubusercontent.com/64970095/130329636-1f198033-94ce-4961-b6d0-1eb21c8793e0.png">
> 
> @suhaniii the images look a bit odd here.

@sayantan1413 Right, it does, I took a screenshot, converted it into .svc format online and finally download... Is there a better way?

2021-08-21 20:54 UTC, suhaniii commented on docs/pages/guides/meshery-metrics.md
> +Static Borads capture the Service Mesh Performance. Certain protos are defined and tracked as a part of performace tests. Static Boards Queries prometheus SDK directly.
Thanks, I have added all there changes

2021-08-21 20:54 UTC, l5io commented
🚀 Preview for commit 4b9b22b86df32a340e617e6288d09f0e087a2be8 at: https://612167ebf96e11a757a89207--meshery-docs-preview.netlify.app

2021-08-21 21:11 UTC, sayantan1413 commented
@suhaniii I think we can use PNG as well here if svg is creating a problem.

2021-08-22 15:24 UTC, l5io commented
🚀 Preview for commit 2f4f39396563adce8d1ea6fab554df6e929d5263 at: https://61226c170f70c9a913ba7e7e--meshery-docs-preview.netlify.app

2021-08-22 15:32 UTC, warunicorn19 approved these changes
LGTM 🎉! Thanks for this @suhaniii

2021-08-22 18:38 UTC, sayantan1413 commented
<img width="720" alt="Screenshot 2021-08-23 at 12 07 00 AM" src="https://user-images.githubusercontent.com/64970095/130366231-dad90174-261a-4e56-98cc-b65b90d8bd5a.png">
Hey @suhaniii I was thinking that if those 5px solid black border at the bottom and top of those two pictures are removed it would look better I guess. What's your view on this @suhaniii ?😅

2021-08-23 12:06 UTC, suhaniii commented
> <img alt="Screenshot 2021-08-23 at 12 07 00 AM" width="720" src="https://user-images.githubusercontent.com/64970095/130366231-dad90174-261a-4e56-98cc-b65b90d8bd5a.png">
> 
> Hey @suhaniii I was thinking that if those 5px solid black border at the bottom and top of those two pictures are removed it would look better I guess. What's your view on this @suhaniii ?😅

You are right @sayantan1413

2021-08-23 12:09 UTC, l5io commented
🚀 Preview for commit 3b6cf4383d937e585bd4099fce5629a7381b4d67 at: https://61238fec85cd081287cdee5d--meshery-docs-preview.netlify.app

2021-08-23 12:22 UTC, sayantan1413 approved these changes
LGTM @suhaniii 🎉🚀

2021-08-24 19:54 UTC, leecalcote requested changes
Please see these instructions - https://github.com/meshery/meshery/issues/3933#issuecomment-902296764

2021-08-25 02:40 UTC, l5io commented
🚀 Preview for commit 970e03753a71c1c1c2fcc84af86b9cbe1ee3eeb4 at: https://6125ad63e7f1673f8670c1e1--meshery-docs-preview.netlify.app

2021-08-25 05:51 UTC, warunicorn19 approved these changes

2021-08-25 06:04 UTC, sayantan1413 approved these changes
The svg looks good now ✔️🚀

2021-08-27 04:53 UTC, merged