[UI] add mapper to podname and version
meshery/meshery pull request #3956
Opened 2021-08-22 08:48 UTC by bariqhibat

Signed-off-by: Bariq <bariqhibat@gmail.com>

**Description**

This PR fixes #3955

**Notes for Reviewers**
Making a function where all the heavy work and bad codes resides.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-08-22 10:03 UTC, warunicorn19 requested changes
Let's keep the version as is, since it comes under a Versions column, we don't really need to add the 'v'. 
Also, if you could refer to these suggestions from nithish: https://github.com/meshery/meshery/issues/3955#issuecomment-903239452

2021-08-22 15:35 UTC, utkarsh-pro commented on ui/utils/nameMapper.js
> +      else if (podName.includes("istio-ingressgateway")) return "Istio Ingress Gateway";
Minor nitpick, you can get rid of most the `else` here. Makes it more readable. :smile:

2021-08-24 10:47 UTC, leecalcote commented
Uh-oh, a merge conflict has arisen.

2021-08-24 19:46 UTC, leecalcote commented on ui/utils/nameMapper.js
> +export const podNameMapper = (serviceMeshName, podName) => {
@bariqhibat thank you for pulling this out separately.

2021-08-24 19:47 UTC, leecalcote commented on ui/utils/nameMapper.js
> +      if (podName.includes("osm-controller")) return "OSM Controller";
If "Open Service Mesh" fits, it'd be good to expand OSM to that.

2021-08-24 19:47 UTC, leecalcote approved these changes
LGTM

2021-08-25 04:29 UTC, merged