[UI] Bulk Delete in Filters + Patterns + Applications
meshery/meshery pull request #3965
Opened 2021-08-23 17:58 UTC by Chadha93

Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**

This PR fixes # my delayed issues (apologize)

**Notes for Reviewers**

https://user-images.githubusercontent.com/65453826/130494357-106cc35f-d776-4b3b-b6b7-54b5ec77a186.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-08-23 19:26 UTC, leecalcote requested changes
Removing the confirmation dialog regresses system behavior. We need to ensure that users are prompted on single filter or bulk filter delete.

2021-08-24 19:27 UTC, Chadha93 commented
@leecalcote Updated, Now the user will be prompted whenever deleting one or more pattern/filter/app(s) 

https://user-images.githubusercontent.com/65453826/130677781-8b8a6715-ce34-4134-93ed-a74915660dd4.mp4

2021-08-24 19:44 UTC, leecalcote commented on ui/components/Filters.js
> +      options : ["YES", "NO"], })
```suggestion
      options : ["yes", "no"], })
```

2021-08-24 19:44 UTC, leecalcote commented on ui/components/Filters.js
> +      if (response === "NO")
```suggestion
      if (response === "no")
```

2021-08-24 19:44 UTC, leecalcote commented on ui/components/Filters.js
> +      if (response === "YES") {
```suggestion
      if (response === "yes") {
```

2021-08-24 19:44 UTC, leecalcote commented on ui/components/MesheryApplications.js
> +      options : ["YES", "NO"], })
```suggestion
      options : ["yes", "no"], })
```

2021-08-24 19:44 UTC, leecalcote commented on ui/components/MesheryApplications.js
> +      if (response === "YES") {
"yes"
```suggestion
      if (response === "yes") {
```

2021-08-24 19:44 UTC, leecalcote commented on ui/components/MesheryApplications.js
> +      if (response === "NO")
```suggestion
      if (response === "no")
```

2021-08-24 19:44 UTC, leecalcote commented on ui/components/MesheryPatterns.js
> +      options : ["YES", "NO"], })
```suggestion
      options : ["yes", "no"], })
```

2021-08-24 19:44 UTC, leecalcote commented on ui/components/MesheryPatterns.js
> +      if (response === "NO")
```suggestion
      if (response === "no")
```

2021-08-24 19:44 UTC, leecalcote commented on ui/components/MesheryPatterns.js
> +      if (response === "YES") {
```suggestion
      if (response === "yes") {
```

2021-08-24 19:45 UTC, leecalcote approved these changes

2021-08-24 20:58 UTC, navendu-pottekkat approved these changes

2021-08-25 04:28 UTC, merged