Added tests for `mesheryctl/config`
meshery/meshery pull request #4047
Opened 2021-09-01 07:17 UTC by shikharvashistha

**Description**

This PR is in accordance to issue #3988 where I've added some tests for `mesheryctl/config`  kindly review and let me know in case of any further changes.

**Notes for Reviewers**
Apologies @utkarsh-pro for closing PR #4042 In my opinion `handlers/config` too need a test suite like `mesheryctl/config` to write and validate tests.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-09-02 14:27 UTC, piyushsingariya requested changes

2021-09-02 14:27 UTC, piyushsingariya commented on mesheryctl/internal/cli/root/config/config_test.go
> +	}
Add some adapters here!

2021-09-03 05:36 UTC, shikharvashistha commented on mesheryctl/internal/cli/root/config/config_test.go
> +	}
Done

2021-09-03 06:15 UTC, piyushsingariya approved these changes
nice work @shikharvashistha !

2021-09-03 06:16 UTC, merged