UX improvements in mesh command
meshery/meshery pull request #4238
Opened 2021-09-23 22:53 UTC by navendu-pottekkat

Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>

**Description**

This PR adds examples and removes the need for providing `--token` flag with the path to the token and instead uses the default token present in `.meshery` folder.

- [ ] Yes, I signed my commits.

2021-09-24 02:15 UTC, navendu-pottekkat commented
@leecalcote We should have this merged. Let's not leave it for after the release. There aren't any functional changes. Only UX changes to ensure consistency.

2021-09-24 03:31 UTC, leecalcote approved these changes

2021-09-24 03:32 UTC, leecalcote requested changes

2021-09-24 03:32 UTC, leecalcote commented on mesheryctl/internal/cli/root/mesh/deploy.go
> +mesheryctl mesh deploy --adapter linkerd --namespace linkerd-ns
Should be `--adapter meshery-linkerd`

2021-09-24 03:32 UTC, leecalcote commented on mesheryctl/internal/cli/root/mesh/deploy.go
> +mesheryctl mesh deploy --adapter linkerd --watch`,
same

2021-09-25 13:09 UTC, navendu-pottekkat commented
@leecalcote Changes made.

2021-09-25 14:34 UTC, piyushsingariya approved these changes
We can merge this!

2021-09-26 05:12 UTC, leecalcote approved these changes
Good 👍

2021-09-26 05:13 UTC, merged