[UI] Updated the UI of confirmation prompt
meshery/meshery pull request #4266
Opened 2021-09-28 18:49 UTC by Meghana-12

Signed-off-by: Meghana-12 <meghana.cosmos@gmail.com>

**Description**
`options` prop is passed to component `PromptComponent`. The first option, `options[0]`, is considered as the primary text and is placed on the right with the current background(primary) as the button color and the second option, `options[1]`, is considered as secondary text and is placed on the left with transparent background.  

![Screenshot 2021-09-29 at 12 12 29 AM](https://user-images.githubusercontent.com/44519203/135146763-1fb8a2f2-5188-45b0-9318-ebf6dd59c840.png)
On hover :  
![Screenshot 2021-09-29 at 12 17 20 AM](https://user-images.githubusercontent.com/44519203/135147558-f3f9369c-02e1-479a-afbc-47f63832aebf.png)

This PR fixes #4209 

**Notes for Reviewers**
@Lee I've attached the screenshot of the update. Is this what you were expecting ?

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-09-28 18:59 UTC, warunicorn19 requested changes
@Meghana-12 Looking good, small nitpick, could you try using a little darker of a color for the `no` button ? something like this 
<img width="1032" alt="Screenshot 2021-09-29 at 12 24 50 AM" src="https://user-images.githubusercontent.com/53532328/135148667-565bf7f3-4937-4d3c-8349-fffdf7119304.png">

and the hover effect would be similar to `View Results` button in the `Performance profiles`

2021-09-28 22:40 UTC, leecalcote approved these changes
Pending consistent styling, this looks great!

2021-09-29 03:21 UTC, leecalcote approved these changes

2021-09-29 03:21 UTC, merged

2021-09-29 06:01 UTC, Meghana-12 commented
@leecalcote Should I create a new PR to add the changes @warunicorn19 suggested ?