Add examples for `mesheryctl` commands
meshery/meshery pull request #4269
Opened 2021-09-29 05:29 UTC by alphaX86

**Description**

This PR fixes #3978 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-09-29 05:31 UTC, l5io commented
🚀 Preview for commit 33acf001de3991290b21355cb1467e2b2c13285b at: https://6153fa192e049b8efa8d102d--meshery-docs-preview.netlify.app

2021-09-29 06:34 UTC, l5io commented
🚀 Preview for commit 67bea2edf0ebb2d8bbd0918118ace4d512a292fd at: https://615408c266f6dd956f62792e--meshery-docs-preview.netlify.app

2021-09-29 14:19 UTC, l5io commented
🚀 Preview for commit 3a3eebd6e062ebda9079b17a4c05e6f877e46ad0 at: https://615475d06e6a851358226c9b--meshery-docs-preview.netlify.app

2021-09-29 15:02 UTC, alphaX86 commented
@navendu-pottekkat could you tell what are the file formats for the SMI conformance file and patterns? For some commands, it's needed and I'm clueless about them. Plus, even the patterns too are bit hard to understand at first glance, like a novice user finds it difficult to implement.

2021-09-29 16:27 UTC, leecalcote commented
@alphaX86 some good stuff happening here!

2021-10-01 05:21 UTC, alphaX86 commented
> could you tell what are the file formats for the SMI conformance and patterns? For some commands, it's needed and I'm clueless about them. Plus, even the patterns too are bit hard to understand at first glance, like a novice user finds it difficult to implement.

@leecalcote could you answer my query so that I can move on?

//cc: @sayantan1413 (since you worked with patterns)

2021-10-01 17:14 UTC, leecalcote commented
@alphaX86 great question. We should not only add examples to `mesheryctl` on these, but also in the Pattern Management and other pages.

- patterns are of the file format yaml. Here are sample patterns: https://github.com/service-mesh-patterns/service-mesh-patterns. Each of these must contain a `name` property and should contain one or more `services`.
- applications are of the file format yaml.
- filters are of a binary file format.

2021-10-01 21:51 UTC, leecalcote commented
https://github.com/meshery/meshery/pull/4269/files#diff-da82e4d8bc231e812de092c80bcf1c565619d07b14d2852ddb730396e16f84dbR38 the description is inaccurate.

this command confirms the version number of meshery client installed on the user's system and the meshery server version of their current context. It also verifies whether the user is running the latest release version or not.

2021-10-01 21:51 UTC, leecalcote requested changes

2021-10-01 21:51 UTC, leecalcote commented on docs/_data/mesheryctlcommands/cmds.yml
> +  description : Global command
```suggestion
  description : A global command that displays an overview of all commands.
```

2021-10-01 21:51 UTC, leecalcote commented on docs/_data/mesheryctlcommands/cmds.yml
> +    mesheryctl system start
This isn't an example of the global command...

2021-10-01 21:51 UTC, leecalcote commented on docs/_data/mesheryctlcommands/cmds.yml
> +      mesheryctl system stop
This isn't an example of the global command...

2021-10-01 21:51 UTC, leecalcote commented on docs/_data/mesheryctlcommands/cmds.yml
>        description: configures Meshery with the kubeconfig, generated with the help of user details, to provide cluster access for public clouds(GKE/EKS).
This description is incorrect. This is the meshconfig.

2021-10-01 21:51 UTC, leecalcote commented on docs/_data/mesheryctlcommands/cmds.yml
>        description: Temporarily change the current context.
Please elaborate on the concept of contexts.

2021-10-01 21:51 UTC, leecalcote commented on docs/_data/mesheryctlcommands/cmds.yml
>          mesheryctl system reset -c [temporary context name]
Please provide explanation of what this example usage actually does.

2021-10-03 06:23 UTC, l5io commented
🚀 Preview for commit 43b6b1e69349b0bf4ed60aa8533a9c129efc95d9 at: https://61594c350e0b4899c3be48b0--meshery-docs-preview.netlify.app

2021-10-03 06:41 UTC, l5io commented
🚀 Preview for commit dd123087dff8e33d361de54481c8b21763fb4b04 at: https://6159508319ab3e9600fde837--meshery-docs-preview.netlify.app

2021-10-06 15:07 UTC, warunicorn19 submitted a review, later dismissed
Till now the changes LGTM, Good stuff! @alphaX86

2021-10-06 18:38 UTC, leecalcote commented on docs/_data/mesheryctlcommands/cmds.yml
>        description: Output shell completion code.
```suggestion
      description: Output shell completion code for the specified shell.
```

2021-10-06 18:40 UTC, leecalcote requested changes
We're almost there!

2021-10-06 18:40 UTC, leecalcote commented on docs/_data/mesheryctlcommands/cmds.yml
> -          # View the logs for a specific component
This update loses the fact that users can filter logs for a specified component.

2021-10-06 18:40 UTC, leecalcote commented on docs/_data/mesheryctlcommands/cmds.yml
>        description: set release channel and version.
```suggestion
      description: Subscribe to release channel and version.
```

2021-10-07 03:15 UTC, l5io commented
🚀 Preview for commit 30693f5e52d5235c58bdfd668dfbbca2715b88d1 at: https://615e661c75213464fb0219e1--meshery-docs-preview.netlify.app

2021-10-08 01:04 UTC, alphaX86 commented
And BTW @navendu-pottekkat you didn't answer this question yet. What's the file format for a SMP compatible configuration file? I need to use it for `perf --file` I tired but only GUI approach I could do and for CLI approach I'm confused for that alone

2021-10-09 18:13 UTC, navendu-pottekkat commented
The other comment that you only see it in the main page alone. Cool. No problem.

Please ping when you make the edit in `perf` like you mentioned and we can merge this PR/

2021-10-10 13:59 UTC, alphaX86 commented
@navendu-pottekkat it's done...

@leecalcote help here! DCO again! :')

2021-10-13 00:36 UTC, merged

2021-10-13 00:36 UTC, leecalcote commented
yay!