Added meshkit style error in handlers
meshery/meshery pull request #4340
Opened 2021-10-06 19:57 UTC by sayantan1413

Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>

**Description**

Added the meshkit style error in the

1. meshery filter handler

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-10-30 04:31 UTC, leecalcote commented on handlers/error.go
> +	return errors.New(ErrSaveFilterCode, errors.Alert, []string{"Error failed to save filter"}, []string{err.Error()}, []string{}, []string{})
Look to the Error Code Guide in docs.meshery.io for examples, @sayantan1413

2021-11-01 13:06 UTC, utkarsh-pro submitted a review, later dismissed
LGTM. Some items by @leecalcote needs to be addressed.

2021-11-01 13:10 UTC, sayantan1413 commented
Yes @utkarsh-pro I will do those changes soon.

2021-11-01 13:11 UTC, sayantan1413 commented on handlers/error.go
> +	return errors.New(ErrSaveFilterCode, errors.Alert, []string{"Error failed to save filter"}, []string{err.Error()}, []string{}, []string{})
Sure I will add the probable cause and suggested remediation

2021-11-07 04:27 UTC, navendu-pottekkat commented
@sayantan1413 Is this PR ready for a review?

2021-11-07 18:21 UTC, utkarsh-pro approved these changes
LGTM. @leecalcote kindly merge if your comments regarding "probable cause and suggested remediation".

2021-12-01 13:26 UTC, bariqhibat requested changes
Hey @sayantan1413, any updates? We're left with suggested remedition and probable cause, then I think we're good to go (?)

2021-12-01 14:31 UTC, sayantan1413 commented
Hey, @bariqhibat I have already completed writing those.

2021-12-01 15:36 UTC, bariqhibat approved these changes
Looks good

2021-12-16 22:59 UTC, leecalcote approved these changes

2021-12-16 23:05 UTC, merged