[UI] Counter in Performance Profile fixed
meshery/meshery pull request #4518
Opened 2021-10-28 20:03 UTC by ruhi09

Signed-off-by: ruhi09 <rim.sen5613@gmail.com>

**Description**
Count displayed in Performance when content is deleted in bulk. Handles both the case (count == 1 and count > 1).
![Capture](https://user-images.githubusercontent.com/91118779/139702520-e554cf5b-8b3f-4176-939a-6671f4365e09.PNG)
![Capture2](https://user-images.githubusercontent.com/91118779/139702596-8ebfd203-fa29-41d4-b2e8-679101cc0740.PNG)

This PR fixes #4479 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-devel
oper-certificate-of-origin)**
- [x] Yes, I signed my commits

2021-10-31 06:56 UTC, Chadha93 requested changes
Added few comments, please do update that, then we are good to go.

2021-10-31 06:56 UTC, Chadha93 commented on ui/components/MesheryPerformance/PerformanceProfiles.js
> +    let response = await modalRef.current.show({ title : `Delete ${count ? count : ""} Application${count > 1 ? "s" : '' }?`,
@ruhi09 please change Applications to performance profile in title

2021-10-31 06:56 UTC, Chadha93 commented on ui/components/MesheryPerformance/PerformanceProfiles.js
> +      subtitle : `Are you sure you want to delete ${count > 1 ? "these" : 'this' } ${count ? count : ""} application${count > 1 ? "s" : '' }?`,
here also applications to performance profiles

2021-10-31 07:00 UTC, Chadha93 commented
+ update the new screenshots of the performance profile in the description, if you would.

2021-11-01 16:20 UTC, warunicorn19 approved these changes
LGTM, thanks @ruhi09

2021-11-01 17:34 UTC, Chadha93 approved these changes
Nice work, 
Thanks @ruhi09

2021-11-01 18:07 UTC, sayantan1413 approved these changes

2021-11-05 22:12 UTC, leecalcote approved these changes

2021-11-05 22:12 UTC, merged