Updated Load-generator.md
meshery/meshery pull request #4548
Opened 2021-11-02 13:45 UTC by Rahulkumar2002

In load-generator.md updated GetNightHawk to NightHawk

2021-11-02 13:48 UTC, l5io commented
🚀 Preview for commit b5c1f0f8f1d925946d725e3bc30d321cdf56276b at: https://6181419fab599fecd032de7b--meshery-docs-preview.netlify.app

2021-11-02 13:49 UTC, leecalcote reviewed
Thanks, @Rahulkumar2002. Will you also update the hyperlink in the line above to be https://getnighthawk.dev?

2021-11-02 13:52 UTC, Rahulkumar2002 commented
> Thanks, @Rahulkumar2002. Will you also update the hyperlink in the line above to be https://getnighthawk.dev?

Ok I will try , Can you point out the repo for this hyperlink ?

2021-11-03 07:11 UTC, warunicorn19 requested changes

2021-11-03 07:11 UTC, warunicorn19 commented on docs/pages/extensibility/load-generators.md
>  1. [nighthawk](https://github.com/envoyproxy/nighthawk) - Enables users to run distributed performance tests to better mimic real-world, distributed systems scenarios.
```suggestion
1. [nighthawk](https://getnighthawk.dev/) - Enables users to run distributed performance tests to better mimic real-world, distributed systems scenarios.
```
@Rahulkumar2002, @leecalcote is referring to this.

2021-11-05 22:09 UTC, leecalcote approved these changes

2021-11-05 22:11 UTC, merged