[Docs] Add 'Connecting to Remote Providers' section in Troubleshooting Guide
meshery/meshery pull request #4623
Opened 2021-11-12 07:01 UTC by gyohuangxin

**Description**

Add 'Connecting to Remote Providers' section in Troubleshooting Guide

This PR fixes #4597

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-11-12 07:04 UTC, l5io commented
🚀 Preview for commit 9e1af418690cff4c9011a10ad706352ca94d0d31 at: https://618e11c4d1675e1f4cad4d59--meshery-docs-preview.netlify.app

2021-11-12 07:07 UTC, l5io commented
🚀 Preview for commit 3e3b490178bff1984fe30cd81d2d83f306fbd7da at: https://618e1288742b2918843dadd5--meshery-docs-preview.netlify.app

2021-11-12 07:09 UTC, l5io commented
🚀 Preview for commit 744bf47e7af2594cd06fba1d3399c7ec752519dc at: https://618e132494dbd03373200f42--meshery-docs-preview.netlify.app

2021-11-12 08:49 UTC, Mr-DG-Wick commented on docs/pages/reference/troubleshooting/installation.md
> +Once Meshery is installed, the remote provider "Meshery" can be chosen from UI or by using command `mesheryctl system login`:
```suggestion
Once Meshery is installed, the remote provider "Meshery" can be chosen from UI or by using the command `mesheryctl system login`:
```

2021-11-12 09:06 UTC, Mr-DG-Wick requested changes
Thanks for taking this up! @gyohuangxin . Suggested some minor suggestions.

2021-11-12 09:06 UTC, Mr-DG-Wick commented on docs/pages/reference/troubleshooting/installation.md
> +![Providers](/assets/img/providers/provider_screenshot.png)
I think there seems to be an issue with the image. It isn't visible to me in the preview mode.

2021-11-12 15:56 UTC, leecalcote commented
yay, @gyohuangxin! 🎈

2021-11-12 17:21 UTC, leecalcote commented on docs/pages/reference/troubleshooting/installation.md
> +If you cannot see "Meshery" provider and find such error logs in meshery pod's log, please make sure that the meshery pod has the connections to "https://meshery.layer5.io" to initialize remote provi
```suggestion
If you cannot see "Meshery" Remote Provider and find such error logs in Meshery Server's logs (`mesheryctl system logs`), please make sure that Meshery Server is able to reach "https://meshery.layer5.io" in order to initialize the "Meshery" Remote Provider.
```

2021-11-12 17:22 UTC, leecalcote approved these changes
This is great. Thank you, @gyohuangxin 👍

2021-11-12 17:22 UTC, merged

2021-11-14 15:09 UTC, gyohuangxin commented
@leecalcote @Mr-DG-Wick Thank you for your reviews.