Run tests under same performance profile if it is already present
meshery/meshery pull request #4710
Opened 2021-12-03 11:04 UTC by navendu-pottekkat

Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>

**Description**

Updates `mesheryctl perf apply` to first check if a performance profile is already created before running a test under a new performance profile with the same name.

Runs tests under the same profile if it is already present.

This works for tests run with a configuration file, flags or a profile name.

**Notes for Reviewers**

A new release is needed after merging this PR to use this change in the [meshery-smp-action](https://github.com/layer5io/meshery-smp-action/).

- [ ] Yes, I signed my commits.

2021-12-03 11:34 UTC, navendu-pottekkat commented
There shouldn't be a reason for failing tests. I'm not sure why...

2021-12-04 04:58 UTC, piyushsingariya commented
> There shouldn't be a reason for failing tests. I'm not sure why...

You have made quite a significant amount of changes, tests are supposed to fail, I feel!

2021-12-04 13:45 UTC, navendu-pottekkat commented
> > There shouldn't be a reason for failing tests. I'm not sure why...
> 
> You have made quite a significant amount of changes, tests are supposed to fail, I feel!

It shouldn't change the behaviour though. I could not figure it out instantly. Looking into it in detail.

2021-12-06 08:48 UTC, navendu-pottekkat commented
@piyushsingariya Removed the `--perf` flag and is now only using the argument with the profile name.

Rest of the functionality is the same with the ability to override the values in a test configuration with flags.

I will update the unit tests if this is okay.

2021-12-06 09:41 UTC, piyushsingariya commented
@navendu-pottekkat can you update the use-cases here with examples+explaination. Just to be on the same page while reviewing.

2021-12-06 09:49 UTC, navendu-pottekkat commented
The only additional use case here is to run tests on the same performance profile.

If a performance profile exists, run tests under it.
Else check with the user and create a new performance profile.

Earlier we used to default to a new performance profile with a profile name as same as the name provided in the test configuration file. This will be used in the [meshery-smp-action](https://github.com/layer5io/meshery-smp-action/pull/30) to run similar tests and group them under the same performance profile.

2021-12-06 09:58 UTC, piyushsingariya requested changes
Documentation would require a few updates, @navendu-pottekkat please open an issue for this. "good-first-issue" can be added.

2021-12-06 09:58 UTC, piyushsingariya commented on mesheryctl/internal/cli/root/perf/apply.go
>  		// Importing SMP Configuration from the file
Just above this line token is being set twice. Please remove one instance.

2021-12-06 12:28 UTC, navendu-pottekkat commented
@piyushsingariya Updated the inline docs as well as the docs pages by removing references of the `--profile` flag.

Also removed the redundant code for setting token path.

2021-12-06 12:29 UTC, l5io commented
🚀 Preview for commit ca4fed71ee9dd413b8f0d6762ee3be2ac1366df0 at: https://61ae01eacefb1175c10f30e9--meshery-docs-preview.netlify.app

2021-12-06 13:52 UTC, piyushsingariya approved these changes

2021-12-06 13:52 UTC, merged