Added the Prompt component
meshery/meshery pull request #4811
Opened 2021-12-22 18:45 UTC by sayantan1413

Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>

**Description**

Added the Prompt component

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2021-12-24 08:34 UTC, sudo-NithishKarthik commented on ui/components/Prompt/Prompt.js
> +  const show = async (passed) => {
This function need not be async

2021-12-24 08:39 UTC, sudo-NithishKarthik requested changes
Good work @sayantan1413 . There are some modifications to be done. I think you will have to rethink how we can dynamically display the number of options. That would be good challenge also, hope you enjoy 😄

2021-12-24 08:39 UTC, sudo-NithishKarthik commented on ui/components/Prompt/Prompt.js
> +const Prompt = () => {
We should be getting `title` `subtitle` and `options` from the props

2021-12-24 08:39 UTC, sudo-NithishKarthik commented on ui/components/Prompt/Prompt.js
> +        <DialogActions className={classes.actions}>
The number of buttons rendered should be dynamic, i.e it should render a button for every option provided.

2022-01-11 07:36 UTC, bariqhibat requested changes
Some comments

2022-01-11 07:36 UTC, bariqhibat commented on ui/components/Prompt/Prompt.js
> +  let promiseInfo = {};
Won't this be good to be used as a state instead?

2022-01-11 07:36 UTC, bariqhibat commented on ui/components/Prompt/Prompt.js
> +            key={options[1]}
Shouldn't we check the length of this array `options` first? If it's empty then this will throw an error

2022-02-20 14:52 UTC, leecalcote commented
@sudo-NithishKarthik, @sayantan1413 has stepped away from this effort. 

Will you carry this PR to conclusion (merge, fix, close)?

2022-02-20 14:54 UTC, sudo-NithishKarthik commented
Yes. Will do 👍

2022-02-23 11:14 UTC, sudo-NithishKarthik commented
Opening a new PR for this.

2022-02-23 11:14 UTC, closed without merging