Footer refactoring/nik 09/4767
meshery/meshery pull request #4824
Opened 2021-12-23 18:25 UTC by Nik-09

**Description**

This PR fixes #4767 

**Notes for Reviewers**

This PR is currently not ready for review -- working on final nits. 
Thank you

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2021-12-23 18:28 UTC, l5io commented
🚀 Preview for commit ba48ad72f4c3b3415d25fff1bc67a0288f9f4694 at: https://61c4bf96e6b481e1340aad52--meshery-docs-preview.netlify.app

2021-12-23 19:11 UTC, sayantan1413 commented
Hey, @Nik-09 whenever the PR is ready for review remove the label pr/draft.

2021-12-25 07:32 UTC, l5io commented
🚀 Preview for commit 7b876d367808c433fd5f424da5c84dd795287d97 at: https://61c6c8fdb5f4a268a56c7dcb--meshery-docs-preview.netlify.app

2021-12-25 07:35 UTC, Nik-09 reviewed
@sayantan1413 Currently I do not have rights to add/remove label -- can you please remove it, as currently the PR is ready for review.
Thank you.

2021-12-25 22:09 UTC, Abhijay007 approved these changes
LGTM 👍

2021-12-27 07:28 UTC, Nik-09 commented
@Abhijay007 @sayantan1413 -- Do I have to add anything else in order to merge this PR ?
Thank you.

2021-12-27 07:58 UTC, Abhijay007 commented
> @Abhijay007 @sayantan1413 -- Do I have to add anything else in order to merge this PR? Thank you.

It's LGTM I don't think that you need to add anything else !!

2021-12-27 15:56 UTC, warunicorn19 requested changes
Good stuff @Nik-09, just some minor changes. Could you please change the default color of the icons to white, increase the size just a little bit and add some space between the icons.

2022-01-06 18:20 UTC, Nik-09 commented
Hi @warunicorn19 @leecalcote , I need a suggestion from you.
As I am working on https://github.com/meshery/meshery/issues/4767, I need to know that which one of the following will be better:
Same background with white icons (as earlier).
Black background with grey icons (as in Layer5 and Meshery.io website).
Looking forward to your feedback :)

2022-01-06 20:37 UTC, leecalcote commented
@Nik-09 will you take a quick screenshot of the docs.meshery.io footer using the same off-black color used in the meshery.io footer? This will help in evaluating the potential change. The off-black color should be the Dark Jungle Green listed on layer5.io/brand.

2022-01-07 15:41 UTC, Nik-09 commented
@leecalcote 
please take a look.

![image](https://user-images.githubusercontent.com/57531197/148568059-bfd3d4ea-eda0-45a1-990d-b3658359d0b0.png)

2022-01-12 09:34 UTC, l5io commented
🚀 Preview for commit 93a719832682b2f48c37eeaec14bae32903494a5 at: https://61dea07e78f171f08dc5647d--meshery-docs-preview.netlify.app

2022-01-12 09:36 UTC, Nik-09 reviewed
@warunicorn19 @leecalcote Please take a look.

2022-01-12 12:00 UTC, leecalcote commented
Please add a more descriptive PR title, including `[UI]` at the beginning of the title. This saves maintainers time when reviewing PRs. Thanks!

2022-01-13 16:05 UTC, Nik-09 commented
> Please add a more descriptive PR title, including [UI] at the beginning of the title. This saves maintainers time when reviewing PRs. Thanks!

@leecalcote Done

2022-01-16 16:19 UTC, warunicorn19 commented on docs/assets/css/main.css
> +    background-color: #222222;
```suggestion
    background-color: #1E2117;
```

2022-01-16 16:22 UTC, l5io commented
🚀 Preview for commit 85fa548628c9439d9de366dad5d249a31f7d5a1b at: https://61e445fbd5eabef1b499693b--meshery-docs-preview.netlify.app

2022-01-16 18:06 UTC, l5io commented
🚀 Preview for commit 4c38ed13b963aace86c8168e28f60a9a89472d73 at: https://61e45e9fa71e1e288573aee8--meshery-docs-preview.netlify.app

2022-01-16 18:19 UTC, leecalcote commented
Calendar icon is missing the + symbol
<img width="60" alt="Screen Shot 2022-01-16 at 12 14 38 PM" src="https://user-images.githubusercontent.com/7570704/149672616-1279c929-edcf-4d5e-b848-7adab4763703.png">
.

2022-01-16 18:30 UTC, Nik-09 commented
> Calendar icon is missing the + symbol <img alt="Screen Shot 2022-01-16 at 12 14 38 PM" width="60" src="https://user-images.githubusercontent.com/7570704/149672616-1279c929-edcf-4d5e-b848-7adab4763703.png"> .

True, I removed that logo because of the following reasons:
1. Now the logo is matching with [meshery.io](https://meshery.io/) calendar logo in footer section hence it provides consitency.
2. It is new and clear in comparison to previous logo.

Looking forward to your point.
Thank you

2022-01-17 20:59 UTC, leecalcote commented
Thanks for explaining this @Nik-09. I suspect that whoever made the meshery.io footer accidentally forgot to change the color of the internal part of that icon's svg (I haven't looked, but just a guess). I think the calendar icon is too generic when it is more or less only a rounded rectangle. It'd be nice to either include the "+" or find another calendar icon. You're right that we want to be consistent across all uses of this icon. 👍

2022-01-20 16:15 UTC, leecalcote commented
@Nik-09, hopefully, you're able to colorize the "+" into the icon, and then help drive consistency across the rest of the site footers. Let me know if I can aid in updating the icon or finding a new one.

2022-01-21 14:36 UTC, Nik-09 commented
Thank you @leecalcote, I've edited the current svg and added "+" in it.
Please take a look,
![image](https://user-images.githubusercontent.com/57531197/150544343-da6a179b-62d1-4f25-85e3-4f0f498a52ed.png)

Initially gray as similar to other icons and on hover, it will be colored blue(#0073cf).
**Notes:**
Please provide feedback or confirm whether this is ready to be updated on other platforms(meshery.io).

Thank you.

2022-01-30 05:51 UTC, l5io commented
🚀 Preview for commit b90f9f433db7a319e6ef90cfb26df570cf6b0a34 at: https://61f6271e290c89788d304da8--meshery-docs-preview.netlify.app

2022-01-30 06:11 UTC, closed without merging

2022-01-30 06:19 UTC, Nik-09 commented
Closing this pull request because of some problems regarding signing off, the changes are reflected on new PR https://github.com/meshery/meshery/pull/5017

Thank you

2022-01-30 14:57 UTC, leecalcote commented
As you open a new PR, note that the "+" either isn't symmetric or isn't centered.