style changes to text field in RJSF
meshery/meshery pull request #4934
Opened 2022-01-12 23:33 UTC by warunicorn19

Signed-off-by: Aditya Chatterjee <speak2adi@gmail.com>

**Description**

1. Added tooltip to text field. 

https://user-images.githubusercontent.com/53532328/149239499-29d1cf01-d97f-400d-b370-b791a7cf9a01.mov

- [ ] still need to align the helpoutlineicon to the right

2. Changed the format of the tooltip for better readability. 

<img width="296" alt="tooltip" src="https://user-images.githubusercontent.com/53532328/149239695-632b0e98-b8ea-4079-af5e-fca37ef3f3a1.png">

can revert this change if it's not required. 
 

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-01-13 15:06 UTC, warunicorn19 commented
@leecalcote said that behaviour is looking neat 😅, I'll send a video with keeping the position fixed then we can decide which one looks better.

2022-01-13 15:42 UTC, warunicorn19 commented
@Chadha93 it turns out that we can't place an icon to the end of a mui textfield. Or at least I haven't been able to find it. @leecalcote is the above change fine? or do we want the icon to be fixed?

2022-01-13 17:34 UTC, Chadha93 requested changes
The video looks great  @warunicorn19 these are the desired changes as of now for the text fields.

Some minor comments to be addressed.

2022-01-13 17:34 UTC, Chadha93 commented on ui/components/MesheryMeshInterface/PatternService/EnlargedTextTooltip.js
> +    color : '#1E2117',
A defined color from figma?

2022-01-13 17:34 UTC, Chadha93 commented on ui/components/MesheryMeshInterface/PatternService/EnlargedTextTooltip.js
> +
Let's have these in rem

2022-01-13 17:45 UTC, warunicorn19 commented
Okay, pushing above changes.

2022-01-14 04:23 UTC, leecalcote commented
> @Chadha93 @leecalcote thoughts on this?

It's beautiful. This another good step forward. As a future iteration, we might tighten margins, go two-column with the inputs, reduce font size on input fields. Thumbs-up on this PR.

2022-01-14 04:23 UTC, leecalcote commented on ui/components/MesheryMeshInterface/PatternService/EnlargedTextTooltip.js
> +    color : '#1E2117',
Right, yes. Good to check, though.

2022-01-14 04:24 UTC, leecalcote commented on ui/components/MesheryMeshInterface/PatternService/EnlargedTextTooltip.js
> +
Nice.

2022-01-14 11:03 UTC, Abhishek-kumar09 commented
Extra Whitespace on the right hand side of the forms, Are we planning something for it?

2022-01-14 11:23 UTC, Chadha93 commented
We could have two items in a row to eliminate right-side white space...

2022-01-14 13:51 UTC, leecalcote commented
@Chadha93, this aligns with my suggestion. I'm not sure if it'll be too compact, but its worth trying.

2022-01-14 13:51 UTC, merged