[Cypress] Add ui tests for lifecycle
meshery/meshery pull request #5171
Opened 2022-03-03 18:31 UTC by Abhishek-kumar09

Signed-off-by: Abhishek-kumar09 <abhimait1909@gmail.com>

**Description**
1. Add liefcyle (e2e) tests for active adapters

Few Problems that is hindering the further testing: 
1. the navigation to some service mesh from the navigator doesn't work
2. All the service mesh has another enpoint based on their name that shows the way older UI leveraging the hundreds of oam components coming from backend thus freezing the interface sometimes
3. The inactive adapters UI page is the way it is expected, it should provide UI to configure which is not yet done.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-03-03 19:58 UTC, Abhishek-kumar09 commented
The falied e2e test is the proof of the UI not working as expected.

2022-03-03 21:57 UTC, MarioArriaga92 commented
Taking a look but maybe there's a better way to find elements than using `cy.contains`? As per [Cypress Best Practices > Selecting Elements](https://docs.cypress.io/guides/references/best-practices#Selecting-Elements) use of `cy.contains('text').` is recommended on a "Depends" basis as its coupled to text content that may change. If text being asserted on is not likely to change soon or we're okay with fact that test could break if we don't update text in cy commands when we modify it, then okay to keep using it (else we should try to add 'data-cy' attribute dinamically and use it in our cypress tests, when possible)

2022-03-04 23:40 UTC, leecalcote commented
> The falied e2e test is the proof of the UI not working as expected.

Issue(s) filed, @Abhishek-kumar09?

2022-03-09 04:06 UTC, warunicorn19 commented
@Abhishek-kumar09 a little brief on this would be great for the meshery dev call.

2022-03-10 02:17 UTC, leecalcote commented
@MarioArriaga92 can you implement the suggestions that you've made? You can checkout the code in this PR/branch and work on it directly.

2022-03-10 04:37 UTC, MarioArriaga92 commented
Right away @leecalcote

2022-03-15 23:43 UTC, MarioArriaga92 commented on ui/cypress/integration/e2e/lifecyclecheck_spec.js
> +function doGeneralIstioLifecycleChecks(cy) {
Passing 'cy' object is not needed (available globally)

2022-03-15 23:43 UTC, MarioArriaga92 commented on ui/cypress/integration/e2e/lifecyclecheck_spec.js
> +function verifyAllIstioAddons(cy) {
Passing 'cy' object is not needed (available globally)

2022-03-15 23:43 UTC, MarioArriaga92 commented on ui/cypress/integration/e2e/lifecyclecheck_spec.js
> +function doGeneralConsulLifecycleChecks(cy) {
Passing 'cy' object is not needed (available globally)

2022-03-16 00:03 UTC, MarioArriaga92 commented on ui/cypress/integration/e2e/lifecyclecheck_spec.js
> +  cy.get('body').should("not.contain",  "Apply Service Mesh Configuration");
If [a test case](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0&range=138:138) for Consul Meshery Adapter is defined in Meshery Test Plan (“Click the ‘+’ option in the “Apply Service Mesh Configuration” card and try applying those operations that appear on the service mesh management page.“) why shouldn’t that card be present?

2022-03-16 00:04 UTC, MarioArriaga92 requested changes
Left a couple of comments

2022-04-06 19:07 UTC, leecalcote commented
Syncing with `master` again.

2022-04-06 20:04 UTC, MarioArriaga92 commented
@Abhishek-kumar09 can you mention which are the open github issues that cause tests included in this PR to fail please?

2022-04-06 20:07 UTC, MarioArriaga92 commented
Btw integration test fails for filter configuration page because title element found is not "'FiltersBETA'" is this still expected? (probably related to some other PR but wanted to double-check here first)

2022-05-11 16:18 UTC, Abhishek-kumar09 commented on ui/components/MesheryPlayComponent.js
> +    console.log({ adapter, meshAdapters })
```suggestion
```

2022-05-12 09:18 UTC, Abhishek-kumar09 commented
@leecalcote @MarioArriaga92 Can we move here?

2022-05-13 15:26 UTC, leecalcote approved these changes
👨‍🎤 and roll.

2022-05-13 15:26 UTC, merged