handle panic when preference load test is not provided in UserPrefsHandler
meshery/meshery pull request #5177
Opened 2022-03-06 14:17 UTC by sourikghosh

Signed-off-by: Sourik Ghosh <sourikghosh31@gmail.com>

**Description**
When `UserPrefsHandler` is called with no `LoadTestPreferences` it panics because of `nil pointer dereference` at
https://github.com/meshery/meshery/blob/73dec0091c1c0ab0c7a34edf7b28d3d39b77e458/handlers/user_handler.go#L67

This PR fixes #
fixes #5174 
**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-03-06 14:29 UTC, leecalcote commented
Thanks for this, @sourikghosh 👍

Behaviors to verify - https://github.com/meshery/meshery/issues/5174#issuecomment-1059972502

2022-03-07 05:09 UTC, theBeginner86 requested changes
@sourikghosh 
Though these changes handle that panic but lead to some other unwanted behaviors.
I tested your latest changes and got this:

https://user-images.githubusercontent.com/73700530/156971226-35a546a8-82d8-46ee-9dd9-9c8f0d571c77.mov


Moreover, I’m afraid that it doesn’t align with what we are aiming for.

2022-03-07 05:10 UTC, theBeginner86 commented
@sourikghosh 
We want that all the user preferences are persisted. Basically, this means that all users’ preferences remain preserved irrespective of the user session. (Do read the [above](https://github.com/meshery/meshery/pull/5177#issuecomment-1059972846) considerations mentioned by Lee)
1. You must consider that the user preferences should get persisted for both ”None” and “Meshery” Provider.
2. User preferences could be various personal choices of a Meshery user. For eg, duration of a performance test, default load generator for a performance test, other preferences about different extensibility, etc.

To know more about these concepts do check the docs:
- https://docs.meshery.io/extensibility/providers
- https://docs.meshery.io/concepts/architecture

2022-03-07 19:38 UTC, leecalcote commented
@sourikghosh, thanks for jumping in here. 👏 Seemingly small, this issue is slightly involved. Whether this particular PR is eventually merged or not... please keep at it.

2022-03-08 15:13 UTC, sourikghosh commented
The issue is that `UserPrefsHandler` tries to validate the `LoadTestPreferences` object even if it's not sent in the request body. 
```bash
{
    "anonymousUsageStats": false,
    "anonymousPerfResults": true,
    "usersExtensionPreferences": {
        "showOnZoom": false
    }
}
```
Since it's a pointer to an object, we should always keep in mind the nil case. ( nil pointer dereference ).
Moreover, it should only validate if `LoadTestPreferences` is not `nil`.<br>
After applying these changes the persistence of User Preferences works fine for both local/remote providers. <br>
<em><b>local provider</b></em>
https://user-images.githubusercontent.com/61813998/157266230-fc889501-fc63-4652-9325-6eb90f6ba986.mp4

<em><b>remote provider</b></em>

https://user-images.githubusercontent.com/61813998/157266497-6807f3cb-120a-4cd0-9c94-94d0985c36dd.mp4

@theBeginner86  @leecalcote

2022-03-08 17:10 UTC, leecalcote approved these changes
Looking good to me, @sourikghosh 👍

2022-03-09 07:47 UTC, theBeginner86 approved these changes
LGTM!

Thanks @sourikghosh

2022-03-09 16:15 UTC, merged