Add genDocs function for mesheryctl
meshery/meshery pull request #5366
Opened 2022-04-10 16:50 UTC by alphaX86

Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

**Description**

This PR fixes #5201

This PR is a work continued from #5108 

**Notes for Reviewers**
WIP

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-04-14 14:52 UTC, alphaX86 commented on mesheryctl/internal/cli/root/root.go
> +	// Base command
I'll show a demo webpage for this...

2022-04-16 17:05 UTC, alphaX86 commented
Note: The pages needs some work on after review, but as far as concerned except `mesheryctl` page (for now) others are linked with index.

We may also need YAML for index page else it'd get easily lost :)

2022-04-16 17:05 UTC, l5io commented
🚀 Preview for commit ca284b5b7c002bdc725b434842c306f0b8657455 at: https://625af7498c9f153280c0584e--meshery-docs-preview.netlify.app

2022-04-16 17:24 UTC, l5io commented
🚀 Preview for commit 3732ea8508d8c363862fdc6eb999959b3b208040 at: https://625afbc1e76dcd35b5c2e9d1--meshery-docs-preview.netlify.app

2022-04-16 17:27 UTC, alphaX86 commented
> 🚀 Preview for commit [3732ea8](https://github.com/meshery/meshery/commit/3732ea8508d8c363862fdc6eb999959b3b208040) at: [625afbc1e76dcd35b5c2e9d1--meshery-docs-preview.netlify.app](https://625afbc1e76dcd35b5c2e9d1--meshery-docs-preview.netlify.app)

Seems the new created files are not overriding the old ones unlike in local variant...

2022-04-16 17:31 UTC, alphaX86 commented
![image](https://user-images.githubusercontent.com/59508546/163685393-1cfee3a0-604f-41fb-a5c5-b3544210c51a.png)

![image](https://user-images.githubusercontent.com/59508546/163685396-d1757589-91b2-481d-810f-bd9a2cbfe0fc.png)

2022-04-16 17:31 UTC, alphaX86 commented
![image](https://user-images.githubusercontent.com/59508546/163685409-d9ecf9cf-b872-4d3a-9174-e8d2e31c28bb.png)

![image](https://user-images.githubusercontent.com/59508546/163685415-238ef88c-fd75-4610-b95b-1bf3d4bba8b2.png)

2022-04-16 17:32 UTC, alphaX86 commented
I minimized the zoom for better view. The site preview isn't generating the files newly added

2022-04-17 08:40 UTC, l5io commented
🚀 Preview for commit ca0dbf4c675ac6cb16ba3fa8c65e916b3c8735ad at: https://625bd26b37f5c33e788823e1--meshery-docs-preview.netlify.app

2022-04-17 11:02 UTC, l5io commented
🚀 Preview for commit 92a4645e0dbd0b3c967f1dbcfc32cbae09e74b96 at: https://625bf39094cca84ffe0629b2--meshery-docs-preview.netlify.app

2022-04-17 11:12 UTC, l5io commented
🚀 Preview for commit 69a0b700356be24ccc373d29e70e4d3bf54318be at: https://625bf5e5bef9c249919e6724--meshery-docs-preview.netlify.app

2022-04-17 11:22 UTC, alphaX86 commented
Even I removed old site files, it's being redirected to original one :(

2022-04-18 05:14 UTC, piyushsingariya commented
> Even I removed old site files, it's being redirected to original one :(

Yup, not able to check how this looks. PLs fix 😭

2022-04-18 05:23 UTC, alphaX86 commented
😭😭😭

2022-04-18 05:24 UTC, alphaX86 commented
> > Even I removed old site files, it's being redirected to original one :(
> 
> Yup, not able to check how this looks. PLs fix 😭

Could you try looking on local version then? At least for now? :')

2022-04-21 14:20 UTC, l5io commented
🚀 Preview for commit 53d63100477fc97d7b66516888a56e84007ac657 at: https://626167e2a81b4575f085d2b5--meshery-docs-preview.netlify.app

2022-04-21 16:47 UTC, l5io commented
🚀 Preview for commit 4ee37e41dd41284e8c2258caa4eb08913bba779f at: https://62618a4dbae9021df2aada98--meshery-docs-preview.netlify.app

2022-04-21 16:53 UTC, alphaX86 commented
It worked!! 😄

2022-04-21 17:01 UTC, l5io commented
🚀 Preview for commit 02758873afe143fcddc5f91b9c649966949395ce at: https://62618da98fce8e1bcb9d27ca--meshery-docs-preview.netlify.app

2022-04-21 17:10 UTC, l5io commented
🚀 Preview for commit a56a5fe53ff78264d2e53a510a6d5de78dc1b17a at: https://62618fd0c33d211e677773ed--meshery-docs-preview.netlify.app

2022-04-22 02:50 UTC, l5io commented
🚀 Preview for commit 84e33835980188244a83a36ab26d3f896a8ace77 at: https://626217bd9e21ec1392306283--meshery-docs-preview.netlify.app

2022-04-24 09:25 UTC, piyushsingariya commented
@alphaX86 can you pull this off?
https://626217bd9e21ec1392306283--meshery-docs-preview.netlify.app/reference/mesheryctl/system/restart#see-also

Under See Also section.
We include a link to go back to parent command.
We include list of links to other sister commands of the command.
We include list of links to the sub-commands of the command.

2022-04-24 09:30 UTC, piyushsingariya commented
Also I would like you to manually iterate each command's example written in code, add more and elaborated examples, make sure the quality of comments with the examples to be good and understandable.

With that I think we'll be almost at the verge of clearing off this goal from your internship deliverables. 

![image](https://www.icegif.com/wp-content/uploads/yay-icegif-8.gif)

2022-04-24 14:33 UTC, alphaX86 commented
> @alphaX86 can you pull this off? https://626217bd9e21ec1392306283--meshery-docs-preview.netlify.app/reference/mesheryctl/system/restart#see-also
> 
> Under See Also section. We include a link to go back to parent command. We include list of links to other sister commands of the command. We include list of links to the sub-commands of the command.

That's where one issue started, link was able to generate successfully but its being appended so its like ref/mctl/system/context/main etc and so on... Other than that, I need to figure a way

2022-04-24 14:33 UTC, alphaX86 commented
> Also I would like you to manually iterate each command's example written in code, add more and elaborated examples, make sure the quality of comments with the examples to be good and understandable.
> 
> With that I think we'll be almost at the verge of clearing off this goal from your internship deliverables.
> 
> ![image](https://camo.githubusercontent.com/fe6b91adcae0977c564b592c08444369032e66192d67365806bf67d1083e1445/68747470733a2f2f7777772e6963656769662e636f6d2f77702d636f6e74656e742f75706c6f6164732f7961792d6963656769662d382e676966)

So they'd appear in CLI client app as well, is it OK for you to have extended examples in docs?

2022-04-24 15:32 UTC, piyushsingariya commented
With adding examples in the command, I meant a list of commands have outdated examples and very few examples that doesn't cover the complete feature list of the command. So I asked you to make sure we're doing that.

2022-04-25 02:55 UTC, alphaX86 commented
Ok consider it drive

2022-04-28 03:16 UTC, leecalcote commented
Nearly there... good work, @alphaX86

2022-04-28 17:06 UTC, l5io commented
🚀 Preview for commit 8c2f394a6949c33385626f685b15d72bd1e9c1e9 at: https://626ac9754ba81305fec4fa27--meshery-docs-preview.netlify.app

2022-04-29 14:33 UTC, l5io commented
🚀 Preview for commit 7aad98f13a9b1cdd3db6828225a0c9d0b844700d at: https://626bf7157805700d3141c1e2--meshery-docs-preview.netlify.app

2022-04-30 02:34 UTC, leecalcote commented
I didn’t see the GitHub workflow until now. Make sense.

2022-05-08 11:45 UTC, l5io commented
🚀 Preview for commit d75aa32601614758dafa5e0bebcfb94687789135 at: https://6277ad220f4e573a012aa2c0--meshery-docs-preview.netlify.app

2022-05-08 12:05 UTC, l5io commented
🚀 Preview for commit 516688e1bb2934430d5af572ffa3f025a3f783b4 at: https://6277b1db9cbea0432f410177--meshery-docs-preview.netlify.app

2022-05-08 12:09 UTC, alphaX86 commented
Folks, the formatting is now fixed and stable :)

2022-05-08 12:11 UTC, l5io commented
🚀 Preview for commit e287bd51b417b48fe985f3931d3e9aaad4473cc8 at: https://6277b359762cc143cc45043b--meshery-docs-preview.netlify.app

2022-05-09 17:31 UTC, l5io commented
🚀 Preview for commit 4a66f691bec56581adfc70d3a6d5533dea0c22ee at: https://62794fd94d8d51069f06119d--meshery-docs-preview.netlify.app

2022-05-10 14:32 UTC, piyushsingariya submitted a review, later dismissed
LGTM

2022-05-11 03:12 UTC, leecalcote requested changes
Good to go here when `filter` examples are provided, and when autogeneration process is documented. When does this autogeneration occur? Please add to build and release docs section, identifying trigger.

One again, good job on mesheryctl docs, @alphaX86 
Onigger.

2022-05-11 04:35 UTC, alphaX86 commented
Auto generation CI will activate when PR is merged, that is when a user makes any changes to the CLI files.

For the filter subcommands, I'll add the examples today evening and change soon

2022-05-11 15:05 UTC, alphaX86 commented
We got a warning! ⚠️ `cmd/wrk2` seems to be missing and it messes with the docs build! 😨

2022-05-11 15:07 UTC, alphaX86 commented
@leecalcote we need to remove that submodule `cmd/wrk2` to work (since it's not clickable and empty) else it messes the entire docs build...

2022-05-12 15:59 UTC, alphaX86 commented
@warunicorn19 maybe the retrigger of the CI action uses cache of the data previously had :(

So I don't think we can check rerun now, unless if new changes made if I hope

2022-05-13 16:35 UTC, leecalcote commented
Triggering new run of build checks....

2022-05-13 16:38 UTC, l5io commented
🚀 Preview for commit 9bdd18702faa56d1874938073897a21d91ced748 at: https://627e8956891cbd06d638f1e4--meshery-docs-preview.netlify.app

2022-05-13 16:41 UTC, alphaX86 commented
Halt the PR merge... I'll fix the filter table quick

2022-05-13 17:03 UTC, l5io commented
🚀 Preview for commit 7c63bafe764455ec5dec56c81eaf181416d2007f at: https://627e8f3085757e005d487a51--meshery-docs-preview.netlify.app

2022-05-13 17:06 UTC, alphaX86 commented
@warunicorn19 PR now available for final review. Let's tie this off and check CI action as well after merge ;)

2022-05-13 17:07 UTC, leecalcote commented
Formatting issue with anchor. We need a slight change in URL reference for each subcommand
<img width="1080" alt="Screen Shot 2022-05-13 at 12 06 40 PM" src="https://user-images.githubusercontent.com/7570704/168333704-1002b4a4-9d02-425d-b693-ecdd1489c635.png">
.

2022-05-14 15:18 UTC, l5io commented
🚀 Preview for commit 421c85d396d2e974cdcad8ec162522510d8b81f5 at: https://627fc828f8e00e7f943aeb4f--meshery-docs-preview.netlify.app

2022-05-17 14:38 UTC, l5io commented
🚀 Preview for commit f891aac81ca1d816f1953d30af1fcedcdb570a1b at: https://6283b34e0fe4b81ebee5d1dc--meshery-docs-preview.netlify.app

2022-05-18 05:47 UTC, leecalcote commented
Not just Safari, no, but happening in Chrome, too. Try this link: https://6283b34e0fe4b81ebee5d1dc--meshery-docs-preview.netlify.app/reference/mesheryctl/version

2022-05-19 11:42 UTC, alphaX86 commented
Brave:
![image](https://user-images.githubusercontent.com/59508546/169285262-af8c2306-4a69-47df-b9d7-e4bff7266292.png)

Firefox:
![image](https://user-images.githubusercontent.com/59508546/169285282-0fd2694a-8f2f-4e0a-9d3b-47c257e5bf3c.png)

No issues detected, @warunicorn19 any idea you about this?

2022-05-19 14:49 UTC, merged