[Refactor]  UI/restructuring/spinner
meshery/meshery pull request #5565
Opened 2022-06-02 08:16 UTC by YashKamboj

Signed-off-by: Yash Kamboj <yashkamboj29@gmail.com>

**Description**Missing component in the new refactoring ui branch
Conflicted PR #5397 
Previous PR #4828 

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-06-03 13:13 UTC, warunicorn19 requested changes

2022-06-06 18:33 UTC, YashKamboj commented on ui/components/SpinnerLoading/SpinnerLoading.styles.js
> +export const useStyles = makeStyles(() => ({
@warunicorn19 so what should i do, in this case, because we have to change  in all the files

2022-06-06 20:15 UTC, warunicorn19 commented on ui/components/SpinnerLoading/SpinnerLoading.styles.js
> +export const useStyles = makeStyles(() => ({
Use styled-api or css to do this, a lot of the files used styled-api we can change the rest later

2022-06-09 21:10 UTC, leecalcote commented
@YashKamboj how are we taking this one forward?

2022-06-13 19:35 UTC, leecalcote commented
@warunicorn19 good to go?

2022-06-13 19:37 UTC, warunicorn19 requested changes
Let's delete this file if we're not using it. ui/components/SpinnerLoading/SpinnerLoading.styles.js

2022-06-15 12:31 UTC, YashKamboj commented
@warunicorn19 Done!!

2022-06-16 20:44 UTC, merged