Bug fixes
meshery/meshery pull request #5611
Opened 2022-06-13 18:54 UTC by MUzairS15

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-06-13 21:52 UTC, theBeginner86 reviewed
Few things I observed while testing with 2 clusters: `docker-desktop` and `minikube`

- Searching doesn't work on deploy modal

https://user-images.githubusercontent.com/73700530/173449827-5381ff9b-3a1c-4217-a306-3c4aa44ac09e.mov



- If I don't select any cluster then it still deploys the service mesh in some random cluster.

https://user-images.githubusercontent.com/73700530/173449853-dab895b6-e3a1-44cd-b9c1-a4cbf9e95ac5.mov

2022-06-14 02:06 UTC, MUzairS15 commented
@theBeginner86 Searching issue in this PR??

2022-06-14 04:22 UTC, theBeginner86 commented
> @theBeginner86 Searching issue in this PR?? 

@MUzairS15 
Yeah this PR.

2022-06-14 04:58 UTC, MUzairS15 commented
Did you build-ui?? You are on 9081.

2022-06-14 05:19 UTC, theBeginner86 commented
> @theBeginner86 Did you build ui?? You are on 9081.

@MUzairS15 
Yeah I did build the UI but it wasn't working then. 
Could be due to caching issue as now searching does work after rebuilding the UI again 😅

2022-06-14 18:14 UTC, MUzairS15 commented
> LGTM! I think the ConfirmationModal is not working up until yet in Meshery-Extension due to this PR not landed yet! If the rest of comments are resolved, we are fine to merge.

Yes @Abhishek-kumar09 you are right.
@theBeginner86 any more concerns/bugs you encountered??

2022-06-14 18:26 UTC, theBeginner86 approved these changes
LGTM

2022-06-15 14:52 UTC, Abhishek-kumar09 requested changes

2022-06-15 14:52 UTC, Abhishek-kumar09 commented on ui/components/ConfirmationModal.js
> +// }
remove t
```suggestion
```

2022-06-15 15:04 UTC, MUzairS15 commented
@Abhishek-kumar09

2022-06-15 16:40 UTC, Abhishek-kumar09 approved these changes
LGTM

2022-06-15 16:40 UTC, merged