[Docs] Add KubeSphere App Store as a supported platform for Meshery
meshery/meshery pull request #5717
Opened 2022-06-30 20:23 UTC by codrAlxx

Created an entry for the recent addition of Meshery into the KubeSphere App store. 

This PR fixes #5711

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-06-30 20:28 UTC, l5io commented
🚀 Preview for commit bc1292865b763f4f6c791a8e8c9de504c9917e93 at: https://62be0738ec3a3f1235caa550--meshery-docs-preview.netlify.app

2022-07-01 14:40 UTC, karnatisrinivas reviewed
Nice work @codrAlxx 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Efficient

2022-07-01 15:59 UTC, codrAlxx commented
Thanks @karnatisrinivas

2022-07-01 20:31 UTC, l5io commented
🚀 Preview for commit 9efac17a3a50feb3256ef9ce59097027f799030c at: https://62bf5980a2d4272f61d7e679--meshery-docs-preview.netlify.app

2022-07-03 04:56 UTC, l5io commented
🚀 Preview for commit 30e5f5918245d88c85f98789e95e3d35256141cc at: https://62c12151f22cef461eb4223c--meshery-docs-preview.netlify.app

2022-07-04 19:33 UTC, leecalcote requested changes
Thanks for this documentation, @codrAlxx. 👍  Please consider the feedback provided.

2022-07-04 19:33 UTC, leecalcote commented on docs/pages/installation/kubesphere.md
> +- Please make sure you [enable the OpenPitrix system](../../../pluggable-components/app-store/).
This is not a page in Meshery Docs.

2022-07-04 19:33 UTC, leecalcote commented on docs/pages/installation/kubesphere.md
> +- You need to create a workspace, a project, and a user account (`project-regular`) for this tutorial. The account needs to be a platform regular user and to be invited as the project operator with t
Remove URL, please.

2022-07-04 19:33 UTC, leecalcote commented on docs/pages/installation/kubesphere.md
> +    ![meshery-app](/assets/img/platforms/meshery-app.png)
Please include `{{ site.baseurl }}` like:

```suggestion
    ![meshery-app]({{ site.baseurl }}/assets/img/platforms/meshery-app.png)
```

2022-07-04 19:33 UTC, leecalcote commented on docs/pages/installation/kubesphere.md
> +4. For more information about Meshery, refer to [the official documentation of Meshery](https://docs.meshery.io/).
This can be changed to a different instruction and link.

2022-07-04 19:33 UTC, leecalcote commented on docs/pages/installation/platforms.md
> +| &nbsp;&nbsp;&nbsp;<img src="/assets/img/platforms/kubesphere.png" width="20" height="20" /> [Kubesphere]({{ site.baseurl }}/installation/platforms/kubesphere)               |          |
Version is missing.

2022-07-04 19:33 UTC, leecalcote commented on docs/_data/toc.yml
> +          url: installation/platforms/kubesphere
Please list alphabetically.

2022-07-05 05:51 UTC, l5io commented
🚀 Preview for commit c9013b820729afb44f0dd515f30a612f841dda89 at: https://62c3d1374002490d05c891fd--meshery-docs-preview.netlify.app

2022-07-05 07:08 UTC, l5io commented
🚀 Preview for commit e4a785ee14f51c6367f1f0c2625b6f50cd429e35 at: https://62c3e34710ca5a1fa4565eae--meshery-docs-preview.netlify.app

2022-07-05 07:25 UTC, codrAlxx commented
I have updated the changes @leecalcote . Please review it.

2022-07-07 16:28 UTC, merged