Highlight current tab on scroll in table of content in navigation
meshery/meshery pull request #5762
Opened 2022-07-05 23:19 UTC by manikmmalhotra

Signed-off-by: manikmmalhotra <manikmalhotra2113@gmail.com>

**Description**
In the table of navigation, on the right side, the current context is now highlighting while scrolling
![Screenshot from 2022-07-06 04-46-09](https://user-images.githubusercontent.com/63007399/177432157-b4e5d824-4e1f-40db-aea6-b3cdeaef571f.png)
This PR fixes #5525 

**Notes for Reviewers**
Always open for suggestions and improvements. Please point me out if anything should be added/corrected.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-07-05 23:23 UTC, l5io commented
🚀 Preview for commit 926c7f50cb2606ac8b093e176e4107e06877ce0e at: https://62c4c7d7708e253f3c3e4d70--meshery-docs-preview.netlify.app

2022-07-06 19:14 UTC, leecalcote requested changes
Thanks, @manikmmalhotra!

An item that might have gone unnoticed: the last section header never receives highlight. Try clicking on "Related Reading" on this page as an example - https://62c4c7d7708e253f3c3e4d70--meshery-docs-preview.netlify.app/functionality/pattern-management#related-reading

2022-07-06 19:40 UTC, manikmmalhotra commented
> Thanks, @manikmmalhotra!
> 
> An item that might have gone unnoticed: the last section header never receives highlight. Try clicking on "Related Reading" on this page as an example - https://62c4c7d7708e253f3c3e4d70--meshery-docs-preview.netlify.app/functionality/pattern-management#related-reading

@leecalcote i've seen that issue but it was technically correct as the last part never hit the top which normally is the case for refrencing to sidemenu, i would change that i wasn't sure about that so i left that, i will correct that and update this

2022-07-06 19:44 UTC, leecalcote commented
You're right about it being technically accurate, which makes sense to web programmers. Less so to users. Thanks for considering this feedback.

2022-07-06 21:51 UTC, manikmmalhotra commented
> Thanks, @manikmmalhotra!
> 
> An item that might have gone unnoticed: the last section header never receives highlight. Try clicking on "Related Reading" on this page as an example - https://62c4c7d7708e253f3c3e4d70--meshery-docs-preview.netlify.app/functionality/pattern-management#related-reading

@leecalcote fixed the bug for highlighting the last child while scrolling and updated the PR

2022-07-06 21:52 UTC, l5io commented
🚀 Preview for commit e73af77d3056d47b3f2e52ad43c9c46cb0c4037f at: https://62c6040710d0311eddbcad0b--meshery-docs-preview.netlify.app

2022-07-07 09:07 UTC, adithyaakrishna approved these changes

2022-07-07 09:07 UTC, adithyaakrishna commented on docs/_includes/toc.html
> +              $(this).addClass('selected');
Loved the way you have added comments, huge ++ @manikmmalhotra

2022-07-08 20:13 UTC, warunicorn19 reviewed
![Screenshot 2022-07-09 at 1 40 19 AM](https://user-images.githubusercontent.com/53532328/178063735-03842fd8-461b-4b84-9d04-06f9fb5471c8.png)
With the javascript turned off, the table of contents disappears

2022-07-08 21:30 UTC, merged

2022-07-08 21:30 UTC, leecalcote commented
Thanks, @manikmmalhotra! 🎈