[UI] Make UI consistent
meshery/meshery pull request #5765
Opened 2022-07-06 12:00 UTC by MUzairS15

**Description**

This PR 
1. Adds Undeploy in Filters
2. Deployment modal in Grid view
3. Changes for adding Validation support
4. Fix false positive Snackbar, when operation is unsuccessful
**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-07-06 13:21 UTC, leecalcote commented
While the Validation and Deployment modals will be individually available to users, so too, will they be shown together. Perhaps, use the same menu tab style for headings like Environment irrespective of whether Validation is displayed or not. - - reuse the same component.

2022-07-07 20:36 UTC, leecalcote requested changes

2022-07-07 20:36 UTC, leecalcote commented on ui/components/MesheryAdapterPlayComponent.js
> +      console.log(operationName, "PPPPPPPPP", deleteOp, cat);
Remove

2022-07-07 20:36 UTC, leecalcote commented on ui/components/MesheryAdapterPlayComponent.js
> +    console.log("QWERTY", selectedOp);
remove

2022-07-07 20:36 UTC, leecalcote commented on ui/components/MesheryApplications.js
> +    console.log(application_file, "SHAIKH");
remove

2022-07-07 20:36 UTC, leecalcote commented on ui/components/MesheryApplications.js
> +    console.log(typeof (app_file), "SHAIKH");
remove

2022-07-08 04:30 UTC, MUzairS15 commented on ui/components/Filters.js
> +    console.log(filter_file, "QWERTYUZAIR");
O

2022-07-08 04:30 UTC, MUzairS15 commented on ui/components/MesheryAdapterPlayComponent.js
> +      console.log(operationName, "PPPPPPPPP", deleteOp, cat);
O

2022-07-08 04:30 UTC, MUzairS15 commented on ui/components/MesheryAdapterPlayComponent.js
> +    console.log("QWERTY", selectedOp);
P

2022-07-08 04:30 UTC, MUzairS15 commented on ui/components/MesheryApplications.js
> +    console.log(application_file, "SHAIKH");
S

2022-07-08 04:30 UTC, MUzairS15 commented on ui/components/MesheryApplications.js
> +    console.log(typeof (app_file), "SHAIKH");
😅

2022-07-08 04:31 UTC, MUzairS15 commented on ui/components/Filters.js
> +    console.log(filter_file, "QWERTYUZAIR");
done

2022-07-08 17:28 UTC, leecalcote approved these changes
Thanks!

2022-07-08 21:29 UTC, merged