Terminal animation added
meshery/meshery pull request #5821
Opened 2022-07-14 14:15 UTC by sourav-sharma7

Signed-off-by: sourav-sharma7 <souravsharma1321@gmail.com>

**Description**
Animated terminal for meshery docs is added

This PR fixes #734  

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-07-14 14:16 UTC, sourav-sharma7 commented
This PR fixed issue#734 for the meshery.io repository, terminal animation is added.

2022-07-15 11:43 UTC, leecalcote commented
@adithyaakrishna what do you think?

2022-07-19 16:51 UTC, Santosh1176 commented
> @Santosh1176, what do you think?

Looks great. A couple of updates to this could bring more value to the UX.
1. The width of the terminal could be increased to fit in the complete command.
2. Currently, the animation runs on all three terminals at once, while two of them are out of viewport and invisible. If feasible, the animation for the other two terminals could be triggered when those enter the viewport.

2022-07-21 08:57 UTC, sourav-sharma7 commented
@Santosh1176 
Great suggestions will try to implement them as well

2022-07-21 21:56 UTC, leecalcote commented
Thank you, @Santosh1176 👍

2022-07-29 10:25 UTC, l5io commented
🚀 Preview for commit 35796acb7a9c28acc65af59b23e8c0f4a68edd43 at: https://62e3b58992136d73617cfa0a--meshery-docs-preview.netlify.app

2022-08-06 08:26 UTC, adithyaakrishna requested changes
@sourav-sharma7 Could you make the following changes? Once done, I will go ahead and merge this :)

2022-08-06 08:26 UTC, adithyaakrishna commented on docs/assets/js/terminal.js
> +//////array of terminal count
```suggestion
// Array of terminal count
```

2022-08-06 08:26 UTC, adithyaakrishna commented on docs/assets/js/terminal.js
> +/////function to check if element is in view
```suggestion
// Function to check if element is in view
```

2022-08-06 08:26 UTC, adithyaakrishna commented on docs/assets/js/terminal.js
> +         /////scroll eventlistiner for mobile view
```suggestion
         // scroll eventlistiner for mobile view
```

2022-08-06 08:26 UTC, adithyaakrishna commented on docs/assets/js/terminal.js
> +         ////mobile view function
```suggestion
         // mobile view function
```

2022-08-06 08:26 UTC, adithyaakrishna commented on docs/assets/js/terminal.js
> +         ////mobile view function
```suggestion
         // mobile view function
```

2022-08-06 08:26 UTC, adithyaakrishna commented on docs/assets/js/terminal.js
> +         ////mobile view function
```suggestion
         // mobile view function
```

2022-08-06 08:26 UTC, adithyaakrishna commented on docs/assets/js/terminal.js
> +         /////scroll eventlistiner function for window view
```suggestion
         // scroll eventlistiner function for window view
```

2022-08-06 08:30 UTC, adithyaakrishna approved these changes
Added the changes and updated the branch 🚀

2022-08-06 08:33 UTC, l5io commented
🚀 Preview for commit 086e78fbc5c0d9e6d00d8c87dd150aee170950b6 at: https://62ee2718ac35f82737d93a5b--meshery-docs-preview.netlify.app

2022-08-06 08:35 UTC, adithyaakrishna commented
This PR is wrt https://github.com/meshery/meshery.io/issues/734 and https://github.com/meshery/meshery.io/issues/711

2022-08-06 08:36 UTC, merged