[Refactor] Meshery Design Page Card Created
meshery/meshery pull request #5863
Opened 2022-07-21 18:03 UTC by subhradwip01

Signed-off-by: subhradwip01 <subhradwip01@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-07-21 18:15 UTC, YashKamboj requested changes

2022-07-21 18:15 UTC, YashKamboj commented on ui/components/FlipCard/FlipCard.js
> +  const classes=useStyle()
We are not using `useStyles` anymore , please use `styled`

2022-07-22 17:45 UTC, YashKamboj commented on ui/components/FlipCard/FlipCard.style.js
> +}))
@subhradwip01 I think you can move this in the `FlipCard.js`
 as it is not a large styling

2022-07-22 17:52 UTC, YashKamboj commented on ui/components/DesignComponent/MesheryDesignCard.js
> +                src="../../public/static/img/patternwhite.svg"
Just ` /static/img/patternwhite.svg` would work @subhradwip01

2022-07-22 17:54 UTC, chirag0002 reviewed
The code of FlipCard.style.js can be merged in FlipCard.js as it is not a large styling file, also it will become easy to understand the styling of the card if it is present in one file.

2022-07-22 18:20 UTC, YashKamboj requested changes

2022-07-22 18:20 UTC, YashKamboj commented on ui/components/FlipCard/FlipCard.style.js
> +  height:"100%",
@subhradwip01  Remove the height , as this is causing bug in the back side  of the card
![Screenshot (189)](https://user-images.githubusercontent.com/75125203/180500115-df8588a2-1c08-49b7-8309-0b9a383a79f9.png)

2022-07-22 18:20 UTC, YashKamboj commented on ui/components/FlipCard/FlipCard.style.js
> +  height:"100%",
Same, remove height from here too

2022-07-22 18:29 UTC, YashKamboj requested changes

2022-07-22 18:29 UTC, YashKamboj commented on ui/components/FlipCard/FlipCard.style.js
> +export const InnerCard=styled('div')(({flipped,theme})=>({
Use `Paper` here , and remove the background, position, border radius and change the name of InnerCard to CardWrapper

2022-07-22 18:29 UTC, YashKamboj commented on ui/components/FlipCard/FlipCard.style.js
> +      height:"100%",
Also remove the height, as when we flip a card the  height of other cards also increase.

2022-07-22 18:29 UTC, YashKamboj commented on ui/components/FlipCard/FlipCard.js
> +    <Container>
Also remove the `container` as the styles of the container are worthless

2022-07-22 18:29 UTC, YashKamboj commented on ui/components/FlipCard/FlipCard.style.js
> +}))
Remove this component

2022-07-22 19:49 UTC, subhradwip01 commented
Ok...I will change those things according to the review and I will update it by tomorrow morning

2022-07-23 05:10 UTC, YashKamboj requested changes

2022-07-23 05:10 UTC, YashKamboj commented on ui/components/DesignComponent/MesheryDesignCard.js
> +  gap:"10px",
use theme.spacing everywhere

2022-07-23 05:10 UTC, YashKamboj commented on ui/components/DesignComponent/MesheryDesignCard.js
> +              }}
Remove this

2022-07-23 05:39 UTC, YashKamboj approved these changes
LGTM!!! , Great Work

2022-07-23 05:39 UTC, YashKamboj commented
This PR is good to merge 👍

2022-07-23 05:41 UTC, subhradwip01 commented
Resolved all requested changes

2022-07-23 10:51 UTC, YashKamboj commented
@Chadha93 Can we merge this?

2022-08-03 05:25 UTC, YashKamboj commented on ui/components/Patterns/MesheryDesignCard.js
> +  patterns_file : application_file,
remove `application_file` @subhradwip01

2022-08-03 05:28 UTC, subhradwip01 commented on ui/components/Patterns/MesheryDesignCard.js
> +  patterns_file : application_file,
ok

2022-08-03 05:30 UTC, subhradwip01 commented on ui/components/Patterns/MesheryDesignCard.js
> +  patterns_file : application_file,
Check once

2022-08-03 05:32 UTC, YashKamboj approved these changes
LGTM!!! Great Work

2022-08-03 15:56 UTC, merged