[mesheryctl]: change meshery bash script to consider the .tar.gz format
meshery/meshery pull request #5911
Opened 2022-07-29 13:00 UTC by hexxdump

**Description**
Change meshery bash script to consider the .tar.gz format bundle

To avoid the dependency on unzip in the *nix based systems,
goreleaser.yml will publish mesheryctl package bundled in .tar.gz format
rather than in .zip format. For Windows platform, mesheryctl is packaged
in zip format it self
This PR fixes part of #5881 

**Notes for Reviewers**
This commit should go in after PR https://github.com/meshery/meshery/pull/5888 goes in.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.
 Signed-off-by: Hussaina Begum Nandyala <hexxdump@gmail.com>

2022-07-29 13:13 UTC, nishantwrp requested changes
Hi @hexxdump, we should probably remove this block too. 

https://github.com/meshery/meshery/blob/25559fc547f6702ebc7ad040e30a06c880ec198d/meshery#L120-L123

2022-07-29 16:16 UTC, hexxdump commented
> Hi @hexxdump, we should probably remove this block too.
> 
> https://github.com/meshery/meshery/blob/25559fc547f6702ebc7ad040e30a06c880ec198d/meshery#L120-L123

yes, good catch, fixed it

2022-07-30 14:50 UTC, nishantwrp submitted a review, later dismissed
lgtm, thanks for the changes @hexxdump. 

Just one thought, should we have a preflight check for `tar` like we had for `unzip`? Most linux distros have `tar` by default but just in case. What do you think @hexxdump?

2022-07-31 00:30 UTC, hexxdump commented
> lgtm, thanks for the changes @hexxdump.
> 
> Just one thought, should we have a preflight check for `tar` like we had for `unzip`? Most linux distros have `tar` by default but just in case. What do you think @hexxdump?

makes sense @nishantwrp, added the preflight check for tar.

2022-07-31 04:24 UTC, nishantwrp approved these changes
Lgtm

2022-07-31 04:26 UTC, alphaX86 approved these changes
LGTM

2022-08-02 11:54 UTC, leecalcote commented
@AugustasV is this along the lines of what you were thinking? Does this satisfy your deployment scenario?

2022-08-06 09:07 UTC, nishantwrp commented
@leecalcote, i think this pr should be merged too. This updates the mesheryctl installation script to use `tar.gz` artifacts.

2022-08-06 19:44 UTC, leecalcote approved these changes
LGTM

2022-08-06 19:44 UTC, leecalcote commented
Thank you, @hexxdump! 😄

2022-08-06 19:44 UTC, merged