changed System Reset button design
meshery/meshery pull request #6012
Opened 2022-08-11 10:10 UTC by kumarvikramshahi

**Description**
Reverse color (hover color and actual color of button) of System Reset button

This PR fixes #5969 

**Notes for Reviewers**

https://user-images.githubusercontent.com/63746254/184111323-cacbbc68-b250-437d-947c-6dc51edbeab4.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-08-11 17:32 UTC, legendarykamal approved these changes
LGTM congrats on your first PR @kumarvikramshahi :1st_place_medal:

2022-08-11 18:54 UTC, kumarvikramshahi commented
Thank you @legendarykamal .

2022-08-11 19:27 UTC, YashKamboj submitted a review, later dismissed
LGTM!!!

2022-08-11 20:17 UTC, Chadha93 commented
> @kumarvikramshahi Good work, let's use these colors to be consistent for hover and normal state for the button from here [figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=4525%3A26868](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=4525%3A26868) cc @leecalcote

@leecalcote Are these colors for hover and normal state final for the red button across Meshery UI?

2022-08-12 05:31 UTC, leecalcote commented
The red colors are, yes.

<img width="838" alt="Screen Shot 2022-08-12 at 12 30 41 AM" src="https://user-images.githubusercontent.com/7570704/184290780-ac4bd945-706b-4318-bb1d-1684341322d6.png">

2022-08-12 07:20 UTC, Chadha93 requested changes

2022-08-12 07:20 UTC, Chadha93 commented on ui/components/MesherySettings.js
> +    backgroundColor : "#B32700",
```suggestion
    backgroundColor : "#8F1F00",
```

2022-08-12 07:20 UTC, Chadha93 commented on ui/components/MesherySettings.js
> +      backgroundColor : "#dc3545",
```suggestion
      backgroundColor : "#B32700",
```

2022-08-12 07:52 UTC, Chadha93 approved these changes

2022-08-12 07:52 UTC, merged

2022-08-12 07:53 UTC, Chadha93 commented
Yay @kumarvikramshahi 🎈