[UI] Avoiding overlap of anchor with link on search result page
meshery/meshery pull request #6034
Opened 2022-08-14 05:49 UTC by legendarykamal

Signed-off-by: Kamal Nayan <95926324+legendarykamal@users.noreply.github.com>

**Description**

This PR fixes #5917 

**Notes for Reviewers**
![image](https://user-images.githubusercontent.com/95926324/184524284-18206973-3d56-4204-8e27-215ce04e93c7.png)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-08-14 05:53 UTC, l5io commented
🚀 Preview for commit 704cc26b72b9f8f01a0569daccd6efe4aef76833 at: https://62f88dcb6ae19332b8f6dd1b--meshery-docs-preview.netlify.app

2022-08-14 08:58 UTC, Kanika637 commented on docs/assets/css/anchorjs.css
> +    margin-left: -1.6em; /* inorder to avoid overlap with the icon */
A little correction, it should be "-1.6 rem"

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-08-14 08:58 UTC, Kanika637 commented on docs/assets/css/anchorjs.css
> +    margin-left: -1.6em;
It should be "-1.6 rem"

2022-08-15 21:23 UTC, warunicorn19 requested changes
<img width="1334" alt="Screenshot 2022-08-16 at 2 51 46 AM" src="https://user-images.githubusercontent.com/53532328/184720811-09d57b4c-b9f6-4ed6-92c3-db1f6d91a0ef.png">
I can still see the overlap

2022-08-16 10:08 UTC, l5io commented
🚀 Preview for commit 5827685852fdc3fedb289090910684c803e2485b at: https://62fb6c7de701a500759a6175--meshery-docs-preview.netlify.app

2022-08-16 10:09 UTC, legendarykamal commented
@Kanika637 @warunicorn19 I have applied changes in the css file but they are not reflecting back in the docs, am i missing something?
Also I have tried making other simple changes but they too dont get reflected back when i see!

2022-08-17 09:12 UTC, warunicorn19 commented
I'm not too sure, there might be multiple CSS files. You could bring this up on the Meshery Dev call today to discuss if you'd like.

2022-08-26 06:14 UTC, legendarykamal commented
Hey @nishi6verma happy that you are interested 
Go ahead ⏩
Note - If the changes are small, you can request them in this open PR
But If they are more and related to other files, then you can put up a new fresh PR for it.

2022-11-25 16:26 UTC, closed without merging