Filter page
meshery/meshery pull request #6042
Opened 2022-08-16 03:56 UTC by subhradwip01

**Description**

This PR fixes #

**Notes for Reviewers**
Need to test by using data

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-08-16 19:03 UTC, YashKamboj requested changes

2022-08-16 19:03 UTC, YashKamboj commented on ui/components/Filters/MesheryFilterTable.js
> +function MesheryFilterTable({ filters = [], setSelectedRowData, handleModalOpen, user }) {
@subhradwip01 You haven't added page, pagesize etc , i also didn't added it before, have a look at my latest PRs for reference

2022-08-27 18:39 UTC, YashKamboj approved these changes
LGTM!!!

2022-08-28 12:59 UTC, adithyaakrishna approved these changes
LGTM 🎉

2022-08-28 12:59 UTC, merged