[UI] Configurations UI Enhancements | Apps | Designs | Filters
meshery/meshery pull request #6046
Opened 2022-08-16 18:39 UTC by Chadha93

Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>**Description**

This PR fixes #

- [x] Adds source type icon in grid view cards dynamically.
- [x] Adds an icon with a tooltip in the source type column to indicate to the user what action can be performed on icon click—[UX].
- [x] Fixes responsive issue with 3 buttons on designs grid view cards.
- [x] Makes Undeploy and Deploy icon scale to the same ratio.
- [x] Applied standard and hovered state for undeploy red button according to the decided color

**Notes for Reviewers**

https://user-images.githubusercontent.com/65453826/184954013-08a47443-ea08-4c4a-90fd-71b28475d441.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-08-16 18:41 UTC, leecalcote commented
This is looking good. Worth noting that this also brings the grid-based view on par with the table view in terms of functionality.

2022-08-16 18:41 UTC, leecalcote submitted a review, later dismissed

2022-08-16 18:48 UTC, asubedy requested changes
Some typography changes. Rest looks amazing 👍

2022-08-16 18:48 UTC, asubedy commented on ui/components/MesheryApplications.js
> +              <Tooltip title="click source type to download application">
```suggestion
              <Tooltip title="Click source type to download Application">
```

2022-08-16 18:48 UTC, asubedy commented on ui/components/MesheryApplications/ApplicationsCard.js
> +                title="click to download"
```suggestion
                title="Click to Download"
```

2022-08-16 18:48 UTC, asubedy commented on ui/components/MesheryPatterns/MesheryPatternCard.js
> +                title="undeploy"
```suggestion
                title="Undeploy"
```

2022-08-16 18:48 UTC, asubedy commented on ui/components/MesheryPatterns/MesheryPatternCard.js
> +                title="deploy"
```suggestion
                title="Deploy"
```

2022-08-16 18:48 UTC, asubedy commented on ui/components/MesheryPatterns/MesheryPatternCard.js
> +                title="design"
```suggestion
                title="Design"
```

2022-08-16 18:54 UTC, Chadha93 commented on ui/components/MesheryApplications/ApplicationsCard.js
> +                title="click to download"
let's keep this one in lowercase only.

2022-08-16 18:55 UTC, asubedy commented on ui/components/MesheryApplications/ApplicationsCard.js
> +                title="click to download"
"c" of click?

2022-08-17 04:25 UTC, legendarykamal commented
@Chadha93 great work :clap:  
just wanted to ask is that multiple files downloading intentional at 0:14 of the video ?

2022-08-17 09:08 UTC, Chadha93 commented
> @Chadha93 great work clap just wanted to ask is that multiple files downloading intentional at 0:14 of the video ?

@legendarykamal I checked again it's downloading only once. I have pushed more fixes here, feel free to test and report any bugs.

2022-08-17 09:16 UTC, Chadha93 commented
@asubedy @legendarykamal Will you test this pr and try to find and report any bugs if facing?  Do perform all the CRUD operations.
Let's make sure we don't have any bugs left in configurations.

2022-08-17 12:01 UTC, legendarykamal commented
yes Ok I will be testing it out on my local pc today :+1:

2022-08-17 18:40 UTC, merged