[Refactor]-Filter main page
meshery/meshery pull request #6108
Opened 2022-08-27 15:40 UTC by subhradwip01

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-08-27 16:57 UTC, YashKamboj requested changes

2022-08-27 16:57 UTC, YashKamboj commented on ui/components/MesheryFilters.js
> +  function fetchfilters(page, pageSize, search, sortOrder) {
don't make fetchfilters for now  @subhradwip01

2022-09-12 13:52 UTC, Abhishek-kumar09 commented
@subhradwip01 Please post a screenshot...

2022-09-13 06:18 UTC, subhradwip01 commented
> @subhradwip01 Please post a screenshot...

Ok..I will post it by tonight

2022-09-13 06:18 UTC, subhradwip01 commented
> @subhradwip01 Please post a screenshot...

Ok..I will post it by tonight

2022-09-13 20:17 UTC, subhradwip01 commented
![Screenshot from 2022-09-14 01-40-05](https://user-images.githubusercontent.com/88609894/190000639-b7860ed8-cb07-41cb-b7a3-6003e04d07f2.png)
Currently don't have any data..as I am not fetching data from the server..

2022-09-15 19:09 UTC, Abhishek-kumar09 approved these changes
The checkpoint seems Fine

2022-09-15 19:09 UTC, merged