[mesheryctl] improve the error messages shown to users for "mesheryctl"
meshery/meshery pull request #6356
Opened 2022-10-08 22:51 UTC by XDRAGON2002

Signed-off-by: Anant Vijay <anantvijay3@gmail.com>

**Description**

This PR fixes #6265

**Notes for Reviewers**
The error messages have been improved and have been made more user friendly

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-10-11 08:59 UTC, alphaX86 requested changes
PR reviewed. Do the following changes...

Oh and you need to fix the lint issues too @XDRAGON2002

2022-10-11 08:59 UTC, alphaX86 commented on mesheryctl/internal/cli/root/completion.go
> +			return errors.New("shell not supported, requires one of [bash|zsh|fish]")
Could we make it more meaningful? Like....

```suggestion
			return errors.New("shell not supported, requires one of the shells eg:[bash|zsh|fish]")
```

// @harkiratsm @leecalcote

2022-10-13 19:25 UTC, hershd23 reviewed
Mostly LGTM. Don't really have anything to say about the changes. Do fix the linting issues as suggested earlier

2022-10-14 18:52 UTC, XDRAGON2002 commented
> Mostly LGTM. Don't really have anything to say about the changes. Do fix the linting issues as suggested earlier

@hershd23 The linting checks are broken at the moment, see #6385.

2022-10-31 20:33 UTC, leecalcote commented on mesheryctl/internal/cli/root/error.go
> +	return errors.New(ErrUnmarshallingAPIDataCode, errors.Fatal, []string{"Error processing json API data"}, []string{"Error processing json API data", err.Error()}, []string{}, []string{})
More friendly human language. 👍

2022-10-31 20:33 UTC, leecalcote approved these changes
LGTM

2022-11-13 03:31 UTC, legendarykamal commented
Hi @leecalcote, good to merge ? let's do it : or not 

`(ternary operator use ) `

2022-11-18 20:41 UTC, leecalcote commented
Ha! 🙂

2022-11-18 20:41 UTC, merged