Changed size and Removed Extra SVG
meshery/meshery pull request #6375
Opened 2022-10-12 13:13 UTC by Harshit-Dandriyal

Signed-off-by: Harshit Dandriyal <56961488+Harshit-Dandriyal@users.noreply.github.com>**Description**

This PR fixes #
Changed size and Removed Extra SVG
**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-10-12 13:17 UTC, Abhishek-kumar09 approved these changes
LGTM

2022-10-12 13:18 UTC, Abhishek-kumar09 commented
Oh @Harshit-Dandriyal You forgot to add the utf encoding string

2022-10-12 13:19 UTC, Abhishek-kumar09 commented
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg>

ref: https://js.cytoscape.org/#style/background-image

2022-10-13 07:56 UTC, Abhishek-kumar09 approved these changes
LGTM

2022-10-13 08:07 UTC, Abhishek-kumar09 requested changes
The naming convention of svgs are still screwed. Please do the required change in all the places and subsequently make changes in meshery-extensions.
<img width="812" alt="Screenshot 2022-10-13 at 1 29 48 PM" src="https://user-images.githubusercontent.com/48255244/195538914-50b2dd9b-59d3-4fd5-ab8c-4f19d364f923.png">

2022-10-19 05:14 UTC, leecalcote commented
Bump. Poke. Smack.

2022-10-19 10:20 UTC, Harshit-Dandriyal commented
This PR is on little hold as we are on the way to remove the other SVG's here too.

2022-10-19 20:40 UTC, leecalcote commented
> This PR is on little hold as we are on the way to remove the other SVG's here too.

Thanks for confirming. Please update the labels accordingly so that this fact is obvious.

2022-10-21 13:50 UTC, Abhishek-kumar09 commented on install/Makefile.core.mk
> +GOVERSION =
😖

2022-10-21 13:52 UTC, Abhishek-kumar09 commented
@Harshit-Dandriyal is it still `do-not-merge`

2022-10-21 13:58 UTC, Abhishek-kumar09 approved these changes
Looks Good to Me . Thanks @Harshit-Dandriyal Great Job here 🥳

2022-10-21 14:12 UTC, Abhishek-kumar09 approved these changes

2022-10-21 14:13 UTC, merged