Readme, docs: update Meshery logo
meshery/meshery pull request #6441
Opened 2022-10-26 10:04 UTC by tinniaru3005

Signed-off-by: Arunima Chaudhuri <arunimachaudhuri2020@gmail.com>

**Description**
Remove tagline from layer5 and meshery logos
This PR fixes #6216 

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-10-26 14:44 UTC, tinniaru3005 commented
Hey @leecalcote, I made the changes in the README.md. Couldn't find any other place where the logos are used. I didn't delete any of the images as they might be used somewhere in the website. Are any other places where I need to make the changes?

2022-10-28 12:30 UTC, leecalcote requested changes
@tinniaru3005, thank you for this update. I'll supply you with a new community sign. The updated one here has a couple of mistakes.

2022-11-06 09:35 UTC, tinniaru3005 commented
> @tinniaru3005, thank you for this update. I'll supply you with a new community sign. The updated one here has a couple of mistakes.

Hey @leecalcote, is there any update regarding the new community sign

2022-11-24 21:38 UTC, leecalcote approved these changes

2022-11-24 21:38 UTC, merged