Send notifications on Content saving
meshery/meshery pull request #6530
Opened 2022-11-14 18:46 UTC by Revolyssup

Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-11-14 18:48 UTC, leecalcote commented on server/handlers/error.go
> +func ErrSaveApplication(err error) error {
Did you verify that there is the proper error message for unknown components, @Revolyssup?

2022-11-14 18:49 UTC, leecalcote requested changes
The current error message of HTTP 400/500 / Bad request... needs to be made user-friendly.

2022-11-16 04:26 UTC, leecalcote commented
Have error codes been enhanced and notifications sent to Notification Center for Docker Compose uploads, too, @Revolyssup?


<img width="993" alt="Screen Shot 2022-11-15 at 10 16 29 PM" src="https://user-images.githubusercontent.com/7570704/202083495-7e9470ae-2fab-436e-bf11-e3beb1955c41.png">

2022-11-16 07:13 UTC, Revolyssup commented
> Have error codes been enhanced and notifications sent to Notification Center for Docker Compose uploads, too, @Revolyssup?
> 
> <img alt="Screen Shot 2022-11-15 at 10 16 29 PM" width="993" src="https://user-images.githubusercontent.com/7570704/202083495-7e9470ae-2fab-436e-bf11-e3beb1955c41.png">

Yes for all forms of uploads.

2022-11-18 20:33 UTC, leecalcote approved these changes
LGTM

2022-11-18 20:33 UTC, merged