[UI] Icon change for clearing the notification #6560
meshery/meshery pull request #6579
Opened 2022-11-26 09:47 UTC by suhail34

Signed-off-by: suhail34 <suhailkna@gmail.com>

**Notes for Reviewers**

This PR fixes #

Changed the icon for clearing the notification from tick mark to this :
![image](https://user-images.githubusercontent.com/77241166/204082504-ed58b421-474a-46b9-9e3f-8730c406d667.png)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2022-11-26 13:00 UTC, leecalcote commented
Thanks, @suhail34!

2022-11-28 17:14 UTC, leecalcote requested changes
Oh! @suhail34, it should be mentioned that we've recently steered Meshery UI in the direction away from use of FontAwesome and MUI icon libraries. Instead, to ensure all icons scale on zoom in/zoom out, Meshery UI is transitioning to only use SVGs directly. Please see this PR as an example - https://github.com/meshery/meshery/pull/6578. In light of this, will you you refactor this PR?

2022-12-02 21:30 UTC, leecalcote approved these changes

2022-12-02 22:01 UTC, Harshit-Dandriyal requested changes
@suhail34 I appreciate your efforts, but I think you missed here a little :pinching_hand: 

https://user-images.githubusercontent.com/56961488/205397318-e287c0c6-5427-44b8-b3a2-83ca0c6e33a7.mp4

2022-12-03 14:00 UTC, asubedy requested changes
Missed to remove console log here

2022-12-03 14:00 UTC, asubedy commented on ui/components/MesheryNotification.js
> +                          console.log(e.target.style.fill)
```suggestion

```

2022-12-03 14:06 UTC, leecalcote commented
Suggestion merged, @asubedy 👍

2022-12-03 14:11 UTC, asubedy commented
Thank you @leecalcote, the changes looks good here to merge. The video posted by @Harshit-Dandriyal, is not visible though.

2022-12-03 14:13 UTC, Harshit-Dandriyal commented
> Thank you @leecalcote, the changes looks good here to merge. The video posted by @Harshit-Dandriyal, is not visible though.
> 

I think safari does not support mp4, because it is showing in my chrome. Let me do something here.

2022-12-03 14:14 UTC, Harshit-Dandriyal commented
> I've previously informed @Harshit-Dandriyal that his video recordings are not visible in Safari. Hopefully, @Harshit-Dandriyal will change encoding or change recorders so that others can freely collaborate with him. Otherwise, I won't be watching his videos either, I'm afraid.

I am starting to find other recorder then. 👍

2022-12-04 14:42 UTC, suhail34 commented
Thanks for pointing out I didn't noticed that Is this Ok

https://user-images.githubusercontent.com/77241166/205497082-315b6626-c44d-49b7-9f7b-1c59a2a8aa1f.mp4

2022-12-05 20:41 UTC, Harshit-Dandriyal commented
LGTM, Nice work @suhail34

2022-12-05 20:42 UTC, Harshit-Dandriyal approved these changes

2022-12-06 08:10 UTC, asubedy approved these changes
LGTM, too 👍

2022-12-09 07:22 UTC, Chadha93 submitted a review, later dismissed
LGTM, Let's get you covered on DCO. :wink:

2022-12-09 07:25 UTC, Chadha93 commented
Merge conflicts.... @suhail34

2022-12-10 05:31 UTC, suhail34 commented
> LGTM, Let's get you covered on DCO. wink

will this command get my all commits signed off
`git rebase HEAD~8 --signoff`

2022-12-12 19:17 UTC, Chadha93 commented
> > LGTM, Let's get you covered on DCO. wink
> 
> will this command get my all commits signed off `git rebase HEAD~8 --signoff`

Yes, this should.

2022-12-12 19:20 UTC, Chadha93 requested changes
@suhail34 The `package` changes and `go.sum` are not required. You can revert those, then we are good to go with this PR.

2022-12-14 11:17 UTC, suhail34 commented
I didn't made any changes in those file How do i revert

2022-12-15 19:10 UTC, Chadha93 commented
> I didn't made any changes in those file How do i revert

@sahilsuman933 You can compare the changes with the current file and revert or simply create a new PR. Don't worry about the DCO. We will get you covered on it.

2022-12-17 09:36 UTC, Chadha93 approved these changes
LGTM. Thank you @suhail34

2022-12-17 09:36 UTC, merged

2022-12-17 09:37 UTC, Chadha93 commented
Yay @suhail34 :balloon:

2022-12-17 11:39 UTC, suhail34 commented
Thanks for guiding learned a lot