[WIP] Add Support To Logout Remote Provider Session
meshery/meshery pull request #6580
Opened 2022-11-26 14:58 UTC by theBeginner86

Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>

**Notes for Reviewers**

This PR fixes # https://github.com/meshery/meshery/issues/6503

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-11-26 22:44 UTC, theBeginner86 commented
Demo:


https://user-images.githubusercontent.com/73700530/204111491-8394af7c-02a5-4c13-9455-36a01828223e.mov

2022-11-26 22:52 UTC, theBeginner86 commented
**Remaining Items:**

- [ ] Handle Errors more promptly
- [ ] Use better error messages. 
- [ ] Avoid Error status code 500

2022-11-28 17:18 UTC, leecalcote requested changes
This is a well-documented behavior update. Will you consider moving to generic terms / variable names given this update lands inside of an extension point?

2022-11-28 17:19 UTC, leecalcote commented on server/models/remote_provider.go
> +	// considering not every endpoint in remote provider requires it
I ❤️ these comments.

2022-12-03 20:55 UTC, leecalcote commented
A related issue to note - https://github.com/meshery/meshery/pull/6623/checks?check_run_id=9862028249

2022-12-09 22:30 UTC, leecalcote approved these changes

2022-12-09 22:30 UTC, merged