workflow to update discussions data files added
meshery/meshery pull request #6792
Opened 2022-12-27 06:23 UTC by deepakdinesh1123

Signed-off-by: deepakdinesh1123 <d.deepakdinesh13@gmail.com>

**Notes for Reviewers**

This PR fixes #6774
@leecalcote please review this PR and tell me any changes that I need to make to my approach

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-12-27 18:55 UTC, Chadha93 commented
@deepakdinesh1123  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2022-12-27 20:14 UTC, leecalcote commented
> @deepakdinesh1123 Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

That would be great.

2022-12-27 20:16 UTC, leecalcote commented on .github/workflows/discussions-data-files-update.yml
> +        run: curl https://discuss.layer5.io/tag/meshery.json > docs/_data/discuss/meshery.json
I wonder if `-o` as the `curl` native flag is perhaps ideal vs. `>`

2022-12-27 20:17 UTC, leecalcote commented on .github/workflows/discussions-data-files-update.yml
> +          git config user.email "discussions_bot@github.com"
```suggestion
          git config user.email "discussions@meshery.io"
```

2022-12-27 20:19 UTC, leecalcote requested changes
I have a hunch that we'll ultimately need to leverage something like this autocommit action ([example use](https://github.com/meshery/meshery/blob/8ff11b8cb5659bd3842424d2df6cbbf1e6232af6/.github/workflows/integrations-updater.yml#L36-L44)) in order to ensure that the `git` operation is empowered with the appropriate level of permissions to `git push` and override the `master` branch protections.

2022-12-27 20:19 UTC, leecalcote commented
Some good stuff here, @deepakdinesh1123. Thank you.

2022-12-30 23:06 UTC, leecalcote commented
@deepakdinesh1123 does this feedback make sense?

2022-12-31 05:03 UTC, deepakdinesh1123 commented
@leecalcote I am sorry as I could not update this as I had some uni work and exams I will incorporate the suggested changes by Monday

2023-01-03 11:53 UTC, closed without merging

2023-01-03 22:02 UTC, leecalcote commented
> @leecalcote I am sorry as I could not update this as I had some uni work and exams I will incorporate the suggested changes by Monday

Understood. Did you end up opening a new PR?

2023-01-04 05:19 UTC, deepakdinesh1123 commented
@leecalcote I have opened a new PR #6832 as I did a mistake when syncing new changes