Update error message for `mesheryctl system start`
meshery/meshery pull request #6794
Opened 2022-12-27 19:45 UTC by rakshitgondwal

**Notes for Reviewers**
- Updated the error message when the user provides some other platform in `mesheryctl system start --platform`.
- Updated the error message `mesheryctl system start --skip-reset`

This PR fixes #6267 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-12-27 19:54 UTC, rakshitgondwal commented
@leecalcote 
- I could not locate the use `--skip-browser` flag function in `start.go`.
- I made an observation that if a user gives the command `mesheryctl system start --platform` without giving an args to the command, it just shows an error stating that `Err: flag needs an argument`. I tried to solve this by creating a new function inside of `system/error.go`, but I was getting an error, so I'll need a little of guidance over there.
- If a user enters a command say `mesheryctl system start --platform dokcer` and the user has misspelled the word `docker` as `dokcer`, then rather then showing him/her the command unavailable error, we can show him a misspell command error. What do you think?

2022-12-27 20:22 UTC, leecalcote commented
@gopivaibhav it'd be good of you to offer review.

2022-12-28 15:58 UTC, alphaX86 requested changes

2022-12-28 15:58 UTC, alphaX86 commented on mesheryctl/internal/cli/root/system/error.go
> +	return errors.New(ErrUnsupportedPlatformCode, errors.Alert, []string{}, []string{"The platform ", platform, " is not supported for the deployement of Meshery. Supported platforms are:\n\n- docker\n-
```suggestion
	return errors.New(ErrUnsupportedPlatformCode, errors.Alert, []string{}, []string{"The platform ", platform, " is not supported for the deployment of Meshery. Supported platforms are:\n\n- docker\n- kubernetes\n\nVerify this setting in your meshconfig at ", config, " or verify by executing `mesheryctl system context view`"}, []string{}, []string{})
```

2022-12-28 15:58 UTC, alphaX86 commented on mesheryctl/internal/cli/root/system/error.go
> +	return errors.New(ErrResetMeshconfigCode, errors.Alert, []string{"Error resetting meshconfig to default settings"}, []string{err.Error()}, []string{"Meshery server config file is not reset to defaul
This one seems ok to me...

2022-12-28 17:31 UTC, rakshitgondwal commented on mesheryctl/internal/cli/root/system/error.go
> +	return errors.New(ErrUnsupportedPlatformCode, errors.Alert, []string{}, []string{"The platform ", platform, " is not supported for the deployement of Meshery. Supported platforms are:\n\n- docker\n-
Done!

2022-12-28 17:31 UTC, rakshitgondwal commented
> @leecalcote
> 
> * I could not locate the use `--skip-browser` flag function in `start.go`.
> * I made an observation that if a user gives the command `mesheryctl system start --platform` without giving an args to the command, it just shows an error stating that `Err: flag needs an argument`. I tried to solve this by creating a new function inside of `system/error.go`, but I was getting an error, so I'll need a little of guidance over there.
> * If a user enters a command say `mesheryctl system start --platform dokcer` and the user has misspelled the word `docker` as `dokcer`, then rather then showing him/her the command unavailable error, we can show him a misspell command error. What do you think?

Any views on this? @alphaX86

2022-12-28 17:58 UTC, leecalcote commented
> If a user enters a command say mesheryctl system start --platform dokcer and the user has misspelled the word docker as dokcer, then rather then showing him/her the command unavailable error, we can show him a misspell command error. What do you think?

Through use of a library, ideally, one with first-class integration into cobra, yes (as a separate issue to open, solution to research, and proposal to make).

2023-01-05 07:45 UTC, leecalcote commented
@abdullah1308 will you lay your eyes on this PR and give it a review?

2023-01-11 06:48 UTC, abdullah1308 commented
> 
> * I could not locate the use `--skip-browser` flag function in `start.go`.
> * I made an observation that if a user gives the command `mesheryctl system start --platform` without giving an args to the command, it just shows an error stating that `Err: flag needs an argument`. I tried to solve this by creating a new function inside of `system/error.go`, but I was getting an error, so I'll need a little of guidance over there.
> * If a user enters a command say `mesheryctl system start --platform dokcer` and the user has misspelled the word `docker` as `dokcer`, then rather then showing him/her the command unavailable error, we can show him a misspell command error. What do you think?

@rakshitgondwal 

* It is required that you sign your commits when contributing to Meshery as per the [contributing guidelines](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin). You may refer [here](https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits) to sign previous commits.

* The `--skip-browser` flag is implemented here 
https://github.com/meshery/meshery/blob/d601d13acb3793f77592cdba5175528c56e4f758/mesheryctl/internal/cli/root/system/dashboard.go#L204-L212

* The message `Error: flag needs an argument: --platform` is returned by the cobra library and is self explanatory. You need not override it.

2023-01-12 16:35 UTC, rakshitgondwal commented
Thank you for the review! @abdullah1308 
I'll look for the changes in `--skip-browser` asap. Also, I did sign my commits. Please let me know if I did it in the wrong way or is there any other issue.

2023-01-12 19:54 UTC, abdullah1308 commented
> Thank you for the review! @abdullah1308 I'll look for the changes in `--skip-browser` asap. Also, I did sign my commits. Please let me know if I did it in the wrong way or is there any other issue.

@rakshitgondwal Did you use the `-s`  or `--signoff` flag to do so ? I think you haven't. Your commit messages have the following sign-off -

`Signed-off-by: Rakshit Gondwal rakshitgondwal3@gmail.com`

This sign-off would pass the DCO check -

`Signed-off-by: Rakshit Gondwal <rakshitgondwal3@gmail.com>`

2023-01-13 06:37 UTC, leecalcote commented
Adding to @abdullah1308's excellent notes:

In your local branch:

```
git rebase HEAD~3 --signoff
git push --force-with-lease origin dev1
```

2023-01-15 14:08 UTC, rakshitgondwal commented
Thanks a lot for the update @leecalcote @abdullah1308. I am so sorry, I am not being able to work on this as I'm travelling right now. I'll complete this as soon as I reach home.

2023-01-16 14:06 UTC, rakshitgondwal commented
@leecalcote Sorry for the tag but can you please review this?

2023-01-16 14:52 UTC, leecalcote approved these changes

2023-01-16 14:52 UTC, merged

2023-01-16 14:52 UTC, leecalcote commented
Three verbiage improvements approved. Those look good, @rakshitgondwal 👍

2023-01-16 14:56 UTC, rakshitgondwal commented
Thanks a lot for the merge! @leecalcote