[General] Just replaced the code for deleting an application with an …
meshery/meshery pull request #6800
Opened 2022-12-28 13:55 UTC by partik03

…already existing function

Signed-off-by: Partik SIngh <partik.sbumrah.cse21@itbhu.ac.in>

**Notes for Reviewers**

This PR fixes N.A

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-12-28 13:56 UTC, partik03 commented
@leecalcote @Chadha93 Please review this pr

2022-12-30 10:32 UTC, Abhishek-kumar09 submitted a review, later dismissed
Looks Good to Me

2022-12-30 13:48 UTC, Chadha93 commented on ui/components/MesheryApplications.js
> +          enqueueSnackbar(`"${name}" Application Updated Successfully`, {
```suggestion
          enqueueSnackbar(`"${name}" Application Updated`, {
```

2022-12-30 13:50 UTC, Chadha93 commented on ui/components/MesheryApplications.js
> +          enqueueSnackbar(`"${name}" Application Updated Successfully`, {
Please don't use "successfully" in the snackbar messages, please also update the delete snackbar, it should show the app name when deleted. It was there previously.

2023-01-02 02:32 UTC, leecalcote requested changes

2023-01-02 02:32 UTC, leecalcote commented on ui/components/Header.js
> +  console.log(anchorEl);
Please remove this line.

2023-01-02 02:32 UTC, leecalcote commented on ui/components/Header.js
> +  console.log(anchorEl);
```suggestion
```

2023-01-02 02:32 UTC, merged