remove deprecated targets from meshery makefile
meshery/meshery pull request #6810
Opened 2022-12-29 14:56 UTC by ayushthe1

Signed-off-by: ayush_gitk <ayushsharmaa101@gmail.com>

**Notes for Reviewers**
This pr intends on removing all the deprecated targets from this [makefile](https://github.com/meshery/meshery/blob/master/Makefile)

This PR fixes #6685 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2022-12-29 15:01 UTC, l5io commented
🚀 Preview for commit 06eac107d985e4c40944ee4040a5dfd1f96212a3 at: https://63adab6d6f72c13f0d95e847--meshery-docs-preview.netlify.app

2022-12-29 19:05 UTC, leecalcote commented on docs/v0.5/search/index.html
> +						"content": "As a new contributor, you’re going to want to familiarize with the project in order to resolve the issues in the best way. Installing and playing around with Meshery will give you c
@ayushthe1 will you undo this change to this old Meshery version's docs?

2022-12-29 19:07 UTC, leecalcote requested changes
Thanks, @ayushthe1! 

Will you search the entire code base for other stale references to these commands, like this one - https://github.com/meshery/meshery/blob/3a5bea9afdc1273b5dfb95af4268b8dbfbd5e8bc/CONTRIBUTING.md#L250?

2022-12-29 19:07 UTC, leecalcote commented
@Anand-Theertha it'd be good to get your eyes on this.

2022-12-30 07:39 UTC, Anand-Theertha commented
Hey @ayushthe1! Like I said, there are changes to be made in the readme.md file and contributing.md file. I could probably pull another PR for that, or we can connect on Slack to talk about these changes so you can modify the current PR.

2022-12-30 07:58 UTC, ayushthe1 commented
great @Anand-Theertha ,let's connect on slack and discuss this further. I will ping you today once i'm back home.

2023-01-05 07:44 UTC, leecalcote commented
Send word when docs references have been accounted for.

2023-01-06 12:08 UTC, Anand-Theertha commented
Yes @leecalcote, @ayushthe1 and I spoke about the changes in docs. It'll be visible after this PR is updated with the new changes.

2023-01-06 15:35 UTC, ayushthe1 commented
hey @Anand-Theertha ,i made some changes to the pr. Could you please review it.

2023-01-06 15:35 UTC, l5io commented
🚀 Preview for commit accec28987c099be69b269bd464103ea09b29738 at: https://63b83f74da155f091f12283e--meshery-docs-preview.netlify.app

2023-01-06 15:38 UTC, leecalcote commented on .github/workflows/build-ui-server-reusable-workflow.yml
> -          make build-meshery-ui
Good job on catching the changes needed in the workflows, too. 👍

2023-01-10 13:29 UTC, Nikhil-Ladha approved these changes

2023-01-10 18:34 UTC, Chadha93 commented
@ayushthe1  Let's discuss the update of this PR on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-01-12 03:38 UTC, leecalcote approved these changes
Thank you, @ayushthe1!

2023-01-12 03:39 UTC, merged