Improve mesheryctl pattern list error message.
meshery/meshery pull request #6851
Opened 2023-01-09 16:20 UTC by Ebi27

**Notes for Reviewers**

This PR fixes the mesheryctl pattern list error response from ;

Error: Get "http://localhost:9081/api/pattern": dial tcp [::1]:9081: connect: connection refused

To
Error: Unable to reach MESHERY server at %s. Verify your environment's readiness for a MESHERY deployment by running `mesheryctl system check`

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-01-12 04:30 UTC, leecalcote requested changes
Thanks, @Ebi27. Will you sync your fork/clone/branch in order to ensure that only files that you've changed show in this PR? Find instructions here - https://github.com/meshery/meshery/blob/master/docs/CONTRIBUTING-gitflow.md

2023-01-12 04:31 UTC, leecalcote requested changes

2023-01-12 04:31 UTC, leecalcote commented on mesheryctl/internal/cli/root/pattern/list.go
> +			return errors.Errorf("Unable to reach MESHERY server at %s. Verify your environment's readiness for a MESHERY deployment by running `mesheryctl system check`. ", mctlCfg.GetBaseMesheryURL())
Only capitalize "M" in Meshery, please.

2023-01-12 19:48 UTC, Ebi27 commented on mesheryctl/internal/cli/root/pattern/list.go
> +			return errors.Errorf("Unable to reach MESHERY server at %s. Verify your environment's readiness for a MESHERY deployment by running `mesheryctl system check`. ", mctlCfg.GetBaseMesheryURL())
okay, on it.

2023-01-13 17:25 UTC, leecalcote commented
You'll also need to sign your commits - https://github.com/meshery/meshery/pull/6851/checks?check_run_id=10620373572

2023-01-16 14:53 UTC, closed without merging