[Doc] - Meshery installation documentation update
meshery/meshery pull request #6857
Opened 2023-01-09 22:32 UTC by gurpreet-legend

Signed-off-by: Gurpreet Singh <lostlegend2701@gmail.com>

Updated the installation troubleshooting documentation as per the discussion in #6621 

This PR fixes #6629 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-01-09 22:40 UTC, gurpreet-legend commented
@meshery/meshery-docs-contributors, can someone review this?

2023-01-09 22:40 UTC, l5io commented
🚀 Preview for commit 0b659c10da3756e5915596bb10d0669e9f246c13 at: https://63bc97aa5546a2054e823e74--meshery-docs-preview.netlify.app

2023-01-10 05:44 UTC, leecalcote requested changes
Thanks, @gurpreet-legend. Will you undo changes to the older version(s) of the docs, leaving changes only to the current / latest version?

2023-01-10 05:44 UTC, leecalcote commented on docs/pages/reference/troubleshooting/installation.md
> +3. For `kind`, I prefer installing MetalLB with a custom configmap.
Let's avoid first-person statements in Meshery Docs, using active voice instead; e.g. "You can install MetalLB with a custom ConfigMap".

2023-01-10 05:44 UTC, leecalcote commented on docs/pages/reference/troubleshooting/installation.md
> +    A more simple way to resolve this issue can be `port-forwarding`. Run the following command in terminal:
"more simple" change to "simpler"

2023-01-10 05:45 UTC, leecalcote commented on docs/pages/reference/troubleshooting/installation.md
> +The difficulty with Minikube and Kind clusters is that they typically don't have a loadbalancer, whereas Meshery gives its users complete control over how networking is configured. As a result, netwo
If "loadbalancer" in this sense refers to the Kubernetes construct, please capitalize the "L" and "B".

2023-01-10 05:46 UTC, leecalcote commented on docs/v0.5/guides/troubleshooting/installation.html
> +    <p>Use the MetalLB minikube add-on that provides load balancing.<code class="language-plaintext highlighter-rouge">minikube addons enable metallb</code></p>
Please capitalize the "M" in Minikube

2023-01-10 05:46 UTC, leecalcote commented on docs/v0.5/guides/troubleshooting/installation.html
> +    <p>Use the MetalLB minikube add-on that provides load balancing.<code class="language-plaintext highlighter-rouge">minikube addons enable metallb</code></p>
...for all instances of Minikube that are not CLI references

2023-01-10 06:24 UTC, gurpreet-legend commented
@leecalcote , all the required changes are done.

2023-01-10 06:25 UTC, l5io commented
🚀 Preview for commit e30590abe334342b16e3365814b38f10a103abbf at: https://63bd049fcf0769583d01886b--meshery-docs-preview.netlify.app

2023-01-10 18:56 UTC, gurpreet-legend commented
> 

@Chadha93, sure will discuss this at the meet then :)

2023-01-12 04:24 UTC, leecalcote reviewed
Excellent.

2023-01-12 04:24 UTC, leecalcote commented on docs/pages/reference/troubleshooting/installation.md
> +The difficulty with Minikube and Kind clusters is that they typically don't have a LoadBalancer, whereas Meshery gives its users complete control over how networking is configured. As a result, netwo
```suggestion
The difficulty with Minikube and Kind clusters is that they typically don't support LoadBalancer service networking by default. Meshery UI and Meshery Broker are configured for LoadBalancer service networking by default. There are a number of solutions this overcoming this challenge. Here are a few methods:
```

2023-01-12 04:25 UTC, leecalcote approved these changes
Tweaked the language a little.

LGTM 👍

2023-01-12 04:25 UTC, merged