Removed inconsistency in navigator
meshery/meshery pull request #6867
Opened 2023-01-11 12:20 UTC by hs05june

**Notes for Reviewers**

This PR fixes #6860 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 

https://user-images.githubusercontent.com/103871275/211804769-fa984c31-c8d4-4f0f-8380-da2c93a89270.mp4

2023-01-12 04:27 UTC, leecalcote commented
@hs05june commits from @Abhishek-kumar09 and @sudo-NithishKarthik are included in this PR by accident, I assume. Will you sync your fork/clone with `head` in order to ensure that only your commits are included?

2023-01-12 10:31 UTC, Harshit-Dandriyal requested changes
Everything looks cool except the traefikMesh naming. nice work..!

2023-01-12 10:31 UTC, Harshit-Dandriyal commented on ui/assets/icons/LifecycleIcons/TraekFileIcon.js
> +const TraekFileIcon = (props) => {
Can you rename it, TraefikMeshIcon

2023-01-12 11:00 UTC, hs05june commented on ui/assets/icons/LifecycleIcons/TraekFileIcon.js
> +const TraekFileIcon = (props) => {
Done @Harshit-Dandriyal

2023-01-12 13:07 UTC, Harshit-Dandriyal approved these changes

2023-01-13 12:37 UTC, Abhishek-kumar09 reviewed
I think this is not the approach we would go for. I know that you've been seeing some other SVGs like this, but in the last dev call we discussed to remove those svgs as they were written.

Additonally, https://docs.meshery.io/project/contributing/contributing-ui#static-files-and-icons has the norm that svg files should be written with ".svg" extension and should follow certain conventions. We dont want react components for svg file unless very required. 

As you know, the colors, height width, and other things can be configured using [this approach](https://stackoverflow.com/a/62532186). Would you like to give it a try?

2023-01-13 23:06 UTC, hs05june commented
@Abhishek-kumar09 I will be trying it that way

2023-01-16 09:22 UTC, hs05june commented
@Abhishek-kumar09 I tried the approach suggested by you. But it could set only the attributes of the svg tag.
![Code Image](https://user-images.githubusercontent.com/103871275/212640913-110e185f-c418-4dad-a064-24b01c3078b0.png)
To ensure that the icons have correct color, I have also changed the attributes of the path, polygon and g tag. It wasn't working properly.

2023-01-18 10:12 UTC, hs05june commented
@Abhishek-kumar09 please suggest any other approach

2023-01-27 23:38 UTC, leecalcote commented
Uh-oh. Some merge conflicts have cropped up.

2023-02-02 05:03 UTC, leecalcote commented
@hs05june will you be attending to these conflicts?

2023-02-21 01:36 UTC, leecalcote commented
Merge conflicts...

2023-02-21 19:45 UTC, hs05june commented
@leecalcote  Yeah looking into them.

2023-02-23 00:31 UTC, leecalcote commented
Circling back to review. Still merge conflicts.

2023-02-23 09:20 UTC, closed without merging

2023-02-23 09:28 UTC, hs05june commented
Hey @leecalcote . I had a word with @Abhishek-kumar09. He suggested me another better approach to solve this issue. I am closing this PR. I will be making another PR for this issue using what @Abhishek-kumar09 has suggested.

2023-02-23 13:33 UTC, leecalcote commented
Ok. Understood.