improved error message for system cmd - config, logs
meshery/meshery pull request #6930
Opened 2023-01-25 10:36 UTC by kernelpanic77

Signed-off-by: kernelpanic77 <shanware.ishan@gmail.com>

**Notes for Reviewers**

This PR fixes #6266 

Added user friendly messages for the following system subcommands:
- [x] config
- [x] logs

I am improving the error messages for dashboard, login, logout and token. Will add more commits to the same PR. Please provide feedback for config and logs subcommands.

Suggestions in cobra does not seem to work for sub sub commands.  For instance, 
running
```
mesheryctl pattern aply  
```
does not suggest "did you mean ? apply".
 
**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-01-25 12:10 UTC, Chadha93 commented
@kernelpanic77  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-01-25 16:52 UTC, leecalcote commented
@abdullah1308 will you review?

2023-01-25 17:07 UTC, alphaX86 requested changes

2023-01-25 17:07 UTC, alphaX86 commented on mesheryctl/internal/cli/root/system/config.go
> +			return fmt.Errorf("Expected one argument recieved multiple arguments")
```suggestion
			return fmt.Errorf("Expected one argument received multiple arguments")
```

2023-01-25 17:21 UTC, alphaX86 requested changes

2023-01-25 17:21 UTC, alphaX86 commented on mesheryctl/internal/cli/root/system/config.go
> +			return fmt.Errorf("Expected one argument received multiple arguments")
```suggestion
			return fmt.Errorf("expected one argument received multiple arguments")
```

2023-01-26 10:39 UTC, abdullah1308 commented
LGTM

2023-01-26 12:57 UTC, alphaX86 submitted a review, later dismissed
LGTM

2023-01-26 19:05 UTC, leecalcote reviewed
Thanks, @kernelpanic77. 👍

2023-01-26 19:05 UTC, leecalcote commented on mesheryctl/pkg/utils/platform.go
> +			return nil, fmt.Errorf("pod \"%s\" specified, does not exist in the 'meshery' namespace. Please  Run mesheryctl `system status` to view the available pods", sp)
```suggestion
			return nil, fmt.Errorf("pod \"%s\" specified, does not exist in the 'meshery' namespace. Please  Run `mesheryctl system status` to view the available pods", sp)
```

2023-01-26 19:05 UTC, leecalcote commented on mesheryctl/internal/cli/root/system/config.go
> +			return fmt.Errorf("name of kubernetes cluster to configure meshery not provided\n\n%v", errMsg)
```suggestion
			return fmt.Errorf("name of kubernetes cluster to configure Meshery not provided\n\n%v", errMsg)
```

Always capitalize Meshery.

2023-01-26 19:05 UTC, leecalcote approved these changes

2023-01-26 19:06 UTC, merged