[WIP] Fix issues with loading User Account Extension
meshery/meshery pull request #7153
Opened 2023-02-22 14:42 UTC by theBeginner86

**Notes for Reviewers**

This PR addresses issues with loading user account extension in Meshery UI.

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-02-22 14:45 UTC, leecalcote commented
Curious: what is `type` is used for?

2023-02-22 14:45 UTC, leecalcote requested changes
Is there an update to the https://docs.meshery.io/extensibility/providers#ui-extension-points to accompany this?

2023-02-22 14:48 UTC, theBeginner86 commented
> Curious: what is `type` is used for?

`type` means the type of remote extension.
Could be:
1. Navigator
2. Account
3. Graphql
4. User Prefs.

2023-02-22 14:48 UTC, theBeginner86 commented
> This PR is not complete yet. I've just fixed one of the two issues I identified. Will explain more in today's dev call.

2023-02-24 20:22 UTC, leecalcote commented
> > Curious: what is `type` is used for?
> 
> `type` means the type of remote extension. Used to determine what `type` of extension to render onto Meshery UI. Could be:
> 
> 1. Navigator
> 2. Account
> 3. Graphql
> 4. User Prefs.

Aha! But, of course. Thank you.

Is this PR still `do-not-merge`?

2023-02-25 16:44 UTC, theBeginner86 commented on ui/pages/extension/[...component].js
> +    // For no restricted, we will show extensions
```suggestion
    // For unrestricted access, show extensions
```

2023-02-25 16:57 UTC, theBeginner86 commented
Ready

<details>
<summary>demo</summary>
<br>


https://user-images.githubusercontent.com/73700530/221369545-a2fda520-8ee6-4727-9304-81fee0c03a18.mov



</details>

2023-02-25 17:02 UTC, theBeginner86 commented on ui/pages/extension/[...component].js
> +      console.log("inside if")
```suggestion

```

2023-02-28 23:51 UTC, merged