Allow env variable to disable operator in Meshery instance
meshery/meshery pull request #7222
Opened 2023-02-28 13:54 UTC by Revolyssup

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-02-28 14:19 UTC, leecalcote requested changes
Contributor and User documentation is missing.

2023-02-28 18:30 UTC, leecalcote commented
@Azanul you may well want to add some thoughts here.

2023-02-28 19:38 UTC, Azanul commented
The variable and method names seem confusing to me. Names like `OPERATOR_STATUS`, `SetOperatorStatus` seem to fit better. At least `Deploy`/`Undeploy` for function and `Deployed`/`Undeployed` for the booleans.

2023-02-28 19:48 UTC, Azanul reviewed
These are the ones I am talking about

2023-02-28 19:48 UTC, Azanul commented on install/playground/meshery-playground-deployment.yaml
> +            - name: DISABLE_OPERATOR
.

2023-02-28 19:48 UTC, Azanul commented on server/models/meshery_controllers.go
> +		DisableOperator:         disabled,
.

2023-02-28 19:48 UTC, Azanul commented on server/models/meshery_controllers.go
> +func (ot *OperatorTracker) Undeployed(ctxID string, undeployed bool) {
.

2023-02-28 20:00 UTC, Azanul commented
I recommend using `SetOperatorStatus` because I plan on using an enum for tracking status of connections. But we can do that with the state machine implementation.

2023-03-01 00:43 UTC, Azanul commented on server/models/meshery_controllers.go
> +func (ot *OperatorTracker) Undeployed(ctxID string, undeployed bool) {
`SetUndeployed` does feel like an improvement on `Undeployed`. How about `SetDeploymentStatus`?

2023-03-01 12:47 UTC, l5io commented
🚀 Preview for commit 366d0e004e252f4ed3b3b7a2856dd0158489168d at: https://63ff495a84b8a9006cada6de--meshery-docs-preview.netlify.app

2023-03-01 14:05 UTC, leecalcote reviewed
Please open a separate issue to track the ability to disable the operator for a given meshconfig context. // @abdullah1308

2023-03-01 14:06 UTC, leecalcote approved these changes
Thanks for these docs.

2023-03-01 16:31 UTC, Revolyssup commented
> Please open a separate issue to track the ability to disable the operator for a given meshconfig context. // @abdullah1308

https://github.com/meshery/meshery/issues/7233

2023-03-01 22:47 UTC, leecalcote commented
Did you gents conclude?

2023-03-02 19:21 UTC, merged