aligned meshery operator with the heading
meshery/meshery pull request #7282
Opened 2023-03-05 16:57 UTC by Ambareen09

**Notes for Reviewers**

This PR fixes #7279 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
Updated the size of the icon to align it wth the heading

- [x] Yes, I signed my commits.

2023-03-05 17:02 UTC, l5io commented
🚀 Preview for commit 93aaea40e63997ced84760a9fceff02b65ebb01f at: https://6404cb04c15eee320a63d772--meshery-docs-preview.netlify.app

2023-03-05 17:51 UTC, l5io commented
🚀 Preview for commit c51a22d59c58f78019bf4893029a10e70783ad29 at: https://6404d6729f540d44880ef772--meshery-docs-preview.netlify.app

2023-03-05 20:34 UTC, gurpreet-legend approved these changes

2023-03-06 03:19 UTC, leecalcote requested changes

2023-03-06 03:19 UTC, leecalcote commented on docs/pages/concepts/architecture/operator.md
> +# Meshery Operator <img src="{{ site.baseurl }}/assets/img/architecture/B203EFA85E89491B.png" width="20px"/>
Thanks for contributing, @Ambareen09 👍 

Please use dynamic styling (e.g flex with justify-content) as opposed to static sizing that suffers fragility and will inevitably not be appropriately positioned depending upon the scenario.

2023-03-06 06:43 UTC, l5io commented
🚀 Preview for commit 5d0ac6a693c2af91f06e01e25a581b56aa1313c8 at: https://64058b670dfed03091d8efb8--meshery-docs-preview.netlify.app

2023-03-06 06:49 UTC, l5io commented
🚀 Preview for commit 640ebc15d23b1f3c1d80a523880a2b38394c2548 at: https://64058cb4ac95be43d4619bac--meshery-docs-preview.netlify.app

2023-03-06 12:03 UTC, gurpreet-legend reviewed
Below "500px", the icon becomes too small, need to have some media query for this

![image](https://user-images.githubusercontent.com/75157493/223105136-e7df7819-3bd4-491f-8a6c-28f020c9d5cd.png)

2023-03-06 22:00 UTC, leecalcote commented
min-width, max-width, flex, ... helpful for dynamic css.

2023-03-07 10:04 UTC, l5io commented
🚀 Preview for commit 9cadbdca145c3332c17316ab5ab850666aeed390 at: https://64070c0eda40386753daf338--meshery-docs-preview.netlify.app

2023-03-07 10:12 UTC, l5io commented
🚀 Preview for commit 81565eed543e7b4363cd4827f2087116ad467b5c at: https://64070de8ccc0566bccf6fda7--meshery-docs-preview.netlify.app

2023-03-07 10:14 UTC, Ambareen09 commented
I think it's responsive now, can you please have a look now?

2023-03-07 23:15 UTC, leecalcote commented
@Ambareen09 Nope, not quite. I think the concept of static vs dynamic CSS alludes us here. Try again. Fourth time is a charm?

2023-03-08 10:43 UTC, l5io commented
🚀 Preview for commit add2ec1fb5fcad776d52d50fa1ef27fb6cc73f11 at: https://640866b06eb2b2173e0dd3fc--meshery-docs-preview.netlify.app

2023-03-08 10:51 UTC, l5io commented
🚀 Preview for commit 230703b1d2325ef93f1274e7c14eaf230674bef0 at: https://6408688c005808167d6984bc--meshery-docs-preview.netlify.app

2023-03-08 11:09 UTC, l5io commented
🚀 Preview for commit 669b75fe2f279dbedbde4de2e464a6a01125f317 at: https://64086cb99903cc1771391310--meshery-docs-preview.netlify.app

2023-03-08 11:13 UTC, Ambareen09 commented
Hey, I believe CSS is not working in the .md file, can you please suggest anything which would make me resolve this issue? I am unable to use the style tags in the .md file as well (separately) and the media query isn't working with inline style. can you help me figure out how to work?

2023-03-08 11:43 UTC, Chadha93 commented
@Ambareen09  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-03-08 12:12 UTC, Ambareen09 commented
Sure, could you please give me access to edit so that I can add my name? Or you can fix the meeting at your convenience anytime today.
My email is ambubushra@gmail.com

2023-03-08 12:18 UTC, Chadha93 commented
> Sure, could you please give me access to edit so that I can add my name? Or you can fix the meeting at your convenience anytime today @Chadha93 My email is [ambubushra@gmail.com](mailto:ambubushra@gmail.com)

@Ambareen09 Please fill this form to access - [layer5.io/newcomers](https://layer5.io/newcomers). You can add your items as suggestions.

2023-03-08 12:38 UTC, Ambareen09 commented
> > Sure, could you please give me access to edit so that I can add my name? Or you can fix the meeting at your convenience anytime today @Chadha93 My email is [ambubushra@gmail.com](mailto:ambubushra@gmail.com)
> 
> @Ambareen09 Please fill this form to access - [layer5.io/newcomers](https://layer5.io/newcomers). You can add your items as suggestions.

Added in list of topics as suggestions. When will be the call?

2023-03-08 15:28 UTC, l5io commented
🚀 Preview for commit e47edcd885cb1eab8d4a1cfbe3b9f05071df91d4 at: https://6408a98bcd34d75c22d82e56--meshery-docs-preview.netlify.app

2023-03-13 04:48 UTC, leecalcote commented
@Ambareen09 kudos to you for not giving up. 

> > > Sure, could you please give me access to edit so that I can add my name? Or you can fix the meeting at your convenience anytime today @Chadha93 My email is [ambubushra@gmail.com](mailto:ambubushra@gmail.com)
> > 
> > 
> > @Ambareen09 Please fill this form to access - [layer5.io/newcomers](https://layer5.io/newcomers). You can add your items as suggestions.
> 
> Added in list of topics as suggestions. When will be the call?

@Ambareen09 regarding when the call will be: it's today (every Monday). Click the big yellow button on https://meet.layer5.io subscribe to the community calendar.

2023-03-13 04:49 UTC, leecalcote commented
This CSS styling isn't what I'm referring to when asking for dynamic styling, but let's move forward anyway.

2023-03-13 04:49 UTC, merged

2023-03-13 05:25 UTC, Ambareen09 commented
Thank you for accepting my first PR!