Search UI changes
meshery/meshery pull request #7295
Opened 2023-03-07 07:44 UTC by VIKAS0264

**Notes for Reviewers**

This PR fixes #7106 

* search ui was unresponsive because of missing form tags, added the missing form tags. 
* added necessary style changes for search ui.
* all the units are in rem.
* Added necessary js to auto-fill the the search bar with the query.

### Behaviour of current search bar
https://user-images.githubusercontent.com/71399937/223356497-70efafc2-69e8-47cd-a00b-9b827a099bb7.mp4

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-03-07 07:49 UTC, l5io commented
🚀 Preview for commit 96a2fbb582d0068a5262ddd63f2e79afa95285fd at: https://6406ec414667ef4ea27bb6d9--meshery-docs-preview.netlify.app

2023-03-07 07:56 UTC, VIKAS0264 commented
@Chadha93 @Harshit-Dandriyal  @GaganpreetKaurKalsi I'm so sorry guys my previous pull request got really messed up please do check this PR i have worked on all the previously told suggestions.

2023-03-08 11:44 UTC, Chadha93 commented
@VIKAS0264  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-03-13 04:38 UTC, leecalcote commented
Review on Websites call?

2023-03-13 09:26 UTC, b0id commented
@VIKAS0264 was there an open issue on this PR?

2023-03-13 11:54 UTC, b0id approved these changes
Looks like issue resolved.

2023-03-13 14:12 UTC, VIKAS0264 commented
> Looks like issue resolved.

Hey @b0id what do you think about lee's suggestion, I think its better we have one search input as lee suggested.

2023-03-14 19:25 UTC, GaganpreetKaurKalsi requested changes
Noticed a few things
1. The font-family for the placeholder text and the content inside search input doesn't match the one we use across meshery docs.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/225114414-e1d404da-8210-4ed0-901b-d7cb0861d126.png">

2. The search icon is not visible.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/225114507-c330842c-3e15-4c78-9de5-a3ee18e25b20.png">

3. Also I think a little more padding on top and bottom of the input would look good. The search input looks too thin right now.

2023-03-15 02:34 UTC, VIKAS0264 commented
Hey @GaganpreetKaurKalsi , @Chadha93  suggested that I use that font, i think we should change it to what is being used across the docs.

2023-03-27 03:01 UTC, closed without merging