add endpoint to get user by id (uuid)
meshery/meshery pull request #7301
Opened 2023-03-07 18:06 UTC by MUzairS15

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-03-07 23:44 UTC, leecalcote commented on server/models/remote_provider.go
> +	logrus.Errorf("error while fetching user profile: %s", bdr)
Are MeshKit Errors not being used here?

2023-03-07 23:44 UTC, leecalcote requested changes
Lint items to attend to

2023-03-09 18:39 UTC, Chadha93 commented
https://github.com/layer5labs/meshery-extensions/pull/1638

2023-03-10 01:33 UTC, leecalcote commented on server/models/remote_provider.go
> +	logrus.Errorf("error while fetching user profile: %s", bdr)
@MUzairS15 an item to consider.

2023-03-12 12:56 UTC, Chadha93 approved these changes
LGTM, Thank @MUzairS15

2023-03-12 12:56 UTC, merged