bug fixes across meshery docs
meshery/meshery pull request #7411
Opened 2023-03-29 07:37 UTC by sudhanshutech

**Notes for Reviewers**

This PR fixes #
1. Alignment of tables description across api reference tables
![image](https://user-images.githubusercontent.com/90546692/228460198-debe85c2-4473-4298-b9f8-c3337caab756.png)
there are more tables like this
2. Dark mode bug fixed
![image](https://user-images.githubusercontent.com/90546692/228459971-56784364-cadd-4dad-9a43-a560d92b83da.png)
![image](https://user-images.githubusercontent.com/90546692/228460442-6b844eca-d814-4f35-b81d-380b30d76720.png)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-03-29 07:43 UTC, l5io commented
🚀 Preview for commit 6f9ff498abeea463891db657540b59ac7d3fbb25 at: https://6423ebd06dac136b81811684--meshery-docs-preview.netlify.app

2023-03-29 09:07 UTC, sudhanshutech commented
![image](https://user-images.githubusercontent.com/90546692/228484872-527bcd75-bace-4500-b31c-fa243b217eac.png)

2023-03-29 09:12 UTC, l5io commented
🚀 Preview for commit 57da26e65bdca833df329325dada04bb5537e5d5 at: https://642400cad369af7ee5969421--meshery-docs-preview.netlify.app

2023-03-30 03:28 UTC, leecalcote requested changes

2023-03-30 03:28 UTC, leecalcote commented on docs/_sass/table.scss
> +  text-align: center;
Not desired. Left-aligned content is preferred.

2023-03-30 03:28 UTC, leecalcote commented on docs/_sass/table.scss
> +}
```suggestion
```

2023-03-30 03:29 UTC, leecalcote approved these changes

2023-03-30 03:29 UTC, merged