[MeshModels] Add Core Application component in MeshModel
meshery/meshery pull request #7432
Opened 2023-03-31 21:17 UTC by Abhishek-kumar09

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-03-31 21:18 UTC, Abhishek-kumar09 commented
Some meshery-extensions tests were failing in absence of this component, and this regression was quickly picked.

2023-03-31 21:28 UTC, leecalcote commented on server/meshmodel/components/core/v1.0.0/Application.json
> +	"apiVersion": "core.oam.dev/v1alpha1",
@Revolyssup oam?

2023-03-31 21:29 UTC, leecalcote requested changes
Needs to be of type MeshModel

2023-04-03 14:09 UTC, Abhishek-kumar09 commented on server/meshmodel/components/core/v1.0.0/Application.json
> +	"apiVersion": "core.oam.dev/v1alpha1",
```suggestion
	"apiVersion": "core.meshmodel.dev/v1alpha1",
```

2023-04-03 14:55 UTC, Revolyssup approved these changes

2023-04-03 14:55 UTC, merged