WIP: While importing kubeconfig, showback information about K8s context registration
meshery/meshery pull request #7571
Opened 2023-04-18 19:47 UTC by MdSahil-oss

**Notes for Reviewers**

This PR fixes #6331

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-04-19 07:31 UTC, Chadha93 commented
@MdSahil-oss  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-04-19 19:01 UTC, MUzairS15 requested changes

2023-04-19 19:01 UTC, MUzairS15 commented on server/models/k8s_context.go
> +	return ctx, msg
Please send the `contexts` name list in response. UI can present the message accordingly.

2023-04-19 19:37 UTC, MdSahil-oss commented on server/handlers/k8sconfig_handler.go
> +	json.NewEncoder(w).Encode(resp)
@MUzairS15 Please review this PR again

2023-04-21 20:26 UTC, leecalcote commented
@MdSahil-oss, signal when feedback has been incorporated and you're ready for review again.

2023-04-22 18:05 UTC, MdSahil-oss commented
@leecalcote This PR is ready to review :)

2023-05-02 22:20 UTC, leecalcote commented
@MdSahil-oss goooood, good. Did we ever get this one demo'ed on the Meshery Dev meeting? If not, will you do so in this week's meeting?

2023-05-02 22:21 UTC, leecalcote commented
Note that a merge conflict has popped up.

2023-05-12 22:25 UTC, merged