updated the application icon
meshery/meshery pull request #7580
Opened 2023-04-20 16:53 UTC by AakashRaj20

**Notes for Reviewers**

This PR fixes #
updated the new svg for application Icon also added the color prop and also added all the neccessary prop

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-04-20 21:50 UTC, leecalcote requested changes

2023-04-20 21:50 UTC, leecalcote commented on ui/package-lock.json
@AakashRaj20 please remove changes to this file.

2023-04-21 09:31 UTC, Chadha93 commented
@AakashRaj20 This comment is not directly related to your changes. 
@Abhishek-kumar09 @harkiratsm Replacing the app's icon here in Meshery UI is overriding the app's icon in Meshery Extensions (making disappear). I checked in extensions, we are not referencing this SVG from Meshery anywhere. I observed that when the Meshery drawer is active, the apps icons appears to be fine in extensions. Capability Registry might be affecting here on show - https://github.com/meshery/meshery/blob/master/ui/components/Navigator.js#L429

2023-05-12 22:23 UTC, leecalcote commented
@UsmanDev09  has this already been taken care of by @duckling69 ?

2023-05-14 18:34 UTC, UsmanDev09 commented
I am not aware of @duckling69 involvement in this issue but I will update you. @leecalcote

2023-05-14 18:48 UTC, UsmanDev09 commented
He worked on issue #7506 @leecalcote

2023-05-16 16:15 UTC, closed without merging