Replace the Logo of Layer5 with Meshery in config.yml workflow
meshery/meshery pull request #7586
Opened 2023-04-21 04:00 UTC by anshgoyalevil

This is a sister PR to https://github.com/meshery/meshery/pull/7568

It fixes the srcset of images used in previous PR.

2023-04-21 04:07 UTC, anshgoyalevil commented
Actually I was using my Internet Provider's DNS so the images inside the repo were not rendering. Later, I used Raw Image outside of the Repo, and it worked. 

I now tried changing my DNS to Cloudflare 1.1.1.1, and it worked.

2023-04-21 11:08 UTC, vishalvivekm approved these changes
Thanks for updating the srcset @anshgoyalevil // @leecalcote

2023-04-21 11:09 UTC, vishalvivekm approved these changes

2023-04-21 11:09 UTC, vishalvivekm commented on .github/config.yml
👍

2023-04-21 11:32 UTC, vishalvivekm commented on .github/config.yml
one possible enhancement that can be made is: using https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/Meshery-celebration-Dark.svg for Dark mode celebration image and
https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/Meshery-celebration-Light.svg for light mode celebration image

as blob link is failing to render in some of the previews @anshgoyalevil

2023-04-22 07:58 UTC, anshgoyalevil commented on .github/config.yml
@vishalvivekm 

I am still not able to open these images 
https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/Meshery-celebration-Dark.svg

https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/Meshery-celebration-Light.svg

This is due to the DNS issue. Not because of Raw Images.

I guess we can merge this PR without the changes. Anyway, if you still prefer, I would change the srcset, just need another confirmation.

2023-04-22 08:22 UTC, vishalvivekm commented on .github/config.yml
I am perfectly able to open both of these, lemme show you 
![Screenshot from 2023-04-22 13-30-27](https://user-images.githubusercontent.com/110674407/233771162-2e943ed9-406a-499b-a5fa-d92416ba2993.png)
![Screenshot from 2023-04-22 13-30-11](https://user-images.githubusercontent.com/110674407/233771167-41a20816-6a6e-4bb8-8769-052220d05e59.png)

why am i suggesting to use the raw link instead of blob one ( ik blob also is just fine)  is becasue you take your that code : 
```
  <picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github.com/meshery/meshery/blob/master/.github/assets/images/Meshery-celebration-Dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="https://github.com/meshery/meshery/blob/master/.github/assets/images/Meshery-celebration-Light.svg">
  <img alt="Meshery Logo" src="">
  </picture>
  ```


Put it in some html viewer or a ide and it fails to render the image, at least it did for me( in the live preview). It was only when i replaced those srcset with the raw links that i could see the image

Also, the raw link was there by default if you remember, before you making the change.
That said, please try what i said and then you can always put it forward what you think is better @anshgoyalevil , Much Thanks!

2023-04-22 09:47 UTC, anshgoyalevil commented on .github/config.yml
Thanks a lot @vishalvivekm for the detailed insights. I have updated the links to use raw images. Thanks!

2023-04-23 03:24 UTC, vishalvivekm approved these changes

2023-04-25 14:17 UTC, thisiskaransgit requested changes

2023-05-02 22:15 UTC, leecalcote approved these changes
LGTM

2023-05-02 22:15 UTC, merged