Add Support for Credentials
meshery/meshery pull request #7634
Opened 2023-04-30 10:43 UTC by harkiratsm

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-05-08 07:48 UTC, Azanul requested changes
Please fix lint issue too

2023-05-08 07:48 UTC, Azanul commented on server/models/remote_provider.go
> +		fmt.Println("bawi is here", &cp)
.

2023-05-08 08:23 UTC, theBeginner86 commented on server/models/remote_provider.go
> +		fmt.Println("bawi is here", &cp)
👀

2023-05-08 08:35 UTC, harkiratsm commented on server/models/remote_provider.go
> +		fmt.Println("bawi is here", &cp)
yeah, just some debug log.

2023-05-09 23:43 UTC, leecalcote commented
@harkiratsm will you investigate the failing UI tests?

2023-05-11 13:24 UTC, harkiratsm commented
@leecalcote Tests are failing on the latest as well, so I'll investigate the artifacts and create a separate PR.

2023-05-12 22:33 UTC, theBeginner86 approved these changes
LGTM 👌

Works great

2023-05-12 22:38 UTC, theBeginner86 reviewed
@harkiratsm 
2 followup questions:

1. Will you be adding similar view in Meshery Cloud like in Meshery UI? Icons for credential type are not visible in Meshery Cloud

<img width="1440" alt="image" src="https://github.com/meshery/meshery/assets/73700530/1e57065d-0f9c-45e1-87c2-6d2eb0bef258">

2. Auto registration of Kubernetes credentials? That is, migrating current kubernetes contexts into credentials table and using Kubernetes as a connection.

2023-05-12 22:39 UTC, theBeginner86 reviewed
Would you please see why backend lint checks are failing?

2023-05-13 11:39 UTC, leecalcote requested changes
@harkiratsm question #2 above is a big question.

2023-05-24 10:49 UTC, leecalcote commented
> @harkiratsm question #2 above is a big question.

@harkiratsm thoughts?

2023-05-24 16:29 UTC, harkiratsm commented
The credentials are saved when the user uploads the Kubeconfig. I am pushing new changes.

Here is the screenshot.

![image](https://github.com/meshery/meshery/assets/71957674/46994608-8fa3-4255-a61e-e8f23b0c7644)

2023-05-26 15:07 UTC, leecalcote commented
Context = Connection

2023-05-26 15:17 UTC, Azanul commented
@harkiratsm While resolving conflicts do take care that all integration tests should be passing and only one E2E test should be failing. //@MarioArriaga92

2023-05-26 15:21 UTC, leecalcote commented
> Context = Connection

And by this, I mean to highlight that for each context defined within a kubeconfig, there should be one connection creation, maintaining a 1:1 relationship between Context and Connection.

2023-05-26 15:24 UTC, MarioArriaga92 commented
@harkiratsm not sure if this was mentioned during the call but there's a conflict in this file `ui/components/MesherySettings.js`:
<img width="937" alt="CleanShot 2023-05-26 at 09 23 56@2x" src="https://github.com/meshery/meshery/assets/23443575/9c506a64-29d4-4ce7-82af-1be66357e930">

2023-06-05 14:38 UTC, abdullah1308 commented
@MarioArriaga92 @theBeginner86 Any update on when this PR can be merged ?

2023-06-05 17:02 UTC, abdullah1308 commented
@harkiratsm can you resolve conflicts ?

2023-06-24 21:48 UTC, leecalcote commented
Note that there’s a bit of formatting off with the close button being misplaced, it seems.

<img width="732" alt="Screenshot 2023-06-24 at 4 47 00 PM" src="https://github.com/meshery/meshery/assets/7570704/83f36514-f4f6-4be5-bd2d-9de71996212d">



Also, note that one of the conflicts here steps backwards with a short compatibility list of only service meshes, not a more complete model list (which could be and should be programmatically retrieved from` /api/meshmodels/models`)

2023-07-01 02:41 UTC, leecalcote commented
Syncing with `master`

2023-07-07 12:26 UTC, harkiratsm commented
merging this one and will do the remaining in this PR https://github.com/meshery/meshery/pull/8035

2023-07-07 12:26 UTC, merged

2023-07-07 12:27 UTC, harkiratsm commented
left over - 
1. The Type field should contain meshmodel models.