issue #7671 : Updated main.go new.go
meshery/meshery pull request #7681
Opened 2023-05-13 13:08 UTC by RickDeb2004

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-05-26 22:16 UTC, nebula-aac requested changes
@RickDeb2004 Can you update this open PR to tell us what does this PR do?

While we can see the files changes, we want to ensure that whomever is reviewing can gain some understanding of what they are reviewing on this PR.

Also can you update your PR to fix the lint errors as well?

2023-05-27 05:51 UTC, Philip-21 commented
Hello  @RickDeb2004 would like to know what you are working

2023-05-27 05:59 UTC, Philip-21 commented on mesheryctl/pkg/utils/testdata/new.go
> +    if ctx.Err() == context.DeadlineExceeded {
please give some details about this

2023-05-27 06:04 UTC, Philip-21 commented on mesheryctl/pkg/utils/testdata/new.go
> +}
please give some details about this

2023-05-27 08:39 UTC, RickDeb2004 commented
> @RickDeb2004 Can you update this open PR to tell us what does this PR do?
> 
> While we can see the files changes, we want to ensure that whomever is reviewing can gain some understanding of what they are reviewing on this PR.
> 
> Also can you update your PR to fix the lint errors as well?

yes I will

2023-05-27 10:42 UTC, RickDeb2004 commented
review : #7746 
here I have given a brief description
@Philip-21 @nebula-aac

2023-05-29 17:38 UTC, abdullah1308 commented
@RickDeb2004 Refer https://github.com/meshery/meshery/pull/7746#issuecomment-1567373400

Closing PR due to an absence of relevant changes. Feel free to open another one

2023-05-29 17:38 UTC, closed without merging