fix: check if the pattern upload, is valid
meshery/meshery pull request #7784
Opened 2023-06-02 11:51 UTC by harkiratsm

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-06-02 14:33 UTC, Abhishek-kumar09 requested changes

2023-06-02 14:33 UTC, Abhishek-kumar09 commented on server/models/pattern/core/pattern.go
> +		return errors.New("missing services field")
```suggestion
		return errors.New("invalid design-file format: missing services field")
```

2023-06-02 14:33 UTC, Abhishek-kumar09 commented on server/models/pattern/core/pattern.go
> +	}
Not required for a pattern/design to always have traits, although we have traits for every pattern/design now, this is not an important check.

2023-06-06 00:45 UTC, leecalcote commented
@harkiratsm did you address this feedback? If so, re-request a review.

2023-06-06 00:45 UTC, leecalcote commented
and comment on how yo addressed the feedback.

2023-06-06 14:09 UTC, leecalcote commented on server/models/pattern/core/pattern.go
> +	}
```suggestion
//	for serviceName, service := range pattern.Services {
//		if service.Traits == nil {
//			return errors.New("missing traits field for:" + serviceName)
//		}
//	}
```

2023-06-06 14:14 UTC, merged