fix settings page title is not updating
meshery/meshery pull request #7793
Opened 2023-06-05 18:15 UTC by Meyazhagan

**Notes for Reviewers**

This PR fixes #7304 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-06-06 18:27 UTC, 8rxn requested changes
If there's no specific reason, the code may be shifted to `settings.js` for better maintainability

2023-06-06 18:27 UTC, 8rxn commented on ui/components/MesherySettings.js
> +
Hey @Meyazhagan ,
Great work on the PR.
I had a some points to consider:
Is there any specific reason as to why this change was made inside the `MesherySettings.js` and not on `settings.js` inside the pages directory.
That seems like a better approach as there's already a line to updatepagepath there and would make it similar to:

https://github.com/meshery/meshery/blob/005fdd9e53fc4653f04b5a480b3f28c226069c11/ui/pages/system/connections.js#LL13C1-L15C9

2023-06-06 21:16 UTC, 8rxn commented
@Meyazhagan One more thing While you're at it, The same issue exits on the `/user/preferences` page as well. 

It'd be great if you could add fixes to that too in the same PR.

2023-06-12 04:41 UTC, Meyazhagan commented
@8rxn I updated the changes. Take a look

2023-06-12 11:42 UTC, 8rxn approved these changes
looks good to me 🚀

2023-06-13 20:43 UTC, leecalcote approved these changes

2023-06-13 20:44 UTC, merged