fix: fixing docs setup
meshery/meshery pull request #7890
Opened 2023-06-19 08:40 UTC by SimardeepSingh1450

**Notes for Reviewers**

This PR fixes #7792 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.
 
#### Changes :
1. Fixed the broken link under for[ mesheryctl command reference](https://docs.meshery.io/reference/mesheryctl) under [configuration-management](https://docs.meshery.io/guides/configuration-management)
2. Added App [import](https://docs.meshery.io/reference/mesheryctl/app/import) subcommand in the sidebar of reference.
3. Updated the link for [installation methods ](https://docs.meshery.io/installation)under [quick start](https://docs.meshery.io/installation/quick-start) correctly, initially it directed to supported platforms.
4. Corrected the command for setting up the env variable for [Windows](https://docs.meshery.io/installation/platforms/windows#4--install-a-kubernetes-cluster)
from `export KUBECONFIG="$(k3d kubeconfig get 'k3s-default')"` to the following
 `$env:KUBECONFIG = "$(k3d.exe kubeconfig get 'k3s-default')"`

2023-06-19 09:20 UTC, thisiskaransgit requested changes
@SimardeepSingh1450,
- App import has to be added in [reference](https://docs.meshery.io/reference/mesheryctl) page under the [application management table](https://docs.meshery.io/reference/mesheryctl#cloud-native-application-management) command table. Not in the sidebar.
- Also while pushing the changes please revert the changes made in gemfiles

2023-06-19 09:20 UTC, thisiskaransgit commented on docs/pages/installation/windows.md
> +$env:KUBECONFIG = "$(k3d.exe kubeconfig get 'k3s-default')"</div></div>
Here, we are using bash script, we only needed the change in line 153, please revert this one

2023-06-19 09:27 UTC, l5io commented
🚀 Preview for commit 29e04e0fbecb2a8a33eb5b057dcc2da8c54052f2 at: https://64901f3d44734c3f234f158f--meshery-docs-preview.netlify.app

2023-06-19 09:59 UTC, l5io commented
🚀 Preview for commit d7279bf24058117b0af245dca0358b7136016ee5 at: https://649026d2c41d51480a59bac9--meshery-docs-preview.netlify.app

2023-06-19 10:20 UTC, SimardeepSingh1450 commented
@thisiskaransgit can you please tell from where i can change the [reference page](https://docs.meshery.io/reference/mesheryctl) content.

2023-06-19 11:00 UTC, thisiskaransgit commented
> @thisiskaransgit can you please tell from where i can change the [reference page](https://docs.meshery.io/reference/mesheryctl) content.

@SimardeepSingh1450  Refer to this [docs](https://docs.meshery.io/project/contributing/contributing-cli#adding-newremoving-existing-commands-in-the-reference-index)

2023-06-19 12:02 UTC, l5io commented
🚀 Preview for commit 2fcc3fd7aca7803bad72eb15b79d602d67987fb4 at: https://6490439144734c55f74f146a--meshery-docs-preview.netlify.app

2023-06-19 12:09 UTC, l5io commented
🚀 Preview for commit c2609047016c8799ea97a1885d1ca5084821985a at: https://649045500335765c2868d9dd--meshery-docs-preview.netlify.app

2023-06-19 12:31 UTC, l5io commented
🚀 Preview for commit 639f8b026874d2e5fd860f226d9538d81d5563b3 at: https://64904a6e11e1f660d864fadb--meshery-docs-preview.netlify.app

2023-06-19 12:37 UTC, SimardeepSingh1450 commented
@thisiskaransgit why is it behaving like this ?
![image](https://github.com/meshery/meshery/assets/92221517/0d53694b-3c55-4f8a-861a-c06885cabbcc)

2023-06-21 01:48 UTC, vishalvivekm commented
@SimardeepSingh1450 
Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-06-25 10:03 UTC, thisiskaransgit requested changes

2023-06-25 10:03 UTC, thisiskaransgit commented on docs/_data/mesheryctlcommands/cmds.yml
Please do not change the coding style.

2023-06-25 10:04 UTC, thisiskaransgit commented
> @thisiskaransgit can you please tell why is import source-type flag under app behaving like this ? ![image](https://user-images.githubusercontent.com/92221517/246831132-0d53694b-3c55-4f8a-861a-c06885cabbcc.png)


@SimardeepSingh1450 
It does not have to do with the workflow, Increase the `rowspan` for Application Management Table, and it will work fine

2023-06-25 10:10 UTC, thisiskaransgit commented on docs/_data/mesheryctlcommands/cmds.yml
Your extensions might have overridden the default coding style, changing the code style makes the reviewing work difficult and is counted as unwanted, when pushed without prior discussions. Remember it for the next time. Kindly Revert it.

2023-06-25 10:11 UTC, thisiskaransgit commented
@SimardeepSingh1450, The rest looks good, incorporate the above requests and we're good to go 👍🏼

2023-06-30 20:05 UTC, thisiskaransgit commented
@SimardeepSingh1450, What's your progress?

2023-07-01 02:29 UTC, leecalcote requested changes

2023-07-01 02:29 UTC, leecalcote commented on docs/pages/reference/mesheryctl-commands.md
@SimardeepSingh1450 thanks for this PR. will you please remove all other changes outside of this file and [line 154](https://github.com/meshery/meshery/pull/7890/files#diff-edb042f2d27d66af3fb28f3e3a3b4651af11e9844f1f7f087f76d6b8651f66dbR154) of the windows.md file?

2023-07-04 11:46 UTC, leecalcote commented
@SimardeepSingh1450 ?

2023-07-04 11:48 UTC, leecalcote commented
merge conflicts resolved

2023-07-04 11:53 UTC, l5io commented
🚀 Preview for commit a75745e2ab68146d082ddb774651d67843e416b4 at: https://64a407fa4016ad008948ab2d--meshery-docs-preview.netlify.app

2023-07-04 19:08 UTC, Chadha93 commented
@SimardeepSingh1450 Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-07-12 01:32 UTC, leecalcote commented
@SimardeepSingh1450 Will you be incorporating this feedback?

2023-08-19 19:21 UTC, thisiskaransgit commented
Closed as completed via #8128

2023-08-19 19:21 UTC, closed without merging