[Docs]: Server.go file missing #7887
meshery/meshery pull request #7891
Opened 2023-06-19 08:53 UTC by vaibhav-xt

**Notes for Reviewers**

_Updated server.go url and Remote Providers._

This PR fixes #7887

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2023-06-19 08:59 UTC, l5io commented
🚀 Preview for commit a8221c8bd92b53756c46c98817d4882b5e29870e at: https://649018b7033576403b68d988--meshery-docs-preview.netlify.app

2023-06-19 09:00 UTC, vaibhav-xt commented
@Chadha93 @leecalcote 
Please have a look at this pr, it's a very changes I made.

2023-06-19 14:17 UTC, anshgoyalevil approved these changes
LGTM! Thanks @vaibhav-xt for the contribution. 🚀 
Is there any other broken link present in this document?

2023-06-19 14:25 UTC, anshgoyalevil requested changes

2023-06-19 14:25 UTC, anshgoyalevil commented on docs/pages/extensibility/api.md
> +Each of the API endpoints are exposed through [server.go](../../../server/router/server.go). Endpoints are grouped by function (e.g. /api/mesh or /api/perf).
The link here needs to be an absolute path to the ```server.go``` file, since the link is being rendered outside of the GitHub.

2023-06-19 14:25 UTC, anshgoyalevil commented on docs/pages/extensibility/api.md
> +Alternatively, [Remote Providers](./providers.md) can extend Meshery's endpoints behind the `/api/extensions/` endpoint.
This need not be changed since this is referencing the page ```providers```, and not a markdown file.

2023-06-19 14:33 UTC, vaibhav-xt commented
@anshgoyalevil 

I got your points 🫡. I don't know I am saying true or not, but please have a look on all the links of `api.md` file, showing 404 page not found.

2023-06-19 14:41 UTC, anshgoyalevil commented
@vaibhav-xt You may be opening the links directly inside the code editor, which is not supposed to be done here, since the markdown files are being rendered to the docs website, and are not directly consumed on GitHub.

2023-06-19 15:06 UTC, vaibhav-xt commented
@anshgoyalevil 
Hey, I got my mistake 😔. Very Soon I'll make a commit.

2023-06-20 13:11 UTC, l5io commented
🚀 Preview for commit bdb3a8362d8a155a64e911966a45cd5c012ec729 at: https://6491a5656bcec80e677623f2--meshery-docs-preview.netlify.app

2023-06-20 13:12 UTC, anshgoyalevil commented
@vaibhav-xt 
Changes look good 😄 but please sign-off the commits using ```-s``` flag while using the ```git commit``` command

2023-06-20 13:49 UTC, l5io commented
🚀 Preview for commit d912946d6a83e77edbba0dd11cbb6506a8b913da at: https://6491ae2aef4df40513ead175--meshery-docs-preview.netlify.app

2023-06-20 14:54 UTC, closed without merging

2023-06-20 14:56 UTC, vaibhav-xt commented
I forget to add signed off the commit and did many experiments. 😥