[MeshModel] Add `WASM Filter` as a core component.
meshery/meshery pull request #7929
Opened 2023-06-24 06:10 UTC by MUzairS15

**Notes for Reviewers**

This PR fixes #7903
1. Adds `WASM Filter` as a `Core` component under the `Orchestration & Management` Category.
Dependent PR: https://github.com/meshery/meshkit/pull/322

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-06-24 07:45 UTC, leecalcote requested changes
We are spreadsheet driven in terms of ComponentDefinitions. Please define the component in Meshery Integrations.

2023-06-24 07:45 UTC, leecalcote commented on server/meshmodel/components/core/WASMFilter.json
> +        "svgColor": "<svg xmlns=\"http:\/\/www.w3.org\/2000\/svg\" id=\"Layer_1\" data-name=\"Layer 1\" viewBox=\"0 0 134.95 135.02\" height=\"20\" width=\"20\"><defs><style>.cls-1{fill:#00d3a9}.cls-
Please use the webassembly logo, not Meshery.

2023-06-24 07:48 UTC, MUzairS15 commented
@leecalcote yes, reason for not adding in Integration spreadsheet is, this PR is not complete and I don’t know adding this new component may start breaking things hence didn’t added.

I will add checklist for what’s remaining

2023-06-24 07:49 UTC, MUzairS15 commented
- [ ] Relationship Definition
- [ ] Policy for defining context aware behaviour for WASM Filter component

2023-06-24 08:04 UTC, leecalcote commented
> @leecalcote yes, reason for not adding in Integration spreadsheet is, this PR is not complete and I don’t know adding this new component may start breaking things hence didn’t added.
> 
> I will add checklist for what’s remaining

Make sense. For the new ComponentDefinition, we do need to define in the spreadsheet. You’re all clear to do so immediately. 👍 call me if you have questions about the sheet. This is an area that you need to become very familiar with as you go to fill-in for @Revolyssup, who has very little time for this any longer. 

On a related note, the component generation framework in MeshKit, should be setup as a factory system in which support for adding helm repos other than Artifact Hub is possible. There are a many more than helm repos to be added soon.

2023-06-24 18:37 UTC, Abhishek-kumar09 reviewed
Questions:
1. Should all wasm filters contains non-empty config?
2. Filters is an array, do each individual can also contain config and entrypoints?
3. Is there any working prototype that this configuration would work?

2023-06-24 19:18 UTC, MUzairS15 commented
> Questions:
> 
> 1. Should all wasm filter contains non-empty config?
> 2. Filters is an array, do each individual can also contain config and entrypoints?
> 3. Is there any working prototype that this configuration would work?

#1 IMO it should
#2 no it’s a mistake it should be a string 
#3 Only the envoy filter will be deployed and the confit will populated appropriately from WASMFilter component as part of ctx aware policy so any valid Envoy filter will work

2023-06-25 15:33 UTC, MUzairS15 commented
@leecalcote @Abhishek-kumar09 Can we move forward here?

2023-06-25 16:45 UTC, leecalcote commented on server/meshmodel/components/core/WASMFilter.json
> +        "logo-URL": "",
Change to logoURL to maintain our camelcasing design principle. If we have done this in other components, hopefully we don’t have logic expecting a hyphen.

2023-06-25 16:46 UTC, leecalcote commented on server/meshmodel/components/core/WASMFilter.json
> +            "svgColor": "<svg xmlns=\"http:\/\/www.w3.org\/2000\/svg\" id=\"Layer_1\" data-name=\"Layer 1\" viewBox=\"0 0 134.95 135.02\" height=\"20\" width=\"20\"><defs><style>.cls-1{fill:#00d3a9}.
@Revolyssup do you know why were defining model information twice? We see this duplication in a number of other components.

2023-06-25 16:47 UTC, leecalcote commented on server/meshmodel/components/core/WASMFilter.json
> +    "isAnnotation": true,
Sliding this into metadata makes sense.

2023-06-25 17:37 UTC, leecalcote commented on server/meshmodel/relationships/hierarchical_wallet.json
> +    "subType": "Parent",
```suggestion
    "subType": "Inventory",    
```

2023-06-25 17:39 UTC, leecalcote commented on server/meshmodel/components/core/WASMFilter.json
> +        "logo-URL": "",
@Abhishek-kumar09 do you know?

2023-06-25 17:40 UTC, leecalcote commented on server/meshmodel/components/core/WASMFilter.json
> +        "logo-URL": "",
```suggestion
```

2023-06-25 17:48 UTC, leecalcote commented on server/meshmodel/components/core/WASMFilter.json
> +    "apiVersion": "core.meshmodel.dev/v1alpha1",
```suggestion
    "apiVersion": "core.meshery.io/v1alpha1",
```

2023-06-25 17:48 UTC, leecalcote commented on server/meshmodel/components/core/WASMFilter.json
> +        "modelDisplayName": "Core",
```suggestion
        "model": "kubernetes",
        "modelDisplayName": "Kubernetes",
```

2023-06-25 17:51 UTC, leecalcote commented on server/meshmodel/components/core/WASMFilter.json
> +    "schema": "{\"$id\":\"http:\/\/meshery.layer5.io\/definition\/Workload\/WASMFilter\",\"$schema\":\"http:\/\/json-schema.org\/draft-07\/schema\",\"properties\":{\"wasm-filter\":{\"type\":\"string\
```suggestion
    "schema": "{\"$id\":\"https:\/\/meshery.layer5.io\/system\/models\/definition\/Workload\/WASMFilter\",\"$schema\":\"http:\/\/json-schema.org\/draft-07\/schema\",\"properties\":{\"wasm-filter\":{\"type\":\"string\"},\"config\":{\"type\":\"string\"}},\"required\":[\"wasm-filter\",\"config\"],\"title\":\"WASM Filter\",\"type\":\"object\"}"
```

2023-06-25 18:07 UTC, leecalcote commented on server/meshmodel/relationships/hierarchical_wallet.json
> +        }
```suggestion
    "subType": "Inventory",    
    "referenceURI":
    "selectors": {
        "allow": {
          "from": [
              {
                  "kind": "EnvoyFilter",
                  "model": "Istio Base",
                  "patch": {
                    "patchStrategy": "replace",
                    "$mutatedRef": "#configPatches.patch.value",
                    "description": "Receive the WASM filter configuration."
                  }
              }
          ],
          "to": [
              {   "kind": "WASMFilter",
                  "model": "Core",
                  "patch": {
                    "patchStrategy": "replace",
                    "$mutatorRef": "#config",
                    "description": "WASM filter configuration to be applied to Envoy Filter."
                  }
                }
          ],
        },
        "deny": {
            "from": [],
            "to": []
        }
```

2023-06-25 18:07 UTC, leecalcote commented on server/meshmodel/relationships/hierarchical_wallet.json
> +    "subType": "Inventory",
A new subtype of "Inventory" to be defined in for MeshModel Relationships.

2023-06-25 18:13 UTC, leecalcote commented on server/meshmodel/relationships/hierarchical_wallet.json
> +        "displayName": "Core",
```suggestion
        "description": "A hierarchical inventory relationship in which a Core WASM Filter configuration is applied to an Istio Envoy Filter."
    },
    "model": {
        "name": "kubernetes",
        "version": "*",
        "displayName": "Kubernetes",
```

2023-06-25 18:16 UTC, leecalcote approved these changes

2023-06-25 18:31 UTC, leecalcote commented
> @leecalcote @Abhishek-kumar09 Can we move forward here?

LGTM. Thanks for the in-depth reviews. We have three new schema changes coming out of this: 

1. Relationships of subType Inventory
2. Components Metadata of isAnnotation
3. Relationships To/From Patches

Two open questions, @Revolyssup, @Abhishek-kumar09:

1. Why is "logo-URL" not camelcased? I recognize that we don't use the field currently, but it needs to follow spec.
2. Why is "model" repeated twice in the same Component Definition - once under metadata and once under model attribute?

2023-06-25 19:37 UTC, merged

2023-06-25 19:38 UTC, leecalcote commented
One follow up here: the overall conversion of WASM Filters into a MeshModel component, inclusive of binary reference.