Helm Chart to have the "meshery" namespace
meshery/meshery pull request #8044
Opened 2023-07-03 19:52 UTC by Freedisch

**Notes for Reviewers**

This PR fixes #7893 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-07-03 22:37 UTC, leecalcote commented
LGTM, how about you, @AugustasV?

2023-07-03 22:37 UTC, leecalcote submitted a review, later dismissed

2023-07-03 22:38 UTC, leecalcote commented
@AugustasV, speaking of things that look good to you, how does this look? https://github.com/meshery/meshery/pull/8044#issuecomment-1619068573

2023-07-04 10:32 UTC, AugustasV commented
@Freedisch why did you do that? any comment? Not cool to do do like that

2023-07-04 10:45 UTC, Freedisch commented
@AugustasV There is the Release chart ci failing, it seems metadata.namespace field is not directly accessible in the deployment manifest

2023-07-04 11:29 UTC, leecalcote commented on install/kubernetes/helm/meshery/templates/deployment.yaml
> +  namespace: {{ .Values.namespace }}
Good one, @AugustasV 👏

2023-07-04 13:12 UTC, Abhishek-kumar09 reviewed
We don't require changes in the kubernetes manifests right?

2023-07-04 14:47 UTC, MUzairS15 commented on install/kubernetes/helm/meshery/Chart.yaml
> +metadata:
I think it is more appropriate to have it under Values.yaml.

2023-07-04 19:06 UTC, Chadha93 commented
@Freedisch Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-07-06 15:50 UTC, leecalcote requested changes
@Freedisch @AugustasV, here is what I get while running `make helm-lint` against these changes:

```
==> Linting install/kubernetes/helm/meshery
[ERROR] templates/: template: meshery/templates/deployment.yaml:5:25: executing "meshery/templates/deployment.yaml" at <.metadata.namespace>: nil pointer evaluating interface {}.namespace
```

2023-07-06 16:01 UTC, Freedisch commented
> @Freedisch @AugustasV, here is what I get while running `make helm-lint` against these changes:
> 
> ```
> ==> Linting install/kubernetes/helm/meshery
> [ERROR] templates/: template: meshery/templates/deployment.yaml:5:25: executing "meshery/templates/deployment.yaml" at <.metadata.namespace>: nil pointer evaluating interface {}.namespace
> ```

I'll update it, I think `{{metadata.namespace}}` is not accessible...👀 @AugustasV

2023-07-07 21:40 UTC, leecalcote commented on install/kubernetes/helm/meshery/values.yaml
> +namespace: meshery
Does this act as a default setting? Without it, will `meshery` be the default namespace, @AugustasV?

2023-07-07 23:04 UTC, merged