[UI] MesheryFilters/FilterCard  : Add Download Button to Filter Card
meshery/meshery pull request #8073
Opened 2023-07-06 14:11 UTC by aabidsofi19

**Notes for Reviewers**

This PR fixes #CU-85ztd2m9f

Added Button to download wasm binary . 

![image](https://github.com/meshery/meshery/assets/65964225/46cff39a-07cb-4a19-bd80-faa88c60b4d4)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-07-06 14:11 UTC, l5io commented
Task linked: [CU-85ztd2m9f Create a download button for the wasm binaries](https://app.clickup.com/t/85ztd2m9f)

2023-07-06 17:37 UTC, senali-d reviewed
LGTM

2023-07-06 18:30 UTC, leecalcote commented
@aabidsofi19 did you include support for dark mode, too?

2023-07-06 18:31 UTC, leecalcote requested changes

2023-07-06 18:31 UTC, leecalcote commented on ui/components/MesheryFilters/FiltersCard.js
> +                <DownloadIcon fill="#ffffff" className={classes.iconPatt} />
Fill color hard coded. Dark mode supported?

2023-07-06 18:32 UTC, leecalcote commented
Does this grid's responsiveness include an update for this new button?

2023-07-06 18:33 UTC, leecalcote commented
Related: Please make sure that the Clone button maintains aspect ratio on smaller screen widths, @aabidsofi19

2023-07-06 18:34 UTC, leecalcote commented
@ritiksaxena124 is this the right set of colors?

2023-07-06 18:36 UTC, leecalcote commented
@aabidsofi19 any reason that this button deviates from the existing icon? Let's avoid the potential confusion this will mean for users.
<img width="1318" alt="Screenshot 2023-07-06 at 1 35 50 PM" src="https://github.com/meshery/meshery/assets/7570704/7e8efe6a-d38c-4386-8b71-f0a6fe66b26c">

2023-07-07 04:38 UTC, aabidsofi19 commented
> @aabidsofi19 did you include support for dark mode, too?

working fine , btn turns teal and fill is white

2023-07-07 04:40 UTC, aabidsofi19 commented
> @aabidsofi19 any reason that this button deviates from the existing icon? Let's avoid the potential confusion this will mean for users.
> <img width="1318" alt="Screenshot 2023-07-06 at 1 35 50 PM" src="https://github.com/meshery/meshery/assets/7570704/7e8efe6a-d38c-4386-8b71-f0a6fe66b26c">
> 

This looked a bit better as this is a big btn , if it's confusing let's avoid it ..

2023-07-07 05:13 UTC, aabidsofi19 commented
@leecalcote  @@senali-d  I left the button grid unmodified since it has five columns. However, it's not fully responsive on mobile devices, causing the button text to overflow even without adding a new button. Considering that we will likely have a maximum of three buttons ("publish/unpublish," "download," and "clone"), I suggest using three columns for mobile devices.

2023-07-07 05:48 UTC, leecalcote commented
@aabidsofi19 we will have more than three buttons. Make the card responsive. Don't allow spill over.

2023-07-07 05:52 UTC, aabidsofi19 commented
> @aabidsofi19 we will have more than three buttons. Make the card responsive. Don't allow spill over. 

@leecalcote  then should we truncate text on mobile as well  .

2023-07-07 06:01 UTC, leecalcote commented
do it: remove the text

2023-07-07 06:18 UTC, aabidsofi19 commented
https://github.com/meshery/meshery/assets/65964225/1e8cab47-d3b5-435c-b241-bf6920cb232b

2023-07-07 07:02 UTC, ritiksaxena124 commented
@aabidsofi19 looks to me, small changes 
1. The color that we are using for the text "_Modified on: July 7, 2023 10:34 AM_" i.e., #607d8b is not our brand color could you update it to color Hoki (#677E88) please? Other colors used are good
2. On smaller screens the download icon is not in center

2023-07-07 11:37 UTC, aabidsofi19 commented
> @aabidsofi19 looks good to me, small changes
> 
> 1. The color that we are using for the text "_Modified on: July 7, 2023 10:34 AM_" i.e., #607d8b is not our brand color could you update it to color Hoki (#677E88) please? Other colors used are good
> 2. On smaller screens the download icon is not in center
> 3. Don't import icons from Material UI instead use the JS version of the SVG

3rd change will need refactoring of more than 10-15 components , lets do it in a separate pr .

2023-07-07 13:33 UTC, aabidsofi19 commented
@ritiksaxena124  we are using primary  for modifed on subheading :confused

2023-07-07 13:36 UTC, ritiksaxena124 commented
> @ritiksaxena124 we are using primary for modifed on subheading :confused

Yes, the Hexcode for primary needs to be updated

2023-07-07 13:38 UTC, aabidsofi19 commented
> > @ritiksaxena124 we are using primary for modifed on subheading :confused
> 
> Yes, the Hexcode for primary needs to be updated

in the theme/app.js

2023-07-07 13:41 UTC, aabidsofi19 commented
@ritiksaxena124 what should be the main , dark and light variant for it

2023-07-07 13:46 UTC, ritiksaxena124 commented
we are using blueGrey for both dark and light and we can replace it with "Hoki". it will work in both dark and light mode as the current color and hoki has a very slight difference

2023-07-07 15:52 UTC, aabidsofi19 commented
there is no Hoki color exported from mui : 
![image](https://github.com/meshery/meshery/assets/65964225/06a604da-11bf-4b49-a1fd-b5aa8a6cc846)

2023-07-07 16:07 UTC, aabidsofi19 commented
> 

@ritiksaxena124

2023-07-07 17:44 UTC, leecalcote commented
> there is no Hoki color exported from mui :
> ![image](https://user-images.githubusercontent.com/65964225/251793749-06a604da-11bf-4b49-a1fd-b5aa8a6cc846.png)

Don't use MUI colors, @aabidsofi19. Use our theme colors. Import the theme.

2023-07-07 19:45 UTC, aabidsofi19 commented
> > there is no Hoki color exported from mui :
> 
> Don't use MUI colors, @aabidsofi19. Use our theme colors. Import the theme.

@leecalcote  thats right ,@ritiksaxena124   asked to change the primary color in theme from blueGreen to "hoki" . But I can't find the color anywhere .. rest assured we are not importing colors from mui in these components .

2023-07-08 05:16 UTC, aabidsofi19 commented
> > @ritiksaxena124 we are using primary for modifed on subheading :confused
> 
> Yes, the Hexcode for primary needs to be updated

fixed it .

2023-07-08 06:05 UTC, leecalcote commented on ui/themes/app.js
Please revert this, @aabidsofi19. Just use the existing colors.

2023-07-08 07:12 UTC, merged