[PERFORMANCE PROFILE] - Specify flags in performance profile
meshery/meshery pull request #8219
Opened 2023-07-19 12:48 UTC by UsmanDev09

**Notes for Reviewers**

This PR fixes #

When i create a profile, subscribePerformanceProfiles() does not return metadata. When i reload the page fetchPerformanceProfiles() returns metadata and it is visible.

https://github.com/meshery/meshery/assets/31584129/7a9cdeba-1c63-4477-9d45-736839125444

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-07-20 19:55 UTC, leecalcote commented on go.mod
> +	github.com/layer5io/gowrk2 v0.6.1
@abdullah1308, will you confirm if we're going to have an issue with this newer version of gowrk2 and fortio?

2023-07-20 19:56 UTC, leecalcote commented on go.mod
> +	github.com/layer5io/gowrk2 v0.6.1
Ok, I see that this is @abdullah1308's commit. 👍

2023-07-21 08:25 UTC, UsmanDev09 commented
I have added a file upload option and it validates if it contains json or not. 

https://github.com/meshery/meshery/assets/31584129/24af9c80-98e8-409a-8dba-3668714ee1db

2023-07-31 16:15 UTC, MUzairS15 commented
@UsmanDev09 UI gets distorted when JSON is large, both at the time of upload and when viewing the profile. Try uploading a JSON with many options.

2023-07-31 16:20 UTC, MUzairS15 commented
@UsmanDev09 I have updated the subscription but could not verify, since after updating the subscription UI crashes if there is empty additional options.

2023-07-31 22:41 UTC, leecalcote commented
I'll see about resolving these merge conflicts.

2023-08-01 11:45 UTC, UsmanDev09 commented
@MUzairS15 I have handled the large json file issue as follows: 


https://github.com/meshery/meshery/assets/31584129/e6ec3375-afaa-4e63-8ba5-3181acaa926d


I have also handled the empty additional option edge case.

2023-08-01 13:12 UTC, MUzairS15 requested changes
One last item @UsmanDev09, at time of uploading (a large JSON), will you also add expand / collapse ? It would be more better if expand / collapse is present at top itself, instead of need to scroll at bottom (to click on Show less)

2023-08-01 15:10 UTC, MUzairS15 commented
@UsmanDev09 Is it possible to add helper text for upload ssl certificate field, (to mention .crt files supported) ?

2023-08-01 19:12 UTC, UsmanDev09 commented
@MUzairS15 I have added `...` to indicate that full json is not being displayed. 

![dots](https://github.com/meshery/meshery/assets/31584129/a8e90662-f2ca-4fcb-a481-3e9a91461c94)

2023-08-02 13:17 UTC, MUzairS15 commented
<img width="330" alt="Screenshot 2023-08-02 at 6 45 01 PM" src="https://github.com/meshery/meshery/assets/79860504/0d22898d-1329-4a68-ae87-81c566545cc5">

@UsmanDev09 A helper text in this form?

2023-08-02 21:15 UTC, UsmanDev09 commented
@MUzairS15 i have added the helper text and persisted the file name upon editing too. 

https://github.com/meshery/meshery/assets/31584129/3094e96d-10d1-43c2-96cb-abacb194e4f8

2023-08-02 21:16 UTC, UsmanDev09 commented
Upon uploading .crt files, the same subscription issue occurs. Reload is required to see the profile

2023-08-03 10:31 UTC, MUzairS15 submitted a review, later dismissed
@UsmanDev09 Subscription is working for me, I can see updates without refreshing.
Thhough there is another issue, try editing a profile which already has a certificate, when you upload a new cert, the name field is not updated, instead label is updated. 
https://github.com/meshery/meshery/assets/79860504/bd55bd09-2294-40d5-8e1c-78c070b366dd

I am merging this PR, please handle this in separate PR.

2023-08-03 11:34 UTC, merged