first commits
meshery/meshery pull request #8220
Opened 2023-07-19 13:32 UTC by Philip-21

**Notes for Reviewers**

This PR fixes for  #8087

Unit test for Mesheryctl's [delete.go](https://github.com/meshery/meshery/blob/master/mesheryctl/internal/cli/root/filter/delete.go) in the filter package

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-07-19 20:16 UTC, suhail34 requested changes
I tried testing but giving me errors
![image](https://github.com/meshery/meshery/assets/77241166/a703c3e9-6cc6-4474-a060-98a7e3726155)

2023-07-20 20:09 UTC, Philip-21 commented on mesheryctl/internal/cli/root/filter/delete_test.go
> +			Fixture:          "delete.id.api.golden",
yh its done

2023-07-20 20:10 UTC, Philip-21 commented
@suhail34, outputs are generated perfectly , you can still look through it .

2023-07-31 23:22 UTC, leecalcote approved these changes

2023-07-31 23:22 UTC, merged