Refactor/diviz11/mesheryctl-filter-import-update
meshery/meshery pull request #8254
Opened 2023-07-22 14:28 UTC by diviz11

**Notes for Reviewers**

This PR fixes #8244 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [✅] Yes, I signed my commits.

2023-07-23 06:18 UTC, alphaX86 requested changes

2023-07-23 06:18 UTC, alphaX86 commented on mesheryctl/internal/cli/root/filter/import.go
> +mesheryctl filter import /path/to/filter.wasm -wasm-config [filepath|string]
```suggestion
mesheryctl filter import /path/to/filter.wasm --wasm-config [filepath|string]
```

2023-07-23 06:18 UTC, alphaX86 commented on mesheryctl/internal/cli/root/filter/import.go
>  mesheryctl filter import /path/to/filter.wasm -name [string]
```suggestion
mesheryctl filter import /path/to/filter.wasm --name [string]
```

2023-07-24 19:32 UTC, leecalcote commented
@abdullah1308 feedback?

2023-07-25 03:36 UTC, alphaX86 submitted a review, later dismissed
Since cobra doesn't support more than 1 ASCII character for shorthand flag, I'm approving this for now

LGTM

2023-07-25 11:15 UTC, suhail34 approved these changes
LGTM
For supporting more than one ascii letter i think we have to create our custom parsing logic

2023-07-25 12:34 UTC, suhail34 requested changes

2023-07-26 09:19 UTC, Chadha93 commented
@diviz11  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-07-26 19:00 UTC, merged