✨ description added using CURL
meshery/meshery pull request #8265
Opened 2023-07-24 13:28 UTC by spacemc2

**Notes for Reviewers**

This PR fixes #8179 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-07-24 17:07 UTC, leecalcote commented
@spacemc2 excellent!

2023-07-24 18:21 UTC, asubedy requested changes

2023-07-24 18:21 UTC, asubedy commented on docs/pages/reference/rest-api-reference.md
> +--header 'meshery-token: &lt;mytoken&gt;\
```suggestion
--header 'meshery-token: &lt;yourToken&gt;\
```

2023-07-24 18:21 UTC, asubedy commented on docs/pages/reference/rest-api-reference.md
> +--header 'Cookie: meshery-provider=Meshery; meshery.layer5.io_ref=/;token=&lt;mytoken&gt;
```suggestion
--header 'Cookie: meshery-provider=Meshery; meshery.layer5.io_ref=/;token=&lt;yourToken&gt;
```

2023-07-24 19:23 UTC, spacemc2 reviewed
The suggestions were resolved!

2023-07-24 19:24 UTC, l5io commented
🚀 Preview for commit 016d3a9fff7e18b8d0d8e855a3f1bbb6b3630ef8 at: https://64becfed90cf16116b8ab377--meshery-docs-preview.netlify.app

2023-07-26 09:21 UTC, Chadha93 commented
@spacemc2  Let's discuss this on the Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-07-31 22:32 UTC, leecalcote approved these changes
Most excellent, @spacemc2 👏

2023-07-31 22:32 UTC, merged