[WIP] [Server] Add server support to share WASM Filters
meshery/meshery pull request #8274
Opened 2023-07-25 13:45 UTC by Chadha93

**Notes for Reviewers**
Add server support to share WASM Filters

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-07-28 10:18 UTC, l5io commented
🚀 Preview for commit 7654b46a740d871870d3a3cfba40a68e023816c1 at: https://64c395d7c33bb066ad7b2824--meshery-docs-preview.netlify.app

2023-07-30 18:39 UTC, suhail34 requested changes

2023-07-30 18:39 UTC, suhail34 commented on server/handlers/user_handler.go
> +	statusCode, err := provider.ShareDesign(r)
```suggestion
	statusCode, err := provider.ShareFilter(r)
```
It will be shareFilter right?

2023-07-31 20:48 UTC, leecalcote requested changes

2023-07-31 20:48 UTC, leecalcote commented on docs/_data/swagger.yml
This file is autogenerated and shouldn't be included.

2023-07-31 22:42 UTC, l5io commented
🚀 Preview for commit 5b09113eceb8ae01288e0f8b6424fcb4c3124798 at: https://64c838a952a8f403a1b2edd4--meshery-docs-preview.netlify.app

2023-08-10 23:34 UTC, leecalcote commented
Merge conflicts

2023-08-14 12:30 UTC, MUzairS15 submitted a review, later dismissed

2023-08-17 13:49 UTC, l5io commented
🚀 Preview for commit fdabeb82748a2e86f8fb02b17f4f4113e5ab52c6 at: https://64de2564ee581409761acb05--meshery-docs-preview.netlify.app

2023-08-17 22:39 UTC, merged