[MeshModel] Add supported relationships screenshots
meshery/meshery pull request #8287
Opened 2023-07-26 19:53 UTC by Boombag0607

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-07-26 22:29 UTC, leecalcote commented on .github/assets/images/network_edge_relationship_ingress_service.png
When @Abhishek-kumar09 addresses this bug (wrong namespace coloring), we'll want to take a new screenshot for this relationship type.

2023-07-26 22:30 UTC, leecalcote requested changes
@Boombag0607 thanks! Unless these are going into the readme, please put these screenshots into the /docs/<somewhere>/... folder.

2023-07-27 05:19 UTC, Boombag0607 commented
Added a quick fix to include all screenshots in contribution docs.

2023-07-27 05:22 UTC, l5io commented
🚀 Preview for commit f7803bfa3aae07ca642e8b68ff959aba27c221c6 at: https://64c1fee65f34b44bb7dfeeef--meshery-docs-preview.netlify.app

2023-07-27 06:23 UTC, l5io commented
🚀 Preview for commit cc310141fbc9240a49b916fef0b272db1191abf5 at: https://64c20d39e696c653ce67dc75--meshery-docs-preview.netlify.app

2023-07-27 07:51 UTC, l5io commented
🚀 Preview for commit 2e26245d5afb145367ac6571a4a00fdf62c6879b at: https://64c221e3c83715583d043c28--meshery-docs-preview.netlify.app

2023-07-27 11:26 UTC, leecalcote approved these changes

2023-07-27 11:26 UTC, merged