Docs meshmodel
meshery/meshery pull request #8291
Opened 2023-07-27 07:23 UTC by Yana-Gupta

**Notes for Reviewers**

This PR fixes #8221
The pr fixed point 1 and 4 mentioned in the issue.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-07-27 07:26 UTC, l5io commented
🚀 Preview for commit 8b5eea50ee3d719ec1d342b08df5f07b553c6127 at: https://64c21c21c83715557503a8ae--meshery-docs-preview.netlify.app

2023-07-27 09:31 UTC, Boombag0607 reviewed
@Yana-Gupta Looks great! Nice work. (Just make sure you stay consistent with the spellings)

2023-07-27 09:50 UTC, Yana-Gupta commented
> @Yana-Gupta Looks great! Nice work. (Just make sure you stay consistent with the spellings)

Thank you! I'll make sure to maintain consistency with the spellings.

2023-07-27 10:03 UTC, l5io commented
🚀 Preview for commit 345ef2c5c8f0a91cf1628f516538cbd6c071f730 at: https://64c240f1af01d46fb007dcea--meshery-docs-preview.netlify.app

2023-07-30 10:57 UTC, Yana-Gupta commented
@thisiskaransgit and @Chadha93 would you review it once.

2023-07-30 11:46 UTC, sudhanshutech commented
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

2023-07-30 20:48 UTC, thisiskaransgit requested changes
Hey @Yana-Gupta, thanks for working on this 👍🏼 , some things for you to consider here would be 
For Mehsmap: 
- How to access the extension's UI should be explained once 
- We have thoroughly described Mehsmap and how to use its features in /extensions section/ CTAs for the page should be included in the page.
- images in a queue does not look good

1. Include the href of layer5.io pages for respective modes.
2. Take reference from the websites pages and community resources to describe the steps
3. Include current existing gifs, on the page if it describes the step better.

For Meshmodel page, include a short paragraph describing  meshmodal summary

2023-07-30 20:58 UTC, thisiskaransgit commented on docs/assets/img/meshmap/meshmap-design-creation.png
@Yana-Gupta, not this image, please.

2023-07-30 20:58 UTC, thisiskaransgit commented on docs/pages/guides/meshmap.md
> +The option to access the MeshMap is available as the last option inside the sidebar of Meshery UI. Upon clicking the icon, the extension MeshMap will enable on your screen, and then you can choose th
```suggestion
In the Dashboard, the MeshMap visualization tool is accessible via a sidebar option located at the bottom of the navigation menu. To access MeshMap, click on this option, and the MeshMap extension will activate on the screen. From there, you can select the "design" option.```

2023-07-31 05:09 UTC, Yana-Gupta commented on docs/assets/img/meshmap/meshmap-design-creation.png
okay @thisiskaransgit

2023-07-31 17:47 UTC, l5io commented
🚀 Preview for commit 1014e744bebf5990976ebdab3bc6f6b7685081b8 at: https://64c7f375073d992f5aec7ac8--meshery-docs-preview.netlify.app

2023-07-31 18:01 UTC, l5io commented
🚀 Preview for commit e83011e8d9098be0bc793c66ba4ad639a4774952 at: https://64c7f6b79467062dbd58cccc--meshery-docs-preview.netlify.app

2023-08-02 09:13 UTC, Yana-Gupta commented
@thisiskaransgit some test are failing. Could you please take a look about failing test and provide some insights.

2023-08-02 11:16 UTC, vishalvivekm commented
@Yana-Gupta Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-08-03 14:04 UTC, thisiskaransgit commented
@Yana-Gupta, No worries the workflow failure is not related to the PR.

2023-08-04 07:01 UTC, l5io commented
🚀 Preview for commit abd5870df9a4df4c5ebde0a20a3b36f4d3c548e6 at: https://64cca210842a6d600297c3e5--meshery-docs-preview.netlify.app

2023-08-04 17:32 UTC, Yana-Gupta commented
@thisiskaransgit please review

2023-08-08 07:58 UTC, l5io commented
🚀 Preview for commit e31190ff23f65bc92d2dede71cf2d47afbdeb666 at: https://64d1f541fc96e83dce4c69b1--meshery-docs-preview.netlify.app

2023-08-09 10:19 UTC, thisiskaransgit requested changes

2023-08-09 16:59 UTC, l5io commented
🚀 Preview for commit 7d4dae4678bc1b7a3bd8223f4485f7dda80dcfd7 at: https://64d3c5d9d41d05008f880999--meshery-docs-preview.netlify.app

2023-08-09 17:05 UTC, l5io commented
🚀 Preview for commit 639f4103177f1ca35796ca6fdb31d6b345790618 at: https://64d3c72489a9ec073ebe5d39--meshery-docs-preview.netlify.app

2023-08-11 16:01 UTC, l5io commented
🚀 Preview for commit 3b505a05ea902cabe5d765abcefcdf917125cdc9 at: https://64d65b2a0aeedc7cdee944b5--meshery-docs-preview.netlify.app

2023-11-20 01:43 UTC, closed without merging