Mesheryctl
meshery/meshery pull request #8297
Opened 2023-07-27 14:44 UTC by EraKin575

**Notes for Reviewers**

This PR fixes #8245

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.
 

Removed system check requirements before mesheryctl login

2023-07-27 20:02 UTC, leecalcote commented
@zakisk a review here would be helpful. 👍

2023-07-28 01:02 UTC, zakisk commented
@EraKin575 please sign off your commits.

2023-07-28 05:23 UTC, hexxdump commented on mesheryctl/internal/cli/root/system/login.go
```suggestion
```

2023-07-28 05:23 UTC, EraKin575 commented
I did my signoff using this: git commit -s -m “my commit message w/signoff”. Do I have to do something else?

2023-07-28 06:30 UTC, zakisk commented
@EraKin575 your first commit isn't signed off.

2023-07-28 06:51 UTC, EraKin575 commented
> @EraKin575 your first commit isn't signed off.

Should I add the line "Signed Off by ...." by editing the commit message?

2023-07-28 07:20 UTC, zakisk commented
> > @EraKin575 your first commit isn't signed off.
> 
> Should I add the line "Signed Off by ...." by editing the commit message?

First set your git `HEAD` to unsigned commit and then run `git commit --amend -s --no-edit` and then force the push. See a tutorial on this, ChatGPT would be better.

2023-07-28 20:50 UTC, leecalcote commented
> > > @EraKin575 your first commit isn't signed off.
> > 
> > 
> > Should I add the line "Signed Off by ...." by editing the commit message?
> 
> First set your git `HEAD` to unsigned commit and then run `git commit --amend -s --no-edit` and then force the push. See a tutorial on this, ChatGPT would be better.

@zakisk please point contributors to the project's contributing docs (not chatgpt) - https://docs.meshery.io/project/contributing#general-contribution-flow

2023-07-28 20:51 UTC, leecalcote commented
For this PR specifically, execute these git commands - https://github.com/meshery/meshery/pull/8297/checks?check_run_id=15423783353

2023-07-28 21:15 UTC, yash37158 commented
Hello @EraKin575, we appreciate your interest in contributing to meshery ! Kindly refrain from creating PRs without assignment to ensure task allocation, and code quality, and avoid conflicts.

2023-07-29 10:53 UTC, suhail34 requested changes

2023-07-29 10:53 UTC, suhail34 commented on .github/label-commenter-config.yml
> +         To amend the commits in this PR with your signoff using the instructions provided in the DCO check. \n\n
```suggestion
         To amend the commits in this PR with your signoff using the instructions provided in the DCO check above. \n\n
```
Please remove this changes Why did you made this changes

2023-07-31 04:12 UTC, leecalcote approved these changes
LGTM

2023-07-31 04:12 UTC, merged

2023-07-31 10:01 UTC, EraKin575 commented
Thanks!