Resolve indefinite hang during  mesheryctl system login with an active Meshery Cloud session
meshery/meshery pull request #8299
Opened 2023-07-27 20:37 UTC by yash37158

**Notes for Reviewers**

This PR fixes #8247 
Fixed the indefinite hang during `mesheryctl system login` with an active Meshery Cloud session

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-07-27 20:54 UTC, yash37158 commented
here is the reference:
[Click to watch the video](https://youtu.be/2PXeEp4LrWg)

2023-07-27 20:54 UTC, yash37158 commented
// @abdullah1308 @Chadha93 @leecalcote

2023-07-27 20:55 UTC, leecalcote commented
Thanks for posting a video.

2023-07-27 20:55 UTC, leecalcote commented
@zakisk review?

2023-07-27 20:58 UTC, yash37158 commented
You are always welcome @leecalcote, I also mentioned a bug in meshery cloud on Slack if you can spread some light on that too

2023-07-28 00:39 UTC, zakisk commented
> @zakisk review?

Yes

2023-07-28 20:40 UTC, leecalcote commented
@zakisk [this failure](https://github.com/meshery/meshery/actions/runs/5695534531/job/15438880533?pr=8299#step:5:12) is unrelated to this PR. Is this something that you can look into?

2023-07-31 10:02 UTC, yash37158 commented
Hey @leecalcote, @Chadha93, @abdullah1308 are we good to merge this?

2023-07-31 10:41 UTC, zakisk commented
> @zakisk [this failure](https://github.com/meshery/meshery/actions/runs/5695534531/job/15438880533?pr=8299#step:5:12) is unrelated to this PR. Is this something that you can look into?

@leecalcote this error error is same as we've got [here](https://github.com/meshery/meshery/pull/8272#issuecomment-1650064762) it as well, I am finding its solution. it wiil may be a `good first issue` or could be complex if it is used in project on many places and needs to be changed on every place with precaution.

2023-07-31 10:50 UTC, zakisk commented
@leecalcote I've checked and I think that it can be a `good first issue` because [json.RawMessage](https://pkg.go.dev/encoding/json#RawMessage) is nothing but a wrapper to `[]byte` type. it is used in project on many places but as json.RawMessage's underlying type is []byte it wouldn't cause any problem, what's your take about this?

2023-08-02 11:16 UTC, vishalvivekm commented
@yash37158 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-08-02 19:57 UTC, leecalcote commented
> @leecalcote I've checked and I think that it can be a `good first issue` because [json.RawMessage](https://pkg.go.dev/encoding/json#RawMessage) is nothing but a wrapper to `[]byte` type. it is used in project on many places but as json.RawMessage's underlying type is []byte it wouldn't cause any problem, what's your take about this?

It'd be good to hear from @hexxdump

2023-08-04 09:12 UTC, hexxdump commented
> > @leecalcote I've checked and I think that it can be a `good first issue` because [json.RawMessage](https://pkg.go.dev/encoding/json#RawMessage) is nothing but a wrapper to `[]byte` type. it is used in project on many places but as json.RawMessage's underlying type is []byte it wouldn't cause any problem, what's your take about this?
> 
> It'd be good to hear from @hexxdump

Clearly, RawMessage has advantages over plain []byte, however we are introducing a new package (encoding/json) dependency here. 
Before deciding whether to choose RawMessage or not, it would be good to root cause why the parsing failed in [here](https://github.com/meshery/meshery/actions/runs/5695534531/job/15438880533?pr=8299#step:5:12) and [here](https://github.com/meshery/meshery/actions/runs/5657521386/job/15326944619?pr=8272#step:5:31)

2023-08-08 18:58 UTC, yash37158 commented
Hey @leecalcote @suhail34 @abdullah1308  reminder for this PR

2023-08-09 21:05 UTC, suhail34 requested changes
I wasn't having auth.json file and was logged in to meshery cloud this what auth.json looked like after running `mesheryctl system login`
![image](https://github.com/meshery/meshery/assets/77241166/5279ee4f-1b4d-48d9-8a65-d39ab183de25)

2023-08-09 21:05 UTC, suhail34 commented
Will debug why does this happened

2023-08-10 10:38 UTC, abdullah1308 commented on mesheryctl/pkg/utils/auth.go
> +	case <-time.After(5 * time.Second): // Set the timeout duration as needed
@yash37158 This does not solve the issue. The issue required that `mesheryctl system login` be successful when an active meshery cloud session was already present in the browser.

Also this line causes the bug where `mesheryctl system login` finishes execution before the login is completed on the following page. This is invalid behaviour.

<img width="1399" alt="image" src="https://github.com/meshery/meshery/assets/76054921/b3cbed41-360a-498f-8324-d7d586322680">

2023-08-10 10:45 UTC, abdullah1308 commented
Closing this PR for 2 reasons -

1. The issue has not been addressed 
2. The changes made introduce bugs in `mesheryctl system login` -
     a. It can take upto 10-15 seconds to log in through SSO. If the log in isn't completed within 5 seconds, the changes make running the command useless causing the login to fail.

@yash37158 Please feel free to open another PR.

2023-08-10 16:57 UTC, yash37158 commented
Thanks for your feedback @abdullah1308, will come with a valid PR again

2023-08-11 18:20 UTC, closed without merging