modifications for codecov report to generate
meshery/meshery pull request #8478
Opened 2023-08-15 17:12 UTC by ash-kamrip

**Notes for Reviewers**

This PR fixes #7805

Hi , I've tried to update some of the golden files and commented out a few tests that needs modification , this PR should fix the current unit tests so that we can get updated code coverage. 

P.S i am not able to fix any of the integration test so those will def fail 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-08-15 17:22 UTC, l5io commented
🚀 Preview for commit 4934d78f89fdeb824f5f086e378ebdad48c4d139 at: https://64dbb45544a2fb0986d358d6--meshery-docs-preview.netlify.app

2023-08-15 17:49 UTC, l5io commented
🚀 Preview for commit 318648b975bd54aa2989a9600ac697b5ac9ce41b at: https://64dbba918254031268fd590b--meshery-docs-preview.netlify.app

2023-08-15 20:07 UTC, l5io commented
🚀 Preview for commit c8370e068e1773e08828b6ae194262680c4ced4a at: https://64dbdae35df0102d5e60f4c9--meshery-docs-preview.netlify.app

2023-08-15 20:14 UTC, Philip-21 commented on mesheryctl/doc/cmds.yml
> +usage: test [flags]
I would like to know why this file was created, it seems you added the test keyword to be detected for the test coverage ?

2023-08-15 20:17 UTC, Philip-21 reviewed
@ash-kamrip alot of changes here, the code coverage rate currently seems to increase to 19%
also when you ran these test that you changed were outputs generated successfully ?

2023-08-15 20:30 UTC, Philip-21 commented
@ash-kamrip i have dropped some comments here , please you can give a brief description of what you implemented so we can know where we are headed at. I want to work on some oter unit tests genearting errors i want to follow your approach but i need to understand why  certain things were implemented

2023-08-15 20:44 UTC, Philip-21 commented
there seems to be an issue with the Error [codes](https://github.com/meshery/meshery/actions/runs/5871215689/job/15920035007?pr=8478) please check it out

2023-08-15 20:44 UTC, Philip-21 commented
@ash-kamrip the integration tests are failing

2023-08-16 10:28 UTC, vishalvivekm commented
@ash-kamrip Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-08-16 15:37 UTC, l5io commented
🚀 Preview for commit c8370e068e1773e08828b6ae194262680c4ced4a at: https://64dced139f7e46298dc3b8d7--meshery-docs-preview.netlify.app

2023-08-16 16:29 UTC, l5io commented
🚀 Preview for commit 6d40ef493ff132b154eef160aaf37b48a450fc56 at: https://64dcf92fe7aa1d0488bf9091--meshery-docs-preview.netlify.app

2023-08-16 16:33 UTC, l5io commented
🚀 Preview for commit da23dd5d271d5d09235b727bdc6890c3d2b2381c at: https://64dcfa4cf2b35106f55488cb--meshery-docs-preview.netlify.app

2023-08-16 17:25 UTC, suhail34 requested changes
Please remove the changes you made to error-code-updates.yaml it isn't needed as it is not a private repo that it would require github access token to checkout

2023-08-16 17:53 UTC, ash-kamrip commented
Oopsies will remove them ! my bad wanted to commit to the other branch

2023-08-16 18:00 UTC, l5io commented
🚀 Preview for commit 4550228388e277533e251336a1beed704592cecb at: https://64dd0eafa975f20e3a81d849--meshery-docs-preview.netlify.app

2023-08-16 18:35 UTC, l5io commented
🚀 Preview for commit 318648b975bd54aa2989a9600ac697b5ac9ce41b at: https://64dd16b5e4ec051608da3fd6--meshery-docs-preview.netlify.app

2023-10-06 08:31 UTC, closed without merging