added wrapper function for json parsing
meshery/meshery pull request #8556
Opened 2023-08-21 08:05 UTC by EraKin575

**Notes for Reviewers**

This PR fixes #8496

Added a wrapper function for json parsing

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-08-21 08:09 UTC, l5io commented
🚀 Preview for commit 00eeb6b19fc07dbe9239ebf8aef56ef31ab929ac at: https://64e31b7b7de90c60886c42f1--meshery-docs-preview.netlify.app

2023-08-22 05:01 UTC, leecalcote requested changes
1. Don't change older versions of the docs. Those snapshots are frozen in time.
2. Don't intermix json.parse for docs (not part of the original request) with the originally requested Meshery UI changes.

2023-08-22 09:16 UTC, EraKin575 commented
@leecalcote so I have to wrap every JSON.parse except the docs, right?

2023-08-22 09:29 UTC, leecalcote commented
> @leecalcote so I have to wrap every JSON.parse except the docs, right?

@EraKin575 you have to execute on the original request by making changes to Meshery UI.

2023-08-22 10:45 UTC, l5io commented
🚀 Preview for commit 2e9e30bef184f91c0369085ca7490b68ab9d39aa at: https://64e49194dafe34027b6e5472--meshery-docs-preview.netlify.app

2023-08-22 20:43 UTC, leecalcote requested changes

2023-08-22 20:43 UTC, leecalcote commented on docs/assets/js/lightbox.js
> +import jsonParse from "../../../ui/components/ConnectionWizard/helpers/parseJson";
No docs updates requested.

2023-08-23 04:31 UTC, vishalvivekm commented
@EraKin575 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-08-23 04:32 UTC, EraKin575 commented
sure thing @vishalvivekm

2023-09-05 02:59 UTC, aabidsofi19 requested changes
@EraKin575   rename this to `safeJsonParse` and  add jsDoc comments  . then we are good to merge

2023-09-09 17:22 UTC, leecalcote commented
@EraKin575 merge conflict...

2023-09-09 18:32 UTC, l5io commented
🚀 Preview for commit efd06baf552c9ea5e951adc67c8f3f8c5379edb1 at: https://64fcba2f130f941068f25ddf--meshery-docs-preview.netlify.app

2023-09-10 09:42 UTC, l5io commented
🚀 Preview for commit fc508dba5b7e312a7ec1919671b5879bdbbbea24 at: https://64fd8f6bfa00dc0452fbc0af--meshery-docs-preview.netlify.app

2023-09-14 06:56 UTC, EraKin575 commented
@aabidsofi19

2023-09-14 08:24 UTC, l5io commented
🚀 Preview for commit 9a5c41eee00c1852ec781f566ff19b7bd7560b91 at: https://6502c3245cd4a732161e7251--meshery-docs-preview.netlify.app

2023-09-16 08:15 UTC, sudhanshutech commented
@EraKin575 there is still docs changes which is not needed, revert any change made to docs

2023-09-17 08:11 UTC, l5io commented
🚀 Preview for commit d9b11d4a41f69e9ed9794acf0b164c41b53d4507 at: https://6506b49b0c4f2c173f04bda9--meshery-docs-preview.netlify.app

2023-09-17 08:15 UTC, l5io commented
🚀 Preview for commit 0ce4909521c326927b1ec38b671714555d473585 at: https://6506b57c30d1f517158a9d19--meshery-docs-preview.netlify.app

2023-09-17 09:19 UTC, l5io commented
🚀 Preview for commit b13aeb390bd02e547ab857e63f1490c2ad429932 at: https://6506c49dfbb37b1e97cf0b5d--meshery-docs-preview.netlify.app

2023-11-07 19:04 UTC, closed without merging