fixed mispelling on the connections page
meshery/meshery pull request #8615
Opened 2023-08-29 23:38 UTC by vobanghia12

**Notes for Reviewers**

This PR fixes #8612

This PR fixes UI Misspelling in connections page #8612

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-08-30 08:05 UTC, vishalvivekm commented
@vobanghia12 Let's discuss this on Meshery Dev call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#) if you would. :)

2023-08-30 09:06 UTC, AugustasV requested changes

2023-08-30 13:37 UTC, vobanghia12 commented on ui/components/Dashboard/ConnectionCharts.js
> +          .filter((data) => isValidColumnName(data.status))
It's just because of prettier extension

2023-08-30 16:06 UTC, Ckbhatia commented on ui/components/Dashboard/ConnectionCharts.js
> +          .filter((data) => isValidColumnName(data.status))
You need to undo this change if it's due to your personal preference settings. It's totally unnecessary until it was badly formatted or not following project-level preferences.

2023-08-30 16:07 UTC, vobanghia12 commented on ui/components/Dashboard/ConnectionCharts.js
> +          .filter((data) => isValidColumnName(data.status))
Ok thanks I got it

2023-09-04 19:31 UTC, leecalcote commented on ui/components/Dashboard/ConnectionCharts.js
> +          .filter((data) => isValidColumnName(data.status))
@vobanghia12 will you be correcting this in the current PR or closing and opening a new one?

@Ckbhatia thank you for your reviews. Most helpful. 💯

2023-09-04 19:34 UTC, closed without merging

2023-09-04 19:34 UTC, vobanghia12 commented on ui/components/Dashboard/ConnectionCharts.js
> +          .filter((data) => isValidColumnName(data.status))
@leecalcote yes I closed it thanks