added registrant_columns
meshery/meshery pull request #8670
Opened 2023-09-06 12:38 UTC by Freedisch

**Notes for Reviewers**

This PR fixes #8225 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-09-06 14:14 UTC, Freedisch commented
Not yet ready, missing a few updates

2023-09-06 18:24 UTC, leecalcote requested changes
@sudhanshutech @Freedisch there seems to be a missing colspan; the row border under duplicates doesn't extend to registrants.

2023-09-07 02:27 UTC, leecalcote commented
@Freedisch will you provide an example response of from the API that shows all duplicates?

2023-09-07 11:49 UTC, Freedisch commented
> @Freedisch will you provide an example response of from the API that shows all duplicates?

I don't think duplicates are being returned in the response, but I will update my Meshery version and check

2023-09-07 17:37 UTC, leecalcote commented on ui/components/MeshModelComponent.js
> +        sort : view === COMPONENTS || view === RELATIONSHIPS ? true : false,
@aabidsofi19 thoughts?

2023-09-07 17:37 UTC, leecalcote commented on ui/components/MeshModelComponent.js
> +        sort : view === COMPONENTS || view === RELATIONSHIPS ? true : false,
@sudhanshutech where is data table on your revision list?

2023-09-08 05:06 UTC, aabidsofi19 requested changes

2023-09-08 05:06 UTC, aabidsofi19 commented on ui/components/MeshModelComponent.js
> +        sort : view === COMPONENTS || view === RELATIONSHIPS ? true : false,
```suggestion
        sort : view === COMPONENTS || view === RELATIONSHIPS ,
```
the ternary check is not required

2023-09-08 05:06 UTC, aabidsofi19 commented on ui/components/MeshModelComponent.js
> +        searchable : view === RELATIONSHIPS ? false : true,
```suggestion
        searchable :  view !== RELATIONSHIPS 
```

2023-09-09 19:11 UTC, sudhanshutech commented on ui/components/MeshModelComponent.js
> +        searchable :  view !== RELATIONSHIPS
@leecalcote i guess a `,` missed here

2023-09-09 19:14 UTC, sudhanshutech approved these changes

2023-09-15 19:39 UTC, Chadha93 commented
@sudhanshutech Will yo please takeover this PR?

2023-09-18 03:11 UTC, sudhanshutech commented
> @sudhanshutech Will yo please takeover this PR?

okay

2023-11-08 12:44 UTC, closed without merging