FIXED: adapter deployment permission denied error on docker platform
meshery/meshery pull request #8694
Opened 2023-09-08 16:24 UTC by zakisk

**Notes for Reviewers**

This PR fixes #8693

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-09-09 16:06 UTC, leecalcote requested changes
@zakisk, please address failed lint checks.

@nebula-aac how does the rest of this PR look?

2023-09-09 16:34 UTC, zakisk commented
> @zakisk, please address failed lint checks.
> 
> @nebula-aac how does the rest of this PR look?

@leecalcote sure!

2023-09-13 21:09 UTC, leecalcote commented on mesheryctl/internal/cli/root/system/start.go
> +			return errors.Wrap(err, utils.SystemError("unable to add group_add option"))
```suggestion
			return errors.Wrap(err, utils.SystemError("unable to add group_add option. Meshery Server cannot perform this privileged action"))
```

2023-09-13 21:10 UTC, leecalcote commented
@zakisk we're not getting all of Meshery Server's errors sent to the /apis/events, are we?

For instance, I see this error on stdout, but not via Meshery UI:

```
ERRO[2023-09-13T16:07:12-05:00] the platform local is not supported currently. The supported platforms are: Docker and Kubernetes  app=meshery code=1231 probable-cause="Your platform is not supported for deploying Meshery Adapters" severity=3 short-description="Unable to deploy Meshery Adapter in the current environment" suggested-remediation="Consider using a supported platform for deploying Meshery Adapters"
```

I wonder if you can help with this in a separate PR.

@MUzairS15 guidance?

2023-09-13 21:15 UTC, merged

2023-09-14 12:24 UTC, zakisk commented
> @zakisk we're not getting all of Meshery Server's errors sent to the /apis/events, are we?
> 
> For instance, I see this error on stdout, but not via Meshery UI:
> 
> ```
> ERRO[2023-09-13T16:07:12-05:00] the platform local is not supported currently. The supported platforms are: Docker and Kubernetes  app=meshery code=1231 probable-cause="Your platform is not supported for deploying Meshery Adapters" severity=3 short-description="Unable to deploy Meshery Adapter in the current environment" suggested-remediation="Consider using a supported platform for deploying Meshery Adapters"
> ```
> 
> I wonder if you can help with this in a separate PR.
> 
> @MUzairS15 guidance?

will check and let you know.

2023-09-14 18:05 UTC, leecalcote commented
@zakisk will you open an issue? If not, @MUzairS15 will you carry this forward?