Connections row expand data with styling
meshery/meshery pull request #8840
Opened 2023-09-20 13:50 UTC by senali-d

**Notes for Reviewers**

This PR fixes #

<img width="1512" alt="connection" src="https://github.com/meshery/meshery/assets/52546856/f85a6a89-a02f-4807-aa17-7f22701f36fe">

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-09-20 16:10 UTC, MUzairS15 requested changes

2023-09-20 16:10 UTC, MUzairS15 commented on ui/components/connections/index.js
> +            <Tooltip title={tableMeta.rowData[1]} placement="top" >
Can we move away from this type of indexing? Since the data is structured we know what attribute is on which index, this avoids future confusion.

2023-09-20 16:10 UTC, MUzairS15 commented on ui/components/connections/index.js
> +                          {/* <List>
Pls remove commented code.

2023-09-20 16:45 UTC, leecalcote commented on ui/components/connections/index.js
> +    [theme.breakpoints.down(1050)] : {
@senali-d is the the same approach that we're using in Cloud? If not, can we shift?

2023-09-20 16:46 UTC, leecalcote requested changes

2023-09-23 00:55 UTC, leecalcote approved these changes
Moving forward with merge. Hardcoding to be addressed in subsequent PR.

2023-09-23 00:55 UTC, merged