[UI] Converted MesheryPerformanceComponent from class-based to functional component
meshery/meshery pull request #9075
Opened 2023-10-11 15:12 UTC by captain-Akshay

#8975

**Notes for Reviewers**
This PR fixes #8814 

## Results:-

### After the conversion of class based to functional component

[Screencast from 2023-10-01 13-38-49.webm](https://github.com/meshery/meshery/assets/59491379/83598bb7-39f6-462e-a226-01264456f830)

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2023-10-11 15:14 UTC, captain-Akshay commented
@aabidsofi19  do take a look on this one!

2023-10-12 15:02 UTC, Yashsharma1911 reviewed
Some good work here @captain-Akshay

2023-10-12 15:02 UTC, Yashsharma1911 commented on ui/components/MesheryPerformance/index.js
> +                      <HelpOutlineOutlinedIcon style={{ color: '#929292' }} />
We should use theme reference color

2023-10-12 17:19 UTC, captain-Akshay commented on ui/components/MesheryPerformance/index.js
> +                      <HelpOutlineOutlinedIcon style={{ color: '#929292' }} />
Ok sure!

2023-10-12 17:19 UTC, captain-Akshay commented on ui/components/MesheryPerformance/index.js
> +  //   useState(false);
OK :+1:

2023-10-13 06:50 UTC, captain-Akshay commented
@Yashsharma1911 the two helper functions are only used in this file, & i wasn't able to locate the theme section for tooltip icon color so made it into a class as the other css for consistency

2023-10-17 17:13 UTC, Ckbhatia requested changes

2023-10-17 17:14 UTC, Ckbhatia commented on ui/components/MesheryPerformance/index.js
> +import { useEffect } from 'react';
Critical

2023-10-17 19:08 UTC, saurabh100ni commented
Thanks for raising the PR, let's Discuss this in the Meshery Development Call today,
Please add this as an agenda in the Doc : [Doc](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit)

2023-10-18 12:15 UTC, aabidsofi19 commented
@captain-Akshay  is the work here complete

2023-10-21 09:46 UTC, aabidsofi19 commented
@captain-Akshay  merging this .  please keep an eye on any bugs arising ( incase )

2023-10-21 09:46 UTC, merged