Zubyyy
meshery/meshery pull request #9126
Opened 2023-10-16 14:52 UTC by Zubiii333

**Notes for Reviewers**

This PR fixes #
Signed Off Commits and added a few QnAs

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-10-16 14:56 UTC, l5io commented
🚀 Preview for commit fceb39a6b05f374eb901f0436d1ee59ec70dda21 at: https://652d4ef3d153d521b3151ceb--meshery-docs-preview.netlify.app

2023-10-16 14:58 UTC, abhijeetgauravm commented
Hey @Zubiii333, please edit the PR description to include the issue it's fixing. This will make it easier for reviewers to review the PR.

2023-10-16 16:55 UTC, leecalcote requested changes

2023-10-17 12:25 UTC, leecalcote commented on docs/pages/project/FAQ.md
> +**Answer:** _Meshery is an open source, vendor neutral project that facilitates testing across meshes. Other performance benchmark tools are not packaged into a mesh testing utility, but are only loa
@Zubiii333 message when you have changed this.

2023-10-17 16:53 UTC, l5io commented
🚀 Preview for commit 42900a415c530e6e089ce84c3ced0d4780fa79be at: https://652ebc007008be35274e8f92--meshery-docs-preview.netlify.app

2023-10-17 19:10 UTC, saurabh100ni commented
Thanks for raising the PR, let's Discuss this in the Meshery Development Call today,
Please add this as an agenda in the Doc : [Doc](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit)

2023-10-18 23:20 UTC, leecalcote commented on docs/pages/project/FAQ.md
> +**Answer:** _Meshery is a powerful tool for managing ​service meshes and ​Kubernetes infrastructure. It seamlessly integrates with different service meshes and offers extensibility through dedicated
```suggestion
**Answer:** _Meshery is a powerful tool for managing ​Kubernetes infrastructure. It seamlessly integrates with different hundreds of tools and offers extensibility through many different [extension points]({{site.baseurl}}/extensibility/#extension-points). With Meshery, you can easily discover your environment, collaboratively manage multiple Kubernetes clusters, connect your Git and Helm repos, and analyze app and infra performance._
```

2023-10-18 23:21 UTC, leecalcote commented on docs/pages/project/FAQ.md
> +**Answer:** _No, as the cloud native management plane, Meshery provisions and manages the lifecycle of service meshes and all other kinds of cloud native infrastructure._
```suggestion
```

2023-10-18 23:21 UTC, leecalcote approved these changes

2023-10-18 23:21 UTC, merged