updtaing twitter logo to x
meshery/meshery pull request #9155
Opened 2023-10-20 08:20 UTC by akagami-harsh

**Notes for Reviewers**

This PR fixes #
- updating twitter logo to x 
- not tested!

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-10-20 08:23 UTC, l5io commented
🚀 Preview for commit 5d428b526ca4499c764616fcb5320c04bb3260b5 at: https://653238ee1529747a56856191--meshery-docs-preview.netlify.app

2023-10-20 09:08 UTC, l5io commented
🚀 Preview for commit fd82a857afe36b51816e5914bf7809c83d6f7c02 at: https://653243723cc9eb029b3ab134--meshery-docs-preview.netlify.app

2023-10-20 09:08 UTC, l5io commented
🚀 Preview for commit fd82a857afe36b51816e5914bf7809c83d6f7c02 at: https://6532437c2d9aba7fd921e41e--meshery-docs-preview.netlify.app

2023-10-24 05:11 UTC, leecalcote requested changes
Thanks for this PR, @akagami-harsh 👍

2023-10-24 05:11 UTC, leecalcote commented on ui/package-lock.json
Will you undo / remove changes to the package-lock.json?

2023-10-24 05:22 UTC, akagami-harsh commented on ui/package-lock.json
Done!

2023-10-24 05:26 UTC, l5io commented
🚀 Preview for commit 0cc9fc5a81a7b0ac37ac44d3d49620c17c8d623a at: https://653755397b046325e68d417b--meshery-docs-preview.netlify.app

2023-10-24 06:07 UTC, l5io commented
🚀 Preview for commit faa3070992a12fa91192d184aa3b35765796503e at: https://65375ec813f95e2d6590ed6c--meshery-docs-preview.netlify.app

2023-10-24 06:24 UTC, vishalvivekm commented
on [homepage](https://docs.meshery.io): 
<img width="712" alt="Screenshot 2023-10-24 114856" src="https://github.com/meshery/meshery/assets/110674407/ee4c8e8e-f842-478a-ac7b-f05e232ed5a2">

2023-10-24 06:30 UTC, l5io commented
🚀 Preview for commit aef7531a532a4859491feef074ea37bd0929c694 at: https://653764424b582932576e3795--meshery-docs-preview.netlify.app

2023-10-24 06:30 UTC, vishalvivekm approved these changes
LGTM.
Thanks @akagami-harsh

2023-10-24 09:21 UTC, Yashsharma1911 requested changes
nice work @akagami-harsh, it seems X logo is small compared to other logos, can you make sure it is similar in height and width to other logos

![Screenshot 2023-10-24 at 2 50 41 PM](https://github.com/meshery/meshery/assets/71271069/33a9a0f3-80ef-45e8-bd62-f35d47f813c3)

2023-10-24 10:19 UTC, l5io commented
🚀 Preview for commit e10c63aa4ac0177a5cc83d710724817fb0e06506 at: https://653799e89d171b12fff2259a--meshery-docs-preview.netlify.app

2023-10-24 11:02 UTC, l5io commented
🚀 Preview for commit e4f96b7079f1608b9b337ce535e083dd6c1aa876 at: https://6537a3ed3bd3db19df34c649--meshery-docs-preview.netlify.app

2023-10-24 11:39 UTC, l5io commented
🚀 Preview for commit bcf6ff00a13e9f24b17ade42cdf50b9e2f06aafb at: https://6537aca98fdc6b216a9ef135--meshery-docs-preview.netlify.app

2023-10-24 16:06 UTC, l5io commented
🚀 Preview for commit 42d554804c22a2b2c93ff7021d3cf25af830a547 at: https://6537eb64313ef6142491c1a0--meshery-docs-preview.netlify.app

2023-10-24 19:00 UTC, saurabh100ni commented
Let's discuss this on the Meshery dev call tomorrow at 7:30 pm IST / 9:00 am CT,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

2023-10-25 20:44 UTC, l5io commented
🚀 Preview for commit 59d2eb70a4e31d1a863855ecd72dd9e064ec604b at: https://65397e079c5ddb2ce7b347af--meshery-docs-preview.netlify.app

2023-10-25 21:11 UTC, Yashsharma1911 approved these changes
Thanks @akagami-harsh LGTM

2023-10-25 21:13 UTC, merged