[mesheryctl] fixed meshery start command bug with adapter components
meshery/meshery pull request #9160
Opened 2023-10-21 06:45 UTC by zakisk

**Notes for Reviewers**

This PR fixes #9149

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-10-21 19:00 UTC, leecalcote commented
There are a couple of these that you might be able to tackle at the same time, @zakisk - SA1019: cliflags.NewCommonOptions is deprecated

2023-10-21 19:01 UTC, leecalcote commented
What other commands other than `start` will now need to be updated to use this new Compose manifest reference?

2023-10-24 01:57 UTC, leecalcote requested changes
@zakisk please fix the two failing lint checks.

2023-10-24 04:41 UTC, leecalcote approved these changes
@zakisk let's move forward prematurely (before lint checks are fixed) in order to include this bug fix in today's release.

2023-10-24 04:42 UTC, merged

2023-10-25 04:09 UTC, hexxdump commented on mesheryctl/internal/cli/root/system/start.go
>  		//changing the port mapping in docker compose
This comment becomes obsolete now, isnt it ?
We are programmatically reading the port mapping from helpers.go rather than the docker compose file.