[Docs] TOC: Add section describing the use of children and grandchildren
meshery/meshery pull request #9172
Opened 2023-10-23 18:20 UTC by coder12git

**Notes for Reviewers**

This PR fixes #9165

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-10-23 18:24 UTC, l5io commented
🚀 Preview for commit e13fd4d19608d69721162416ba05601accc4387b at: https://6536ba44086c4f6e6e4ce620--meshery-docs-preview.netlify.app

2023-10-23 18:30 UTC, coder12git commented
@leecalcote here it is :)

2023-10-23 21:02 UTC, leecalcote approved these changes

2023-10-23 21:03 UTC, leecalcote commented on docs/pages/project/contributing/contributing-docs.md
> +In the Sidebars, overall we have three sections -
```suggestion
In `docs/_includes/sidebar.html` contains three levels of navigation hierarchy.
```

2023-10-23 21:04 UTC, leecalcote commented on docs/pages/project/contributing/contributing-docs.md
> +
@coder12git, where does `links:` fit into all this?

2023-10-23 21:04 UTC, leecalcote requested changes

2023-10-23 21:04 UTC, leecalcote commented on docs/pages/project/contributing/contributing-docs.md
> +
@coder12git, where does `links:` fit into all this?

2023-10-24 05:56 UTC, l5io commented
🚀 Preview for commit 68fb82628c701bc709ede065b5c9db5317ade9e7 at: https://65375c6df75c7a28e22bfa0d--meshery-docs-preview.netlify.app

2023-10-24 18:59 UTC, saurabh100ni commented
Let's discuss this on the Meshery dev call tomorrow at 7:30 pm IST / 9:00 am CT,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

2023-10-27 18:58 UTC, leecalcote commented on docs/pages/project/contributing/contributing-docs.md
> +- **Parent**: It serves as a top level category for related content.
Parent isn't explicitly a thing, so please ensure that you are listing implicitly.

2023-10-27 18:59 UTC, leecalcote commented
@coder12git should I continue to follow up on this PR or is it closing in favor of Debaditya's?

2023-10-27 19:02 UTC, coder12git commented
> @coder12git should I continue to follow up on this PR or is it closing in favor of Debaditya's?

I think, both PR's are different, his PR is about alerts. html file, so i believe we shouldn't merge both in one PR, rest up to you, whatever you prefer it's fine from my end.

2023-10-30 18:18 UTC, leecalcote submitted a review, later dismissed
Thank you for this, @coder12git 💯

2023-10-30 18:19 UTC, leecalcote commented
@coder12git, will you follow up on the merge conflict at your convenience? Good to go afterwards.

2023-10-30 18:47 UTC, l5io commented
🚀 Preview for commit e61a3de879ab0fc1add3b287ed4a2ccac0903e60 at: https://653ffa14c2f8ba2eb64769c3--meshery-docs-preview.netlify.app

2023-10-30 21:04 UTC, merged