Enhanced contributing-docs.html
meshery/meshery pull request #9179
Opened 2023-10-24 10:24 UTC by Debaditya-Som

**Notes for Reviewers**

Changes Made:

- Added a new section in https://docs.meshery.io/project/contributing/contributing-docs that describes the "alerts.html" feature.
- Included a clear example of how to use the "alerts.html" feature in documentation.
- Ensured proper formatting and styling for clarity and consistency.

This PR fixes #9094 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-10-24 10:27 UTC, l5io commented
🚀 Preview for commit 0848e023b47c2bc05482d58e107633da7105f07f at: https://65379bfe063f8f156a1dbb37--meshery-docs-preview.netlify.app

2023-10-24 18:56 UTC, leecalcote commented
@coder12git would you like to review?

2023-10-24 18:58 UTC, leecalcote requested changes
Thanks for putting forth effort here, @Debaditya-Som 👍

2023-10-24 18:58 UTC, leecalcote commented on docs/v0.5/project/contributing/contributing-docs.html
The v0.5 version of the docs is archived - a snapshot in time.

2023-10-24 18:58 UTC, saurabh100ni commented
Let's discuss this on the Meshery dev call tomorrow at 7:30 pm IST / 9:00 am CT,
Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

2023-10-24 19:01 UTC, Debaditya-Som commented
> Let's discuss this on the Meshery dev call tomorrow at 7:30 pm IST / 9:00 am CT, Please add this as your agenda item in Docs: https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit

Yes surely

2023-10-24 19:03 UTC, Debaditya-Som commented
> Thanks for putting forth effort here, @Debaditya-Som 👍

You're welcome :)

2023-10-25 16:03 UTC, coder12git commented
@Debaditya-Som Let me know, what help you need :)

2023-10-25 16:13 UTC, coder12git commented
@Debaditya-Som actually you need to add a new section describing "alerts.html" in this file -`docs/pages/project/contributing/contributing-docs.md`, not the one you did

2023-10-26 05:12 UTC, Debaditya-Som commented
> @Debaditya-Som actually you need to add a new section describing "alerts.html" in this file -`docs/pages/project/contributing/contributing-docs.md`, not the one you did , that version of the docs is archived now .

Okay got it, so I need to create a section in the mentioned file. Could you tell me whether the documentation that I have done in the archived version is accurate or not?

2023-10-27 12:06 UTC, leecalcote commented
@coder12git ?

2023-10-27 12:23 UTC, coder12git commented
> > @Debaditya-Som actually you need to add a new section describing "alerts.html" in this file -`docs/pages/project/contributing/contributing-docs.md`, not the one you did , that version of the docs is archived now .
> 
> Okay got it, so I need to create a section in the mentioned file. Could you tell me whether the documentation that I have done in the archived version is accurate or not?

@Debaditya-Som looks good to be, just move the given content to the specified file!

2023-10-27 12:53 UTC, Debaditya-Som commented
> 
> @Debaditya-Som looks good to me, just move the given content to the specified file!

I have made the necessary changes, kindly review it.

2023-10-27 13:19 UTC, coder12git commented
> > @Debaditya-Som looks good to me, just move the given content to the specified file!
> 
> @leecalcote ,@coder12git I have made the necessary changes, kindly review it.



> > @Debaditya-Som looks good to me, just move the given content to the specified file!
> 
> @leecalcote ,@coder12git I have made the necessary changes, kindly review it.

Also, do the changes suggested by me in the content and  you need to revert your commits too so that only those changes will be shown in which you have done changes, in your case just this file `docs/pages/project/contributing/contributing-docs.md`.

2023-10-27 13:34 UTC, Debaditya-Som commented
> 
> Also, do the changes suggested by me in the content and you need to revert your commits too so that only those changes will be shown in which you have done changes, in your case just this file `docs/pages/project/contributing/contributing-docs.md`.

Yes, I have also made the changes that was suggested by you, only the updated commit, that is the one made in the specified file is made and the previous changes were reverted.

2023-10-27 15:48 UTC, coder12git commented
> > Also, do the changes suggested by me in the content and you need to revert your commits too so that only those changes will be shown in which you have done changes, in your case just this file `docs/pages/project/contributing/contributing-docs.md`.
> 
> Yes, I have also made the changes that was suggested by you, only the updated commit, that is the one made in the specified file is made and the previous changes were reverted.

No, it'a not, first check carefully what changes i told you to make. Check the reviews that i have wrote in both files.
Also, by reverting i mean that you need to revert your PR, so that there is only commit made inside the specified file.

2023-10-27 16:02 UTC, coder12git requested changes

2023-10-27 16:18 UTC, coder12git commented
> > Also, do the changes suggested by me in the content and you need to revert your commits too so that only those changes will be shown in which you have done changes, in your case just this file `docs/pages/project/contributing/contributing-docs.md`.
> 
> Yes, I have also made the changes that was suggested by you, only the updated commit, that is the one made in the specified file is made and the previous changes were reverted.

By revert, i mean revert your PR to only those commits which shows changes in the suggested file.

2023-10-28 04:43 UTC, Debaditya-Som commented
> 
> By revert, i mean revert your PR to only those commits which shows changes in the suggested file.

![image](https://github.com/meshery/meshery/assets/121785700/e66bdbb0-65d5-4894-845f-5db740819580)


I'm facing this error while reverting the initial commit

2023-10-28 06:10 UTC, Debaditya-Som commented
I am facing merge conflict while working on this branch, I have created a new branch and submitted a new PR : #9226 , kindly review that PR and ignore this one

2023-10-29 13:06 UTC, closed without merging