[Docs]- Fix Flickering in Links
meshery/meshery pull request #9198
Opened 2023-10-25 13:40 UTC by coder12git

**Notes for Reviewers**

This PR fixes #9196

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-10-25 13:44 UTC, l5io commented
🚀 Preview for commit 94d333d83b9a03d2775a12e6b6f70843f617c363 at: https://65391b77e54a6c1c5a574561--meshery-docs-preview.netlify.app

2023-10-25 13:46 UTC, coder12git commented
Links that flickers in https://docs.meshery.io/ -

- https://docs.meshery.io/installation/mesheryctl
- https://docs.meshery.io/installation/compatibility-matrix
- https://docs.meshery.io/project/contributing

2023-10-25 13:48 UTC, coder12git commented
// @vishalvivekm

2023-10-25 16:21 UTC, abhijeetgauravm reviewed
Looks good to me!

2023-10-26 19:17 UTC, sudhanshutech submitted a review, later dismissed

2023-10-26 19:18 UTC, sudhanshutech commented
@coder12git merge conflict

2023-10-26 21:49 UTC, leecalcote requested changes

2023-10-26 21:49 UTC, leecalcote commented on docs/pages/installation/mesheryctl.md
> - - installation/mesheryctl/
Thanks. We need to keep the redirect that has the trailing `/`.

2023-10-26 21:51 UTC, leecalcote commented on docs/pages/installation/mesheryctl.md
>  category: mesheryctl
```suggestion
category: mesheryctl
redirect_from:
 - installation/mesheryctl/
```

2023-10-26 21:51 UTC, leecalcote commented on docs/pages/project/compatibility_matrix/compatibility.md
>  permalink: installation/compatibility-matrix
```suggestion
permalink: installation/compatibility-matrix
redirect_from: 
 - project/compatibility-matrix/
 - installation/compatibility-matrix/
```

2023-10-26 21:51 UTC, leecalcote commented on docs/pages/project/contributing/contributing.md
>  description: How to contribute to the Meshery project.
```suggestion
description: How to contribute to the Meshery project.
redirect_from:
 - project/contributing/
```

2023-10-26 21:52 UTC, merged