Standardization of kubernetes.md
meshery/meshery pull request #9201
Opened 2023-10-25 14:10 UTC by aboobakersiddiqr63

**Notes for Reviewers**

This PR fixes #9199 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ✓] Yes, I signed my commits.

2023-10-25 14:14 UTC, l5io commented
🚀 Preview for commit f4933e3475baf6f05bac29bdd6a395eb73a730c2 at: https://6539227ff9afd6009479e8d5--meshery-docs-preview.netlify.app

2023-10-25 16:18 UTC, alphaX86 requested changes

2023-10-25 16:18 UTC, alphaX86 commented on docs/pages/installation/kinD.md
> +Before executing the below command, go to ~/.meshery/config.yaml and ensure that current platform is set to kubernetes.
```suggestion
Before executing the below command, go to `~/.meshery/config.yaml` and ensure that current platform is set to kubernetes.
```

2023-10-25 16:41 UTC, aboobakersiddiqr63 commented on docs/pages/installation/kubernetes.md
> +Manage your kubernetes clusters with Meshery. Deploy Meshery in kubernetes [in-cluster](#in-cluster-installation) or outside of kubernetes [out-of-cluster](#out-of-cluster-installation). **_Note: It
@alphaX86 thanks for pointing it out will fix it

2023-10-25 17:59 UTC, aboobakersiddiqr63 commented on docs/pages/installation/kubernetes.md
> +Manage your kubernetes clusters with Meshery. Deploy Meshery in kubernetes [in-cluster](#in-cluster-installation) or outside of kubernetes [out-of-cluster](#out-of-cluster-installation). **_Note: It
@alphaX86 fixed the issue :)

2023-10-25 18:02 UTC, l5io commented
🚀 Preview for commit 9f54da9c2d7d6ad47e731f5e9799d4ed84779ba2 at: https://653958131fad360f95d184de--meshery-docs-preview.netlify.app

2023-10-26 16:40 UTC, l5io commented
🚀 Preview for commit 54ded6515921a1c9f159c5ccaf7a99df92b1a102 at: https://653a96730a2f791661d5597c--meshery-docs-preview.netlify.app

2023-10-26 16:43 UTC, alphaX86 approved these changes
LGTM 👍

2023-10-26 16:47 UTC, merged