Registry Mobile View
meshery/meshery pull request #9344
Opened 2023-11-11 16:18 UTC by ptdatta

**Notes for Reviewers**

This PR fixes the registry mobile view.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2023-11-14 16:17 UTC, abhijeetgauravm commented
Hey @ptdatta  Let's discuss this on Meshery Development Meeting tomorrow at 8:30 PM IST / 9 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1Dg4Uz9rGTuGHmYZwIt47z1j5x3LmnpxD1M1SgypAkQ0/edit#).

2023-11-15 21:41 UTC, leecalcote requested changes

2023-11-15 21:41 UTC, leecalcote commented on ui/assets/styles/general/tool.styles.js
> +    [theme.breakpoints.down('sm')]: {
@ptdatta what else uses these styles? Please list here.

For each one, confirm that these changes don't have a negative affect.

2023-11-22 05:39 UTC, leecalcote commented on ui/assets/styles/general/tool.styles.js
> +    [theme.breakpoints.down('sm')]: {
@ptdatta ?

2023-11-24 20:22 UTC, closed without merging