Registryui
meshery/meshery pull request #9370
Opened 2023-11-15 18:25 UTC by ptdatta

**Notes for Reviewers**

This PR fixes 
1. Rounded and Square corners. ✅
2. Long vertical line. ✅
3. Remove animation. ✅
4. Each branch of the tree lazily loaded. ✅
5. Eliminate the need for the scrollbar - restyle it when it does need to be displayed.✅
6. Expand all / Collapse all to simply be standard icons. ✅
7. Eleminate X✅
8. Search doesn't work. ✅

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-11-15 21:35 UTC, leecalcote requested changes
Detailed feedback provided in Slack.

2023-11-17 11:27 UTC, sudhanshutech requested changes

2023-11-17 11:27 UTC, sudhanshutech commented on ui/utils/data-table.js
> +    console.log(data);
remove this please

2023-11-17 11:28 UTC, sudhanshutech commented
at certain width when the search expands hide the collapse icons and switcher and again visible as the search closes
![image](https://github.com/meshery/meshery/assets/90546692/3d5e015d-6238-41c8-a72b-8cfc4dc9c7df)

2023-11-17 11:30 UTC, sudhanshutech commented
remove the count from tabs after certain width you will get some extra space
![image](https://github.com/meshery/meshery/assets/90546692/662897d2-e0b8-4f13-be51-b90dc5652a07)

2023-11-17 11:31 UTC, sudhanshutech commented
Make the tabs horizonal scroll when they start squezing

2023-11-17 11:33 UTC, sudhanshutech commented
Have you thought any thing for this @ptdatta ?    // @ritiksaxena124 

![image](https://github.com/meshery/meshery/assets/90546692/7648d990-7b32-4030-9888-b10dd20010dc)

2023-11-17 11:36 UTC, sudhanshutech commented
@ritiksaxena124 after certain width can be remove overview tab and instead display a back arrow icon ? // @ptdatta

2023-11-17 12:04 UTC, ptdatta commented
@sudhanshutech actually there is another PR which contains the registry mobile view which not yet merged.

2023-11-17 22:21 UTC, leecalcote commented
```
#28 216.8 Module not found: Can't resolve 'styled-jsx/server' in '/ui/pages'
```

2023-11-18 03:24 UTC, ritiksaxena124 commented
> @ritiksaxena124 after certain width can be remove overview tab and instead display a back arrow icon ? // @ptdatta

We are completely removing the Overview tab. It will only be shown when the user clicks the `Registry` tab.

2023-11-19 14:06 UTC, leecalcote commented
Resyncing fork.

2023-11-19 14:08 UTC, leecalcote commented
While the Registry may still have bugs that @ptdatta _will immediately fix_, we might be able to accept the current set of fixes so that existing users can stop suffering with the current implementation in the meantime. @ptdatta _hurry up_.

2023-11-20 03:38 UTC, leecalcote commented
@ptdatta done?

2023-11-20 03:39 UTC, merged

2023-11-20 03:47 UTC, ptdatta commented
> @ptdatta done?

Yes✅