Use proper svgs for connections
meshery/meshery pull request #9388
Opened 2023-11-18 11:15 UTC by sudhanshutech

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-11-19 09:26 UTC, MUzairS15 requested changes
https://github.com/meshery/meshery/assets/79860504/a2ea632a-3b3e-46b4-8627-71b596ee8be7

The adapter synthetic check doesn't work.

2023-11-19 09:33 UTC, MUzairS15 requested changes

2023-11-19 09:33 UTC, MUzairS15 commented on ui/components/MeshConfigComponent.js
> +                handleKubernetesClick(data[tableMeta.rowIndex].connection_id, tableMeta.rowIndex)
https://github.com/meshery/meshery/pull/9388/files#diff-9514a9ef762e5d87704d59bd30ae5c0a1744322ddcc1bda1a51034bacf4ff690R260 Delete this func, and use the k8s hook.

2023-11-19 09:33 UTC, MUzairS15 commented on ui/components/MeshConfigComponent.js
> +                                tooltip={`Server: ${contexts[rowMetaData.rowIndex].server}`}
Make the server URL clickable if not already.

2023-11-19 09:33 UTC, MUzairS15 commented on ui/components/MeshConfigComponent.js
> +                                    label={'NATS'}
```suggestion
                                    label={'Meshery Broker'}
```

2023-11-19 09:33 UTC, MUzairS15 commented on ui/components/MeshConfigComponent.js
> +                                    label={'NATS'}
https://github.com/meshery/meshery/pull/9388/files#diff-9514a9ef762e5d87704d59bd30ae5c0a1744322ddcc1bda1a51034bacf4ff690R795
Same thing here.

2023-11-19 09:33 UTC, MUzairS15 commented on ui/components/MeshConfigComponent.js
> +                                    label={'NATS'}
And here as well.
https://github.com/meshery/meshery/pull/9388/files#diff-9514a9ef762e5d87704d59bd30ae5c0a1744322ddcc1bda1a51034bacf4ff690R800

2023-11-19 11:59 UTC, sudhanshutech commented
ok i will update the changes, i will be travelling to college for exams so i will try to fix asap

2023-11-21 22:45 UTC, leecalcote commented
Thanks, @sudhanshutech. Heads-up: merge conflict.

2023-11-24 23:45 UTC, leecalcote commented
Thanks, @sudhanshutech. Heads-up: merge conflict.

2023-11-26 23:12 UTC, leecalcote requested changes
Chips still don't invoke an ad hoc connectivity test on click, @sudhanshutech

2023-11-26 23:12 UTC, leecalcote commented
Let me know when you have actually fixed this and it is ready for re-testing, @sudhanshutech

2023-12-28 05:15 UTC, leecalcote commented
> Let me know when you have actually fixed this and it is ready for re-testing, @sudhanshutech

@sudhanshutech, ping

2023-12-28 05:15 UTC, leecalcote commented
Merge conflicts.

2023-12-28 09:33 UTC, sudhanshutech commented
Its already been done, i guess only metrics page need a update that i will add. We will use the sistent chip so this not required now.

2023-12-28 09:33 UTC, closed without merging