[Server] MeshSync fingerprinting support.
meshery/meshery pull request #9442
Opened 2023-11-24 05:50 UTC by MUzairS15

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-11-24 23:39 UTC, leecalcote requested changes
@MUzairS15 are these failures expected?

2023-11-26 03:39 UTC, MUzairS15 commented
Meshsync package needs upgraded. Since a new meshsync is released I will upgrade.

2023-11-26 19:51 UTC, MUzairS15 commented on ui/components/configuratorComponents/MeshModel/NodeIcon.js
Sourced from extensions.
Needs to be deleted from extensions and injected as a remote component.

2023-11-26 19:51 UTC, MUzairS15 commented on ui/components/configuratorComponents/MeshModel/DesignerDrawerNodeShapes.js
Sourced from extensions.
Needs to be deleted from extensions and injected as a remote component.

2023-11-26 22:58 UTC, leecalcote requested changes
@MUzairS15 build and lint checks are still failing. Let me know when the is ready for review.

2023-11-27 10:42 UTC, MUzairS15 commented
<img width="1311" alt="Screenshot 2023-11-27 at 4 12 24 PM" src="https://github.com/meshery/meshery/assets/79860504/3c775cd1-738a-411f-8fff-601404619bac">
On local UI lint and Meshkit error utility passes.

2023-11-27 17:24 UTC, merged