[GraphQL] Update `graphql` schema
meshery/meshery pull request #9452
Opened 2023-11-25 05:49 UTC by MUzairS15

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-11-25 21:17 UTC, leecalcote requested changes
Build failures; lint failures

2023-11-25 21:18 UTC, leecalcote commented on server/internal/graphql/model/helpers.go
> +	case controllers.Undeployed:
Please link to where these statuses are documented in Meshery Docs.

2023-11-25 21:18 UTC, leecalcote commented on server/internal/graphql/model/helpers.go
> +	case controllers.Undeployed:
If they aren't, please document and include in this PR.

2023-11-26 19:38 UTC, MUzairS15 commented
> Build failures; lint failures

There aren't any build failures.

Lint failures addressed.

2023-11-26 19:39 UTC, MUzairS15 commented
Failing GraphQL validation is because of outdated workflow I assume.

2023-11-26 23:00 UTC, leecalcote commented
@MUzairS15 the UI is still failing to build.

2023-11-29 21:14 UTC, leecalcote commented
@MUzairS15 merge conflicts.

2023-11-30 14:23 UTC, merged