fix: fix bug where node name is empty
meshery/meshery pull request #9511
Opened 2023-12-01 09:44 UTC by VihasMakwana

**Notes for Reviewers**

This PR fixes #9510

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-12-01 12:21 UTC, sudhanshutech commented
@VihasMakwana can you share some screenshot that name is now displaying

2023-12-02 13:20 UTC, MUzairS15 requested changes
https://github.com/meshery/meshery/pull/9511/files#diff-aed9822aac9d7cd6ca2a26e1c5773286ea72d0946885d06fdf08dced2842a072R32  Add `undefined` check around meshsyncResource[tableMeta.rowIndex] to prevent a crash, as it may happen that data is not loaded initially.

2023-12-02 19:52 UTC, VihasMakwana commented
> https://github.com/meshery/meshery/pull/9511/files#diff-aed9822aac9d7cd6ca2a26e1c5773286ea72d0946885d06fdf08dced2842a072R32 Add `undefined` check around meshsyncResource[tableMeta.rowIndex] to prevent a crash, as it may happen that data is not loaded initially.

Hmm, this is the case with every dashboard component. I'll raise a separate PR for this check.

2023-12-02 19:53 UTC, VihasMakwana commented
> https://github.com/meshery/meshery/pull/9511/files#diff-aed9822aac9d7cd6ca2a26e1c5773286ea72d0946885d06fdf08dced2842a072R32 Add `undefined` check around meshsyncResource[tableMeta.rowIndex] to prevent a crash, as it may happen that data is not loaded initially.

Hmm, this is the case with every dashboard component. I'll raise a separate PR for this check.

2023-12-06 13:28 UTC, theBeginner86 approved these changes
LGTM.

2023-12-06 18:51 UTC, MUzairS15 commented
> > https://github.com/meshery/meshery/pull/9511/files#diff-aed9822aac9d7cd6ca2a26e1c5773286ea72d0946885d06fdf08dced2842a072R32 Add `undefined` check around meshsyncResource[tableMeta.rowIndex] to prevent a crash, as it may happen that data is not loaded initially.
> 
> Hmm, this is the case with every dashboard component. I'll raise a separate PR for this check.

Thanks.

2023-12-06 18:52 UTC, MUzairS15 approved these changes

2023-12-06 18:52 UTC, merged