[server][meshsync] hard reset database
meshery/meshery pull request #9545
Opened 2023-12-02 10:36 UTC by VihasMakwana

The hard reset worked partially before because we didn't reset Registries. Reset all known tables and create fresh ones with no data after.

**Notes for Reviewers**

This PR fixes #8503

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-12-02 12:32 UTC, MUzairS15 approved these changes
Don’t drop events table.

2023-12-02 12:32 UTC, MUzairS15 requested changes
Don’t drop events table.

2023-12-02 19:31 UTC, VihasMakwana commented
> Don’t drop events table.

understood.

2023-12-04 00:29 UTC, leecalcote commented on server/internal/graphql/resolver/meshsync.go
> +					r.Log.Error(err)
@VihasMakwana can this be a MeshKit-style error?

https://docs.meshery.io/project/contributing/contributing-error

2023-12-07 02:02 UTC, leecalcote approved these changes
Good work, @VihasMakwana 🥇

2023-12-07 02:02 UTC, merged