Fix GetApplicationTypes() to return []ApplicationTypeResponse.
meshery/meshery pull request #9738
Opened 2023-12-27 19:19 UTC by shanukun

`GetApplicationTypes()` should return `[]ApplicationTypeResponse` instead of `[]DesignTypeResponse`.

This PR fixes #9691

**Notes for Reviewers**

This PR fixes #

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-12-27 19:49 UTC, shanukun commented on server/models/meshery_application.go
> +		Type:                ApplicationType(HelmChart),
@theBeginner86, one of the possible solution is to make it return []ApplicationTypeResponse and explicity converting the DesignType to ApplicationType.

2023-12-28 13:33 UTC, theBeginner86 requested changes
Thanks for this.

As I mentioned earlier on the issue, please consider using the `DesignTypeResponses` construct in `mesheryctl` and don't revert back to `ApplicationTypeResponses`. Otherwise it would only lead to confusion as backend no more explicitly calls out Applications and all UI clients requests /patterns handlers due to recent migration.

2023-12-28 16:08 UTC, shanukun commented
> all UI clients requests /patterns handlers due to recent migration.

@theBeginner86 In that case, shouldn't we drop `/api/application/types` endpoint and use `/api/pattern/types` for requesting source types along with a more pertinent struct to unmarshal the json respone.

2023-12-30 14:01 UTC, theBeginner86 commented
> > all UI clients requests /patterns handlers due to recent migration.
> 
> @theBeginner86 In that case, shouldn't we just drop `/api/application/types` endpoint and use `/api/pattern/types` for requesting source types along with a more pertinent struct to unmarshal the json respone.

yes, we should. Would you like to take a crack at it and ensure that mesheryctl uses that API?

2024-01-01 07:25 UTC, theBeginner86 commented
Added a couple of updates to import 👍

2024-01-01 07:26 UTC, theBeginner86 approved these changes
Thanks @shanukun. LGTM

<img width="888" alt="Screenshot 2024-01-01 at 12 45 12 PM" src="https://github.com/meshery/meshery/assets/73700530/324d5989-5290-41aa-b953-9f16d38d0261">

> _(neglect the extraneous debug log. I had added for testing. Its not part of the actual output)_

2024-01-01 09:21 UTC, theBeginner86 commented
Lets merge this....

I am creating a new PR to update rest of the app commands and test cases 👍

2024-01-01 09:22 UTC, merged