Added new icons for MeshMap components
meshery/meshery pull request #9866
Opened 2024-01-08 11:14 UTC by nwanduka

Added icons for Kubernetes components - Token Review and Subject Access Review

**Notes for Reviewers**
I've not updated the Integrations spreadsheet yet. Waiting to get these icons approved first before I go ahead.

For the cytoscape shape, I propose we use a rounded rectangle for both icons.

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2024-01-09 10:12 UTC, sandramsc reviewed
LGTM

2024-01-09 19:07 UTC, ritiksaxena124 requested changes

2024-01-09 19:07 UTC, ritiksaxena124 commented on ui/assets/new-icons/Token Review Colored.svg
@nwanduka Thank you for this but the lock is used mostly for security or privacy.

2024-01-09 19:07 UTC, ritiksaxena124 commented on ui/assets/new-icons/Subject Access Review Colored.svg
This looks more like searching for a person. 

These icons don't fit the component you are targeting here but can be used for another component that fits.

2024-01-11 05:09 UTC, leecalcote commented
Title updated.

2024-01-11 06:11 UTC, goldfishdolphin approved these changes
Looking Good

2024-01-11 12:40 UTC, nwanduka commented on ui/assets/new-icons/Subject Access Review Colored.svg
Now that you mentioned it, it does look like we're searching for a person. Let me make some adjustments.

2024-01-11 12:40 UTC, nwanduka commented on ui/assets/new-icons/Token Review Colored.svg
Oh okay. noted. I'll update the design

2024-01-23 02:23 UTC, leecalcote approved these changes
Will reconcile any changes needed in Figma. 👍 

Thanks, @nwanduka!

2024-01-23 02:23 UTC, merged