[WIP]Tutorials
meshery/meshery pull request #9868
Opened 2024-01-08 12:14 UTC by vishalvivekm

**Notes for Reviewers**

This PR fixes #9867 
-  init tutorials collection

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-01-08 12:18 UTC, l5io commented
🚀 Preview for commit 7d74df6e4e7e42de23109fe9ee3d4e127fa4aed8 at: https://659be7f45fbe6952a078c177--meshery-docs-preview.netlify.app

2024-01-08 20:52 UTC, leecalcote requested changes
The actual layout is missing.

Should "tutorials" be located under "guides"?

2024-01-08 22:46 UTC, leecalcote commented
> The actual layout is missing.
> 
> Should "tutorials" be located under "guides"?

I see the WIP label now...

2024-01-12 14:55 UTC, leecalcote commented
ETA?

2024-01-15 14:14 UTC, vishalvivekm commented on docs/_config_dev.yml
> +
```suggestion
```

2024-01-15 14:19 UTC, l5io commented
🚀 Preview for commit d105b19e3381765b031e3294a8899548b2d6f4d2 at: https://65a53ee42043d4151577fdcd--meshery-docs-preview.netlify.app

2024-01-17 08:18 UTC, vishalvivekm commented
@leecalcote 
For now, I've used two of the random tutorials post just so that I can show the output :
- on landing page of Tutorials:  [guides/tutorials](https://65a549a6f790771f3a646268--meshery-docs-preview.netlify.app/guides/tutorials), tutorials will be listed model wise ( using model frontmatter variable) : 

<img width="883" alt="image" src="https://github.com/meshery/meshery/assets/110674407/b2a7c931-8536-420d-8946-c74061bb2837">

- Each individual tutorial, will also have suggested-reading at the bottom: 
<img width="526" alt="image" src="https://github.com/meshery/meshery/assets/110674407/8cf3ce75-f289-41ce-a1fc-88e8980eb35e">

If this looks good, I'll remove the two post and then we can merge this for now. @leecalcote

2024-02-24 01:23 UTC, leecalcote commented on docs/_layouts/tutorials.html
I wonder if you might remove this until its necessary?

or if you might add a permanent "Related Tutorials" section that would then justify a dedicated layout.

2024-02-27 17:05 UTC, vishalvivekm commented on docs/_layouts/tutorials.html
Let's keep it for now, I'll come back to this.

2024-02-27 17:07 UTC, merged