broken link issue #9991 fixed
meshery/meshery pull request #9998
Opened 2024-01-17 18:57 UTC by neerajmanivarnan

**Notes for Reviewers**
This PR fixes the broken link in the page https://docs.meshery.io/guides/configuration-management/importing-apps

This PR fixes #9991 

**[Signed commits](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-01-17 19:02 UTC, l5io commented
🚀 Preview for commit 0078f7b4139653b50462c24c7dfd55a4c33d873c at: https://65a8240bb54013059c71b0c2--meshery-docs-preview.netlify.app

2024-01-17 19:50 UTC, l5io commented
🚀 Preview for commit 9cba3eb75dad627a9a966f7e8a63ae25047cfa96 at: https://65a82f7649068a00a469b8c6--meshery-docs-preview.netlify.app

2024-01-23 02:22 UTC, leecalcote requested changes

2024-01-23 02:22 UTC, leecalcote commented on docs/pages/guides/configuration-management/importing-applications.md
> +  - /installation/quick-start.md
Wrong format, sir.

2024-01-27 03:14 UTC, neerajmanivarnan commented
This issue has been resolved

2024-01-27 03:14 UTC, closed without merging